### ISSUE TITLE
Visualizations: switching from number to date variable on scatterplot and (forthcoming) lineplot y-axis causes an exception

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1003]
This may also affect other visualizations, but for sure scatter and line.

Reproduce with any scatter plot with two number variables on x and y. Then change the y variable to "observation date" (GEMS1, or whatever date variables are available in the study you are using).

The problem is that, when the user changes the `yAxisVariable`, the `defaultDependentRangeMargin` calculation uses the new value of `yAxisVariable.type` (which is now `"date"`) but the old values of `data.value.yMin` and `data.value.yMax` are still hanging around and contain numbers, not dates. This causes the error in `axisRangeMargin()`.

I can't see how to fix this right now, or I would have fixed it for line plot!

**Comment by moontrip** [comment]
@bobular Thank you for reporting the bug. I will take a look at it. Have a great vacation!

**Comment by aaronwlsong** [comment]
It seems that after change y as date format var, the range is still number not date format.

In GEMS1 Case control, scatter plot, using x=weight, y=age as initial vars, then change y to "observation date
<img width="1739" alt="Screen Shot 2022-04-11 at 4 42 48 PM" src="https://user-images.githubusercontent.com/61077845/162828707-1f9f25db-3ac6-4d5b-b948-f74defc60ae9.png">

<img width="1445" alt="Screen Shot 2022-04-11 at 4 42 34 PM" src="https://user-images.githubusercontent.com/61077845/162828714-abdf4942-9475-4cf7-869e-fdfaa6a9d136.png">

In MAL-ED, lineplot, x=age, y=weight, then change y as "observation date"
<img width="999" alt="Screen Shot 2022-04-11 at 4 46 39 PM" src="https://user-images.githubusercontent.com/61077845/162829370-99c2a103-1b68-4647-bf66-dc900414865d.png">

<img width="1140" alt="Screen Shot 2022-04-11 at 4 45 18 PM" src="https://user-images.githubusercontent.com/61077845/162829372-b12aba53-f82e-48ea-9cb3-a921f6e6d902.png">

**Comment by moontrip** [comment]
@aaronwlsong thank you for your detailed review! 👍

**Comment by aaronwlsong** [comment]
Thanks @moontrip :)
