### ISSUE TITLE
ClinEpi DIY: Incorporate User-Uploaded Studies into "All Studies" page

### ISSUE THREAD

**Issue by jtlong3rd** [VEuPathDB/web-eda#1008]
As mocked up [here](https://www.figma.com/file/3BZwX3F6P00Ik0E4mgljbp/DIY-workspace?node-id=16%3A157).

**Comment by danicahelb** [comment]
FYI I'm moving this ticket to b59. We want DIY to be publicly released in b59, but made available on the QA site in b58.

**Comment by jtlong3rd** [comment]
Duplicate of https://github.com/VEuPathDB/ClinEpiWebsite/issues/51

**Comment by SheenaTomko** [comment]
Looks great
