### ISSUE TITLE
Improve UI for axis controls on visualizations

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1011]
The UX for x-axis and y-axis controls is confusing, it is not clear that X-axis and Y-axis are titles for these sections

Suggested improvements:
Underline the text for x-axis and y-axis
Put a line between the controls for x-axis and y-axis

Similar styling of the axis controls section should be implemented for all visualizations

**Comment by moontrip** [comment]
Hi @danicahelb I made a mock up for two colors of vertical line on the scatterplot viz: with underscored text for X- and Y-axis. Think that light gray works but just in case made a gray line too. Do these changes satisfy the improvements you have listed? Certainly will do this for other Vizs.

- light gray line
![scatter-lightgray](https://user-images.githubusercontent.com/12802305/162049094-5832c5da-a5bf-4b1f-840c-7eed9f6a4d3f.png)

- gray line
![scatter-gray](https://user-images.githubusercontent.com/12802305/162049116-5055bdf9-516b-4bba-9f87-8c3c37b7686f.png)

**Comment by danicahelb** [comment]
This looks much better! I like the grey line version. Thanks @moontrip!

**Comment by moontrip** [comment]
discussed with Danica via slack about that, shared mockups. Leaving some summary in this comment for a record.

Texts are now changed to black. Border color of input boxes is not pursued for now as it is material-ui stuff: but will revisit it later. Final product looks like this.

![black](https://user-images.githubusercontent.com/12802305/162274372-ae18cc05-e0d3-4cfc-a63f-33182660f80e.png)

**Comment by moontrip** [comment]
due to above change, now this PR relies on a [PR at web-components](https://github.com/VEuPathDB/web-components/pull/337)

**Comment by asizemore** [comment]
Hi sorry to butt in but i'm concerned about adding the underline. I think this would be one of maybe a few underlines, and it's the only one on the page which suggests it's of higher importance than text that is of similar height and weight/boldness. I don't think that's true in this case, and for that reason strongly caution against adding the underline. 

Repeating the "Axis Variables" and "Stratification Variables" styling would make more sense here, in my opinion, because they are all titles of sections.

**Comment by moontrip** [comment]
Thank you for sharing your thought, @asizemore. I also heard the same opinion from @bobular, going without borderline. What do you think, @danicahelb?

**Comment by danicahelb** [comment]
Yes, I see @asizemore's point.

So we would use the same font and size for "Y-axis" and "X-axis" as we do above for "Axis variables" and "Stratification variables" (no underline).

How do you all feel about changing the verbiage to "Y-axis controls" and "X-axis controls"? @bobular @asizemore @steve-fischer-200 @moontrip  @SheenaTomko

**Comment by moontrip** [comment]
Personally I like to add `controls` word, which is more clear to me.
However... I may be wrong for this - it was named as `X-axis controls` in the very beginning, but shortened to `X-axis` for some reasons.

**Comment by SheenaTomko** [comment]
I also like the idea of adding "controls" to the labels.

**Comment by asizemore** [comment]
Love adding "controls"!

**Comment by bobular** [comment]
Haha yes we have probably been around in circles from "X-axis controls" already. I don't remember why we changed the first time.  I do remember the first iteration of this being more visually complex (outlined boxes, fancy labels embedded in the outline). Maybe we pushed to simplify and went too far?

Happy to (re)add "controls"

**Comment by moontrip** [comment]
thank you for sharing your thoughts, all. Here is a screenshot to have 'controls' and revert back to original text style, FYI.

![axis-controls](https://user-images.githubusercontent.com/12802305/162444453-3984da04-8022-4358-96e7-3e18d55ce057.png)

**Comment by danicahelb** [comment]
@moontrip please increase the font for "Y-axis controls" and "X-axis controls" text so that it uses the same font and size as the text for "Axis variables" and "Stratification variables".

Everything else is looking really nice!

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/25450900/163026213-ec8c2492-d525-4ca7-82e5-e355c134d92a.png">

**Comment by moontrip** [comment]
@danicahelb yep I will do that. I am working on other viz work so I will add the change in there. Here is a screenshot I just changed at upcoming PR - used the same data with your screenshot 😃 .

![sample2](https://user-images.githubusercontent.com/12802305/163028121-f19dde71-da7d-4c2c-a427-87e082bcea6c.png)

**Comment by danicahelb** [comment]
looking better! @moontrip can you also use the same size and font for "Plot modes"?

**Comment by moontrip** [comment]
> looking better! @moontrip can you also use the same size and font for "Plot modes"?

@danicahelb No problem. I just added the change to my existing PR. Here is a screenshot for you :) Not quite sure if you want lowercase for "M" in the "Modes"?

![plotmodes1](https://user-images.githubusercontent.com/12802305/163069095-edf39be8-0e8f-4c71-94ec-67f27c0f090d.png)

**Comment by moontrip** [comment]
@asizemore Yes I noticed those items but just left it as are because of no requests 😄 Thank you for pointing these out! Will work for that

**Comment by danicahelb** [comment]
Hi @moontrip 

please make the "M" in "Plot modes" lowercase.

@asizemore good catches! I agree with both of those points

**Comment by moontrip** [comment]
@danicahelb @asizemore I am including the changes to my other PRs (#1032 and https://github.com/VEuPathDB/web-components/pull/341) which I am working on. Here is a screenshot to reflect all of your changes (font color and weight are matched too):

![scatter-ui](https://user-images.githubusercontent.com/12802305/163233236-23237089-9c0a-467a-b4e2-a4c780c2bdb0.png)

**Comment by asizemore** [comment]
Lovely!!

**Comment by danicahelb** [comment]
Its beautiful! thanks @moontrip!

**Comment by moontrip** [comment]
@danicahelb my pleasure. The changes would be reflected when corresponding PR is merged and ready to be deployed, which I am preparing for merge now. https://github.com/VEuPathDB/web-eda/pull/1032

**Comment by bobular** [comment]
@danicahelb  - there is no such "Plot modes" heading for the map viz. Should we have one? (for b58...)

**Comment by bobular** [comment]
PS not "Plot mode" singular?

**Comment by bobular** [comment]
PPS. does this need moving to To be deployed on the board?

**Comment by asizemore** [comment]
oh @bobular you're right. "Plot mode" singular makes more sense  😄 
Probably not necessary to change before b57 @danicahelb ?

**Comment by danicahelb** [comment]
Looks nice, closing ticket.

Yes, it should be "Plot mode", I'll make a ticket for b58

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/25450900/163551474-28f9b265-901b-401b-862e-e3bc9306032f.png">
