### ISSUE TITLE
Plot padding should not affect data ranges

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1015]
Discussed in 4/4/2022 EDA meeting

Padding in plots prevents data points from appearing on axes
Currently the padding looks like data (ie, shows up in the range selector in axis zoom controls); if the user truncates the padding, a yellow bar blocks the data even though only the padding was truncated out
Padding should instead be a few pixels of space around the edges of the plot; the range selector should indicate the actual data range, not the range of padding

**Comment by danicahelb** [comment]
Plot padding looks much better, but there are now too many digits in the range box

<img width="985" alt="image" src="https://user-images.githubusercontent.com/25450900/166513230-49d6a3b0-31b7-41ae-aab6-045f17cffb0e.png">

I'm not sure what rule we were previously using... (4 decimal places? 3 sig figs?) but please implement that here also.

On the live site, the range has a more appropriate number of decimal places:
<img width="333" alt="image" src="https://user-images.githubusercontent.com/25450900/166513663-2e098046-1c36-44df-aa01-3bce5fb49a3a.png">

**Comment by moontrip** [comment]
@danicahelb thank you for your review and check. I will take a look at it 👍

**Comment by moontrip** [comment]
@danicahelb Can you please let me know what study you have used for making the screenshot?

**Comment by moontrip** [comment]
@danicahelb FYI, the X-axis range (for all Vizs that use such a range control) utilizes backend response, either displayMin/Max or rangeMin/Max. Thus usually I did not have to fix decimal points. Y-axis range is data-based value, i.e., computed from data to find min/max, thus it certainly has a setting to fix decimal points, 4.

I could not find the study but from my guess, it is an exception case to have such a lengthy decimal points. The variable is Age in year unit, so for example a new-born baby has more likely day unit, which will have decimal points when converting to year. The value shown in your screenshot, 0.041666... is about 15 days 😃 Anyway I will try to set the decimal points for X-axis range too

**Comment by danicahelb** [comment]
@moontrip it was LLINEUP

**Comment by moontrip** [comment]
@danicahelb Thank you for your information! 👍 Will check it!

**Comment by moontrip** [comment]
@danicahelb @dmfalke 

I have checked the corresponding variable's metadata (`Ages`) and below is the record. As you can see, its `rangeMin` has the lengthy decimal points shown in the screenshot. Certainly it can be handled at either frontend or backend. However, I could easily find other variables that have such lengthy decimal points in the LLINEUP, e.g., "Cluster-level parasite prevalence", "Household wealth index, numerical", etc. , and I presume that perhaps more in other studies also have, I opine that this is better to be done in the frontend for now.

```
{
    "id": "OBI_0001169",
    "parentId": "EUPATH_0000310",
    "providerLabel": "[\"hh_member_06m::ageyrs\",\"hh_member_00m::ageyrs\",\"hh_member_12m::ageyrs\",\"hh_member_18m::ageyrs\"]",
    "displayName": "Age",
    "definition": "Age in years.",
    "displayType": "default",
    "displayOrder": 4,
    "type": "number",
    "hideFrom": [],
    "dataShape": "continuous",
    "distinctValuesCount": 127,
    "isTemporal": true,
    "isFeatured": true,
    "isMergeKey": false,
    "isMultiValued": false,
    "imputeZero": false,
    "distributionDefaults": {
        "rangeMin": 0.04166666790843,
        "rangeMax": 110,
        "binWidth": 4.23
    },
    "units": "years",
    "precision": 16
},
```

**Comment by moontrip** [comment]
@dmfalke thank you for your confirmation about the truncation of the decimal points. Actually we already have used a function to set the four decimal points for dependent axis range, but not for independent axis range. So I can use that function in this case too.

**Comment by moontrip** [comment]
@danicahelb for your information, this is now addressed and will be deployed to qa later. You can see my screenshot at https://github.com/VEuPathDB/web-eda/pull/1123#issue-1225806766

**Comment by bobular** [comment]
Ready for second QA

**Comment by sweverschulman** [comment]
ticket paused until issues around continuous var errors in browse and subset are fixed.

**Comment by moontrip** [comment]
@danicahelb I wonder if we need to address above issue: markers may be partially cut due to a user-defined axis range. Personally it is what it is, due to the nature of axis range control where the range setting matches with the graph. No clear answer to avoid this: perhaps user can changes the range, e.g., 19.5 for min to avoid the phenomenon in the above screenshot.

**Comment by danicahelb** [comment]
Closing this ticket. New ticket for markers cut in half here: https://github.com/VEuPathDB/web-eda/issues/1209
