### ISSUE TITLE
Scatterplot: Give feedback when smoothed mean returns no points

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1016]
To reproduce the error:

Filter: Cluster study arm: Handwashing

<img width="1786" alt="Screen Shot 2022-03-30 at 5 56 31 PM" src="https://user-images.githubusercontent.com/11710234/160937782-d540214d-2696-4e94-806a-2fe53aedad49.png">
<img width="1692" alt="Screen Shot 2022-03-30 at 5 56 41 PM" src="https://user-images.githubusercontent.com/11710234/160937796-70b8226f-0263-44db-92f3-e74d1e35f95a.png">

The scatterplot response is fine, but the smoothedMeanX, smoothedMeanY, etc are just empty arrays. 

Should we offer some sort of info/warning about why the user isn't seeing any smoothed mean lines, even after clicking the Smoothed mean with raw option?

**Comment by danicahelb** [comment]
yes, we should definitely offer feedback.

**Comment by nkittur-uga** [comment]
It worked.
<img width="1373" alt="Screen Shot 2022-04-15 at 12 23 26 PM" src="https://user-images.githubusercontent.com/67710160/163595642-f77ae7d3-1478-4dbd-af09-3319ae09c020.png">
 I got an informative message.
