### ISSUE TITLE
Map viz markers

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1025]
Notes from 4/4/2022 EDA UX meeting:

We will offer users the option to choose between 3 map markers: (https://www.figma.com/file/GhufkPGsVPmhdb8terdaxk/Map-viz?node-id=0%3A1)

1. Bar plots of counts
2. Bar plots of proportions
3. Pie plots

**Comment by bobular** [comment]
Hi @danicahelb, @asizemore and @d-callan 

Below is the barplot/proportional mode, with y-axis range always set to [0,1].  Do we want to try it scaled to [0,max(on-screen-proportions)]?

![image](https://user-images.githubusercontent.com/308639/163147251-5d82b6c1-0d9f-4117-9fec-5e692dd3cf63.png)

**Comment by bobular** [comment]
Also, the "ones" are a tricky issue

They are correctly showing the sum of the proportions.  If we de-select some values in the legend, then the totals are no longer 1, so there is potentially some useful functionality here??

![image](https://user-images.githubusercontent.com/308639/163147636-0d1dd82e-0ea5-4c16-8812-afa0d0db627d.png)

**Comment by SheenaTomko** [comment]
I agree with Ann and like the scaling as it is. This looks great so will move to complete.
