### ISSUE TITLE
provide tooltip for why some smooth mean lines & CI are greyed out

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1029]
related to this ticket: https://github.com/VEuPathDB/EdaNewIssues/issues/168

when one of the strata doesn't work for loess, it gets greyed out in the legend. we should provide the user with some information so that they can understand whey they are not getting a line for that strata
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/25450900/156061327-537fa06b-5504-452b-9d3f-575dab5ddee1.png">

**Comment by moontrip** [comment]
@danicahelb I have tested this and reminded myself that actually this was already addressed by implementing banner message to show via https://github.com/VEuPathDB/web-eda/issues/1016. If at least one smoothed mean is missing, then a banner is shown. Below is an example screenshot with GEMS1 Case Study, taken at QA site. As you can see,  a similar message as suggested by Danielle above (but refined) is shown for non-existent smoothed means and confidence intervals for India and Kenya (grayed out checkbox at legend). Thus, I think that this ticket can be closed.

![scatter-message2](https://user-images.githubusercontent.com/12802305/193182744-2a67676e-715d-4d1d-a975-4b7c84534b47.png)

**Comment by dmfalke** [comment]
I'm going to close and move to **Ready for testing**

**Comment by danicahelb** [comment]
I'm marking this ticket as complete. We would like some changes to the banner so that it is always visible, but a new ticket has been made for that: https://github.com/VEuPathDB/EdaNewIssues/issues/452
