### ISSUE TITLE
Data access restrictions modal has broken link to Data Access and Use Policy

### ISSUE THREAD

**Issue by jernestmyers** [VEuPathDB/web-eda#1030]
Clicking the link to the `Data Access and Use Policy` in the data access restrictions modal routes to a `Page Not Found` page.

I encountered this error doing the follow:
1. Navigated to MAL-ED study and clicked the "Download" tab
2. Clicked the "Participant Repeated Measures" dataset in the "My Subset" section
3. Clicked the link to the Data Access and Use Policy in the modal that popped up

![image](https://user-images.githubusercontent.com/69446567/159552179-6664ae15-7977-412e-863f-7ba2516b773b.png)
![image](https://user-images.githubusercontent.com/69446567/159552308-4477d161-6947-4c1e-af8f-584635b0aced.png)

**Comment by SheenaTomko** [comment]
The link works now.
