### ISSUE TITLE
line plot error message when selecting non-ordinal categorical x-axis variable

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1034]
I was testing the line plot tool with LLINEUP data, trying to see if non-ordinal categorical variables could be selected on the x-axis. when I changed the x-axis variable from "age group" to "country" I got the error message below (Note, technically I should NOT be able to select "country" for the x-axis on the line plots (see VEuPathDB/EdaLoadingIssues#28)

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/25450900/162853577-3e8ab912-0f06-4e0f-8d16-30bfbe765dd4.png">

**Comment by danicahelb** [comment]
this should be fixed once https://github.com/VEuPathDB/EdaLoadingIssues/issues/28 is fixed.
I'm moving this ticket to "Ready to QA" with a pause label

**Comment by SheenaTomko** [comment]
@danicahelb I removed the pause label and added you as an assignee to qc this ticket. Jay has finished reloading all studies except SHINE and PROMOTE (which won't be released as part of b57).

**Comment by danicahelb** [comment]
I can no longer select a non-ordinal categorical, so there is no way to get the error message. Ticket passed QA

**Comment by danicahelb** [comment]
@dmfalke why did this ticket get moved out of "complete"? Do we need to test it again?

**Comment by danicahelb** [comment]
confirmed with @dmfalke this was moved to ready for testing by accident
