### ISSUE TITLE
Map viz tool need variable completeness table

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1037]
Please add a variable completeness table to the map visualization. The table should include information on the main variable as well as for lat/long coordinates

**Comment by chowington** [comment]
Here's what I have currently:

![image](https://user-images.githubusercontent.com/12377649/166307873-9e2252d7-d2e4-4a5c-9080-b86e94917965.png)

The backend doesn't give separate values for lat & lon, only the completeness for the geohash variable, which has a nonsensical name to users. I assume the geohash value exists iff lat & lon both exist, so logically it's pretty much equivalent. I don't see a huge need to distinguish between latitude and longitude for variable completeness purposes, so I'm personally fine with just the geohash variable.

The question is what to call it in the table. "Latitude & longitude"? Just leave the geohash name? Another name?

@danicahelb @d-callan

**Comment by d-callan** [comment]
I'd be fine w 'geolocation', it's less wordy than saying 'latitude and longitude' but I think/hope equally understandable to most

**Comment by SAK22** [comment]
Map tool currently down on QA.

**Comment by SAK22** [comment]
Looks good!
