### ISSUE TITLE
Visualization: Always show plot and controls

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#104]
If no variables are selected, or if the plugin returns a 500, we should still render an empty plot and controls.

**Comment by moontrip** [comment]
@dmfalke I need a clarification for the case of grid view, not full screen.  Under the conditions, which one should be shown at grid view between fontawesome icon or empty plot ? Is it still empty plot?

**Comment by dmfalke** [comment]
I would use an empty plot. We're getting rid of the fontawesome icons for this use.

**Comment by moontrip** [comment]
addressed empty plot for both scatter and bar plot vizs. For scatter plot viz, its plot control is now always shown for no data or data error. See linked PRs for screenshots
