### ISSUE TITLE
Map viz: Legend support discretized gradient colormaps

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1040]
talking to @asizemore, we noted the legend needs updating to interpret the new gradient colormap that will be used with continuous variables on the map

Fixed by #1186 

the gradient colormap ticket is: VEuPathDB/web-eda#1041

**Comment by asizemore** [comment]
Specifically, this ticket refers to taking the appropriate continuous colormap (sequential, diverging, etc), discretizing the colormap based on the number of bins, and then showing an appropriate legend.

For example, see discretized sequential gradient colormap on the right:
<img width="892" alt="Screen Shot 2022-04-19 at 5 37 14 PM" src="https://user-images.githubusercontent.com/11710234/164106040-3bf036d5-c862-4498-bd73-578db6bb2c5b.png">

**Comment by asizemore** [comment]
@moontrip i believe we can use the existing gradient colormaps in https://github.com/VEuPathDB/web-components/pull/275
I think i'll likely just make a web-components PR that adds these colormaps to `addOns.ts`. That way everyone can start using the colormaps :)

That old PR i made did have some work on a legend, but it only had work on a continuous gradient colormap legend (left side in screenshot above). For the map, we'll need to take the colormap defined in `addOns.ts`, break it up into n steps (i think d3 has logic for this), and then show it in the legend as colored squares (discretized gradient colormap, right side in screenshot above).

I can make the PR for adding the colormaps tomorrow, but i won't have time to work on the discretized gradient colormap legend for many weeks probably, so i'm totally happy for you to work on it, @moontrip , if you'd like!! Besides, you are the legend expert 😄

**Comment by moontrip** [comment]
@asizemore I am flattered 😄 Anyway, thank you for your detailed information! 👍 When I saw your images above I misunderstood that you would make another svg like continuous gradient (pre-existing one you have made before) but sounds like it would be another type of legend to be made in coding. Then, I will take a look at it later! Perhaps I would have some questions to you about that at the time I will work for that

**Comment by moontrip** [comment]
@asizemore I had a chance to look at your `PlotGradientLegend` component more carefully and it looks quite good. I referenced it for making its discretized one, though I didn't use SVG in that case: more or so I used custom legend style for a possible combined legend in the future 😃 https://github.com/VEuPathDB/web-components/pull/348

**Comment by bobular** [comment]
Closing because for the map viz we have this implemented

![image](https://user-images.githubusercontent.com/308639/172921371-5637e955-c62c-402c-8ac0-56ca8474e602.png)

**Comment by danicahelb** [comment]
there are new tickets to adjust the legend styling:
https://github.com/VEuPathDB/EdaNewIssues/issues/315
https://github.com/VEuPathDB/plot.data/issues/170

I'm closing this ticket as the legend for discretized colormaps has been implemented
