### ISSUE TITLE
Gradient color map needed for continuous variables

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1041]
Notes from 4/4/2022 EDA UX meeting:

Categorical variables will use a discrete color map

Continuous variables will use a discrete gradient color map

Default # of bins for continuous variables = 8. This matches the max number of bins allowed for categorical data
We will allow users to change the total number of bins

We don't need to define a maximum number of bins for continuous variables. If the user chooses to have a very large number of bins, the color map will look like a continuous gradient & legend may get annoyingly long but this is OK

**Comment by danicahelb** [comment]
I've removed the "map" label as this ticket is to create a gradient color map with can be used broadly in different viz tools. I will create another ticket specific to using continuous "Main" variables on the map viz tool

**Comment by asizemore** [comment]
Addressed with web-components [PR](https://github.com/VEuPathDB/web-components/pull/275)

Nothing for outreach to QA - this ticket was addressed by adding colormaps to web-components that can be accessed by the developers.
