### ISSUE TITLE
Visualizations: move "clear selection" action outside dropdown

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1042]
Currently the Clear selection button lives inside of the variable picker dropdown. Users may get confused and think they have to clear their selection before selecting a new variable.

<img width="495" alt="Screen Shot 2022-03-31 at 1 42 24 PM" src="https://user-images.githubusercontent.com/11710234/161117116-7cf29409-41ec-4570-a097-b64b0d773a88.png">

To clear this up, the proposal is to separate "Clear selection" from the dropdown menu. Perhaps a small X next to the dropdown? Or a small "Clear"?

**Comment by danicahelb** [comment]
I agree with @asizemore. Also, I personally find it a bit annoying to have to open the variable tree if I just want to remove the overlay (for ex). I like the idea of a small "clear".  We can discuss in an upcoming EDA mtg.

**Comment by asizemore** [comment]
unless we feel like there is a clear path forward, this might be a decent issue for the eda styling group to discuss before bringing to the larger eda meeting because they might have some ideas about what is common/what are the styling rules for this type of action. Just a suggestion!

**Comment by danicahelb** [comment]
good idea @asizemore. is the styling group actively meeting?

**Comment by asizemore** [comment]
no, we've only been meeting when necessary :) 

I could plan something for next week if that is soon enough?

**Comment by danicahelb** [comment]
@asizemore can you add this to an upcoming styling WG agenda? thanks!

**Comment by danicahelb** [comment]
Discussed in 6/27/2022 EDA UX meeting

There is agreement that having a way to clear parameter selections without opening up the dropdown would be useful.

It would be good to also keep the “Clear selection” button within the dropdown. We would NOT want to introduce clickable elements inside of other clickable elements (ie, we do NOT want to have a button within a button)

Perhaps we could add a small “X” button immediately to the right of each of the dropdown menus. @danicahelb will make mockups

**Comment by danicahelb** [comment]
discussed in 7/1/2022 EDA UX meeting

update mockups to use the stylized close icon with an x in a circle

**Comment by danicahelb** [comment]
discussed in 7/1/2022 EDA UX meeting

update mockups to use the stylized close icon with an x in a circle

**Comment by danicahelb** [comment]
Mockups: https://www.figma.com/file/LVDoPrzKkd1rCYJgdgCCKC/New-viz-tab-buttons%3A-(1)-clear-parameters%3B-(2)-display-%2F-update-viz%3B-(3)-zoom-to-plotted-data?node-id=0%3A1

folks prefer v2 (where there is no close icon until a parameter is selected)

passing over to @asizemore to discuss in styling WG on 7/13

**Comment by asizemore** [comment]
Discussed in 8/31 [meeting](https://veupathdb.atlassian.net/wiki/spaces/WG/pages/58687496/EDA+Styling+Meeting+August+31+2022). Continue with MUI "Cancel" icon (`import CancelIcon from '@mui/icons-material/Cancel';`

**Comment by asizemore** [comment]
The styling part of this issue is done (see above comment). @danicahelb is there a separate issue for implementation?

**Comment by danicahelb** [comment]
I don't think there is an implementation ticket, I am just going to convert this ticket into an implementation ticket by changing the title and removing the styling WG label.

**Comment by chowington** [comment]
I'm using this as the final mockup:

![image](https://user-images.githubusercontent.com/12377649/191110900-d2abd135-2ef6-4813-b717-6f1e314018b8.png)

It comes from [this Slack message](https://epvb.slack.com/archives/C02R14DUYLX/p1661972245134669?thread_ts=1661970200.232249&cid=C02R14DUYLX). Let me know if this isn't the correct final version @asizemore @danicahelb.

**Comment by aaronwlsong** [comment]
Looks good now, closing ticket. 

![Image](https://user-images.githubusercontent.com/61077845/195704789-f198a9cb-091a-444c-ae7e-9a4a5be657d0.png)
