### ISSUE TITLE
Use the value order for multifilters

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#1043]
EX: PROMOTE has multifilters like "Child symptoms" where the values for each multifilter variable should be ordered Absent, Mild, Moderate, Severe, Life-threatening. However, right now they appear in alphabetical order, despite Jay loading the value order.

<img width="456" alt="Screen Shot 2022-03-30 at 3 59 38 PM" src="https://user-images.githubusercontent.com/54597319/160929915-856f3611-946c-4d04-a2c6-38bc58b62142.png">

**Comment by dmfalke** [comment]
You can use the variable property `displayOrder` to determine the correct order. If the property doesn't exist, then we should fall back to `displayName`.

See https://github.com/VEuPathDB/web-eda/blob/60d01f59a8d37b444862da0d30ded9b724da42f9/src/lib/core/types/study.ts#L106.

I'm happy to discuss in more detail.

**Comment by jernestmyers** [comment]
@dmfalke From what I've seen, `displayOrder` is only attached to the variable, like this:
![image](https://user-images.githubusercontent.com/69446567/164484021-0c0bb238-c5ca-4617-b0a1-a7da473c8c5b.png)
That appears (to me) to be used to ensure "Child symptoms" is displayed in the fourth position in the section "Child signs and symptoms" but I don't see anything similar to order the symptom severity, in which case the `displayName` may be the only option.

**Comment by dmfalke** [comment]
@jernestmyers as discussed in [slack](https://epvb.slack.com/archives/C01894F7P89/p1650554774278259), we are going to remove the code that unions all of the values together, and only display the values available to the child variable.

There are two pieces to this:
1. In wdk-client, [remove the code](https://github.com/VEuPathDB/WDKClient/blob/848aa586188298e2be139ad084215bb4b8e4b06d/Client/src/Components/AttributeFilter/MultiFieldFilter.jsx#L221-L226) that unions the value across all child variables.
2. In web-eda, use the child variable's `vocabulary` property to [generate `valueCounts`](https://github.com/VEuPathDB/web-eda/blob/e783782b18dcf01f3ef52fe13229ca09df754d64/src/lib/core/components/filter/MultiFilter.tsx#L238-L242).

**Comment by nkittur-uga** [comment]
This issue is fixed. QA is complete.
