### ISSUE TITLE
Inconsistent min values between browse/subset & default min scatter plot

### ISSUE THREAD

**Issue by sweverschulman** [VEuPathDB/web-eda#1044]
Noticed that the min values in the scatter plot for 'Schistosoma mansoni infection intensity, by microscopy (eggs per gram)' by 'Hookworm infection intensity, by microscopy (eggs per gram)' in SCORE Burundi and those in the browse/subset tab are different.

In the browse subset tab - both variables min are 0
![Screen Shot 2022-03-25 at 11 26 41 AM](https://user-images.githubusercontent.com/62298921/160167862-78ce4a39-e60e-4178-89af-44700d449e9f.png)
![Screen Shot 2022-03-25 at 11 26 33 AM](https://user-images.githubusercontent.com/62298921/160167967-b79fe9d3-cc85-4620-a3e4-c8df89bf097c.png)

 However in the scatterplot they are negative numbers
![Screen Shot 2022-03-25 at 11 26 10 AM](https://user-images.githubusercontent.com/62298921/160167751-a9ecf631-1b8b-4c3c-b784-06a517258963.png)
 

I can see this being confusing for the user.

**Comment by moontrip** [comment]
@sweverschulman (and @dmfalke)  we have ticket to address this, https://github.com/VEuPathDB/web-eda/issues/1015, for next release (b58) - will start working this just after b57 works are done

**Comment by danicahelb** [comment]
I'm closing this ticket as it will be addressed with https://github.com/VEuPathDB/web-eda/issues/1015
