### ISSUE TITLE
Reduce duplicated fetch calls in SubsettingDataGridModal

### ISSUE THREAD

**Issue by jernestmyers** [VEuPathDB/web-eda#1045]
This issue extends [this issue regarding the performance of the download modal](https://github.com/VEuPathDB/web-eda/issues/988).

Specifically, when `handleSelectedVariablesChange` is first triggered on a new study, the `fetchPaginatedData` method is called 3 times. Subsequent click events only trigger one fetch call, as desired.

The fetch call is made [in this `useEffect`](https://github.com/VEuPathDB/web-eda/blob/76bd9137c126f216c8b6e073d8210076b0c2b767/src/lib/workspace/Subsetting/SubsettingDataGridModal.tsx#L237-L242).

**Comment by dmfalke** [comment]
@jernestmyers, @jtlong3rd, and I identified some potential changes to the `Modal` and `SubsettingDataGrid` components that may address this issue.

In `Modal`, remove the `onOpen` and `onClose` callbacks, remove residual state and effect hooks.

In `SubsettingDataGrid`, move logic that is currently passed to `Modal` in the `onClose` and `onOpen` callbacks. Also, remove unnecessary hooks.

**Comment by SheenaTomko** [comment]
Nothing to qc, marking as complete
