### ISSUE TITLE
Update Y-axis labels for line plots 

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1050]
**For mean and median modes, add "Mean: " or "Median: "**
For example, the label should look like "Mean: Age (years)"

**For proportion mode, label should just be "Proportion"**

Y-axis for line plots in proportion mode is confusing. Currently users will have to be careful about interpretation. Here I chose to plot the "No" proportion for Undernutrition, but the Y axis title is just Undernutrition, and the user has to be remember that in fact they plotted the proportion of kids that don't have undernutrition.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/25450900/163027473-58cb245b-ad42-4de3-a91c-4af428773778.png">

It would be better if the Y-axis label just said "Proportion" for line plots in proportion mode.

In the future, we can offer users the ability to edit labels (see placeholder ticket VEuPathDB/web-eda#1053)

**Comment by moontrip** [comment]
I will take a look at this

**Comment by danicahelb** [comment]
looks great, thanks DK!

**Comment by moontrip** [comment]
My pleasure 😃 Happy Easter!
