### ISSUE TITLE
use "scale" to automatically display variables on a log scale if the data is logged

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1055]
We are using “scale” annotation in the owl file to indicate whichever type of log (log2, log10, ln, etc.) the data has been loaded in.

use scale to automatically display variables on a log scale if the data is logged

see also https://redmine.apidb.org/issues/43947

**Comment by dmfalke** [comment]
This likely also requires an update in https://github.com/VEuPathDB/EdaSubsettingService

**Comment by danicahelb** [comment]
I just mean that the axis tick marks and labels would be different.

for data on a linear scale the axis tick marks would look like this y-axis (for example):
<img width="655" alt="image" src="https://github.com/VEuPathDB/web-eda/assets/25450900/d3264e8e-4e83-450b-97f4-3e4286df844c">

and for data that was loaded in a log-transformed format, the axis tick marks would look like this y-axis:
<img width="600" alt="image" src="https://github.com/VEuPathDB/web-eda/assets/25450900/9ba3a138-eb27-41a9-a835-e3f3d10b6c55">

**Comment by bobular** [comment]
I made some exponentially distributed random numbers, _e_, in Google spreadsheets and plot a scatterplot vs a uniform random number (just to spread them out)

![image](https://github.com/VEuPathDB/web-eda/assets/308639/fe08d817-e382-43c9-8372-9bb087fbcd87)

If we plot these data on a log scale y axis, things look more agreeable

![image](https://github.com/VEuPathDB/web-eda/assets/308639/55184f0f-85b8-4cc8-9be7-73195af79141)

If we take logs of the exponential data in our spreadsheet, and plot log(_e_) on a regular axis, it also looks right:

![image](https://github.com/VEuPathDB/web-eda/assets/308639/d3af71b9-b74e-4135-ad1b-52aaffcc8809)

But if we change the y-axis to log scale style, we lose half the data and it is meaningless

![image](https://github.com/VEuPathDB/web-eda/assets/308639/0e69ea4a-bcab-4b95-bccb-93cfc52fee7f)

**Comment by bobular** [comment]
I think I'd still need to see examples.

In my example "logged_exponential" is a simulation of data that we receive that has already been logged. To get the effect Dave described, I think we would need to un-log the data and then show it with a log scale. But then we'd be showing numbers different to what was submitted/is downloadable.

**Comment by bobular** [comment]
Or perhaps the variable annotation is simply "this is exponentially-distributed data - it needs to be shown on a log scale and geometric mean is most appropriate" ?

**Comment by danicahelb** [comment]
the "scale" variable annotation is to indicate that the data has been given to us log-transformed (not that the data is exponentially distributed and should be shown on a log scale)

I think I've been convinced that we should not change the way the axis tick marks are displayed.

And I think I agree with @bobular's proposal that we should be disabling log scale for variables flagged as already being log-transformed & disable geometric means for log-space variables. but also... perhaps it is just not worth doing? There are only a handful of log-transformed variables in the database. If someone displays log-transformed data on a log scale, its not the end of the world... 

I'm considering closing this ticket without asking for anything to be done. @dmfalke @bobular do you agree?

**Comment by dmfalke** [comment]
That works for me 😀

**Comment by bobular** [comment]
Same here!
