### ISSUE TITLE
VariableTree scrollbar solution side effect in Download Modal

### ISSUE THREAD

**Issue by jernestmyers** [VEuPathDB/web-eda#1057]
[A recent merge](https://github.com/VEuPathDB/web-eda/pull/1002) that addressed the issue of the extra scrollbar in the `VariableList` dropdown container had a side effect in the `SubsettingDataGridModal`. The result is that the variable selection container's height isn't constrained, which leads to the behavior shown in these screenshots:
![image](https://user-images.githubusercontent.com/69446567/163043997-4d5b97e6-9e68-49aa-b530-21ec47b7b3a4.png)
![image](https://user-images.githubusercontent.com/69446567/163044090-1e258aa7-41e4-4217-8624-39ec07cebb95.png)
![image](https://user-images.githubusercontent.com/69446567/163044153-6f67f959-24d4-4f33-a003-bf458a389ed3.png)

In essence, the variable list container is about 3.5x the height of the modal itself and creates a lot of unnecessary scrolling.

**Comment by dmfalke** [comment]
Can we address this by setting a max-height on the variable tree container in the modal?

**Comment by jernestmyers** [comment]
Yes, that's what I did. I guess when you moved it from `EdaNewIssues` my PR link got lost along the way.

**Comment by sweverschulman** [comment]
There is now a scroll bar in variable selection container. This allows for scrolling within that container and no longer a need to scroll in the larger container
<img width="714" alt="Screen Shot 2022-04-15 at 12 10 41 PM" src="https://user-images.githubusercontent.com/62298921/163595545-d8eaa1fb-293b-41f3-953e-4956ac6e29a4.png">
