### ISSUE TITLE
Line plot error message when plotting a continuous integer as a proportion

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1064]
Using LLINEUP.

"Meals per day" is one of those weird variables where there are only 9 unique values but it technically is a continuous integer and not a categorical variable. 

I tried to create a proportion and got an error:

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/25450900/163239426-15e50ca1-f1d5-4478-aa74-25dfbc17954a.png">

**Comment by danicahelb** [comment]
Yeah, for b57 we just don't want to trigger an error. If @bobular can have low cardinality continuous variables offer mean and median but not proportions on the front end easily that would be fine

**Comment by bobular** [comment]
Accidentally duplicated by https://github.com/VEuPathDB/web-eda/issues/1066
But this ticket has better screenshots, so I will link the PR to here and close #1066

**Comment by danicahelb** [comment]
I can now only select mean and median

<img width="651" alt="image" src="https://user-images.githubusercontent.com/25450900/163629801-e9555058-7824-4962-b0ec-cb6db602e8e5.png">
