### ISSUE TITLE
Lineplot visualization - erroneous logic to determine proportion vs mean/median mode

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1066]
e.g. LLINEUP
x-axis: household coll. date
y-axis: Meals per day

This is being treated as a categorical variable.  There are no server-side constraints provided for yAxisVariable so it is up to the client to decide what to do.

The current logic sees the vocabulary for this variable and distinctValuesCount > 1 and decides it's suitable for proportion mode.
The back end doesn't like this and throws a 500.

I think I'll add a `dataShape !== 'continuous'` and see how we get on with that.

**Comment by dmfalke** [comment]
Why don't we have constraints for this? Wouldn't that be the correct way to address this? Or are the constraints too complex?

**Comment by bobular** [comment]
Constraints would only tell `InputVariables` which to show/grey out.

The client would still have to figure it out.

Having said that, we do need some constraints, @d-callan, to make sure that the variable will be suitable for one or the other mode of lineplot

E.g. no single-valued variables:

![image](https://user-images.githubusercontent.com/308639/163469624-ea9cb18b-288c-439c-92ef-4b113a0fd41d.png)

**Comment by dmfalke** [comment]
I see! I misunderstood.

**Comment by bobular** [comment]
Removing this from the board, and closing this as a duplicate of #1064

**Comment by bobular** [comment]
> E.g. no single-valued variables:

I'll make a b58 ticket to add some simple constraints
