### ISSUE TITLE
In line plots, choosing a Y-axis variable with only one value throws an error message

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#1079]
The example below comes from PRISM without any filtering. I believe this error message is coming because choosing Country on the Y-axis should enable proportions, but there is only one value for the variable Country in this study. Some possible solutions: 1) remove variables with single values as options in the drop down menu, 2) give people a more distinct error message, 3) update how proportions work when there is only one possible value.

![image](https://user-images.githubusercontent.com/54597319/163398028-b31185d1-6051-4f28-b662-adcd082686fc.png)

**Comment by bobular** [comment]
I think this will be obviated by https://github.com/VEuPathDB/EdaDataService/issues/178

**Comment by asizemore** [comment]
In the data viz meeting, decided to allow vars with only one unique value in proportions. Also decided to allow the numerator=denominator.

**Comment by danicahelb** [comment]
I'm removing the dependency label as we have decided to NOT impose the constraints indicated in https://github.com/VEuPathDB/EdaDataService/issues/178

**Comment by moontrip** [comment]
@danicahelb I think that I have addressed this in the following PR. I made a couple of screenshots in there, so can you please see if it is appropriate outcome? https://github.com/VEuPathDB/web-eda/pull/1204#issue-1269899970

**Comment by sweverschulman** [comment]
I have confirmed that the error message is removed, I was able to configure the proportion and that the y =1.

It was a little confusing that I can't click on mean and median - but that can be discussed later.
