### ISSUE TITLE
Line plot styling changes needed

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1080]
When using the proportion mode of the line plot, the user must set up their proportion calculation before anything will appear on the plot. This has surprised me a few times as all other plots auto-populate immediately after x and y axis variables have been selected. 

I think a couple of tweaks would help:

1. There is a lot of white space between Axis variables and Y-axis aggregation sections (when the y-axis variable selector gets wrapped under the x-axis variable selector), and a lot less white space next to Stratification variables. We should move the Y-axis aggregation section closer to the axis variables selection because these are the 2 sections requiring input. We can leave more white space between the Y-axis aggregation and Stratification variables sections because selection of stratification variables is optional.

2. We should to indicate that the plot isn't loading due to a bug, but that the user still needs to set up the proportion. We could use the space between the axis variable selectors and the plot. The message could be something like "Set up the proportion calculation to configure plot" 

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/25450900/163278029-c3be2923-9cb0-4d26-9b9c-10c9a84c79a7.png">

We can discuss in an upcoming UX meeting

**Comment by danicahelb** [comment]
For the proportion selector, verbiage should be `Select value(s)` not `Choose values`

**Comment by danicahelb** [comment]
Discussed in 5/20/2022 EDA UX meeting.

Ideas (to be mocked up):
- Alter font type (ie, bold) and/or color to indicate which items have been selected vs. need to be selected
- Alter color of the boxes for required vs selected vs optional items
- Grey out the plot area until all required options are selected
- Superimpose verbiage indicating that some selections still need to be made
- Add an asterisks (try out black and also red) to the right of each required pulldown menu. Asterisks could disappear after that item has been selected. The legend for the asterisks could be superimposed on the graph

**Comment by danicahelb** [comment]
Discussed in 6/6/2022 EDA UX meeting.

Only the proportion mode on the line plots is causing issues, users seem to understand that they need to select X-axis and Y-axis variables for the plot to configure

Instead of indicating ALL required fields on ALL viz tools, only show the “Please select all required* selections” on the plot area and make the “proportion” text red once X & Y variables for the line plot are selected

<img width="877" alt="image" src="https://user-images.githubusercontent.com/25450900/172225944-b51cbcb4-3717-4ada-8dcf-05fd3ce99f99.png">

**Comment by danicahelb** [comment]
At the 8/15/2022 EDA UX meeting, we made the following decisions which update the deliverables in this ticket.

We will add `Please select all required* parameters.` to all viz tools when all required parameters have not been selected _e.g., opening up a new viz tool would always have this text in the plot window since x-axis and y-axis variable had not yet been selected_

All required parameters will be marked with an asterisks (ex: `X-axis*`) and will be in red text until a selection has been made. After a selection is made, the text should turn black

See: https://github.com/VEuPathDB/EdaNewIssues/issues/407

**Comment by danicahelb** [comment]
@moontrip:

These things still need to be addressed:

- [ ] The spacing of the parameter selectors is still off--there should not be more space between axis variables & y-axis aggregation than between y-axis aggregation and stratification variables. The required parameters (axis variables & y-axis aggregation) should be closer together with more white space between y-axis aggregation & stratification variables. alternatively, equal spacing between all 3 sections would also be fine.

- [ ] For the proportion selector, verbiage should be Select value(s) not Choose values

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/25450900/190275793-8fc97d0d-77a1-43fd-9d69-bec7514f0bdb.png">

**Comment by jernestmyers** [comment]
I've amended the verbiage in the [PR that replaces the old selection buttons](https://github.com/VEuPathDB/web-eda/pull/1354) with new `CoreUI` components.

![image](https://user-images.githubusercontent.com/69446567/191979730-3c41cf5f-7b59-4cd9-852f-31d5c07bedec.png)

**Comment by danicahelb** [comment]
Info from @jernestmyers about the white space "spacing" issue:

> Maybe someone else has a better idea for how to approach it? My initial ideas didn't pan out. It feels like it should be simple but I was striking out!

I will close this ticket as the important work has been completed. A new ticket to address the white space issue has been opened: https://github.com/VEuPathDB/SiteSearchData/issues/21
