### ISSUE TITLE
Line plot tool - update UI for 0/0 proportions

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1082]
We need to revisit the UI for line plots with proportions where we have 0/0.

This is a screenshot from the LLINEUP study. The design of this study was such that only kids 2-10 years were tested for malaria.

The issue is that -- because there are so many points between 11yrs - 110yrs, the null points along the x-axis actually look to be a connected line.

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/25450900/163234962-245d9cb3-ec64-438c-8f48-a5440da1ed4e.png">

**Comment by danicahelb** [comment]
Related to https://github.com/VEuPathDB/web-eda/issues/1411

Discussed in 12/2/2022 EDA UX meeting. Markers at 0 when y-axis proportions are 0/0 are confusing to users. This was brought up by participants during the TMRC workshop in October

For continuous variables, we do NOT show markers at 0 when there is no data

The birds eye view & variable completeness table exist so that missing data is accounted for

**Decision**: do not add markers at 0 when the proportion is 0/0

**Comment by danicahelb** [comment]
Related topic: https://github.com/VEuPathDB/EdaNewIssues/issues/503

**Comment by danicahelb** [comment]
Discussed UI updates to clarify instances of 0/0 in the line plot in the 12/12/2022 EDA UX meeting

**0/0 markers should be hollow instead of filled & will remain at y=0** 
- if the user selects an overlay variable, the hollow markers will be colored according to the legend
- We acknowledge that there may be overplotting of hollow 0/0 markers at y=0 when an overlay variable has been selected

**Mouseover information for the 0/0 markers will be updated** 
- to address overplotting when an overlay has been selected, the mouseover should have information for ALL overlay values at that x-axis position, each in boxes colored according to their legend colors
- change `y: 0` to `y: undefined`
- change `n: 0/0` to `n: count of values removed from denominator`

**Add information to the legend indicating what the hollow markers mean**

**When the user selects “Auto-zoom” for the x-axis, the 0/0 markers should NOT influence the auto-zoomed x-axis range. **

We will not update the birds eye view or variable completeness table when a user removes a value from both the numerator and denominator of the proportion selector
- Technically the user is creating a new “subset” within the line plot
- However, t birds eye view or variable completeness table refer to the ANALYSIS SUBSET created in the B&S tab and the user is not removing values from the subset in the analysis

@d-callan will mockup these updates for sign-off in an EDA UX meeting

In the future, we will move the hollow markers for 0/0 to a plot carpet (or ceiling, to reserve plot carpets for other annotations the user may want to add to the plot). See: https://github.com/VEuPathDB/EdaNewIssues/issues/516

--

**Comment by danicahelb** [comment]
@d-callan please update mockups in time for the 1/9/2023 EDA UX meeting

**Comment by d-callan** [comment]
mockups [here](https://www.figma.com/file/kF2dYzNAwEiHW8Khxo6B1I/Lineplot-undefined-(ie%2C-0%2F0)-proportions?node-id=33%3A225&t=Gtwkp6DSVia4tRND-0) ready for eda ux review

**Comment by danicahelb** [comment]
Mockups have been finalized:
https://www.figma.com/file/kF2dYzNAwEiHW8Khxo6B1I/Lineplot-undefined-(ie%2C-0%2F0)-proportions?node-id=93%3A1742&t=DMtQkj93Um1avPbS-0

**Comment by chowington** [comment]
> Discussed UI updates to clarify instances of 0/0 in the line plot in the 12/12/2022 EDA UX meeting
> 
> **0/0 markers should be hollow instead of filled & will remain at y=0**
> 
> * if the user selects an overlay variable, the hollow markers will be colored according to the legend
> * We acknowledge that there may be overplotting of hollow 0/0 markers at y=0 when an overlay variable has been selected
> 
> **Mouseover information for the 0/0 markers will be updated**
> 
> * to address overplotting when an overlay has been selected, the mouseover should have information for ALL overlay values at that x-axis position, each in boxes colored according to their legend colors
> * change `y: 0` to `y: undefined`
> * change `n: 0/0` to `n: count of values removed from denominator`
> 
> **Add information to the legend indicating what the hollow markers mean**
> 
> **When the user selects “Auto-zoom” for the x-axis, the 0/0 markers should NOT influence the auto-zoomed x-axis range.**
> 
> We will not update the birds eye view or variable completeness table when a user removes a value from both the numerator and denominator of the proportion selector
> 
> * Technically the user is creating a new “subset” within the line plot
> * However, t birds eye view or variable completeness table refer to the ANALYSIS SUBSET created in the B&S tab and the user is not removing values from the subset in the analysis
> 
> @d-callan will mockup these updates for sign-off in an EDA UX meeting
> 
> In the future, we will move the hollow markers for 0/0 to a plot carpet (or ceiling, to reserve plot carpets for other annotations the user may want to add to the plot). See: #1526
> 
> --

@danicahelb Just checking---are all of these changes still desired?

**Comment by danicahelb** [comment]
hey @chowington, yes (other than the tooltip updates, which I believe @jernestmyers has handled...but outreach should double-check when QA'ing this ticket). please follow the mockups, and slack me with any questions

**Comment by bobular** [comment]
Hi @danicahelb 
We've done some partial work on this ticket but it has turned out more complex than expected - even just the hollow markers aspect...

As you can see in https://github.com/VEuPathDB/web-eda/pull/1686#discussion_r1132880819 we can't easily get rid of the horizontal line without sending another separate data series to Plotly in a component that is already overly complex.

Also, it's not clear to me what
> change `n: 0/0` to n: `count of values removed from denominator` 

means? Or is the mouse-over stuff already done?

The other points (legend, y-axis auto zoom) probably won't open up a can of worms.

We propose moving this to b63, and likely scheduling some medium cost refactoring at the same time. Happy to discuss.

**Comment by chowington** [comment]
> hey @chowington, yes (other than the tooltip updates, which I believe @jernestmyers has handled...but outreach should double-check when QA'ing this ticket). please follow the mockups, and slack me with any questions

Per Danica, the popup stuff should be separately handled, though I'll check to make sure

**Comment by danicahelb** [comment]
Hi @bobular @chowington, we can certainly move this to b63.

I went to double check that the tooltip was fixed and noticed that the qa site is no longer showing any data points for 0/0 proportions.

See this example from LLINEUP (unfiltered)

**QA site looks like this: (birds eye view shows 115,542 data points but not all are represented on the plot since 0/0 markers are missing):**
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/25450900/224828165-5209f1a2-ce54-4e5a-947a-7596c59446d8.png">

**Live site looks like this:**
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/25450900/224828418-7250b828-838d-4eae-8eaf-b93e0c3a7f08.png">

**Comment by chowington** [comment]
Note: This change may impact the changes made in these previous tickets:

https://github.com/VEuPathDB/web-eda/issues/1519
https://github.com/VEuPathDB/web-eda/issues/1411

**Comment by bobular** [comment]
Hi @chowington and @danicahelb 

If we merge Connor's PR as-is, we *will* see the 0/0 markers (see below). They will be unfilled circles, but unfortunately with the line through them that Connor has started to address (but I don't think we should commit that for b62).

I check to see how it impacts on other tickets/behaviours

![image](https://user-images.githubusercontent.com/308639/224996647-51cabe8b-dfa6-4fe3-aebb-1b0a38ccd269.png)
