### ISSUE TITLE
Apps: Allow computed vars to appear in variable coverage table

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1086]
Variable coverage table in ranked abundance and alpha diversity vizs does not add the computed variables. Note the computed variables are returned in the complete cases table response data, but this info doesn't make it onto the screen.

<img width="1758" alt="Screen Shot 2022-04-19 at 4 19 09 PM" src="https://user-images.githubusercontent.com/11710234/164088716-a28610a6-50f0-4b0e-ba05-8cae9aa41cea.png">

Possibly related to VEuPathDB/plot.data#164

**Comment by dmfalke** [comment]
Does the backend provide this data, and the frontend is simply not rendering it? Regardless, I just want to mention that we want to approach this in a generic way.

**Comment by asizemore** [comment]
Good call. The backend does provide the information (see screenshot: feature mbio, GEMS, ranked abundance, no subset), but i'm guessing there is a check or filter somewhere on the front end to use only those vars in the table that match one of the input variables? I haven't looked into it deeply yet, that's just a guess. 

<img width="1766" alt="Screen Shot 2022-04-20 at 9 41 36 AM" src="https://user-images.githubusercontent.com/11710234/164243785-b0f84af6-d9b7-42a2-8377-e2ce922c041e.png">

Note that in the response, there is one row for each box in the boxplot. This is a consequence of using a collection-type variable on the x axis.

**Comment by moontrip** [comment]
Please refer to what I temporarily did for alphadiv's variable coverage table before, but it is not a generic way to do
https://github.com/VEuPathDB/web-eda/pull/1018

I forgot a detailed info myself but there are several issues for abundance case, e.g., multiple values in completeCases, no specific info to search for X and Y variable details, etc. I may take a look at it later to remind myself :)

**Comment by dmfalke** [comment]
I want to point you both (@asizemore and @moontrip) to https://github.com/VEuPathDB/web-eda/issues/580. Ultimately, I envision a component (currently referred to as `StandardVisualization`) that would handle this sort of thing. It would help to think about how one would make a generic component that will do what we're discussing here.

I'm working on a prototype of `StandardVisualization` right now. Hopefully we can look at it soon, and think more about this issue.

**Comment by asizemore** [comment]
Thank you both!
@moontrip thank you for the reminder - I will remind myself what we discussed and think about how we might want to change the response. You brought up some good points and you're right i haven't addressed them yet.

@dmfalke very cool! Really looking forward to the prototype!

**Comment by asizemore** [comment]
@dpbisme assigning to you for qa, but @danicahelb and @SheenaTomko would be curious to know how intuitive you find the table as well. There's a little time to make adjustments before release.

**Comment by SheenaTomko** [comment]
I think the table makes sense. Is it worth adding the method to the name of the X-axis variable in the ranked abundance app? For instance in this image, say that the X-axis variable is "Relative abundance of phylum data; Method median"? In a scatter plot add it to the Overlay variable name? I was playing around with methods and noticed that different methods returned different numbers of categories (on the X-axis in box plots, overlay in scatter plots) and thought having the method there too might help make it more obvious why
<img width="1215" alt="Screen Shot 2022-08-16 at 5 05 45 PM" src="https://user-images.githubusercontent.com/54597319/184985055-0b48f1ad-84a4-44c3-b3e5-fb9ab0afeccd.png">

**Comment by asizemore** [comment]
This is done. Moving to complete
