### ISSUE TITLE
Apps: hide no data toggle

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1089]
Consider ranked abundance scatter

<img width="1591" alt="Screen Shot 2022-04-19 at 5 13 05 PM" src="https://user-images.githubusercontent.com/11710234/164102838-e8ba2a80-64e9-4dd9-a6b2-e7b05e02af12.png">

Does it make sense to have the no data toggle here? We could possibly end up with a "No data" group for the computed var, which is sort of odd since we're in the app in order to see the outputs of the computation.

@dpbisme and @d-callan what do you think?

**Comment by asizemore** [comment]
We could have a rule that any viz with a computed var won't have the no data toggle. That's maybe aggressive because sometimes the computed var is a strata var but other times is an axis var, but as a rule is not too complicated

**Comment by asizemore** [comment]
Note in plot.data we have a rule that we can't have the no data toggle on _and_ have a collection var. We'll need to replicate this rule at least in web-eda to prevent users getting lots of errors

**Comment by danicahelb** [comment]
@asizemore @moontrip can we move this out of "this cycle" as it has a milestone of b59 and we are in crunch time for b58? thanks!

**Comment by asizemore** [comment]
The work for this is already done, it's just in final review. It'll be simpler and faster to just approve/merge the PR then to try to hold off and have to maintain the branch. I'll finish the review today so it'll be ready for @moontrip on Monday.

**Comment by asizemore** [comment]
Assigning to @dpbisme for qa
