### ISSUE TITLE
Visualizations: Long values in overlay variable legend are not wrapped

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#109]
The solution is probably to be made in `web-components` but logging it here.
GEMS->Household->Dwelling facilities->Waste disposal->Child waste disposal
is a good example

![image](https://user-images.githubusercontent.com/308639/119975634-fffdc280-bfad-11eb-852b-28d29fa3535b.png)
![image](https://user-images.githubusercontent.com/308639/119975698-14da5600-bfae-11eb-94b0-e29ef2d90b3f.png)

**Comment by bobular** [comment]
Wait until we decide what to do with faceting (it has its own legend needs)

**Comment by moontrip** [comment]
Just out of curiosity, I have briefly looked into this issue before and I think perhaps an ellipsis (truncated text with triple dots ...) with tooltip would be a good solution. I have a partially working solution, though I need more changes for our app. Will work for this and then share with others to resolve one unsolved issue.

**Comment by bobular** [comment]
Related to https://github.com/VEuPathDB/web-components/issues/166

**Comment by moontrip** [comment]
now this is merged at web-components through the PR: https://github.com/VEuPathDB/web-components/pull/170

**Comment by danicahelb** [comment]
@SAK22 can you QA this? thanks!

**Comment by SAK22** [comment]
Looks good!
