### ISSUE TITLE
Apps: Organize vizs in thumbnail page by app type and parameters

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1095]
05/13/22 Updates in a comment below.

For this ticket, let's apply the styling of app info and vizs seen in the below screenshot. 

<img width="714" alt="Screen Shot 2022-04-21 at 11 55 55 AM" src="https://user-images.githubusercontent.com/11710234/164501613-a5650304-379d-423c-ab81-79db8413f0b5.png">

In short, each app should have its user-given name, the app's display name, and icons+styling as a sort of heading that separates the apps. Each app's visualizations are in thumbnails right underneath the heading, and next to the + New Visualization button.

**Comment by asizemore** [comment]
See v6.1 in figma file for more details.

Let's organize the visualizations on the thumbnail page by 1) app type, 2) parameter set. In web-eda, if each viz is added to the app instance that matches its app type and parameter set, then implementing this layout should just be going through each app instance and having the app display name in a header (for the first instance of that app type), and then the  parameters listed within a subheader. 

Let's try ordering app types and parameter sets by most recently made. So if i go make a new ranked abundance viz with a brand new configuration, when i go to the thumbnail page i see:
Ranked abundance
    The new viz i just made
    Second most recently used ranked abundance parameter set and associated vizs
    Third most recently used param set...
Second most recently opened app type
... 

<img width="1338" alt="Screen Shot 2022-05-13 at 11 45 11 AM" src="https://user-images.githubusercontent.com/11710234/168319727-25622606-b21e-47e2-9638-5c8e082e3146.png">

**Comment by dmfalke** [comment]
The behavior of clicking the **New Visualization** button is not yet confirmed (see https://github.com/VEuPathDB/web-eda/issues/1130). Let's hold off on making that button to anything, until we have sign-off, which will hopefully be soon.

**Comment by asizemore** [comment]
Confirmed we're good with the behavior in #1130

**Comment by asizemore** [comment]
Closing and assigning to dan for QA. Deployed on feature.
