### ISSUE TITLE
Allow continuous variables to be visualized on map tool

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1096]
Allow continuous variables to be selected as the "Main" variable on the map viz tool.

This ticket is dependent on:

Add gradient colormap for continuous variables (sequential, diverging): https://github.com/VEuPathDB/web-eda/issues/1041  

Backend needs to know number of unique values of var in the dataset in order to determine if it’s a discrete continuous or continuous overlay: https://github.com/VEuPathDB/plot.data/issues/156 

Legend update to handle binned continuous variables (discretization of the continuous colormap): https://github.com/VEuPathDB/EdaNewIssues/issues/218

**Comment by bobular** [comment]
Mostly implemented in https://github.com/VEuPathDB/web-eda/pull/1186 but keeping this open until the discrete/continuous thing is addressed.

**Comment by bobular** [comment]
I can't see how we can test low-cardinality numeric variables right now. SCORE Seasonal/Mozambique and UMSP don't have such variables.

Shall we close this ticket @d-callan and @asizemore ?  I am happy to.

**Comment by danicahelb** [comment]
looking good!
