### ISSUE TITLE
Implement new Axis Range Controls on viz tab

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1097]
We want to include (as part of the axis controls) a button per axis to zoom to the range of data actually being plotted.

after mockups are approved (VEuPathDB/web-eda#1100) we will implement the zoom to plotted data buttons

**Comment by dmfalke** [comment]
I'm tentatively costing this as **medium**. We may need to adjust when mock-ups are done.

**Comment by danicahelb** [comment]
Discussed in 7/25, 7/29, & 8/1 EDA UX meetings:

[Mockups (see page labeled "Axis controls")](https://www.figma.com/file/LVDoPrzKkd1rCYJgdgCCKC/New-viz-tab-buttons%3A-(1)-clear-parameters%3B-(2)-reset-to-defaults-%2F-zoom-to-plotted-data?node-id=127%3A500) 

<img width="797" alt="image" src="https://user-images.githubusercontent.com/25450900/182264159-593dab58-7866-441d-bb0e-079054c52170.png">

**_We will have radio buttons for Axis range options: `Full` vs `Auto-zoom` vs `Custom`_**

**Full range:** Default axis range selection: `Full` (user will need to actively select `Auto-zoom` or `Custom` to change the axis range)
- Full range will always includes the origin, even if the dataset does not include 0. 
- Full range **minimum** should either be (i) a negative number (if the minimum value in the full dataset or annotated range is negative) or (ii) zero (if the minimum value in the full dataset is 0 or a positive number) 
- Full range **maximum** will be the maximum value in the full dataset or annotated range + any buffer needed for error bars, Confidence intervals, etc

**Auto-zoom**
- Auto-zoom range will always include the origin, even if the user has applied a filter that would have removed 0 from the subsetted data
- If a user chooses `Auto-zoom`, the axis range will be be zoomed to the range where there is corresponding y-axis data for every x-axis point (and visa-versa)… 
- Note: auto-zoom range can be different from the range of the variable in the subset. For example, in LLINEUP, participants in the study are between 0-110 years of age but microscopy was performed only on kids 2-10 years. If I filter LLINEUP to include participants 0-50 years, plot Age vs microscopy, and then select `Auto-zoom` the x-axis would extend from 0-10 (keep the origin!) even though the subset ranges from 0-50.

**Custom range:** User can have full control over the axes ranges
- If user types into the axis range selector boxes, the radio button selection auto-updates to `Custom`

**_Range selector boxes_**
- The text in the range selector boxes should indicate the range of the axes on the plot, not the range of the data in the full dataset or subset
- In the future, consider an additional table on each visualization that indicates the range of the full dataset vs the subset vs the plotted points

**Comment by danicahelb** [comment]
Hi @moontrip,

**For your first question:**

- The range selector boxes should only be active if the user selects "Custom". If the user selects "Auto-zoom" the range will change but in a way that is done automatically on the backend. If the user chooses either "custom" or "auto-zoom" and then later selects "Full", the range update will also automatically, back to the default

- for "Auto-zoom" and "Full", I prefer the disabled (ii) option where the input fields are greyed out.

- Is it possible to have the range selector boxes show different values for "Auto-zoom" and "Full"? For example--in a scatter plot-- if the x-axis ranges from 0 to 100 but the largest x-axis value that has a corresponding y-axis value is 50, then I'd like the range selector to show 0 to 100 for "full" but 0 to 50 for "auto-zoom"

**For your second question**

- yes, I agree with option b. input range fields should be read-only for "Auto-zoom"

Let me know if you have any more questions! Thanks

**Comment by moontrip** [comment]
@danicahelb Thank you for your detailed answers which would be helpful for my work. 👍 
As for the third bullet at the first question, I did observe a similar case that X-max from annotated data (meta data) has much larger than data-based X-max (Auto-zoom), so, in that case X-max in Full should have different value from X-max in Auto-zoom: Auto-zoom is basically data-based min/max (with origin in min). One of your comment earlier (Aug 1), you described this case, citing: "Note: auto-zoom range can be different from the range of the variable in the subset. For example, in LLINEUP, participants in the study are between 0-110 years of age but microscopy was performed only on kids 2-10 years. If I filter LLINEUP to include participants 0-50 years, plot Age vs microscopy, and then select Auto-zoom the x-axis would extend from 0-10 (keep the origin!) even though the subset ranges from 0-50."

**Comment by bobular** [comment]
Hi @danicahelb - I'm reviewing DK's excellent work on this ticket.

Re: **histogram** for a variable like "Temperature" in India ICEMR Cohort (which is reasonably within the range 32-39ish, unlike GEMS!) I can understand the "Full" range starting at zero but it seems intuitive that Auto-zoom would zoom to where the data is.

Personally, I think Auto-zoom for histograms should not always include zero, but this could be a topic of UX discussion.

**Comment by bobular** [comment]
Note also that for count-based axes (Histogram and Barplot when not in proportion mode) the Full and Auto-zoom options are the same.  Should we gray-out Auto-zoom in this case?

**Comment by danicahelb** [comment]
great feedback @bobular, I will add this to an upcoming UX meeting once the new axis range controls are up on the QA site

**Comment by danicahelb** [comment]
With the change mentioned directly above, there is no need to gray out the auto-zoom option for count-based axes.

**Comment by danicahelb** [comment]
auto-zoom now looks good with "temperature"



![Image](https://user-images.githubusercontent.com/25450900/197245997-fe56b4ad-ae57-401f-86ed-cc45ae00e156.png)
