### ISSUE TITLE
Switch position of X-axis controls and Y-axis controls on all viz tools

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1098]
Axes controls for X- and Y-axes should always be shown in that order (meaning X-axis is listed first, or on the left).

**Comment by moontrip** [comment]
Hi @danicahelb I wonder if we should always place the Y-axis controls in the right side for the case that there is no X-axis controls such as barplot and boxplot Vizs: currently it is in the left side (location of the X-axis controls).

**Comment by danicahelb** [comment]
Discussed in 5/16/2022 EDA UX meeting

@moontrip
When there are no x-axis controls, the y-axis controls should be left justified (this is the way things currently are on the live site)

<img width="977" alt="image" src="https://user-images.githubusercontent.com/25450900/168656265-a80f7025-a2f5-4b4b-b5f8-5494a155784b.png">

**Comment by moontrip** [comment]
@danicahelb Thank you for your information. I will comply with it 👍

**Comment by aaronwlsong** [comment]
Looks good, closing ticket. 

Randomly chose some studies and explored their line plots, mosaic plot and scatter plots (which contains both x-axis and y-axis), seems that they are all in expected order (x-axis is on left and y-axis is on right). 
<img width="1715" alt="Screen Shot 2022-06-02 at 9 42 30 AM" src="https://user-images.githubusercontent.com/61077845/171644404-7d2670ab-23f7-4b2e-a42a-665a9f10a7ef.png">
<img width="947" alt="Screen Shot 2022-06-02 at 9 42 49 AM" src="https://user-images.githubusercontent.com/61077845/171644407-da1661b8-3750-4e7c-8e2b-475f71b32726.png">
<img width="1018" alt="Screen Shot 2022-06-02 at 9 43 36 AM" src="https://user-images.githubusercontent.com/61077845/171644409-bb1dc179-f60d-489c-bc0e-43ff167e5d37.png">
<img width="1419" alt="Screen Shot 2022-06-02 at 9 45 07 AM" src="https://user-images.githubusercontent.com/61077845/171644412-76df0bab-eb50-435b-b648-4f56144f98f7.png">
<img width="1053" alt="Screen Shot 2022-06-02 at 9 45 24 AM" src="https://user-images.githubusercontent.com/61077845/171644416-5a769dbd-7c22-48cb-a68e-7de44b536e16.png">
<img width="1017" alt="Screen Shot 2022-06-02 at 9 45 39 AM" src="https://user-images.githubusercontent.com/61077845/171644417-e65c3f64-3602-4b28-a367-e3f1c1e5fbce.png">
<img width="999" alt="Screen Shot 2022-06-02 at 9 46 07 AM" src="https://user-images.githubusercontent.com/61077845/171644419-0f45c504-b1c1-4125-a761-889344ac5228.png">
