### ISSUE TITLE
standardize x- and y- axes ranges in all viz tools

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1099]
discussed in april 20, 2022 data viz meeting

We want to be consistent across visualizations with the default ranges on x- and y- axes. How the axes are scaled should depend on the type of axis rather than the type of visualization.

1. Axes representing **proportions** will scale 0-1 by default.
2. Axes representing **counts** will scale 0-{max value of bins seen in subset}. _Note, we may revisit the max value for count axes in the future, based on (i) user feedback and (ii) whether we can find a reasonable way to scale it based on something other than filtered data._
3. Axes representing **counts** (ie, integers) should only have ticks at whole numbers 
4. Axes representing user-selected **categorical variables** will include tick marks for all values in the data set regardless of filtering.
5. Axes representing user-selected **continuous variables** will scale according to _`study metadata`_ (for the whole data set) and -- if the resulting range does not include 0 -- it will expand as necessary to do so. _Note, we may revisit expanding the range to include 0 if we can think of a clever way to automate differentiation of ‘measures’ vs ‘counts’_ 

_`Study metadata`_ refers to using the annotated display range from the owl file (`defaultDisplayRangeMin`, `defaultDisplayRangeMax`) when available or the full data set range if not annotated)

**Comment by dmfalke** [comment]
I'm pretty sure this is all web-eda work, but it's possible there may be some backend changes needed.

**Comment by danicahelb** [comment]
Hi @moontrip Yes i think all of this still needs to be implemented. @d-callan should be able to answer specific questions.

**Comment by moontrip** [comment]
@danicahelb Thank you for your confirmation 👍

**Comment by danicahelb** [comment]
as noted in https://github.com/VEuPathDB/EdaNewIssues/issues/428

decimals on y-axis for count variables doesn't make sense. does the backend currently differentiate between numbers and integers? If so, integers (counts) should only have ticks at whole numbers
