### ISSUE TITLE
Apps: ensure display range min and max are numbers

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1107]
See https://github.com/VEuPathDB/microbiomeComputations/issues/17 for more details.

In short, displayRangeMin and max within computedVariableMetadata are currently strings. They should be numbers (they are numbers in the study metadata for continuous vars). This issue was blissfully hiding until a recent commit exposed it.

**Comment by asizemore** [comment]
Found a note that said we had the display range min and max as strings in order to better handle dates.
So instead of changing the api, i'll just force those to numbers when necessary. Changing the issue title to reflect this update.

**Comment by asizemore** [comment]
deployed to mbio feature. Moving to Ready for Testing

**Comment by asizemore** [comment]
@dpbisme to QA, please check that the following works: GEMS > Ranked abundance > Genus data and ranking method=median > boxplot. If the boxplot works as it does for any other collection, then we're good :)

**Comment by dpbisme** [comment]
@asizemore - this looks good to me!
