### ISSUE TITLE
Bar plot: proportion markers on the Map Viz Tool should display counts

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1114]
Discussed in 5/2/2022 EDA UX meeting.

Bar plot: proportion markers have a proportion ranging from 0-1 under the x-axis, which looks odd and is confusing (especially when all values are included, “1” is displayed on every marker). For example: "age group" in SCORE seasonal.

We decided that -- instead of displaying the proportion for the bar plot: proportion markers -- we will display counts making up each marker graphic. This is in line with what is being displayed for both bar plot: count markers and also pie markers.

Previous discussion can be found in this closed ticket: https://github.com/VEuPathDB/web-eda/issues/1025

NOTE FOR TESTERS: for the first time the back end's `sampleSizeTable` responses are parsed "in anger" by the front end. The parser needed some work and may fail (with pink errors) for other visualizations in edge cases (main cases have been tested). Please report any issues!

**Comment by moontrip** [comment]
I may be able to work for this but you can also do that @bobular if you have time: because I will be off from this Wed to the weekend.

**Comment by bobular** [comment]
Having a go at this now.

**Comment by bobular** [comment]
Closed because this ticket's PR #1137 was branched into #1186 and that has been merged. So, by extension, so has this. Sorry for the confusion.  I couldn't merge the earlier PR due to back end changes.

**Comment by nkittur-uga** [comment]
Tested with SCORE Mozambique ("Age group" and "S. haematobium, by microscopy") and it looks good!
