### ISSUE TITLE
Standardize behavior of `Reset to defaults` buttons across viz all tools

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1127]
In histogram it resets the bin width, but in lineplot it doesn't.  It should probably be consistent, but feedback from ClinEpi folk would be helpful.

**Comment by danicahelb** [comment]
Discussed in 7/25 EDA UX meeting

Folks are generally happy with the placement & functionality of the reset button in the [mockups](https://www.figma.com/file/LVDoPrzKkd1rCYJgdgCCKC/New-viz-tab-buttons%3A-(1)-clear-parameters%3B-(2)-reset-to-defaults-%2F-zoom-to-plotted-data?node-id=10%3A154):
<img width="405" alt="image" src="https://user-images.githubusercontent.com/25450900/180867955-b2adca5f-01c4-47b8-8d43-fc32aa31d716.png">

@Ann Blevins and Styling WG should pick a better icon for the “reset to default” buttons

**Comment by danicahelb** [comment]
reset to default button: https://github.com/VEuPathDB/CoreUI/issues/111

**Comment by moontrip** [comment]
For Outreach/UI/UX team: Current plan is to use Undo icon only to replace Reset to defaults button as shown in https://github.com/VEuPathDB/web-eda/issues/1127#issuecomment-1194586363. But Bob and I think that icon with text looks okay as well (see below screenshot), thus it would be great if you can choose which one is better - the change in between icon without text and icon with text is quite simple.

![196177163-e5a0e519-6dc1-4952-9fa6-c4d3cae41345](https://user-images.githubusercontent.com/12802305/196244617-5e6f225c-1e5b-4510-98b6-93672aae2e43.png)

**Comment by bobular** [comment]
Oh, I thought since you (@moontrip) fixed the tooltip width problem, we'd go with the text-less version?

I prefer that, at least.

**Comment by moontrip** [comment]
@bobular yes the implementation is certainly icon **without** text (merged) as suggested earlier, but I wanted to ask the team if they prefer icon **with** text like above, just in case :)

**Comment by sweverschulman** [comment]
plot reset is consistent across different plots
