### ISSUE TITLE
Subsetting results modal primary and foreign keys should contain "ID" in label

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1128]
Currently, columns representing primary and foreign keys in the subsetting results tables just say "Household", "Participant", "Participant repeated measure", etc.

We need to clarify that these are unique identifiers. Please update the labels to add "ID" to the end of all column headers for these keys, making sure to use sentence case:

Household ID
Household repeated measure ID
Participant ID
Sample ID
etc...

we want to roll this out along with the styling updates to the modal: https://github.com/VEuPathDB/web-eda/issues/935

**Comment by dmfalke** [comment]
This change can be made here: https://github.com/VEuPathDB/web-eda/blob/c4c7246d9bf944160226d7e32cd6291533de2664/src/lib/workspace/Subsetting/hooks.ts#L53
