### ISSUE TITLE
Apps: add vizs to an app instance based on configuration

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1130]
After discussion with Dave, we think it would be advantageous to modify how we handle apps and vizs. 

In short, we propose having a 1:1 relationship between (App type, configuration) and app instance. 

When a new visualization is created, it's configuration should be either the default set of parameters or the most recent configuration used with that app. The visualization gets added to/created in the app instance that has those same parameters. If the user changes the parameters, then the viz should get taken out of the previous app instance and then added to the app instance that now matches the new configuration. App instances get created whenever a visualization is made with that configuration for the first time.

**Comment by asizemore** [comment]
@jernestmyers it's likely that in addressing the other tickets, this one will get addressed as well

**Comment by jernestmyers** [comment]
Indeed, this is getting addressed by [the work in this PR](https://github.com/VEuPathDB/web-eda/pull/1149).

**Comment by asizemore** [comment]
Closing thanks to [1149](https://github.com/VEuPathDB/web-eda/pull/1149). Assigning to dan for qa. Deployed to feature.
