### ISSUE TITLE
Minor viz tab thumbnail page adjustments

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1134]
I propose the following updates to the thumbnail page:
1. Changing the "+ New Visualization" button to a regular button (useful for mbio, not sure yet about clinepi)
2. Adding the "My visualizations" header to the page
3. The first time the user lands on this page, there is some friendly help text that says "To get started, add a new visualization" or similar.

<img width="1267" alt="Screen Shot 2022-05-13 at 2 53 53 PM" src="https://user-images.githubusercontent.com/11710234/168353782-0393a579-66e9-44d2-b7d9-98a340f1d0e8.png">

@danicahelb do you think clinepi would be interested in all three of these changes? Or just a subset?

**Comment by danicahelb** [comment]
Discussed in 5/16/2022 EDA UX meeting.

1. ClinEpi would also like to change the styling of the "+ New visualization" button, to the one Ann proposed above

2. We would like to add breadcrumbs to the top of the viz tab to help with navigation

**It is unlikely that we want to make these changes also, but we are still awaiting a final decision:**

- Add friendly instructions for the first visit to the page

- Add "My visualizations" header

@asizemore if you could explain your rational for these additional changes, please let me know and I will make the case to the ClinEpi team

**Comment by asizemore** [comment]
@danicahelb are there breadcrumb mockups somewhere?

**Comment by asizemore** [comment]
Also note if we only change the button styling (no header added) the page will be very empty when a user first arrives:

<img width="1337" alt="Screen Shot 2022-05-23 at 7 41 59 AM" src="https://user-images.githubusercontent.com/11710234/169844805-97ce1eda-d531-4fb1-868c-59a3c6b4dc97.png">

**Comment by asizemore** [comment]
The breadcrumbs may also address my above concerns, so im open to seeing what those look like!

**Comment by danicahelb** [comment]
I started mockups here: https://www.figma.com/file/LsbPRQbJw4qNTERLO3SKPt/Viz-tab-thumbnail-page?node-id=0%3A1

**Comment by danicahelb** [comment]
6/17/2022 EDA UX decision: We will not add “My visualizations” header or friendly instructions to the top of the visualization tab

@asizemore see current plan to improve overall UI for the viz tab here: https://github.com/VEuPathDB/web-eda/issues/1122
