### ISSUE TITLE
Subsetting: Styling of histogram subsetting controls

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#114]
Too blue, too big, lose the "Axis Controls" - lose surrounding box.  Hope for more breathing space to x-axis

**Comment by bobular** [comment]
Could look into grey/dark grey focus issue

**Comment by steve-fischer-200** [comment]
the x-axis and y-axis controls look bad when forced to wrap, with a more narrow screen.  minimally they should be the same width.  or, like live site, when wrapped, take up full screen width

**Comment by danicahelb** [comment]
This seems to be fixed. @bobular can you take a look at this ticket & close if fixed?

![image](https://user-images.githubusercontent.com/25450900/134996339-62bdb4e7-967e-405e-962a-87ef36ca34d5.png)

**Comment by bobular** [comment]
I think it's basically fixed now.  It's not any smaller/more compact but I've got used to it this size and think it's OK.
Danica's screenshot looks a bit messed up, but that's a **very** narrow screen.  I checked at 1280px and 1024px and it looks fine.

Closing this ticket.
