### ISSUE TITLE
mapViz: thumbnail does not work correctly for some baselayers

### ISSUE THREAD

**Issue by moontrip** [VEuPathDB/web-eda#1142]

**Comment by moontrip** [comment]
While testing mapViz with react-leaflet v3, Bob noticed that thumbnails do not work properly for all baselayers except the default one, 'Street'. I have also tested the cases and confirmed that they did not work. Since it is related to v3, it would be addressed at the react-leaflet v3 PR, https://github.com/VEuPathDB/web-components/pull/347

As a part of v3 tests, I found that similar issue existed at the current mapVis, which utilizes react-leaflet v2: thumbnails for some baselayers do not show correct image. This will be sought in this ticket.

**Comment by bobular** [comment]
This has been discussed in a react-leaflet-v3 thread: https://github.com/VEuPathDB/web-components/pull/347#issuecomment-1133019184 

But I want to bring this back to v2/b58 land...

I have just tried a longer (2x previous = 2000ms) timeout (in MapVEuMap.tsx in web-components) and the problem still occurs: the "Terrain" layer doesn't seem to work at all (the default tile layer always shows up in the thumbnail) and the "Light" layer is still patchy.

Unless anyone has any bright ideas, I think we should let this slip to b59. It's purely cosmetic and only affects Chrome (as far as I know) - the layer choices are still remembered and render fine in the normal-sized viz.  The [Chrome performance bug](https://github.com/VEuPathDB/web-components/issues/360) also concerns the screenshotting plugin and should take priority. 

@danicahelb - move to b59?

**Comment by moontrip** [comment]
I think that this was addressed by me and Dave before, so closing: current mapViz is now working fine with thumbnail.

**Comment by SAK22** [comment]
Terrain not working, OSM looks like the thumbnail for terrain. Satellite, if I go into a visualisation and change to satellite, the thumbnail does not change.

**Comment by moontrip** [comment]
@SAK22 Thank you for your review. I just tested https://qa.clinepidb.org/ and they worked correctly for me. Please note that there are 2 second delay to create thumbnail so please wait a while after changing layer then minimize the viz to see the thumbnail. It would be great if you can test it again 👍

**Comment by SAK22** [comment]
Ah yes if I counted to 3 then closed it you are right! All good.
