### ISSUE TITLE
Download tab: disable whole study section for mbio beta release

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#1145]
The whole dataset files for mbio are unlikely to be ready by the initial beta site release. Is it simple to either put "Coming soon!" or just totally remove the Full Dataset section of the Downloads tab? 

If i understand correctly, the My Subset portion is just generated by the eda so as long as the eda works, that section will work.

**Comment by asizemore** [comment]
Related to https://github.com/VEuPathDB/MicrobiomeWorkflow/issues/13
If the above can't be resolved within a reasonable timeframe, we'll have to move forward with simply disabling the whole dataset download part of that tab for mbio.

Note i checked today and the current behavior is that once we click on the download tab it shows an error box. But if you clear that box, the My Subset downloads work great.

**Comment by dmfalke** [comment]
I see two requests that are failing on that page, fwiw:
![image](https://user-images.githubusercontent.com/365139/170123895-0350328d-d876-419f-8331-229868ee2054.png)

Not sure if they are related, but we could probably catch these errors and handle them in such a way that the error modal doesn't appear.

**Comment by asizemore** [comment]
Related to https://github.com/VEuPathDB/EdaLoadingIssues/issues/37

**Comment by asizemore** [comment]
Update: sounds like loading the full dataset files may not happen by b59. So if it's easy to simply catch the error so that the modal doesn't appear, that'd be a really helpful fix until we can get the download files

**Comment by dmfalke** [comment]
The latest update is that the downloads files might be ready, after all. I will wait until I hear otherwise to work on this. @asizemore please update this issue if/when that time comes. Thanks!

**Comment by dmfalke** [comment]
This was addressed by adding the table `DownloadVersions` to the mbio model.

**Comment by asizemore** [comment]
Thanks @SheenaTomko ! This is all expected. The full dataset files aren't ready yet, so we should only be seeing the subset options.
Not seeing the preview table is a separate [issue](https://github.com/VEuPathDB/EdaNewIssues/issues/405) that has to do with the size of the data tables.

So as long as when you select the Downloads tab, you don't get hit with an error, then this ticket would be good!

**Comment by SheenaTomko** [comment]
Great, moving this to complete
