### ISSUE TITLE
Apps: improve default configuration

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#1147]
For each app, define a default configuration that pre-populates the app parameter selection dropdowns. Currently the defaults are the first entry in the collections or methods arrays.

Default configuration:
Alpha diversity
- Collection variable ("Data"): If the study has metagenomic data, choose the WGS Species as the collection. Else if 16S Genus exists, choose 16S Genus. Else pick first collection var in the collection list (i dont think it'll ever come to this but just in case)
- Method: shannon

Ranked abundance
- Collection variable ("Data"): Same as for alpha diversity
- ranking method: median

NOTE: @asizemore to find out actual terms for 16S Genus and WGS Species. Data is currently being reloaded so i'll update with the correct terms once the data is back and then will make this into a real issue!

**Comment by asizemore** [comment]
Discussed in ux meeting on 01/13. We're removing default parameters. Closing ticket and moving to complete.
