### ISSUE TITLE
visualizations: scatter plot axes need log scale toggles 

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1153]
David was trying to recreate this figure for a talk:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/25450900/170085518-a7ad7cc7-8df8-46f1-b5a2-c5f043eed818.png">

The best approximation he could make was:

<img width="963" alt="image" src="https://user-images.githubusercontent.com/25450900/170085626-51ba5ffa-8b2a-42d0-bfca-7b472b8763d7.png">

the user needs to be able to choose to plot things on log scale for both x-axis and y-axis data on scatter plots but also other plot types (so please add log scale toggle)

**Comment by danicahelb** [comment]
hey @moontrip can you add a little buffer to the plot margins so that the data points don't get cut in half? thanks!

this example was using PRISM2 ICEMR

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/25450900/171283919-674d71d4-1ced-4326-b715-637599aff8f5.png">

**Comment by moontrip** [comment]
Thank you for letting me know about that @danicahelb 👍 It may not be that easy to make it happen because of the nature of log scale, though I will try/test and see

**Comment by moontrip** [comment]
> hey @moontrip can you add a little buffer to the plot margins so that the data points don't get cut in half? thanks!
> 
> this example was using PRISM2 ICEMR
> 
> <img alt="image" width="1243" src="https://user-images.githubusercontent.com/25450900/171283919-674d71d4-1ced-4326-b715-637599aff8f5.png">

This suggestion is now addressed so ready for QA.

**Comment by danicahelb** [comment]
looks good 
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/25450900/172711799-447f14c8-0bc7-4f8d-b25d-1ec842a89814.png">

**Comment by moontrip** [comment]
@danicahelb Thank you for your tests and review! 👍
