### ISSUE TITLE
vizualizations need toggles to log scale axes

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1157]
building on the emergency ticket (VEuPathDB/web-eda#1153) to add log scale toggles to the scatter plots in time for David's PRISM SAB presentation, we want to also add log scale toggles to other viz types.

Next step is for the data viz group to discuss which axes of which vizs we need to do this for.

To do:

- [x] Change "Log Scale" to "Log scale"
- [x] Disable log toggle while in scatterplot line-fit modes (instead of current behaviour that forces the user back to "raw" mode)
- [x] disallow log scale in binned line plot 
- [x] ensure at least two tic marks on log scale axes (in `web-components`)
- [x] if a user-inputted axis range is active, and it starts at or below zero, then when switching on logscale for that axis, the zero or negative value must be reset to minPos
- [x] provide a notification when all values are negative for a particular axis (scatterplot and lineplot at least) - example to test with is Weight for age Z-score vs age group in a line plot (all the means are negative) - can also use filters on household wealth, for example
- [x] disable logScale when error bars are in force

**Comment by asizemore** [comment]
At the data viz meeting, we decided to allow log axes for continuous vars when not dates or bins:
- line plot
- scatter
- gradient colormaps (when they come along)
- map markers y axis of bars

Additional decisions
-  For scatter plot, we should not allow trendlines and log scale at the same time. The log scale can always be available, but if i'm in smoothed mean mode and click log scale, the plot mode goes back to raw
- when choosing new var, should go back to linear scale
- Want to disallow log scaling if the data has already been transformed. So we should add a var attribute to flag if the var has already been log transformed
- If plotting a var with 0s or negative values and a user toggles on the log scaling, the data truncation indicators should appear to let the user know we can't plot 0 or negative values.

**Comment by danicahelb** [comment]
WRT disallowing log scaling if the data has already been transformed...
Currently, if data is provided to us on a log scale, we load that variable as is and annotate `"scale" = log` (or ln, etc) in the .owl file. The database is not currently reading this information in, but should be by b60 (see: https://github.com/VEuPathDB/EdaSubsettingService/issues/64)

In the future, we will allow the user to transform data, possibly via derived variables or some other mechanism. How would the user-log transformed variables be flagged?

**Comment by danicahelb** [comment]
@moontrip i moved this out of "this cycle" as it is only a nice to have and we are in crunch time for b58. thanks!

**Comment by danicahelb** [comment]
Discussed in 7/13/2022 DataViz meeting. Log scale is a problem for terms with negative or zero values

**Decisions:**

1. Disallow log scale if variable’s annotated range minimum is < 0
2. Allow log scale if variable’s annotated range minimum = 0. Show truncation indicators when cutting off values at 0.
3. Disable log scale when line plot error bars are on. Reasoning: (i) Lower bound of the error bar can be negative; (ii) Error bars are calculated for display on a linear scale

**Comment by danicahelb** [comment]
Discussed in 7/13/2022 EDA UX meeting

Decision 1 in the comment above is no longer accurate. Instead:

- All continuous variables can be plotted on a log scale, regardless of whether the minimum value is less than zero or not
- Data less than or equal to 0 will removed from the plot when the log scale is selected, and truncation indicators will be used to show that values below 0 are cut off
- We will include messaging next to the log scale toggle, similar to messaging next to geometric mean selections on line plot (see figma [mockups](https://www.figma.com/file/BEZ9fdHolDuj4NGICqj4qs/Line-plot-%2B-geo-mean?node-id=21%3A722)) 
 
`Log scale (will exclude values ≤ 0):`

See comment in: https://github.com/VEuPathDB/web-eda/issues/1228

**Comment by SheenaTomko** [comment]
Changes look good
