### ISSUE TITLE
map tool down in QA clinepi

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB/web-eda#1174]
When looking at the SCORE Mozambique and other studies I get this error @bobular.
<img width="1186" alt="Screenshot 2022-06-06 at 17 23 26" src="https://user-images.githubusercontent.com/22981342/172202912-f7c13a71-cfe6-4fe9-802e-75d447d28892.png">

**Comment by danicahelb** [comment]
confirmed, maps are working. thanks!
