### ISSUE TITLE
Enable column sorting on subsetting results tables

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1176]
It would be great if we could allow users to sort the subsetting results tables by one of the columns, and allow both ascending and descending ordering. Thanks!

**Comment by dmfalke** [comment]
FYI, the service already supports this: https://veupathdb.github.io/EdaSubsettingService/api.html#resources:/studies/{study-id}/entities/{entity-id}/tabular:post (see `reportConfig.sorting`)

**Comment by SAK22** [comment]
Looks good!
