### ISSUE TITLE
Viz tab: add * next to labels for all required fields

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1177]
Add an asterisks next to the label for all required fields in all viz tools:

Main* (histograms / bar plots / maps)
X-axis* (scatter / line / mosaics/ box plots)
Y-axis* (scatter / line / mosaics/ box plots)
Function* (line plots only, to be implemented in https://github.com/VEuPathDB/web-eda/issues/1038)
Proportion* (line plots only, to be implemented in https://github.com/VEuPathDB/web-eda/issues/1038)

For example:

<img width="875" alt="image" src="https://user-images.githubusercontent.com/25450900/172232177-26114a47-9139-442e-8684-06eb861439b3.png">

**Comment by danicahelb** [comment]
Hey @jernestmyers we discussed this in the 6/6/2022 EDA UX meeting. We decided to go with black asterisks... it will be more subtle but that is ok. The team preferred visual simplicity.

Thanks!

**Comment by jernestmyers** [comment]
Looks good on the feature mbio backend! Screenshot below is from `Bangladesh 5yr > Alpha Div > Box plot` but I also checked other config/viz combos and they all checked out.

![image](https://user-images.githubusercontent.com/69446567/177813524-f0c3433b-602d-4332-9ad3-ce8f6bf79dbe.png)

**Comment by asizemore** [comment]
Great! Thank you for checking @jernestmyers ! And with that confidence i have now deployed the same data service fix to qa so it should be on clinepi shortly if not already.

**Comment by asizemore** [comment]
@jernestmyers just a heads up - the data service upgrade broke a few other things on mbio so i reverted to an older tag. The data service upgrades you need are still on clinepi qa though!

**Comment by nkittur-uga** [comment]
Looks good. Required components are in red with (*) and turn black once selected.
