### ISSUE TITLE
Map viz: incorporate improved back end behaviour for "overlay" data requests

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1191]
The back end (`map-markers-overlay`) now does several new things
1. For categoricals with >8 values, the "best 7 + 1" will be reported for the viewport data, not total subset
2. It can accept bin range from the client, and will return a list of bin labels in numeric order, including any empty bins.

On the client side we have fully specified the overlay bin range and width (like we do for histograms) for continuous vars.

When there are >8 values for categoricals (only testable in UMSP at the moment) then we have some special logic for resetting any manually checked legend items.

### QA advice

Don't test UMSP (because it isn't public, performance is tricky, and we possibly have some issues with date variables in `map-markers-overlay`), just use **SCORE Seasonal** and **SCORE Mozambique**

So no need to test >8 value categoricals. Please just test the hell out of those two studies (they don't have many variables).  There are no date variables we can test in these studies either.

**Comment by danicahelb** [comment]
if high cardinality variable (like district in UMSP), we only show the top 8
you want to see the top 8 in the current viewport, and should change as you move around the map

**Comment by bobular** [comment]
> if high cardinality variable (like district in UMSP), we only show the top 8 you want to see the top 8 in the current viewport, and should change as you move around the map

That's correct.

If there are fewer than 8 in the vocabulary, they are shown in vocabulary order and the colours don't change.

**Comment by SAK22** [comment]
SCORE seasonal just keeps freezing on me (the map) so cannot change variables

**Comment by bobular** [comment]
Is this **SCORE S. mansoni Cluster Randomized Trial** ? @sweverschulman 

I think it might be. It has an occupation variable.

**Comment by sweverschulman** [comment]
Yes @bobular. Its SCORE S. mansoni Cluster Randomized.

**Comment by bobular** [comment]
@sweverschulman  "Other" is the union of all other values for this variable, so that is correct.

**Comment by sweverschulman** [comment]
ah. that makes sense. Thank you for clarifying. Then this ticket should now pass qa and can be moved to complete.

**Comment by bobular** [comment]
But maybe we need to show that it's a dynamic, generated 'Other', compared to many other variables in ClinEpi with actual 'Other' strings stored in the db?

**Comment by sweverschulman** [comment]
@bobular if we could somehow make that clear, that would be great. But I don't know if that is needed for this release. @danicahelb could you confirm.

**Comment by bobular** [comment]
Not for this release. Needs UX discussion I believe.

**Comment by danicahelb** [comment]
@bobular please make a ticket for clarifying the UX for this, we will get to it for b59

**Comment by bobular** [comment]
Sure thing --> https://github.com/VEuPathDB/EdaNewIssues/issues/326
