### ISSUE TITLE
Bug: addition of stratification variables resets other selections (like range)

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1195]
Bug: when I add a stratification variable, this resets the x-axis range graph parameters, so I have to go back to reset the range … this is annoying, and forces user to wait to reload again (doesn’t reset bin controls, which is good).

This is especially problematic when looking at large datasets like UMSP

**Comment by bobular** [comment]
Poss relevant to https://github.com/VEuPathDB/web-eda/issues/1338

**Comment by SAK22** [comment]
Looks good!
