### ISSUE TITLE
Legend colors for discretized colormaps (continuous overlays) needs styling fix

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1200]
For discretized colormaps used with continuous overlays, the darkest color is currently representing the smallest value, and the lightest color currently represents the largest value. 

<img width="283" alt="image" src="https://user-images.githubusercontent.com/25450900/173114004-574c0291-9d02-4c0c-9aab-dd820f194203.png">

It would be more intuitive if the darker values instead corresponded to the largest values.

**Comment by aaronwlsong** [comment]
It seems this issue still there. Tested two studies containing this variable on map, the darkest color represents the smallest value.

![Image](https://user-images.githubusercontent.com/61077845/186929597-f89b428d-6271-4a1d-a08e-bf4428e8a091.png)

![Image](https://user-images.githubusercontent.com/61077845/186929598-341305b8-a5f4-4ce3-8dbb-91bea17b94e8.png)

**Comment by moontrip** [comment]
@aaronwlsong Thank you for tests and review. Can you please let me know what system you have used? Is it qa, qa restricted, or feature (link would be helpful). 

Actually I could see correct color order with the same exaple at my dev environment as follows, so I need to check the live site.

![s-niger-map1](https://user-images.githubusercontent.com/12802305/186933837-e344f2a8-ac7a-4491-ade7-d346bda2ffff.png)

**Comment by moontrip** [comment]
@aaronwlsong I have tested this at qa site, https://qa.clinepidb.org/, and it seems to work fine in there. Here is a screenshot with the same example. Just in case can you please hard refresh your web-browser? (typically short cut key with CTRL+F5 in chrome)

![qa-site-legend-color](https://user-images.githubusercontent.com/12802305/186934452-f8331387-7f94-4e92-8d4b-5f051996f2ea.png)

**Comment by aaronwlsong** [comment]
@moontrip , Thanks for following-up this ticket. I tested it on qa.website: https://qa.restricted.clinepidb.org/
You are right, after I cleaned my caches, I can see the correct the color order~~~! Sorry for that confusion. I will change it to complete.~~~:)

**Comment by aaronwlsong** [comment]
Latest update for QA result: Looks good now, closing tickets.



![Image](https://user-images.githubusercontent.com/61077845/186940403-633eed0a-1fd9-4bdf-8ba3-ddd77de325db.png)

**Comment by moontrip** [comment]
@aaronwlsong No problem! 👍 I’m glad it turned out to be not a critical issue 😃
