### ISSUE TITLE
Fix scrolling behavior of subset download modal

### ISSUE THREAD

**Issue by chowington** [VEuPathDB/web-eda#1207]
The way scrolling works in the subset download modal isn't the best UX. See https://github.com/VEuPathDB/web-eda/issues/1169

**Comment by danicahelb** [comment]
Discussed in 7/1/2022 EDA UX meeting

The separate scrollable sections for the variable tree and for the data table are looking really nice!

The header is wasting a lot of the modal's real estate. Please make these changes:
- For longer study titles, do not wrap the title onto 2 lines. Instead, shorten with ellipses and show the full title on mouseover
- Make the analysis name the 2nd line in the header, under the study title
- analysis name and entity counts can be placed on the upper left side of the modal, below the header

**Comment by sweverschulman** [comment]
I can confirm that three dots and the mouse over do work. However, the mouse over is a little bit delayed, as if it needs to "think"

Could @chowington or @danicahelb confirm that this is ok, before I officially sign off.


![Image](https://user-images.githubusercontent.com/62298921/182877693-dbf1e618-0307-4d89-a439-da77ab7c9978.png)

**Comment by danicahelb** [comment]
I agree, it takes a long time for the mouseover text to appear. @chowington how difficult would this be to speed up?

**Comment by chowington** [comment]
Not bad. This is due to us using different tooltip methods in different areas of the site. The styling group will discuss harmonizing tooltips at a future meeting. For now I will use a tooltip component that appears faster than the current method.

**Comment by sweverschulman** [comment]
The mouseover text speed has increased dramatically and there is no longer a long lag.
