### ISSUE TITLE
Map viz: Clarify to users that the "Other" category is dynamic

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1219]
When there are more than 8 categories (SCORE S. mansoni randomized controlled trial-->Occupation is an excellent example that I didn't know about during implementation/testing) in the overlay variable, the back end will calculate the top 7 individual categories, and then lump everything else remaining into "Other".

We need to have some UX discussions how best to communicate this to users.  They may see "Other" as an actual database-stored value in the same or other studies.

**Comment by dmfalke** [comment]
I moved this to web-eda, but we can move it again, if we decide to handle this on the backend.

**Comment by danicahelb** [comment]
I'm closing this ticket. We have decided that Other should NOT be dynamic. This ticket will change the variable constraints to prevent high cardinality variables from being used on the map: https://github.com/VEuPathDB/EdaNewIssues/issues/596
