### ISSUE TITLE
Viz: set a correct log scale range and truncation

### ISSUE THREAD

**Issue by moontrip** [VEuPathDB/web-eda#1228]
This includes two issues:

- set a correct log scale range
While I was working on truncation for log scale in Viz, which is a sub task of https://github.com/VEuPathDB/web-eda/issues/1157#issuecomment-1144909026, I realized that a log scale range is incorrect. When I implemented log scale before, I used a minimum range of 0.1 for all Viz concerning log scale, following the criterion used in the histogram filter by Bob. It is probably fine for histogram or barplot because they are of great interest on the maximum value, not minimum one. However, I found that for scatter and line plots, there may be a case where some data  values are smaller than 0.1 (but still larger than 0), which lead to not showing some data in the plot: below screenshot is an example case of a scatter plot using **GEMS1**. One can see that the y-axis min value still shows negative value and the graph is cut from 0.1 (not that visible in the plot but it is actually 0.1 at min range in the plot, though). In addition, a correct log scale range, especially for minimum value, is important aspect for displaying truncation. 

- truncation when log scale
As mentioned above, this is a sub task of https://github.com/VEuPathDB/web-eda/issues/1157#issuecomment-1144909026, but since this task also depends on log scale range above, this is separated from the original ticket. The requirement is like this: "If plotting a var with 0s or negative values and a user toggles on the log scaling, the data truncation indicators should appear to let the user know we can't plot 0 or negative values."

![scatter-qa-log](https://user-images.githubusercontent.com/12802305/175976599-797557e1-698d-40c2-9495-819b251cd17b.png)

**Comment by danicahelb** [comment]
Discussed in 7/18/2022 EDA UX meeting

All continuous variables can be plotted on a log scale, regardless of whether the minimum value is less than zero or not 

Data less than or equal to 0 will removed from the plot when the log scale is selected, and truncation indicators will be used to show that values below 0 are cut off

We will include messaging next to the log scale toggle, similar to messaging next to geometric mean selections on line plot: 
`“Log scale (will exclude values less than or equal to zero):”`

**Comment by SheenaTomko** [comment]
This looks great now
<img width="703" alt="Screen Shot 2022-08-09 at 1 05 40 PM" src="https://user-images.githubusercontent.com/54597319/183713472-cbcb30bd-c003-4d50-9a03-7a04cc933a90.png">
