### ISSUE TITLE
Viz tab: when log scale toggle is engaged, we cannot select a range < 1

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1232]
David Roos noticed this. 

We cannot set the range selector to <1 when the log scale toggle is on. In the screenshot below, I tried to select a range minimum of 0.1 and it would not work:

<img width="339" alt="image" src="https://user-images.githubusercontent.com/25450900/174900214-599f85fd-ba8e-46fb-a18c-0d207bca68b2.png">

**Comment by moontrip** [comment]
I have tested this issue with the recent PR concerning Viz range/truncation/log scale for Viz plots that have log scale option such as Histogram, Bar, Scatter, and Line plots. It looks like this is automatically resolved by introducing a correct axis range (by Bob and me), thus I will just link this issue to the PR. 

Here is an example screenshot with Histogram using GEMS1. The default dependent axis range for this case starts from 0.1, but I could change it as other small value, e.g., 0.001, without trouble.
![histogram](https://user-images.githubusercontent.com/12802305/182944447-bab02291-7238-44e6-8156-a94b20fdfc09.png)

**Comment by bobular** [comment]
Cool, thanks DK!

**Comment by SheenaTomko** [comment]
This looks good now
