### ISSUE TITLE
subsetting: in histogram for numerics, limit precision of the reported Mean

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/web-eda#124]
for example, in GEMS, see the "Age at eligibility form completion" variable.  the mean is "17.7058093676607"

probably should use the (upcoming) `precision` meta-data field (and add 1).

Also take care of line wrapping (comment below)

**Comment by bobular** [comment]
Duplicates a subtask of #117 that isn't in its title

**Comment by dmfalke** [comment]
This is computed by the backend plugin, right? Maybe that is the place to limit number of digits after decimal.

**Comment by bobular** [comment]
The scientist in me says keep the number at the highest precision until the
very last moment...

**Comment by dmfalke** [comment]
Yeah, I'm okay with that. Do you think we should show the full value on
mouseover?

**Comment by bobular** [comment]
We could do, but I don't think it will be useful if we show 4 significant
figures already.
If we show fewer sig. figs. then probably yes.

**Comment by bobular** [comment]
@d-callan made this observation on Slack

> the summary stats above the histos on the subset tab sometimes wrap to the next line. and occasionally when this happens it breaks the line on the colon, which i found confusing the first time i saw it. looked like there was no max value..

We should be careful how lines are broken when resizing to a smaller browser width.

**Comment by d-callan** [comment]
so i had made a similar issue in plot.data... if you want to handle it, should i close that one?

**Comment by dmfalke** [comment]
The backend isn't currently provided the `precision` property. For now, I can just default to showing up to 3 decimal places.

**Comment by dmfalke** [comment]
I opened in issue for the missing property: https://github.com/VEuPathDB/EdaSubsettingService/issues/12

**Comment by d-callan** [comment]
Id do 4 decimal places I think.
