### ISSUE TITLE
Swap toggles for CoreUI Switch

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1252]
CoreUI has a `Switch` component intended to replace the toggles, and listens to the site theme. Let's exchange instances of toggles for the CoreUI `Switch`.

Not a high priority, but fun and low cost i'd guess.

**Comment by dmfalke** [comment]
I scheduled this for this release. It's a nice bit of cleanup :slightly_smiling_face:

**Comment by chowington** [comment]
@asizemore Do you think we should also replace the custom toggle (and other custom widgets as appropriate) in web-components? They're used mainly in the plot controls

**Comment by asizemore** [comment]
@chowington yes i think that'd be great! Thank you! They should be using the primary theme color i'd think?

**Comment by SheenaTomko** [comment]
Looks great! Replaced in drop down menus, below stratification variables, and in plot parameters below plots
