### ISSUE TITLE
Mbio downloads: extra spaces and capitalization getting added

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1257]
Only observed in the downloads tab for 16S assay entities.

The entity name is "16S rRNA (V4) assays". Curious why some of the text is getting transformed to uppercase (the r in rRNA) and some extra spaces are appearing?

<img width="393" alt="Screen Shot 2022-07-13 at 4 49 11 PM" src="https://user-images.githubusercontent.com/11710234/179256062-91e8281b-ef04-4e29-ad69-3842a76f8369.png">

**Comment by asizemore** [comment]
As of now this fix has only been deployed to clinepi qa, not to mbio feature yet. I'll be deploying to mbio feature later this evening and will update this issue when it's done!

For clarity, when qa-ing this ticket please check that
1. the text on the subset download buttons looks good in clinepi
2. the text on the subset download buttons for 16S entities matches the text in the entity tree for mbio 
(really, all the text in these buttons should match the entity diagram now)

**Comment by asizemore** [comment]
deployed to mbio feature. Ready for qa on both sites!

**Comment by SheenaTomko** [comment]
This looks great on both sites!
