### ISSUE TITLE
MALED PRM subsetting results downloads has many duplicated columns for Age

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1264]
I am trying out the subsetting results download for MALED participant repeated measures (live site). I noticed that I am getting ~20 columns of duplicated “Age (days)” data (ie, the mergeKey term). This only happens if I add several variables to the results download; if I just add a single variable to the results download this doesn’t happen. any idea what is going on???

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/25450900/180567121-d400fcff-6ee3-4c64-8e64-d8260c373af8.png">

@dmfalke said: "i suspect the client code is adding that key multiple times"

**Comment by dmfalke** [comment]
The client code is indeed adding the **Age (days)** variable multiple times.
