### ISSUE TITLE
Remove hardcoded clinepi-specific text

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1266]
<img width="1723" alt="Screen Shot 2022-07-25 at 10 40 02 AM" src="https://user-images.githubusercontent.com/11710234/180803872-493385ed-8bdf-45fc-958d-2cd08d767e50.png">

While on mbio, i get a warning about making the analysis appear on the ClinEpiDB page. I propose we change the language to say
"This analysis will appear on the Public analyses page." Alternatively, we do get the project name so we might be able to use that in the text.

**Comment by dmfalke** [comment]
A quick search shows that we use the string "ClinEpiDB" in a few places. We should never hardcode a website name in the project.

**Comment by asizemore** [comment]
Seems like it should be possible to use the `projectId` var which we use to filter apps ([line](https://github.com/VEuPathDB/web-eda/blob/8e149f94a57fb4be89918aa47da26698e6e378d7/src/lib/workspace/ComputationRoute.tsx#L41))? 

Otherwise we should just make the text here and in [Variables.tsx](https://github.com/VEuPathDB/web-eda/blob/main/src/lib/workspace/Variable.tsx) general. 

Between Variables.tsx and this public analysis warning, i think that's all the hardcoded website names!

**Comment by dmfalke** [comment]
We should either make it generic or use https://github.com/VEuPathDB/WDKClient/blob/6d01ca1a547f9c8df65c5bd6d3ff597da9fe3313/Client/src/Service/ServiceBase.ts#L73. If the latter, we might want to make it a toplevel prop for `WorkspaceRouter` and make it available via a hook.

**Comment by SheenaTomko** [comment]
Looks good
