### ISSUE TITLE
User datasets: Disable the public checkbox for user datasets

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#1268]
On the "My Analyses" page, we need to remove the ability for users to make an analysis public on a user dataset. User datasets aren't released, so it shouldn't be possible to make a public analysis. May want to do this by greying out the check box, removing it, or exploring other options.

<img width="1219" alt="Screen Shot 2022-07-25 at 12 41 13 PM" src="https://user-images.githubusercontent.com/54597319/180830543-7d60f144-8a9d-4cc1-bd8c-3146c1a86646.png">

**Comment by jtlong3rd** [comment]
To address this issue, I'll only enable the checkbox for studies which are public, controlled, or protected. 

(Context: https://epvb.slack.com/archives/C0132PM1MT5/p1631641982133200?thread_ts=1631639802.128800&cid=C0132PM1MT5)

**Comment by SheenaTomko** [comment]
Looks great!
