### ISSUE TITLE
LLINEUP viz tab histogram for "age" fails

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1272]
On the live site & also on qa.clinepi:
In the LLINEUP study with no filters, I tried to plot "Age" in the viz tab histogram, and got this error msg:
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/25450900/179316771-ad824b0d-9298-4fb3-840d-349e89947fb0.png">

**Comment by dmfalke** [comment]
This is either due to an incorrect io-ts type on the frontend, or an incorrect value from the backend.

**Comment by bobular** [comment]
Seems solved by https://github.com/VEuPathDB/plot.data/issues/182 moving to ready for testing

**Comment by sweverschulman** [comment]
Age histogram forL LINEUP is no longer throwing an error and displaying on the site. 

![Image](https://user-images.githubusercontent.com/62298921/183676230-755a5e4e-e3ec-40df-b354-dc0d7d0d8c0d.png)
