### ISSUE TITLE
Bug: order in which plot controls are applied determines if the plot appears or not

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1279]
Using LLINEUP, In the viz tab bar plot tool, I select "cluster as treated for my main variable.

Then, I change the y-axis range to 0-0.5. The graph updates as expected.

Next, without changing my range selections, I click on the log scale toggle button. The plotted data disappears:
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/25450900/179318026-dcdaed62-e5a0-4809-9585-a693349db2f7.png">

If I change the order of operations and 1st click the log scale toggle and 2nd update my range selections, my plot looks good:
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/25450900/179318399-22f9e264-158b-4113-9144-0484439b2c69.png">

**Comment by moontrip** [comment]
I have tested this with the latest PR that involves several Viz changes, https://github.com/VEuPathDB/web-eda/issues/1228. I cannot reproduce the issue reported in this ticket so it seems like those changes might have fixed this issue as a byproduct. So, I am linking this issue to the PR, instead.

**Comment by SheenaTomko** [comment]
Looks good
