### ISSUE TITLE
make beta div-specific viz selector icon

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1287]
App-specific viz selector icons:

- [ ] Ranked abundance box: boxes decreasing in height
- [ ] Ranked abundance scatter: two trends?
- [ ] Beta div scatter: look clustered
- [ ]

**Comment by asizemore** [comment]
@dpbisme ideas for alpha div box and scatter?

**Comment by asizemore** [comment]
After much thought, I decided against making app-specific visualization selector icons except in very specific situations. Consider that in the future, ranked abundance and alpha div will have box, scatter, and line plots. So we'd need three different viz selector icons for line plot. This won't scale well. 

Instead, i propose that unless a user will be prevented from clicking on the icon when using the default version, use the default version associated with the viz type. For example, in beta div we use a scatter plot, but the computation is defining both axes so the plot is really more a "pcoa plot", for lack of a better name. Users don't think of this viz as a scatterplot with defined axes.

@d-callan

**Comment by danicahelb** [comment]
@asizemore can we close this ticket?

**Comment by asizemore** [comment]
Not yet. I still need to implement the finalized icon for beta div.

**Comment by asizemore** [comment]
This is done. I'm happy with what we have :)

To QA, please just verify that the scatterplot viz icon and the beta div viz icon are different. Tanks!

**Comment by SheenaTomko** [comment]
Looks great!
