### ISSUE TITLE
Viz tab: allow log scale toggle even when error bars are toggled on (lineplot)

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1291]
In 8/1/2022 EDA UX meeting, @bobular demo'd his work on improving viz tab log scale & axis truncation functionality. 

Currently, the user cannot choose log scale for the y-axis if error bars are turned on in the line plot. 

It would be better if toggling on log scale auto-toggles off error bars (and visa versa). Please add a snackbar to alert the user that this has happened

**Comment by bobular** [comment]
Clarification of requirements:

line plot: 

For 
- x-axis for logs and binning
- y-axis for logs and error bars

Turning on logs will cancel binning or error bars, with a snackbar explaining why.
Turning on bins or error bars will cancel logs, with a snackbar explaining why.


scatterplot: if the user is in a fitted line mode, the log scale button is still active. when clicked, it kicks the user out of fitted line mode back into raw points mode. with a snackbar explaining why  (and vice versa, choosing the fitted plot modes will kick the user out of logscale mode)

**Comment by nkittur-uga** [comment]
Snackbar is working nicely as intended.
