### ISSUE TITLE
Lineplot and histogram vizualizations: improve truncation warning behaviour

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1295]
### The issue

Currently, most plots only display axis truncation warnings when data from the *current subset* has been excluded by user axis ranges.

However, for lineplot (when binning) and histogram x-axes, there is a problem.

Study: India ICEMR Severe P. vivax and falciparum Cohort
Filters: filter on Temperature, so that just the middle values are present (e.g. 37 to 37.5)
Then make a histogram and adjust the ranges slightly inwards (but nowhere near the filtered range) - this is what we call "zooming".

![image](https://user-images.githubusercontent.com/308639/183443084-7ee621e7-837f-41a7-af29-319e3d1dd83f.png)

Note that the warnings are displayed even though no data was cut off.

### Implementation notes

We'll need to make a special unzoomed data request in order to get the true xMin and xMax of the filtered subset.  Though if we're not zooming, we should avoid making this twice.  We'll probably have to move the data request into a custom hook.

**Comment by dmfalke** [comment]
Making a second request for the unzoomed data is not ideal. Could the data service tell us if we're leaving out data points (cc @asizemore)?

**Comment by asizemore** [comment]
sorry i don't quite follow yet - do we know is different about the binned requests/responses (binned line and histo) and the non-binned requests/responses that cause the issue? I guess why do we not have the xMin and xMax of the filtered subset information for binned axes but we do in raw datapoint axes?

**Comment by bobular** [comment]
Update!

As of today, the above example now has no yellow bars (my filter is slightly different, ignore that):
![image](https://user-images.githubusercontent.com/308639/202723784-b654d6ea-dfa5-4150-b954-b897858481e9.png)

But if we zoom in, we also don't get yellow bars (which ideally, we should)

![image](https://user-images.githubusercontent.com/308639/202724058-3b4c5739-ec78-4677-8aa8-8f5653d00118.png)

The problem is basically that the yellow bar check is made using min and max values determined from the back end response. When sending a `viewport` in the request to the back end (e.g. for zooming in) the back end (correctly) returns only data within that viewport.

There's an existing comment from me in LineplotVisualization.tsx along the same lines:

```
      // This useBinning edge case handling is a bit of kludge.
      // The same situation affects the histogram independent axis (all the time).
      // The problem is if you make a data request for an x-axis viewport (aka zoom to range), then
      // the xMin and xMax are calculated from the response, which is just for the requested
      // viewport.  Using the data-derived xMin and xMax works great for client-side zooming,
      // because the data doesn't change. But for server-side zooming we can't use xMin and xMax from
      // the response.
      // Two possible solutions I can think of:
      // 1. Client makes a request for unzoomed data to get the xMin and xMax, and remembers this.
      // 2. Server returns the truncation flags for us, somehow.
```

Not urgent, but I'm thinking more and more that if the back end could return the truncation flags, that would be ideal. @d-callan
