### ISSUE TITLE
Subsetting: Anchor variable tree search bar to top of scroll container

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#13]
It should always be visible when the user is scrolling.

Here is an example from clinepidb.org:
![image](https://user-images.githubusercontent.com/365139/112055451-3ee64680-8b2d-11eb-922f-a3f96c73429f.png)

**Comment by moontrip** [comment]
@dmfalke This is addressed at https://github.com/VEuPathDB/web-eda/commit/cc96f05d55a3e102f998bd8bf6b913125ec5cba5 
As noted at Slack, the height of tree list is temporarily set to 50vh for now

**Comment by dmfalke** [comment]
Thanks, @moontrip! We should link this issue to the PR so it gets closed when the PR is merge.

**Comment by moontrip** [comment]
@dmfalke I think probably Bob needs to set additional CSS for Subsetting viz tab purpose :) Anyway, I will make PR but the commits also involve typescript one (VariableList.tsx) which needs your (soft) touch haha.

**Comment by moontrip** [comment]
this was reviewed/approved/merged by Dave so I am closing this issue
