### ISSUE TITLE
SCORE Mozambique variable gives 500 error in map viz overlay for School-age children in village count

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1301]
Looks like this bug https://github.com/VEuPathDB/plot.data/issues/179 is back!

Although this time it's **School-age children in village count** (last time it was School-age children **treated** in village count, which works fine now)

Study: **SCORE Mozambique S. haematobium Cluster Randomized Trial**
Viz: map
Variable: School-age children in village count

In the logs the error is now:
```
Error in plot.data::validateBinRange(xVals, binRange, "NUMBER", FALSE) : 
  Invalid bin range provided: Bin range cannot represent a subset of the data range.
```

Update for testers:

If there is no pink warning, all is good!

**Comment by bobular** [comment]
I reckon that rounding ought to make use of the new R function I made the other day... (But I'll port it to JS don't worry.)

**Comment by nkittur-uga** [comment]
No pink warning, all is good!
