### ISSUE TITLE
Something very wrong with some log-scale proportion-mode map chart markers

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1313]
SCORE Mozambique S. haematobium Cluster Randomized Trial
Map viz
Variable = School age children in village count

The markers are empty, and the mouse-over enlargements are upside down.

Something wrong with the dependentAxisRange passed to the markers  `{"min":-14570,"max":0.5}`

![image](https://user-images.githubusercontent.com/308639/184380006-0472aaa0-6ec7-4c93-9b7d-825383809b92.png)

**Comment by dmfalke** [comment]
Can’t help but wonder if this has something to do with recent updates impacting svg processing

**Comment by bobular** [comment]
No I think it's untested proportion+log mode.

**Comment by dmfalke** [comment]
> No I think it's untested proportion+log mode.

😁

**Comment by bobular** [comment]
> > No I think it's untested proportion+log mode.
> 
> grin

Doesn't affect all variables though.  Investigating now. Don't expect it's too tricky to fix.

**Comment by dmfalke** [comment]
Is it related to negatives?

**Comment by bobular** [comment]
It's something wrong with the significant digit manipulations I introduced...

**Comment by bobular** [comment]
A TO DO was to add some tests for this function!

**Comment by bobular** [comment]
Though it is partially related to negatives.  I forgot an `abs(x)` in the JS port... :roll_eyes:

**Comment by dmfalke** [comment]
Let me know if you need orientation to writing tests.

**Comment by bobular** [comment]
> Let me know if you need orientation to writing tests.

Thanks, yes please I do, but maybe others do too, so we could schedule an overspill meeting some time.

**Comment by sweverschulman** [comment]
The map and bar chart seem to be working correctly however, it seems as if x axis label is cut off
<img width="871" alt="Screen Shot 2022-08-16 at 2 34 58 PM" src="https://user-images.githubusercontent.com/62298921/184953927-91471823-11bd-464a-b814-8552bfdd1cf3.png">

**Comment by bobular** [comment]
Thanks Steph. I made a new issue for that
