### ISSUE TITLE
Scatter plots with trend lines and no overlay variable seem to have lost their legend

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1316]
The legend was useful for disabling the point data to see the trend line more clearly.

Maybe this was intentional?  Probably not!

**Comment by aaronwlsong** [comment]
Seems the legend has not beed added in scatter plot when there is smooth line and **NO** overlay variable.

<img width="1331" alt="Screen Shot 2022-09-22 at 9 35 03 AM" src="https://user-images.githubusercontent.com/61077845/191761705-3967f748-954d-4433-b5bf-d7c00e696b16.png">

**Comment by moontrip** [comment]
@aaronwlsong Thank you for your tests. I wonder what study you used for the plot? For example, I have tested qa site with GEMS1 case control but it worked just fine as shown in the below screenshot.

![GEMS1](https://user-images.githubusercontent.com/12802305/191817745-d45679ac-c52c-4fca-a0cb-515bb49165fb.png)

**Comment by aaronwlsong** [comment]
Hi @moontrip, I used ELICIT Randomized Controlled Trial. You are right, after I hard refresh my laptop, it shows up. Thanks a lot for letting me know~~! I am gonna close this ticket~~~:)

**Comment by moontrip** [comment]
@aaronwlsong Thank you for your information and quick tests and confirmation! 👍 Sounds great it worked 😃
