### ISSUE TITLE
Test that date variables work in new map marker overlay

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1323]
I've just seen in the map visualization source code several "TO DOs" related to handling date variables as the overlay.

There are no such variables in SCORE studies and UMSP seems unavailable to me on qa.restricted even when logged in.

So we have not given it much thought.

We need to be on top of this when the popbio data reaches EDA, so just making a ticket to remind us.

Could involve front and back end work.

**Comment by chowington** [comment]
Is this ticket still relevant? @bobular @dmfalke

**Comment by bobular** [comment]
It's likely still very relevant @chowington 

**Jilinde Prospective Cohort** seems to not have geolocation map support at the moment, so we can't work on it right this minute :-(

**Comment by steve-fischer-200** [comment]
Also make sure the new overlay plugin stuff works in regular visualizations.

**Comment by jernestmyers** [comment]
I'm off today, so I'll un-assign myself and let someone else pick this up. When I first looked into this, most continuous vars were silently failing. But I haven't tested things for a week or two.

**Comment by bobular** [comment]
Did some diagnosis/debugging and filed https://github.com/VEuPathDB/EdaDataService/issues/278

**Comment by chowington** [comment]
Looks like with the completion of https://github.com/VEuPathDB/EdaDataService/issues/278, this is working now
