### ISSUE TITLE
Full Screen Map: full screen component

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#1327]
This issue is about implementing the React component that will be used for the full screen computation/app. See the [mock-ups](https://docs.google.com/presentation/d/17Yg4Kz00pW6wbNo3bK0DpQjW4cVEzrq0VQ75pw1xZNc/edit). Note that for this issue, we are planning to only support **Visualize** mode. Thus, we will not need the **Subset | Visualize** toggle.

In addition to the MapVEuMap component, we will need the following:

- [x] #1347
- [x] Viz selector modal. (See https://docs.google.com/presentation/d/17Yg4Kz00pW6wbNo3bK0DpQjW4cVEzrq0VQ75pw1xZNc/edit#slide=id.g13e1893ab5c_0_310)
- [x] Floating viz component for active viz. (See https://docs.google.com/presentation/d/17Yg4Kz00pW6wbNo3bK0DpQjW4cVEzrq0VQ75pw1xZNc/edit#slide=id.g13e1893ab5c_0_333)
- [x] Update computation config based on map interactions.

Note that we might want to use an icon for viz thumbnails since thumbnails can frequently become invalid since they are sensitive to the map viewport.

Also note that we still need to finalize what the computation configuration (aka, ui config) will look like.

**Comment by bobular** [comment]
See preliminary work already started for this ticket https://github.com/VEuPathDB/web-eda/issues/1307
