### ISSUE TITLE
Clean up computation-related parts of the visualization plugin API

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1329]
In preparation for compute service wiring, take stock of what we have and consider how it could be cleaned up.

**Comment by d-callan** [comment]
impl might look something like the following pseudo, included here mostly as a summary of current thinking:

```
variables: VariableMetadata[]

VariableSpec:
    variableId: string
    entityId: string

VariableClass:
    type: string
    values: ['native', 'derived', 'computed', 'collection']

VariableMetadata:
    class: VariableClass
    variableSpec: VariableSpec
    displayName?: string
    displayRangeMin?: number | date
    displayRangeMax?: number | date
    vocabulary?: string[]
    members?: VariableSpec[]
```

where variables is incorporated as part of the existing config obj of the data service plugin responses, and also as part of the new metadata endpoint in the compute service. technically `members` is only needed for collections and the display ranges, names and vocabs for non-native types.

**Comment by d-callan** [comment]
this is going to end up seeing work in loads of places. first three where i refactor the api:
https://github.com/VEuPathDB/EdaCommon/pull/19
https://github.com/VEuPathDB/service-eda-compute/pull/36
https://github.com/VEuPathDB/EdaDataService/pull/214

next will require some work in the various R packages to meet the new api, then on to the front end devs to accomodate the new api.

**Comment by d-callan** [comment]
i figure i can have EdaCommon, EdaDataService and Rserve still on the branches while the frontend work is done since this is likely breaking.. @dmfalke let me know if you had other plans.

**Comment by bobular** [comment]
I'd be up for having a crack at the client side, if, as you say, the service code is all on branches/images I can fire up from docker-compose.

**Comment by d-callan** [comment]
Rserve and eda data builds on the branch seem to have succeeded

**Comment by SheenaTomko** [comment]
compared ECAMs ranked abundance and alpha diversity plots on the feature and beta site. No differences spotted
