### ISSUE TITLE
Bug in hiding variable from variable tree

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#1330]
The term EUPATH_0038405 (Cause of death, from autopsy) in SIP is supposed to be hidden in the variable tree but available on download. Right now it appears everywhere. Other terms like Village ENVO_01000773 and 'Kebele (subdistrict) in Ethiopia' EUPATH_0038722 have also been hidden from the variable tree in SIP and are working correctly. Not sure why this variable is being treated differently.

This study is not yet released and only on qa.restricted

**Comment by dmfalke** [comment]
I believe the problem has to do with the logic for finding the root of the variable tree in this code: https://github.com/VEuPathDB/web-eda/blob/1f1972cbc765419ea2f59d201e6f1a887460ab19/src/lib/core/utils/wdk-filter-param-adapter.ts#L260-L294.

Note that traversal begins at the end of the function, with the variable whose parent ID is the same as the entity ID (i.e., its parent ID is not defined). No such variable exists for the entity **Participant Repeated Measures**. Thus, the variables of that entity are not being traversed. We need a more resilient way to find the root variable.

**Comment by sweverschulman** [comment]
I can confirm that EUPATH_0038405 (Cause of death, from autopsy) is currently hidden on the variable tree but available for download

![Image](https://user-images.githubusercontent.com/62298921/200013432-23ac59d9-d567-44b0-bb8c-660a28247157.png)



![Image](https://user-images.githubusercontent.com/62298921/200013440-5f90b321-6ffc-42b3-a61e-155056b5749a.png)
