### ISSUE TITLE
Full Screen Map: Implement FullScreenMapApp

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#1334]
This depends on #1326, #1327, #1333

- [x] Define UI state
- [x] Create a modified set of visualizations based on those used by the pass app. This will include passing options to disable faceting and provide an overlay variable.
- [x] Render map using the FullScreenApp component (see #1327)
- [x] #1368

**Comment by jernestmyers** [comment]
Closed in 09/28/2022 EDA dev meeting.
