### ISSUE TITLE
bugs on histogram and barplot Vizs with proportion

### ISSUE THREAD

**Issue by moontrip** [VEuPathDB/web-eda#1350]
While I am checking/working on https://github.com/VEuPathDB/web-eda/issues/1099, especially the first and second one (count and proportion), I noticed at least two bugs concerning the plot mode of proportion, thus histogram and barplot Vizs are related. Below are demo examples for those cases with histogram Viz.

a) proportion and logscale on: It looks like minPos (nonzero minimum positive value) is not computed correctly thus somehow dependent axis range min is still zero

![histogram-bug2](https://user-images.githubusercontent.com/12802305/188729502-1b5f37b3-70dd-4ecd-a9c1-6619aa9c7262.png)

b) incorrect truncation with proportion: currently, the range of min max for proportion is set to 0 to 1 for proportion. In the following variable, the max value is less than 0.2. Thus, if, for example, we change the dependent axis range max is 0.5, then truncation (yellow) bar should not be shown, however, it is now shown like data is truncated.

![histogram bug1](https://user-images.githubusercontent.com/12802305/188729700-4af211d1-8065-4d3f-83f4-9088d387a8ed.png)

**Comment by moontrip** [comment]
I found another bug. Somehow, the min and max values can be the same, which causes incorrect plot and truncation warning like below

c) 
![histogram-bug3](https://user-images.githubusercontent.com/12802305/189147543-3744b97d-916e-4948-a5fa-d5472bb5b587.png)

**Comment by nkittur-uga** [comment]
Bugs have been fixed. Min and max values are not allowed to be the same. QA is complete.

**Comment by moontrip** [comment]
@nkittur-uga Thank you for your tests and reviews! 👍
