### ISSUE TITLE
Full screen map has dragging issues

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1367]
This seems to only happen when floating visualizations are open. I suspect it might be some kind of circular state (something coming back from the saved user analysis?) but I can't see an obvious culprit.

To reproduce (in `fsm-all`)
1. open FSM
2. put up a barplot
3. move the map
4. shortly after the barplot has finished updating, drag the map again
5. you should see the map jump back to where you started dragging (and the barplot will update again)

Tested also with boxplot - same issue (and assume same for all)

**Comment by bobular** [comment]
Also, try cancelling the overlay variable (top right panel) at step 4 instead of dragging the map.  That also gets reset.

Wait a few seconds first and it's fine.

**Comment by nkittur-uga** [comment]
No dragging issues seen.
