### ISSUE TITLE
Beta diversity app styling

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1374]
- [ ] Run app button
- [ ] App status indicator
- [ ] Adding helpful text over plots and thumbnails

Mockups: https://www.figma.com/file/0Z6cCnTNg1yAaFGEOXQZeg/Microbiome-apps?node-id=1002%3A9959

**Comment by chowington** [comment]
@danicahelb Are these mockups finalized, and do you know if the backend can support this yet? Just wanting to get some more info about this work :)

**Comment by asizemore** [comment]
Replacing this issue with #1555 . See #1555 for finalized mockups. Closing
