### ISSUE TITLE
line plot - minor issues with Y-axis aggregation 

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1381]
2 minor issues with **Y-axis aggregation**

- [x] for both continuous & categorical Y-axis variables, the question mark icon is a bit too close to the parameter title. Please add a bit more space
<img width="249" alt="image" src="https://user-images.githubusercontent.com/25450900/191057717-887c72c9-2456-442f-bfa1-2e817366c1ca.png"> 

- [x] for continuous Y-axis variables only, I cannot click on the arrow to bring up the dropdown menu. Currently, I need to click on the text itself. Please expand the area where the user can click to the entire grey box.

**Comment by jernestmyers** [comment]
Resolved by https://github.com/VEuPathDB/web-eda/pull/1371 and https://github.com/VEuPathDB/web-eda/pull/1354

**Comment by sweverschulman** [comment]
The "?" has better spacing and I can click on the down arrow to also get the drop down. 
<img width="224" alt="Screen Shot 2022-10-11 at 12 03 14 PM" src="https://user-images.githubusercontent.com/62298921/195142919-236e7526-f244-47d6-8939-adf577a615f1.png">
