### ISSUE TITLE
Mosaic plot (2x2 and RxC) table view needs styling fix for legibility

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1382]
Discussed in 9/12/2022 EDA UX mtg

Current table view of 2x2 and RxC Mosaic plots are hard to read

<img width="551" alt="image" src="https://user-images.githubusercontent.com/25450900/189739370-b49a0aa1-a1f3-4c9e-a716-6ca792c378f7.png">

**suggestions for improvement:** 
- Right-justify everything
- Make the variable labels more clear, use different font from the value labels
- Consider rotating the y-axis variable label 90 degrees
- Use boxes around every cell, with heavier weight boxes separating the values from the totals

@Danica will make mockups and pass around via slack

**Comment by danicahelb** [comment]
Also add percentages (%) to the table.



![Image](https://user-images.githubusercontent.com/25450900/202023469-b123ebfc-2ddf-4631-b8a4-cf43ccd07a5a.png)

**Comment by jernestmyers** [comment]
Adding percentages looks messy with several x-values, like so:
![image](https://user-images.githubusercontent.com/69446567/202036964-2115d8f4-1b28-43f0-b454-4e2bd2096a37.png)

Currently, we set a `750px` width on the table. I'm not sure how many variables would render this many columns, but we should think about how we'd like to handle this formatting. Possible options are:
1. increase the allowable width (could set the `width` explicitly or use `min-width` and/or `max-width`)
2. use a horizontal scrollbar if width exceeds `750px`
3. render the data on two lines: render the value above its percentage
4. other

**Comment by danicahelb** [comment]
discussed in 11/21 UX meeting

We will put percentages on a second line, below counts as 1st iteration

If this doesn’t solve the issue completely, we can consider other potential solutions:

- toggle between counts vs percentages
- expand allowable width & implement scrolling

**Comment by nkittur-uga** [comment]
Looks good!
