### ISSUE TITLE
Mosaic plot (2x2) more information box for parameters - finalize styling & implement

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1383]
As discussed in 8/29/2022 EDA UX meeting, we need a new explanatory information box that allows users to read help / additional information so the sure can refer to it while they are making parameter selections for visualizations or apps.

In ClinEpi, we will use the explanatory info box for the 2x2 mosaic viz tool. The box will be open by default until all required plot parameters are selected, then will auto-close (but the user can click to expand/reopen)

In mBio, an explanatory information box that is open during parameter selection is also needed for many of the mbio apps

The Styling WG should meet to discuss the styling (including header verbiage) of the explanatory info box.

Danica mocked up the function of the box in action in the 2x2 mosaic tool, but styling needs help! https://www.figma.com/file/Su1eNm3Bby85CfrnX42L7q/2x2-table-UI?node-id=20%3A116

Changes to the 2x2 UI cannot happen until decisions on the styling of the box have been made

**Comment by dmfalke** [comment]
I think this is related to https://github.com/VEuPathDB/CoreUI/issues/114, in that we might want to first implement a "CollpsibleSection" component in CoreUI, and use that for this info box.

**Comment by jernestmyers** [comment]
We finalized our style decisions [in this Slack thread](https://epvb.slack.com/archives/C02R14DUYLX/p1665586919851079). Final mockups can be found [here](https://www.figma.com/file/Su1eNm3Bby85CfrnX42L7q/2x2-table-UI?node-id=139%3A233&t=sRnMJ2CGeNmUYsMM-1).

**Comment by danicahelb** [comment]
@moontrip this ticket and https://github.com/VEuPathDB/EdaDataService/issues/130 should be rolled out to QA at the same time

**Comment by danicahelb** [comment]
Discussed in 1/23/2023 EDA UX meeting

@moontrip we made a few (hopefully easy!) changes to the UI:

1. We want to move the position of the more information box to _ABOVE_ the selectors
2. We want to change the verbiage of the first line to: `Learn how to set up a 2x2 contingency table in order for statistics to be calculated correctly. Read less...`

<img width="711" alt="image" src="https://user-images.githubusercontent.com/25450900/214135209-5de0f1a0-559e-4de9-8fc3-305569106111.png">

**Comment by danicahelb** [comment]
**Styling decisions approved**
- background color - blue, like banners
- border - gray, like other containers
- toggle collapse/expansion icon - single arrow/caret
- info icon - include dark blue info icon

More info here: https://www.figma.com/file/Su1eNm3Bby85CfrnX42L7q/2x2-table-UI?node-id=139%3A233&t=C7dsTpu6Y9mLsmoz-0

**Comment by nkittur-uga** [comment]
Looks great.
<img width="1079" alt="Screenshot 2023-02-27 at 4 52 29 PM" src="https://user-images.githubusercontent.com/67710160/221694256-517bfc75-d708-4158-94e6-23ca445dbca6.png">
