### ISSUE TITLE
Mosaic plot (2x2) - statistics tab frontend updates

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1384]
For the 2x2 mosaic plot viz tool, mockups for the statistics tab can be found here: https://www.figma.com/file/Su1eNm3Bby85CfrnX42L7q/2x2-table-UI?node-id=123%3A233

**Comment by dmfalke** [comment]
Related to https://github.com/VEuPathDB/CoreUI/issues/114 and #1383

**Comment by moontrip** [comment]
@danicahelb May I ask a couple of questions regarding this ticket and relevant one (https://github.com/VEuPathDB/web-eda/issues/1383)?

First, I made a collapsible banner and screenshots can be found in https://github.com/VEuPathDB/CoreUI/pull/129#issue-1453839015, which is a mock up for #1383. But from my understanding, there are no Quadrant input variable yet, thus the banner won't be included till the Quadrant input variable is made, right? (Quadrant work is not part of #1383 nor #1384 (this ticket)).

Second, this is a question for this ticket, statistics tab updates: a) If I understand correctly, we will also have a separate banner for this tab only. Can you please confirm this? b) the scoop of this work is to have statistic table too? It is currently shown as "Coming soon".

**Comment by danicahelb** [comment]
Hi @moontrip thanks for raising this topic!

I apologize, this key ticket got lost in the shuffle! https://github.com/VEuPathDB/EdaDataService/issues/130 (the ticket title, major feature & release info are now up to date)

Yes, the stats tab will have a separate banner. See: https://www.figma.com/file/Su1eNm3Bby85CfrnX42L7q/2x2-table-UI?node-id=123%3A234&t=eO7GflQwHS5GJltr-0

We are still finalizing the stats tab and need to make decisions on:
1. what stats to include
2. table layout
3. verbiage for the banner

Please pause work on this ticket until the stats tab has completed review by the EDA UX group

**Comment by danicahelb** [comment]
styling ticket for stats tab: https://github.com/VEuPathDB/web-eda/issues/1253

**Comment by danicahelb** [comment]
backend tickets to calculate the various statistics: https://github.com/VEuPathDB/EdaNewIssues/issues/533 & https://github.com/VEuPathDB/EdaNewIssues/issues/534

We would like to roll out these stats for b62:

1. Chi-square
2. Fischer's exact
3. Prevalence
4. Odds Ratio
5. Risk Ratio

There are an additional 4 stats related to diagnostic test performance, backend for these may not be ready for b62. If backend is NOT ready, please leave placeholder rows in the table with "Coming soon" where the stats would be

**Comment by danicahelb** [comment]
Mockups have been finalized: https://www.figma.com/file/Su1eNm3Bby85CfrnX42L7q/2x2-table-UI?node-id=391%3A637&t=C7dsTpu6Y9mLsmoz-0

95% CI should each be given 2 decimal places

P values should be given to two significant figures, unless p<0.0001

**Comment by nkittur-uga** [comment]
I'm running into this bug when I try to construct a 2x2 table. I will QA this ticket once the bug has been fixed and the plot/stats can be made. 
<img width="1417" alt="Screenshot 2023-02-22 at 12 10 43 PM" src="https://user-images.githubusercontent.com/67710160/220704734-24af03b0-d695-40b6-9e31-fd0acc76e69c.png">

**Comment by moontrip** [comment]
@nkittur-uga Thank you for your information. I have double checked with the backend response (statsTable) just in case that I misallocated values to be displayed but I think the backend did return the same one with the frontend display.

@d-callan Can you please take look at this? Thanks in advance 👍

**Comment by d-callan** [comment]
I think this is due to a difference in how we calculate the odds ratio. From the site linked in a previous comment I see: "Where zeros cause problems with computation of the odds ratio or its standard error, 0.5 is added to all cells (a, b, c, d) (Pagano & Gauvreau, 2000; Deeks & Higgins, 2010)." 

We aren't doing this, and since we instead have NaN I suspect this is the issue.

**Comment by danicahelb** [comment]
@d-callan there are no zeros here, unless I am missing something?
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/25450900/222214024-c4674cfa-cf3b-4d40-b044-150dbae17216.png">

**Comment by danicahelb** [comment]
I used this calculator and got this: http://vassarstats.net/odds2x2.html

<img width="754" alt="image" src="https://user-images.githubusercontent.com/25450900/222214720-28ca489d-67a3-410c-b472-225597ef2abf.png">

**Comment by danicahelb** [comment]
Using this site (which sets up their table differently than us): http://vassarstats.net/odds2x2.html

<img width="704" alt="image" src="https://user-images.githubusercontent.com/25450900/222222171-7da3adb3-6780-4803-8534-0fc225883351.png">

**Comment by danicahelb** [comment]
I've hand checked the calculation for Odds ratio and Risk ratio, using the formulas in our more information dropdown.

I get the same numbers as the calculator:
Odds ratio = 5.63
Risk ratio = 2.04

So the risk ratio point estimate is also wrong.

Please check & fix calculations for:
- Odds ratio 95% CI
- Risk ratio point estimate
- Risk ration 95% CI

**Comment by danicahelb** [comment]
statistics calculations should be addressed in: https://github.com/VEuPathDB/plot.data/issues/202 (which also failed QA)

**Comment by danicahelb** [comment]
@moontrip, can you confirm that you are using the right values for Sensitivity, Specificity, PPV and NPV?

It seems like values for (i) Sensitivity and PPV are swapped; and (ii) values for Specificity and NPV are swapped. I don't know if this should be fixed on the frontend or backend

See more info here: https://github.com/VEuPathDB/plot.data/issues/203

**Comment by moontrip** [comment]
@danicahelb I left my comment with the screenshot of the backend response at https://github.com/VEuPathDB/plot.data/issues/203#issuecomment-1450727474

**Comment by danicahelb** [comment]
@moontrip can you please capitalize the first letter in both words of `Odds Ratio`? thanks!

**Comment by moontrip** [comment]
@danicahelb I have made the corresponding PR to address your request. Here is a screenshot. Please feel free to let me know if you need further change(s)

![mosaic-stats-table-rev1](https://user-images.githubusercontent.com/12802305/223794659-af24114b-23d2-4b35-bfb2-d0c6ae40e5e2.png)

**Comment by danicahelb** [comment]
@moontrip can you also change `Case control or Cross-sectional studies` to `Case control & Cross-sectional studies`

**Comment by moontrip** [comment]
@danicahelb new screenshot with the change:

![mosaic-stats-table-rev2](https://user-images.githubusercontent.com/12802305/223796845-40ce2ec9-938c-484a-81be-d73d44231a1f.png)

**Comment by danicahelb** [comment]
looks good! 

![Image](https://user-images.githubusercontent.com/25450900/224182540-2610f93f-6c0d-435c-a1df-f2e523dfbd1b.png)
