### ISSUE TITLE
Visualizations: make thumbnail capture optional for visualizations, and disable for FSM floating vizs

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1390]
Thumbnail generation was partly involved with fixing the looping problem identified during testing an issue with floating visualizations and checkbox changing https://github.com/VEuPathDB/web-eda/pull/1362

We don't need thumbnails for floating vizs so let's add a prop to make them optional, then add an option override boolean to the FSM vizs.

This may also solve #1367 - though that needs more careful debugging.

**Comment by bobular** [comment]
This is done, right? Open again if I'm wrong ;-) @chowington

**Comment by chowington** [comment]
Never saw this ticket, lol

**Comment by bobular** [comment]
I confirm nothing is user-QA-able here

**Comment by SAK22** [comment]
Spoken to @bobular, this updates things behind the scenes but has solved ticket https://github.com/VEuPathDB/web-eda/issues/1367
