### ISSUE TITLE
Histogram visualization: y-axis proportion numbers not formatted correctly for date variables in logscale mode

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1396]
It looks like 4 digit formatting of logscale proportion y-axis ticks is inappropriate. Compare with a non-date variable to see what it should look like. There's no need to treat the y-axis differently for dates/non-dates in this situation, because it's showing counts or proportions. Never dates.

Screenshot is for LLINEUP Cluster Randomized Trial on qa.

![image](https://user-images.githubusercontent.com/308639/193624214-fd7e1ed0-7077-40c0-a7b3-c954cd987dbc.png)

**Comment by bobular** [comment]
PS. ignore the red warning border around the bin width - that is already reported [here](https://github.com/VEuPathDB/web-eda/issues/1274#issuecomment-1265309212)

**Comment by bobular** [comment]
Looks like there is a related but not identical bug in lineplot

The tick marks should not be the default Plotly single digit minor ticks: 2,3,4,5,6,7,8,9 

But THIS SEEMS FIXED in https://github.com/VEuPathDB/web-eda/pull/1369 - thanks DK

![image](https://user-images.githubusercontent.com/308639/193626325-7d2616da-0ee2-4f2a-bd95-407895b8cbad.png)

**Comment by moontrip** [comment]
@bobular I have examined and tested this issue carefully at both my dev (VM) and qa. My conclusion is that this seems to be addressed from the past PR(s) which I cannot remember right now.

Here are screenshots taken from qa site with the same example. As you can see, y-axis labels look fine:
- LLINEUP, proportion, log scale, Full range option
![histogram-LLINEUP-proportion-log-Full](https://user-images.githubusercontent.com/12802305/200392743-a78cfc53-b2ac-4a41-8b18-f7bf05c37daf.png)

- LLINEUP, proportion, log scale, Auto-zoom range option
![histogram-LLINEUP-proportion-log-Auto-zoom](https://user-images.githubusercontent.com/12802305/200392889-633163de-faa3-4f15-9c7e-94d15afabf2a.png)

**Comment by dmfalke** [comment]
@bobular @moontrip can this be closed?

**Comment by dmfalke** [comment]
I will close. He can open if he disagrees :slightly_smiling_face:
