### ISSUE TITLE
Deployment: enable full screen maps on qa.restricted.clinepidb.org 

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1402]
Purpose: allow specific external users to view a map-based EDA prototype for outbreak monitoring

https://veupathdb.atlassian.net/wiki/spaces/CLIN/pages/48431275/ClinEpiDB+Mini-Retreat+Sept+26-30+2022

Need to make sure the live clinepi site does NOT accidentally end up having full screen maps, post-release! (is this easy/possible?)

**Comment by bobular** [comment]
Not sure if it's just 'restricted' or both vanilla AND restricted

better link here: https://veupathdb.atlassian.net/wiki/spaces/CLIN/pages/79200496/2022-09-29+Maps+and+outbreaks+surveillance?focusedTaskId=36

I think it's both qa and qa.restricted

**Comment by dmfalke** [comment]
I will enable this for all but production sites.

- [ ] Upgrade web-eda, etc, version used by EbrcWebsiteCommon/Client (aka, web-common)
- [ ] Add conifer vars and update base html template to include setting
- [ ] Push config value to WorkspaceRouter component in routes.tsx in web-common.
- [ ] Upgrade ClinEpiWebsite/Site

**Comment by nkittur-uga** [comment]
Yes, FSM are indeed deployed on qa.restricted. 
<img width="849" alt="Screen Shot 2022-10-18 at 10 05 21 AM" src="https://user-images.githubusercontent.com/67710160/196452725-dcc0bf37-c093-4f03-b373-b142bbec81d0.png">
