### ISSUE TITLE
Histogram filter independent axis starts at zero for some edge case year variables that are not stored as dates

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1405]
Since the merge of https://github.com/VEuPathDB/web-eda/pull/1369  an edge case has emerged, see [Slack discussion here](https://epvb.slack.com/archives/C029JGUCD5M/p1665164689230299) (which starts talking about genomics, but we can see the problem in the latest greatest `web-eda/main`.

In a nutshell, we now start the histogram x-axis at zero. This particular variable (WASH Benefits Bangladesh Cluster Randomized Trial -> Participant rep. meas. -> Year) is stored as type='integer' and so no special date treatment is applied (i.e. for dates we don't start at zero, obviously).

Therefore it is not really a bug I guess. Well maybe not in the client code.  But if we stopped starting histogram x-axes at zero, this would go away!  @danicahelb ;-) 

![image](https://user-images.githubusercontent.com/308639/194635615-e0384161-b9ca-4fd4-9d86-08d18506ce59.png)

**Comment by danicahelb** [comment]
We are aware of this issue with years @bobular ;) 
https://github.com/VEuPathDB/EdaLoadingIssues/issues/21

We are handling the year display by annotating defaultDisplayRangeMin, defaultDisplayRangeMax, and defaultBinWidth.
We can consider doing something similar for temperature.

Its on the agenda to discuss at an upcoming EDA UX mtg!
