### ISSUE TITLE
independent behavior of X and Y axis range control and no origin for Auto-zoom

### ISSUE THREAD

**Issue by moontrip** [VEuPathDB/web-eda#1408]
Two things to improve concerning the new axis range control:

a) As raised by Bob at Slack, he found that X and Y axis range controls were not independent: in other words, a change of one axis range control should not affect the other axis range. 

b) based on this decision, no origin is included for Auto-zoom option (https://github.com/VEuPathDB/web-eda/issues/1097#issuecomment-1273655548)

**Comment by bobular** [comment]
I had previously said that x-axis bin width changes could possibly be allowed to reset the y-range (if custom), but let's see how it goes just relying on the yellow truncation bars as a warning.

**Comment by sweverschulman** [comment]
I can confirm that x and y axis range control are independent of each other. 

![Image](https://user-images.githubusercontent.com/62298921/197240959-2d645c07-ade6-47da-b2bc-b5457be58f4a.png)


![Image](https://user-images.githubusercontent.com/62298921/197240970-190da3bf-8575-443e-8912-b84a3ca050ad.png)
