### ISSUE TITLE
Barplot visualization: site footer still shows behind barplot for Bob in FF and Chrome on Windows and Linux

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#141]
See my [comment on an older PR](https://github.com/VEuPathDB/web-eda/pull/92#issuecomment-850633167)

@moontrip couldn't reproduce it, but I'm getting it all the time with barplot (after choosing a main variable).  The empty plot is OK (footer is beneath it) but when you choose a variable, the footer gets partially hidden behind the plot.

Other plots (scatter, histogram) are fine.

Reproduced in Chrome, so unlikely a FF extension problem.

**Comment by bobular** [comment]
I made an investigation - seems to be because the fullscreen barplot plot component does not have a pixel height (or width) and seems to be defaulting to 100%.  This could be fixed by setting width and height to e.g. 1000 and 600 (like the other viz's), but maybe there's a better solution for all plots that doesn't rely on fixed sizes? (I am no expert on this matter...)

**Comment by moontrip** [comment]
@bobular Thank you for your tests and investigations 👍 I could reproduce the issue so I have decided to set the width and height for now like the style at histogram. Relevant changes are made at [barplot component](https://github.com/VEuPathDB/web-components/pull/143) (at web-component) to allow number and string values for width and height. 

changes at viz are also made in [this PR](https://github.com/VEuPathDB/web-eda/pull/145)
