### ISSUE TITLE
Visualizations: Allow multiple data elements to use the same entity constraints

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#1410]
_See related issue https://github.com/VEuPathDB/EdaDataService/issues/190_

We currently only allow linear data element entity constraints in `dataElementDependencyOrder`, something like:

```
  'yaxis' -> 'xaxis' -> 'overlay' -> 'facet'
```

We would like to be able to allow 'overlay' and 'facet' to "share" the same entity constraint:

```
 'yaxis' -> 'xaxis' -> ['overlay','facet']
```

The plan is for the backend to allow a nested array to convey this capability:

```
 [ 'yaxis', 'xaxis', ['overlay','facet'] ]
```

Changes will need to made to https://github.com/VEuPathDB/web-eda/blob/c71bfa78449836c876f89fcd097920d8a3272a40/src/lib/core/types/visualization.ts#L115, https://github.com/VEuPathDB/web-eda/blob/c71bfa78449836c876f89fcd097920d8a3272a40/src/lib/core/components/visualizations/InputVariables.tsx#L107, and https://github.com/VEuPathDB/web-eda/blob/c71bfa78449836c876f89fcd097920d8a3272a40/src/lib/core/utils/data-element-constraints.ts#L12-L93. There may be other functions that need to be updated that assume the type of `dataElementDependencyOrder` to be `string[]`.

**Comment by d-callan** [comment]
For consistency I made it an array of arrays, so expect
[ ['yaxis'], ['xaxis'], ['overlay','facet'] ]
This is drafted backend, including changes to EdaCommon and the data service on branch variable-constraints

**Comment by dmfalke** [comment]
> For consistency I made it an array of arrays, so expect [ ['yaxis'], ['xaxis'], ['overlay','facet'] ] This is drafted backend, including changes to EdaCommon and the data service on branch variable-constraints

Do we ever expect to have an array with more than one element in any place other than the end?

**Comment by d-callan** [comment]
Yes. Ive let the mosaics for ex treat the axes similarly, hoping it'll close a related issue.

**Comment by dmfalke** [comment]
Ah, cool. In that case, we have to determine which entity of those two elements will be the constrainer for the next set of elements. Presumably, we would choose the closest common ancestor entity of those elements; or if one is an ancestor of the others, that one?

**Comment by d-callan** [comment]
I'd imagine we'd find ourselves in a pickle if we tried for ex to put a participant repeated measure on one axis and a household repeated measure on the other... Unless the merging service is cleverer than I know. So I guess all members of any one of the inner arrays will have to belong to the same branch of the entity tree, and then take the most ancestral among them to serve as the constraining entity.

**Comment by sweverschulman** [comment]
Is this ticket related to the conversations that need to happen about [Visualizations: revisit variable constraints](https://github.com/VEuPathDB/EdaDataService/issues/119)? I am pausing until I can check in with @danicahelb.

**Comment by d-callan** [comment]
fwiw i was interpreting this ticket and the one @sweverschulman linked to as functionally duplicates, though each had a different proposed solution. i also think what we implemented was the better of the two proposed solutions. but be sure to let me know if others disagree or theres some use case the current solution doesnt cover.

**Comment by danicahelb** [comment]
issue with dependency order on terms allowed for overlay vs facet is fixed.

Variable constraint documentation needs to be updated to reflect these changes (see https://github.com/VEuPathDB/web-eda/issues/575). In particular, please update the verbiage in this section:


![Image](https://user-images.githubusercontent.com/25450900/200445610-0f8a7079-4005-4bba-8c72-ddfac0339392.png)
