### ISSUE TITLE
Bug with selecting after applying a search filter

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1412]
Categorical variables with a large number of values have a search function ("Find items")

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/25450900/194932005-9bcd5d05-a159-47d4-9f4d-32e716d5ccf0.png">

If user selects all AFTER "Find items", all values are returned (even those that do not contain the search term)

**For example:** 

- see GEMS1 Case-Control, “Reason not evaluated after rehydration” 
- Search for “busy” using "Find items"
- Select all
- Remove “busy” search term → note that ALL values are selected

Please fix this so that ONLY values containing the search term are selected

**Comment by chowington** [comment]
This was fixed earlier in https://github.com/VEuPathDB/WDKClient/pull/250

**Comment by danicahelb** [comment]
confirmed, this is fixed
