### ISSUE TITLE
Variable picker: Can't switch between two same-named variables, e.g. GEMS1 dry mouth

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1414]
This is a bug on my local dev at `main` and on QA, but not on live.

In a visualization, you cannot switch between the two different "dry mouth" variables after one has been selected (e.g. as a x-variable in a RxC mosaic).

Part of the issue may be that "dry mouth" exists as a value in a multi-variable at the Participant level, and a regular categorical variable at Participant repeated measures.  In subsetting they are displayed differently (intentionally) - so you can switch between one and the other.

UPDATE: actually the variable change IS communicated back to parent components, but the widget does not close automatically.

Could be of interest to @jernestmyers

**Comment by jernestmyers** [comment]
I'll take a look at this, and thanks for the details.

**Comment by sweverschulman** [comment]
@jernestmyers could we touch base so that I can understand this issue better.

**Comment by sweverschulman** [comment]
We can now switch between the two different 'dry mouths' within the RxC plot and values update 
<img width="530" alt="Screen Shot 2022-10-21 at 2 02 01 PM" src="https://user-images.githubusercontent.com/62298921/197260410-ff79c9b0-3271-496f-bd84-2d6b273643b6.png">
<img width="557" alt="Screen Shot 2022-10-21 at 2 02 13 PM" src="https://user-images.githubusercontent.com/62298921/197260418-665143e2-a34e-4e9a-ba28-04a3902febfb.png">
