### ISSUE TITLE
All visualization plots need static axes (undraggable/unscrollable)

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#143]
In layout.xaxis and layout.yaxis
 `fixedrange: true`
will solve this

Could we somehow add it at a higher level in PlotlyPlot?

**Comment by moontrip** [comment]
I think it can probably be done at PlotlyPlot component using spread operator, if those changes target for all plots

**Comment by moontrip** [comment]
made a PR at web-components repo, https://github.com/VEuPathDB/web-components/pull/146

**Comment by moontrip** [comment]
This is now approved and merged so I will close this issue
