### ISSUE TITLE
Visualizations: Better handling of studies without collection data

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#1447]
In MicrobiomeDB, if a study does not have collection data loaded, when a user attempts to make an alpha div viz, an unhelpful message is thrown:

![image](https://user-images.githubusercontent.com/365139/198723160-5c0ef304-d864-42f3-9751-2067d2a6c209.png)

We should check for the existence of collections and throw a more helpful message if none are found:
```
Could not create a computation configuration for `${computationName}`. No collection data was found for study `${studyName}`. 
```
https://github.com/VEuPathDB/web-eda/blob/3d489e7363a3bd1823f5b71ba24f67913e3e2056/src/lib/core/components/computations/plugins/alphaDiv.tsx#L95-L105

**Comment by d-callan** [comment]
So something sort of related we should think about is that different types of collections will be valid input for different apps. I'm not sure we currently have a way of differentiating various types of collections?

**Comment by dmfalke** [comment]
> So something sort of related we should think about is that different types of collections will be valid input for different apps. I'm not sure we currently have a way of differentiating various types of collections?

Do you know what the `type` property is used for? Maybe this would allow us to do what you're asking about: https://github.com/VEuPathDB/web-eda/blob/d6f81a718265be1e015ddce6b918b4499cf597ed/src/lib/core/types/study.ts#L207-L223

**Comment by d-callan** [comment]
Yea that's probably it. Maybe I've said this already...

**Comment by sweverschulman** [comment]
@dmfalke or @d-callan do you know of a study that currently has a collection that may throw this errror?

**Comment by d-callan** [comment]
i mean really all studies should have at least one collection thats compatible w the two existing apps, but i dont think the workflow automatically configures collections yet. id guess were seeing this error shortly after a dataset is reloaded before the collections are manually added.

**Comment by sweverschulman** [comment]
@dmfalke and @d-callan is there a way that I could qa this ticket?
