### ISSUE TITLE
Beta diversity app: initial implementation

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#1458]
This issue is focused on initial implementation. There are some questions about styling: https://github.com/VEuPathDB/web-eda/issues/1374, which can be addressed separately.

See https://www.figma.com/file/0Z6cCnTNg1yAaFGEOXQZeg/Microbiome-apps for mock-ups. This initial implementation will not include a button to run a computation. Instead, computation jobs will be created as soon as the configuration is updated. On the overview page, if the subset filters are out of date, we will show the standard "out of sync" message. This means we _should not_ request job status on that page if filters are out of date.

**Tasks for initial implementation (see PR #1483)**
- [x] https://github.com/VEuPathDB/web-eda/issues/1329
- [x] #1247
- [x] #1148
- [x] #1459
- [ ] #1495

_Depends on https://github.com/VEuPathDB/service-eda-compute/issues/34_

**Comment by asizemore** [comment]
closing as it has been deployed to feature!!

**Comment by asizemore** [comment]
Moving to complete. There is one task still open but if I understand correctly would not be necessary for function. @dmfalke is that an accurate depiction? Or would we be putting ourselves in a hole if we went live without #1495 ?
