### ISSUE TITLE
Error in 2x2 mosaic (Invalid value `null` supplied to relativerisk)

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1474]
@sweverschulman encountered the following error when QA'ing https://github.com/VEuPathDB/EdaDataService/issues/213

**2x2 plot in India ICEMR Cohort received the following error:**

![Image](https://user-images.githubusercontent.com/62298921/200023213-713ba547-4c00-4390-b80f-b3392f49d5e6.png)

`Unexpected backend type(s) encountered: Invalid value null' supplied to relativerisk (type: number) of O (type: Partial<{ oddsratio:
(number | null), pvalue: (number | string), orInterval: string, rrinterval: string, relativerisk: number, facetVariableDetails: (I({ entityld:
string, variableld: string ) & ( value: string })I | [(( entityld: string, variableld: string ) & ( value: string }), (( entityld: string, variableld:
string } & { value: string })]) }>) of statsTable (type: Array<Partial<{ oddsratio: (number | null), pvalue: (number | string), orInterval:
string, interval: string, relativerisk: number, facetVariableDetails: ([({ entityld: string, variableld: string } & { value: string })] I [(f
entityld: string, variableld: string } & { value: string }), ({ entityld: string, variableld: string } & { value: string })!) }>>) of 1 (type:
Partial<{ statsTable: Array<Partial<{ oddsratio: (number | null), pvalue: (number | string), orInterval: string, rrinterval: string,
relativerisk: number, facetVariableDetails: ([({ entityld: string, variableld: string } & { value: string })I | [({ entityld: string, variableld:
string } & { value: string }), (( entityld: string, variableld: string ) & { value: string })I) }>>, completeCasesTable: Array<Partial<{
completeCases: number, variableDetails: ( entityld: string, variableld: string ) ]>> }>) of [root] (type: ({ mosaic: ( data: Array«(f
xLabel: Array<string>, Label: Array<Array<string>», value: Array<Array<number>> } & Partial<{ facetVariableDetails: (I({ entityld:
string, variableld: string ) & ( value: string ))I | [(( entityld: string, variableld: string } & ( value: string )), (( entityld: string, variableld:
string } & ( value: string })I) }>)>, config: ( completeCasesAlIVars: number, completeCasesAxesVars: number, ×VariableDetails: (
variableld: string, entityld: string ), yVariableDetails: ( variableld: string, entityld: string ) ) ), sampleSizeTable: Array<{ size:
Array<number> }>, completeCases Table: Array<Partial<{ completeCases: number, variableDetails: { entityld: string, variableld:
string }}>> } & Partial<{ statsTable: Array<Partial«{ oddsratio: (number | null), pvalue: (number | string), orlnterval: string, rrinterval:
string, relativerisk: number, facetVariableDetails: ([({ entityld: string, variableld: string } & { value: string })] | [({ entityld: string,
variableld: string ) & ( value: string )), (( entityld: string, variableld: string ) & ( value: string })]) }>>, completeCasesTable:
Array<Partial<{ completeCases: number, variableDetails: ( entityld: string, variableld: string } )>> }>))`

**Comment by aaronwlsong** [comment]
Replicated the case in india_ICEMER_cohort by using the same variables. Looks good now. Closing ticket. 


<img width="1583" alt="Screen Shot 2022-11-28 at 10 05 54 AM" src="https://user-images.githubusercontent.com/61077845/204311273-e9c3ed6a-ae23-4d44-b7d9-293c43dde7bf.png">
