### ISSUE TITLE
Visualizations: create legend title with overlay variable's name for all plots

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#148]
Currently any viz using an overlay variable can end up with a mysterious "yes, no" legend, as below.
Even the more self-explanatory variables, such as country, should have a title above the legend.

![image](https://user-images.githubusercontent.com/308639/121054134-f5180e80-c7b3-11eb-9ecb-bb441e9a7f29.png)

**Comment by moontrip** [comment]
An example with XYPlot component at web-component is now [approved and merged](https://github.com/VEuPathDB/web-components/pull/152). Thus, other plot components and corresponding vizs would be applied with the approach.

**Comment by bobular** [comment]
Hi @moontrip thank you for this.

I have moved your implementation into the new tidied/refactored PlotlyPlot so I will mark this issue as being solved by the refactoring PR.

**Comment by moontrip** [comment]
Thanks Bob for your information 👍 I glanced at your commits regarding this but it seems like this part is not pushed to the PR yet: will take a look at it later. 

I have also thought of the case to move this legend title part to `Plotlyplot` component. However, I was reluctant to do that because I did not want to send additional prop to `Plotlyplot` beyond key props like `data`, `config`, and `layout`. I thought it is better to handle such a prop (e.g., legendTitle prop) at each plot component level, not `Plotlyplot`. :)

**Comment by bobular** [comment]
Hi DK,

It's here in PlotlyPlot
https://github.com/VEuPathDB/web-components/blob/83784fa1cdf1aacc39d9a3b2385ee42dad43b2b1/src/plots/PlotlyPlot.tsx#L124
and used in a story here
https://github.com/VEuPathDB/web-components/blob/83784fa1cdf1aacc39d9a3b2385ee42dad43b2b1/src/stories/plots/XYPlot.stories.tsx#L38

I worked out (with some help from Dave) how to send non-Plotly props to
PlotlyPlot, so now all the general things like `title`,
`displayLibraryControls`, `displayLegend`, etc are all handled by
PlotlyPlot.

**Comment by moontrip** [comment]
@bobular thank you for sharing the info 👍 

Actually I am thinking of handling the date string for scatter plot viz for my next task (after refactoring boxplot viz), so some of your changes would be helpful - I was thinking that we might not need to use Date type though: perhaps string type is sufficient for plotly purpose but I will revisit it in the near future.

Just for a note, from my understanding and simple tests with plotly examples, setting `type: date or linear` (even with range) seems not to be a must-have: so perhaps no need to have corresponding props like `independentValueType` and `dependentValueType`. I think plotly automatically recognize the format if it is given as `'yyyy-mm-dd' string format - you can test this via https://plotly.com/javascript/time-series/ and play one of example having type: date/liner at CodePen (Try it at CodePen button)

In addition, it would be great if you can change the names, `ScatterplotData` and `ScatterplotProps` to `XYPlotData` and `XYPlotProps` for consistency - sorry that I missed the changes.

**Comment by bobular** [comment]
HI DK - I've already done a scatterplot story with dates and have adjusted
the props to use `string` instead of `Date` to be consistent with what we
decided for Histogram.

Plotly does detect dates but can't detect that "2001" as a string is a
date, so I added (in)dependentValueType props (similar to Histogram's
valueType, which I'll probably rename independentValueType).

Good idea - I will rename ScatterplotData and ScatterplotProps to XYPlotData
and XYPlotProps as suggested - I had been wondering about that.
