### ISSUE TITLE
Legend missing from all viz tools

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1480]
on the lQA site, the plot legend has disappeared from all visualization tools

please bring it back ASAP

**Comment by dmfalke** [comment]
This might already be fixed on `main`.

**Comment by moontrip** [comment]
I tested QA and yes legend is not working. I just checked the latest main at my VM and yes @dmfalke it works fine in there.

**Comment by dmfalke** [comment]
> My two cents are it may be related to gradient color map and it is not deployed yet. One possible case is, though didn't check it out carefully, legend works at web-components repo were deployed while corresponding web-eda work wasn't yet?

That sounds like a good possibility. Thanks for looking into it! I'm closing the issue.

**Comment by dmfalke** [comment]
@moontrip it could be this PR: https://github.com/VEuPathDB/web-components/pull/407

**Comment by danicahelb** [comment]
i confirmed that the legend is back, thanks for the quick fix!
