### ISSUE TITLE
Bug: Scatterplot has legend issue on QA site

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1481]
There is now a bug with the legend when an overlay variable is added to the plot. See this GEMS1 example.

**On the live site it looks fine**

<img width="944" alt="image" src="https://user-images.githubusercontent.com/25450900/202033718-9af0b401-1d74-41ad-82d5-ef6390709e6d.png">

**On the QA site we are getting a gradient color map but the colors don't match what is on the plot and this is a categorical variable**

<img width="980" alt="image" src="https://user-images.githubusercontent.com/25450900/202033790-ad59b01e-2166-493b-9b2f-9466253286d5.png">

**Comment by SheenaTomko** [comment]
Looks great now!
