### ISSUE TITLE
Visualizations: scatter plot opacity slider 

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-eda#1487]
The introduction of the gradient colormap is making it more important we have a means other than hollow markers to address over plotting. The proposal is a unique type of opacity slider which uses filled markers, except on the single condition where the marker is fully  transparent, then it'd switch to the hollow marker.

**Comment by danicahelb** [comment]
I made a duplicate ticket (now closed). adding info from that ticket here in case it is helpful

Discussed in 11/16 data viz mtg

currently scatterplot uses open circles, but circle outline colors are difficult to distinguish. As gradient color map gets implemented, it is increasingly difficult for users to differentiate hues

Add an opacity slider to the plot controls.
- Markers should be filled unless the fill is completely transparent, then switch to hollow markers.
- Default should still be hollow markers, but users can use the slider to add the fill color to increase the colored area, allowing for opaque filled markers will help address overplotting of filled markers

**Comment by asizemore** [comment]
<img width="555" alt="Screen Shot 2023-01-12 at 12 48 57 PM" src="https://user-images.githubusercontent.com/11710234/212141403-1a97c24f-9a0b-4b63-ba25-3dd7ed02345a.png">

Just saw this! Very exciting!
The setting is "0" when we first land on the viz. Marker opacity should be 1 by default. Opacity 1 = markers fully opaque, where opacity=0 means markers are totally transparent. We have the right idea just swap the direction of the slider :)

**Comment by danicahelb** [comment]
since the markers have some amount of transparency, the legend should also have that amount of transparency so that the colors actually match up.

**Comment by danicahelb** [comment]
opacity slider is really nice, thanks @moontrip!

<img width="800" alt="image" src="https://user-images.githubusercontent.com/25450900/215197419-20445cbb-3083-4639-9896-a5edbdcbf109.png">
