### ISSUE TITLE
Stand alone map overlay not working for parent entities of geo-located entity

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1491]
This is only demo-able on in the alpha popbio megastudy: https://feature.vectorbase.org/vectorbase.feature/app/workspace/analyses/DS_4b8cb8bb2e

In full-screen map, try to overlay with a study variable, like Study identifier...

Gives 2 x 500s on the back end.

The `outputEntity` should be Collection site, but we are sending Study to the back end.

**Comment by bobular** [comment]
Seems like the Study --> Years variable is broken/giving a 500. Although this isn't a variable that will stay in the final version, I will investigate this and provide QA advice.  The two other variables work fine.

**Comment by danicahelb** [comment]
SAM QA is paused for now
