### ISSUE TITLE
Standalone map: filter panel

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1498]
Requires https://github.com/VEuPathDB/CoreUI/issues/139

This will be a draggable panel showing the

- [ ] entity diagram
- [x] subsetting filters (just as they are in the EDA subsetting tab)

For now, filter chips can stay there, even though they will be repeated in the header.

**Comment by dmfalke** [comment]
The entity diagram still needs to be added.

**Comment by adnauseum** [comment]
> The entity diagram still needs to be added.

On it!
