### ISSUE TITLE
Reverse order of entity children when displaying variable tree

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#150]
The issue is, given this entity tree
![image](https://user-images.githubusercontent.com/365139/121190975-88dfee00-c839-11eb-8e5f-fa4ffd6beced.png)

we end up with this list of entities
![image](https://user-images.githubusercontent.com/365139/121191095-a4e38f80-c839-11eb-9b82-dd59848de148.png)

Instead, we want **Household observation type** to appear immediately below **Household**. Reversing the order of the children of an entity will address this.

This may not be a long term solution, but we will try it for now.

**Comment by bobular** [comment]
Not much context for this ticket, so glad I'm not a reviewer of the PR.

**Comment by dmfalke** [comment]
Sorry, I got distracted when I made this issue and never updated the description. Just updated it.
