### ISSUE TITLE
update line plots to keep user selections & NOT draw plot when selection combinations are incompatible

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1503]
Line plot currently uses snackbars to inform the user that log scale wasn't appropriate (and gets switched off) when error bars were switched on. Scatter plots have been updated to use content messages for this.

Please update the line plots to use content message for consistency with scatter

**Comment by danicahelb** [comment]
Change: 
`Log scale is no longer appropriate and has been disabled`
to:
`Log scale and binning are not available concurrently. Why?`
and:
`Log scale and binning are not available concurrently. Binning of non-log transformed raw data cannot be accurately plotted on log scale axes. Read less`

Change:
`Error bars are no longer appropriate and have been disabled`
to:
`Y-axis log scale and error bars are not available concurrently. Why?`
and:
`Y-axis log scale and error bars are not available concurrently. Error bars for non-log transformed raw data cannot be accurately plotted on log scale y-axis. Read less`

**Comment by danicahelb** [comment]
we do not want to leave a context message permanently after it is called. it should only be visible when the user selections are incompatible. the current behavior of scatter is what we want for line plots.

**Comment by bobular** [comment]
Hi @danicahelb I'd just like to clarify on behalf of @moontrip 

In lineplot, when a user makes an "illegal" toggle selection, do we want the plot to disappear and the banner to show until the user corrects their "mistake"?  This is what happens in scatter.

**Comment by danicahelb** [comment]
As of 1/13/2023, the content messages are being used appropriately.

However, when a user makes an "illegal" combination of selections, we do not want to auto-change their selections. We just want the content message to appear and the points/lines/data on the plot area to disappear.

currently, we are still auto-changing the user selections so that the plot can be drawn.

I'm changing the title of this ticket to make what has to happen still more clear

**Comment by danicahelb** [comment]
I made a line plot and added both binning and log scale for the x-axis. The appropriate snack bar showed up and no data appeared on the plot.

However, i clicked on the "Restore to defaults" button, which switched the toggles for both binning and log scale off. Data points reappeared on the plot, however the snack bar did NOT disappear


![Image](https://user-images.githubusercontent.com/25450900/221004757-c1618307-b0b5-420e-bfdf-cd49f18a8f5b.png)

Please ensure that the snackbar only shows when selections are incompatible

**Comment by danicahelb** [comment]
same issue is happening with the y-axis controls:



![Image](https://user-images.githubusercontent.com/25450900/221005156-7da28647-56b2-499b-9a58-24dae5c5084a.png)

**Comment by moontrip** [comment]
@danicahelb Thank you for your reviews, tests, and identifying the issue! 👍 I will reopen this ticket and fix the issue

**Comment by moontrip** [comment]
@danicahelb For your information, your findings are now fixed and will be applied to the qa site after Dave will update the server.

**Comment by SheenaTomko** [comment]
@danicahelb this is ready for qa now

**Comment by danicahelb** [comment]
this is fixed, thanks @moontrip
