### ISSUE TITLE
BUG: Line plot shows marker even when data is missing

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/web-eda#1504]
Line plot should not have a marker if data is missing. However in the case below, markers are showing up at y=0 when data is missing (example is circled). 
![Screen Shot 2022-12-05 at 2 04 43 PM](https://user-images.githubusercontent.com/67710160/205735195-31ad81f9-8c0f-439b-b53c-41d8833a91cd.png)

**Comment by danicahelb** [comment]
More info:

when you filter the data so that `Village study arm` = `Arm 6: Gaining-shsh` you can see that we only have data for some of the timepoints

<img width="589" alt="image" src="https://user-images.githubusercontent.com/25450900/206062975-315ecaab-f2aa-4367-af70-40204aec7774.png">

**Comment by danicahelb** [comment]
this issue essentially duplicates https://github.com/VEuPathDB/web-eda/issues/1411 so I am closing this one
