### ISSUE TITLE
Bug: Unexpected backend type(s) encountered in line plot

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1506]
To recreate (QA.clinepi): 
Study: SCORE S. mansoni CRT
Filter: Village study arm = Arm 6: Gaining-shsh
Line plot viz tools with the following parameters selected

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/25450900/206062572-b941ed0f-558c-407c-a236-b03cb6b1476b.png">

**Comment by aaronwlsong** [comment]
Recreated the case, looks good now. Closing ticket. 


![Image](https://user-images.githubusercontent.com/61077845/207441939-ff8e0b60-70df-489e-ae33-1e7e49678c6b.png)

**Comment by moontrip** [comment]
@aaronwlsong thank you for your tests and confirmation! 👍
