### ISSUE TITLE
Implement ability to save visualizations

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1509]
Folks at ASTMH 2022 workshop wanted to be able to download / save visualizations they created on ClinEpiDB.
.pdf format would work.

**Comment by dmfalke** [comment]
What would be included in the download? Just the plot, or what they see on the screen, or maybe something else?

**Comment by danicahelb** [comment]
still TBD... needs UX discussion

**Comment by aurreco-uga** [comment]
there is download offered for plots
there is  already a related issue asking to include info surrounding the plot
so closing this one
