### ISSUE TITLE
Lineplot bug - invalid value `undefined` supplied to `binSlider`

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1523]
This could be a bug I introduced in https://github.com/VEuPathDB/web-eda/pull/1468

In the GEMS1 example below, there is no expectation of binned data coming from the back end (it's a categorical x-axis variable). I will look into this ASAP.

![image](https://user-images.githubusercontent.com/308639/207069411-2dde84c4-0199-4f43-a94c-cef3ccbf1800.png)

**Comment by bobular** [comment]
Wait - this is not an issue on the `main` branch.  Will report back in a minute.

**Comment by moontrip** [comment]
@bobular FYI, it was already addressed at https://github.com/VEuPathDB/web-eda/pull/1507, which was merged into main branch
