### ISSUE TITLE
Visualization: Add viz type displayName as subtitle of visualization

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#154]
This is in the full-screen mode. It should be added underneath the editable name

E.g.:

**Unnamed Scatter plot**
*Scatter plot*

**Comment by moontrip** [comment]
is this acceptable? I thought the `Unnamed Scatter Plot` is bold and `Scatter plot` is italic as you described.

![scatter-subtitle](https://user-images.githubusercontent.com/12802305/121221496-9efaa800-c853-11eb-9711-e75c9076d35e.png)

**Comment by dmfalke** [comment]
I think that looks pretty good. I'd like to see the subtitle a little bit more gray. Maybe something like #333333.
