### ISSUE TITLE
Ranked abundance scatter shows too many overlay values

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1548]
<img width="962" alt="Screen Shot 2023-01-09 at 12 50 06 PM" src="https://user-images.githubusercontent.com/11710234/211374024-d8e19669-07c3-4e2e-a73a-56562245c1ab.png">

Above we have 10 overlay values instead of 8. Not seen on the beta site.

**Comment by asizemore** [comment]
after a bit of investigation, we just need to add this back into the config and plug it into the compute service. 
The param is called "cutoff", see [here](https://github.com/VEuPathDB/microbiomeComputations/blob/f0e961a4ef8852408ecd49523a3fd2291f4d3c88/R/method-rankedAbundance.R#L15)
Need to add this param in the [compute service](https://github.com/VEuPathDB/service-eda-compute/blob/51b3d29eccecc01a32b5f5357ae7eb7b0f358c09/src/main/java/org/veupathdb/service/eda/compute/plugins/rankedabundance/RankedAbundancePlugin.java#L84)
And need to add it in web-eda, either somehow in abundance.tsx or in scatter. Prefer abundance.tsx...

Since many of the services are in flux, i'll wait until the final merge to implement fixes.

**Comment by d-callan** [comment]
believe we fixed this in the data service plugin.

**Comment by asizemore** [comment]
Yes fixed with https://github.com/VEuPathDB/EdaDataService/pull/244
Moving to Complete
