### ISSUE TITLE
Keep track of if that user had just started the computation.

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1564]
In 01.13.23 ux meeting there was concern that the user would get confused if they arrived at a viz and saw the computation had already been complete. If we cannot solve this with verbiage updates, we'll need to keep track of if the user had just made that computation happen. Either they pressed the button and waited around on that view or they pressed the button and went elsewhere and came back. 
If the user did just press the button, the compute status would say something like "Complete, results added to the system". If the user did not just press the button, the status would say something like "Complete, using saved results from the system."

**Comment by asizemore** [comment]
Note: paused because we'll try to solve this issue with a verbiage update and see what our testers think, first.

**Comment by danicahelb** [comment]
@asizemore is there a ticket for verbiage update? we should link this ticket to that one so it doesn't get lost

**Comment by asizemore** [comment]
there's not a verbiage ticket, but we can hold off on making one for a bit until we decide we need to do this one. This ticket came out of a concern from an eda meeting, but before we implement it we should see if it's really a problem with users. 

I'll add a paused label

**Comment by asizemore** [comment]
Closing as this has not been a concern recently. We can always reopen if necessary
