### ISSUE TITLE
Master ticket - Standalone map: working "skeleton" app on dev sites

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1571]
This is more of a master ticket.
Things that are needed for this milestone. Let's **not** include any floating visualizations, study details/DD, downloads or sharing.

- [x] VEuPathDB/web-eda#1549 
- [x] VEuPathDB/web-eda#1546 
- [x] https://github.com/VEuPathDB/CoreUI/issues/139
- [x] https://github.com/VEuPathDB/web-eda/issues/1496
- [x] https://github.com/VEuPathDB/web-eda/issues/1498
- [x] https://github.com/VEuPathDB/web-monorepo/issues/140

**Comment by danicahelb** [comment]
@bobular I made a ticket for finalizing stand alone map mockups: https://github.com/VEuPathDB/EdaNewIssues/issues/543

**Comment by dmfalke** [comment]
Closing!
