### ISSUE TITLE
Mosaic plot (2x2) more information box for stats tab - finalize styling & implement

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1574]
In ClinEpi, we will use the explanatory info box for the 2x2 mosaic viz tool statistics tab. The box will be closed by default but the user can choose to expand / open the box to read more about which statistics are appropriate to use for their analysis. this info box should be similar in styling to the 2x2 mosaic parameter selection screen

the explanatory information box allows users to read help / additional information so the sure can refer to it while they are making parameter selections for visualizations or apps.

mockups here: https://www.figma.com/file/Su1eNm3Bby85CfrnX42L7q/2x2-table-UI?node-id=317%3A623&t=ZCxlWaPOOG1AbgKr-0

**Comment by danicahelb** [comment]
Hey @moontrip we finalized the more info box for the stats tab in the 1/23/2023 EDA UX meeting

See final mockups, which contain approved verbiage: https://www.figma.com/file/Su1eNm3Bby85CfrnX42L7q/2x2-table-UI?node-id=403%3A725&t=sDSejTfcwyglUYu9-0

**For styling:**
- background color - blue, like banners
- border - gray, like other containers
- toggle collapse/expansion icon - single arrow/caret
- info icon - include dark blue info icon

More info here: https://www.figma.com/file/Su1eNm3Bby85CfrnX42L7q/2x2-table-UI?node-id=139%3A233&t=C7dsTpu6Y9mLsmoz-0

**Comment by nkittur-uga** [comment]
Looks good!
<img width="1079" alt="Screenshot 2023-02-27 at 4 52 29 PM" src="https://user-images.githubusercontent.com/67710160/221694558-b2ecd16c-f118-4556-8c4f-ab9baa243941.png">
