### ISSUE TITLE
2x2 Mosaic: update parameter selection frontend to allow users to select reference groups for all variables

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1575]
Related to https://github.com/VEuPathDB/EdaDataService/issues/130

Final parameter selection UI can be found here: https://www.figma.com/file/Su1eNm3Bby85CfrnX42L7q/2x2-table-UI?node-id=44%3A431&t=ZCxlWaPOOG1AbgKr-0

**Comment by danicahelb** [comment]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/25450900/214134698-9aea2d59-0fc5-44be-9d27-e005cbfc6d3c.png">

**Comment by nkittur-uga** [comment]
I keep running into this bug while trying to do this:
<img width="1417" alt="Screenshot 2023-02-22 at 12 10 43 PM" src="https://user-images.githubusercontent.com/67710160/220704142-94654671-9b96-4bba-963b-1318148816c2.png">

**Comment by jernestmyers** [comment]
This is currently only testable on a dev site due to the backend changes.

> Also, I noticed that value selection is only available (enabled) after both X and Y variables have been selected. It left me wondering for a second why the X value selection was not available after I selected the X var.
I initially implemented this along the lines of your thinking, but then [I interpreted the mockups](https://www.figma.com/file/Su1eNm3Bby85CfrnX42L7q/2x2-table-UI?node-id=44%3A263&t=LZfj6TMAUPmdfHKA-0) to enable those buttons only after table vars are selected.

**Comment by nkittur-uga** [comment]
@jernestmyers - I spoke to the team and we feel that the Quadrant A values should become active immediately after their corresponding x- or y-axis variable has been selected. Sorry this is different from the mock-ups! And thank you for making the update.

**Comment by jernestmyers** [comment]
I've merged changes to get the disable/enable behavior to work as requested. The QA site's backend is having trouble getting up-to-date with the client code, but in the meantime things can be viewed/tested [on my dev site](https://jmyers.clinepidb.org/ce.jmyers/app/).

**Comment by nkittur-uga** [comment]
Looks great, thanks Jeremy!
