### ISSUE TITLE
Refactor `rankingMethod`, `betaDivDistanceMethod`, and `alphaDivMethod` data to include `displayName`

### ISSUE THREAD

**Issue by jernestmyers** [VEuPathDB/web-eda#1579]
The current data structure of these methods is defined in the client code of each configurable computation, like so:
```js
const BETA_DIV_DISTANCE_METHODS = ['bray', 'jaccard', 'jsd'];
```

Currently, we [manipulate the string to capitalize the first letter](https://github.com/VEuPathDB/web-eda/blob/9643946983a165217425ae9244674a09e215c6aa/src/lib/core/components/computations/plugins/abundance.tsx#L111-L116). But that's not necessarily the desired ouput.
![image](https://user-images.githubusercontent.com/69446567/214620947-3865aec6-1b53-4c01-852d-13899689783f.png)

**Comment by asizemore** [comment]
@jernestmyers good idea. Lately i've even added logic to more appropriately capitalize the methods, but still it'd be better to add `displayName`s.
