### ISSUE TITLE
incorrect chart marker display for some cases

### ISSUE THREAD

**Issue by moontrip** [VEuPathDB/web-eda#1586]
While working with react-leaflet-v3 updates and tests, I found a bug on chart markers where some markers did not show chart or total numbers. Initially, I thought they were due to v3, but I confirmed that it happened at qa.restricted now. Here are some screenshots.

a) SCORE S. mansonni CRT study
![map-bug-no-data-color](https://user-images.githubusercontent.com/12802305/215610887-25b9a03d-817a-43c7-ba8d-a127d2a1fead.png)

b) SCORE Mozambique (Full screen map)
![mozambique map error1](https://user-images.githubusercontent.com/12802305/215611068-3ff024e4-09cb-487a-90a8-902f0e4acb7f.png)

After delving into the issue, I found the reason why, so a PR will be made at web-components.

**Comment by moontrip** [comment]
I will close this ticket as it is now resolved by merging https://github.com/VEuPathDB/web-components/pull/445

**Comment by SAK22** [comment]
Looks good! I see numbers under charts of charts with 0 on them so this is good. Weirdly though when I first selected age group at the variable on the same study above I got a huge error, picked it again and it was fine.

**Comment by SAK22** [comment]
@moontrip I forgot to tag you in this yesterday :)

**Comment by moontrip** [comment]
@SAK22 No problem! I got your message via email. Thank you for your reviews and tests 👍

**Comment by moontrip** [comment]
@SAK22 Thank you for asking. I think you were worried about the case you experienced the error when selecting age group as you mentioned. Can you please check it out again? I just tried but did not have such an error. If it will be okay, then you can close this ticket 👍

**Comment by SAK22** [comment]
Did not get the error this time! Yay!

**Comment by moontrip** [comment]
@SAK22 🥳 Perhaps it was a temporary glitch from backend at that time? Thank you for your confirmation! 👍
