### ISSUE TITLE
EDA map visualization gives a pink type error when there is no data in the viewport

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1590]
Where: live and qa
How: 
1. SCORE S. mansoni Cluster Randomized Trial (and presumably others)
2. Add a geolocation map viz
3. choose any variable
4. move the map so there is no data on-screen

A pink error occurs
```
Unexpected backend type(s) encountered: Invalid value `null` supplied to value (type: number) of 1 (type: Partial<{ value: number, units: "day" | "week
```
Should be easy to fix (it's an `io-ts` issue presumably)
But is also related to https://github.com/VEuPathDB/web-components/issues/396 because we want to make it easy for users to get back to where there is data.

Also affects standalone map

**Comment by moontrip** [comment]
@bobular Actually I found it strange because I could use qa site for the same example you used at our mtg. I also checked Live and qa again and they worked fine

**Comment by moontrip** [comment]
@bobular Ah I just saw your slack message and I could replicate it when zooming in several times 👍

**Comment by SAK22** [comment]
Looks good!
