### ISSUE TITLE
Standalone map: Left hand menu bar

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1595]
Similar to https://github.com/VEuPathDB/web-eda/issues/1594 this will be a (probably semi-transparent) vertical bar on the left with a show hide button.  Could use the same base component for the show/hide functionality.

Mock-up: https://www.figma.com/file/gKYVrWu6qfDTUgYKQuvaIy/SAM?node-id=148%3A642&t=kZAYjT6DD5vVW5X1-4

More refined mock-ups: https://www.figma.com/file/gKYVrWu6qfDTUgYKQuvaIy/SAM?node-id=283%3A1682&t=cvkaRFX6HTcvXQt5-1

I (Bob) am not sure we need the **"VectorBase"** heading at the top of the menu - let's just put "Menu" there for now, or nothing at all.

- [ ] Populate with a few placeholder items

**Comment by dmfalke** [comment]
Can this be closed?
