### ISSUE TITLE
Subsetting: Change table filter heading "Remaining {entityName}" to "Subset of {entityName}"

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#16]

**Comment by moontrip** [comment]
@dmfalke I have done quick tests for this issue (a) and the other one (b) (Subsetting: Add variable details above filter component: https://github.com/VEuPathDB/web-eda/issues/14#issue-838092357) so I will leave my results for both issues here at once.

a) For resolving this issue, the following function at Membershipfield component needs to be changed (see screenshot attached):


```
  renderFilteredCountHeading1() {
    // return this.renderCountHeading1('Remaining');
    return this.renderCountHeading1('Subsetted');
  }
```


Seems like this change should only be for EDA Subsetting service, the Membershipfield component needs to be copied for modification, I suppose.

b) For adding variable details, which I am not quite sure of the correct location, below modification at FilterContainer component would work:


```
export function FilterContainer(props: Props) {
  const AdditionalDescription = () => {
    return (
      <div style={{marginTop: '.5em'}}>
        <h4>Variable name: {props.variable.displayName}, Provider label: {props.variable.providerLabel}</h4>
      </div>
    );
  }
  return narrowProps(isHistogramVariable, props) ? (
    // <HistogramFilter {...props} />
    <>
      <AdditionalDescription />
      <HistogramFilter {...props} />
    </>
  ) : narrowProps(isTableVariable, props) ? (
    // <TableFilter {...props} />
    <>
      <AdditionalDescription />
      <TableFilter {...props} />
    </>
  ) : (
    <UnknownFilter />
  );
}

```

Please see the sample screenshots in the following:

![variable1](https://user-images.githubusercontent.com/12802305/112359019-3c0f6100-8ca7-11eb-89ad-6db4e2f007af.png)

![variable2](https://user-images.githubusercontent.com/12802305/112359043-403b7e80-8ca7-11eb-9e34-41d8477c0078.png)

**Comment by dmfalke** [comment]
This looks great! A few suggestions:

(a) I will check on if we want this change to be made universally. If not, we can make that an optional prop of the component (e.g., `foregroundLabel`) to override the existing verbiage, so no need to copy.

(b) I think we should have **variable name** on one line, and **provider label** on a second line. We should use `<h3>` for variable name but remove the "Variable name:" prefix, and `<h4>` for provider label, keeping the "Provider label:" prefix.

If you want to get (b) done, feel free to make a PR and link it to the related issue.

Thanks!

**Comment by moontrip** [comment]
@dmfalke Thank you for your reviews 👍 Yes, for a) I also thought of that optional prop if we don't need to significantly change the component 👍 But I will leave it to you as it involves changes at lib :)
b) yes it can be done for this certainly. Will do that and ping at Slack~

**Comment by dmfalke** [comment]
Great! Based on some feedback, I think we should add the prop. They have also requested new verbiage :). I will update the issue title. I can add the prop in wdk-client. I will ping here when it's ready.

**Comment by dmfalke** [comment]
Once https://github.com/VEuPathDB/WDKClient/pull/123 is merged, and a new npm package version is published, this change can be made in this repo.
