### ISSUE TITLE
Do not change legend color to grey when a data series has been disabled

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1602]
Across all visualizations with an overlay, when a user unchecks (ie, disables) a data series in the legend the color for that legend turns gray. 

It is hard to distinguish the grey from a disabled series from the grey used for "no data" series.

Please do not change the color for the data series when it is disabled. Instead, just uncheck the box next to it to indicate that it has been disabled.

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/25450900/214170616-35bef869-8bc3-4faa-99f2-f9b60f351572.png">

**Comment by dmfalke** [comment]
Can this be closed, since #1609 is no longer needed?

**Comment by moontrip** [comment]
@dmfalke Yes you are right. But, just one thing I noticed is that at the current main branch of web-eda, there exists a mismatch of the web-components version (@veupathdb/components) between peerDependencies (showing 0.19.**17**) and devDependencies (0.19.**19**).

**Comment by dmfalke** [comment]
Ah, good catch. I will update the peerDependencies. Thanks!

**Comment by danicahelb** [comment]
looks great, thanks! 

![Image](https://user-images.githubusercontent.com/25450900/220982047-fcad49b6-ca76-4fc4-ab12-17d7d24ef500.png)

**Comment by moontrip** [comment]
Thank you for your tests and confirmation, @danicahelb 👍
