### ISSUE TITLE
Visualizations: Double scroll bars (inner one hardly reachable with mouse) in pop-up variable selector of InputVariables

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#161]
Problem exists in FF and Chrome on Linux

![image](https://user-images.githubusercontent.com/308639/121192229-a37b8c80-c864-11eb-88ca-0dba43568cf3.png)

If I change src/lib/core/components/VariableTree.scss
```
height: calc(100% - 6em);
```
in dev tools to
```
height: calc(100% - 8em);
```
it's OK again.  But I'll leave it to someone more experienced in the art of layout.

Fixed looks like this:

![image](https://user-images.githubusercontent.com/308639/121192309-baba7a00-c864-11eb-9fd7-ce0c4daa8e42.png)

**Comment by dmfalke** [comment]
This was addressed in #181
