### ISSUE TITLE
Update placement of filter chips & remove show all filters button

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1621]
BUG: If i heavily subset the data the filter chips cover the variable label & definition and there is no way for me to read it

if i keep adding filters, chips appear until there is no more room above the data for the selected variable. If i try to add an additional filter, the data is filtered but no chip appears. in the screenshot below, notice that I have filtered on `plasmodium species for last malaria diagnosis` but there is no corresponding chip

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/25450900/216150073-53048d37-cae3-4d96-aa06-67a8cc7e6783.png">

**Comment by dmfalke** [comment]
Another option would be to have a "Show more" button to expand this view (the stuff below it on the page would get pushed down), or to open the modal.

Yet another option would be to have the chips scrollable (left-right), with buttons to scroll left and right. This is probably less idea.

I wonder if we would want to move the filter chips to be above the tabs, just below the entity diagram, and get rid of the "Show all filters" button/modal...?

**Comment by danicahelb** [comment]
@adnauseum had a related issue with adding filter chips to the header for the stand-alone map. currently, when many filters have been applied, only the first ~few are visible and the rest can only be seen upon scrolling.

In 2/15 styling meeting, we discussed possibly using the "Show all filters" button in the SAM header instead of individual chips for each filter. This decision depends on what the purpose of the chips in the header is... thoughts include:

_(i) so folks know what filters had been applied in a screenshot image (if so, individual chips are preferred)_
- but chips only let you know what variables were filtered on, not the values that were selected
- user can also easily crop out the header when taking a screenshot

_(ii) so folks would know what filters had been applied when the SAM is shared to a new user (if so, the show all filters button is fine)_

@bobular FYI...

**Comment by danicahelb** [comment]
See this slack thread for a related issue to consider: https://epvb.slack.com/archives/C0132PM1MT5/p1675278145919009

Users definitely want to see their filters front-and-center when visualizing, but chips are only on the B&S tab.  it's not obvious that they can use the "Show all filters" button to view the applied filters. The issue is that the "show all filters" button is often off screen (too high)

**Comment by dmfalke** [comment]
See related comment https://github.com/VEuPathDB/EdaNewIssues/issues/566#issuecomment-1435000624

**Comment by danicahelb** [comment]
Discussed in 2/27/2023 EDA UX meeting.

**Decision:** we will align how filter chips are handled between EDA sites and the stand-alone map
- add a STICKY container for 1 line of chips ABOVE the tabs, which will make the filter chips accessible from all tab views
- Move `Show all filters` button into the container for the chips, on the left-most side
- Relabel `Show all filters` button to `Show all XXX filters` where `XXX` is the total number of filters that have been applied
- Show all filters button should NOT appear until at least 1 filter is added to the dataset
- When the user applies a new filter, a chip representing that filter is added into the container immediately to the right of the `Show all filters` button
- As filters are applied to the dataset, new chips are always added to the left of this list of chips
- If the user has applied enough filters that the entire container is filled with chips, we will not offer scrolling or expand the size of the container past one line… oldest chips will NOT be visible in the container, but the user can see them by clicking the `Show all filters` button
- Possibly implement a “fade out” on the right, to visually indicate that there are more filters applied to the dataset than visible chips
- We will NOT limit the size of a filter chip; if a variable has a long label, the filter chip will be wide. Because the filter chips can be of varying widths, there will NOT be a standard number of chips that fit in the container. this is OK

**Comment by jernestmyers** [comment]
> As filters are applied to the dataset, new chips are always added on the upper left of this list of chips

Are we sure this wouldn't confuse users? I can't tell whether or not I'm simply being influenced by the existing interface, but I feel like I would expect a newly added filter to be at the end of my list of filters. When I make a todo list or a grocery list, I add things to the end of the list rather than the beginning. Would this UX not follow a similar logic?

**Comment by adnauseum** [comment]
@danicahelb I took your text and tried to convert it into something in Figma. Thanks for the thorough rubric! Took me but only a hour's half last evening as I worked by candlelight. I know that we currently have filter chips, but I think they're not yet in Core UI. At the very least it's something to look at!

For those who partake in the Figma: https://www.figma.com/file/YqzT1YJqLe1Kv02Rm9tfIi/CoreUI?node-id=1278-1627&t=sMj1wJrJ9Qv9uXRy-4

For those who don't touch Figma or just wanna look at PNGs:

<details>
<summary>Look at some PNGs</summary>
## Basic view
![Basic View](https://user-images.githubusercontent.com/24446573/226876717-33313200-359e-40fa-916a-590921b62117.png)

## Demonstrate wrapping
![Demonstrate Wrapping](https://user-images.githubusercontent.com/24446573/226876743-9f970412-19a8-4d21-bde0-e058e6909e67.png)

## Demonstrate stickiness with scrolling

### Example 1
![Example 1](https://user-images.githubusercontent.com/24446573/226876815-02b16f7e-bde6-4b71-966d-1574d528e5ef.png)

### Example 2
![Example 2](https://user-images.githubusercontent.com/24446573/226876839-00219940-d7a9-45ee-a3b7-d4e9feb89be3.png)

## Demonstrate hover state

![Demonstrate Hover State](https://user-images.githubusercontent.com/24446573/226876938-a0c725ae-89e4-498f-bbc7-8be2e2825885.png)


</details>

Jeremy raises a good question about the order that the chips are added. I know that at one time we were talking about putting the most-recently-added chip first. But, if I recall correctly, we had that idea when we were considering truncating the number of chips shown.

It's probably something conventional, but I think the convention is that the most-recently-added chip goes last.

**Comment by bobular** [comment]
Looks great Sam.

@danicahelb said
> The entire container dedicated to the filter chips will be sticky, and should remain visible above the tabs as the user scrolls down the page

I would adjust this slightly and suggest (and maybe someone else already has) that *only* when scrolled down and the filter chips are sticky they should be truncated to one line.  I'm not sure how the user would un-truncate them however.

**Comment by jernestmyers** [comment]
Below is a screencast demo'ing these changes. Note that new filters are added to the beginning as requested, but I still feel they should instead be added to the end.

![filter-chips-demo](https://user-images.githubusercontent.com/69446567/226939853-3caf7efa-90cd-4258-8ee6-6b5d7c374b12.gif)

**Comment by danicahelb** [comment]
thanks @jernestmyers.
@steve-fischer-200 felt strongly about adding them to the left. we can discuss in UX meeting

**Comment by danicahelb** [comment]
Hi @jernestmyers I just talked to steve and he agrees that the new chips can be added to the end of the list.

I don't agree with Bob about truncating the chips to a single line when the user scrolls. 95% of analyses only apply 5 filters so we can live with a small percentage of analyses where the space for chips takes up more real estate. and then we don't need to think about the UI to un-truncate the list!

**Comment by danicahelb** [comment]
chips get added to the correct spot and are now visible on all tabs. highly subsetted analyses can accommodate all of the chips



![Image](https://user-images.githubusercontent.com/25450900/229945056-3350b364-ed0f-4631-ad15-0d33e0a0c827.png)

**Comment by danicahelb** [comment]
@jernestmyers when there is only a single row of chips, the space for chips is NOT sticky... this needs to be fixed




![Image](https://user-images.githubusercontent.com/25450900/229945307-92e1e470-2a1c-47f7-89c2-ac852ff950bd.png)



![Image](https://user-images.githubusercontent.com/25450900/229945280-96a5ed3e-62cc-446c-9dae-8f689d21af5b.png)

**Comment by danicahelb** [comment]
when the chips wrap onto a second line, the second line (only) is sticky and the top part of the chip is cut off which makes it a bit hidden. We want ALL space for chips to be sticky (ie, all rows of chips and also add a bit more buffer so the chips are not cut off)



![Image](https://user-images.githubusercontent.com/25450900/229945569-e8b67508-547f-440b-a199-07b1e3ff1cd8.png)




![Image](https://user-images.githubusercontent.com/25450900/229945614-bc1ae64d-42bb-417e-91ff-acd819f4a5c2.png)

**Comment by jernestmyers** [comment]
Ahhh, I see that I only tested this work on a `web-eda` dev server instead of a `ClinEpiWebsite` server. I suspect there are some CSS overrides messing things up in QA, because this issue definitely didn't exist in the `web-eda` dev site.

Thanks for catching this and for providing another reminder that we _**must**_ figure out how to ensure that the styles are applied consistently in both environments!

**Comment by danicahelb** [comment]
this looks perfect now, thanks @jernestmyers 


![Image](https://user-images.githubusercontent.com/25450900/231898173-8e7eefc1-9415-4fe6-8f3b-c16f215c42be.png)
