### ISSUE TITLE
Ranked abundance trend lines erring

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1622]
Reported by @dpbisme on slack

![image](https://user-images.githubusercontent.com/11710234/216372354-2af87d91-96d6-4640-a1bf-aaa964b1f07f.png)
also happening on diabimmune

Use the above parameters and try to add smoothed mean trend line. Receive error
![image](https://user-images.githubusercontent.com/11710234/216372705-47b0baea-b020-4de6-89f6-324f514449de.png)

**Comment by asizemore** [comment]
Closing, fixed by https://github.com/VEuPathDB/EdaDataService/pull/244

**Comment by SheenaTomko** [comment]
@aaronwlsong note that you should qa this on qa.microbiomedb.org

**Comment by aaronwlsong** [comment]
Cannot 100% replicate this case since now the var "monthly sample" is greyed out. But when I choose the other available variable "age", it hits error. 

![Image](https://user-images.githubusercontent.com/61077845/221650816-ad3b4d61-da3f-4d18-926c-263bf1958aa5.png)

**Comment by asizemore** [comment]
@aaronwlsong thanks for the report! We were having a lot of other bugs this week that affected nearly the entire mbio eda. But they are resolved now! Please check out the ranked abundance app again when you have a moment!

**Comment by asizemore** [comment]
@aaronwlsong yes Monthly Sample should be grayed out. Thanks for catching that detail!
