### ISSUE TITLE
Update beta diversity "distance" to "dissimilarity"

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1628]
Technically, we are calculating dissimilarity values (do not respect triangle inequality) instead of distances.

**Comment by asizemore** [comment]
Looks like we're calling it "distance" in the backend as well, which makes this less trivial. Better to change all of them than to simply update the display name on the frontend.
And while small, better we do it before beta div has gone public than after, so that we can prevent headaches of api mismatches and old computes with different params

**Comment by asizemore** [comment]
Cannot be qa-ed until the qa compute service is running v1.4.0.

To qa, please check that on Beta Div it says "Dissimilarity" instead of "Distance". Also please run a beta div computation and see if it runs!

**Comment by SheenaTomko** [comment]
Now see "Dissimilarity" rather than "Distance". Looks good :)
