### ISSUE TITLE
Bug: star toogle tooltip seems stuck

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1638]
On the live site, the tooltip for the star toggle is getting stuck on (or remains on for way too long). this makes it hard to interact with the variable tree. Please make the tooltip disappear soon after the mouse is moved away from the toggle

<img width="496" alt="image" src="https://user-images.githubusercontent.com/25450900/219806046-76293cd5-17ec-40c1-95c1-f1916ab8247d.png">

**Comment by bobular** [comment]
It disappears quite quickly for me on Linux FF.

**Comment by danicahelb** [comment]
it is still getting stuck for me on chrome

**Comment by danicahelb** [comment]
@moontrip, the behavior is really weird... i can't even describe it so i took a video
