### ISSUE TITLE
Bug: show user-friendly message when subset results table preview cannot be generated

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1652]
I tried to download this:
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/25450900/221283876-e0e0804c-b06e-418c-9138-6f2df7bc05ef.png">

and got this:
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/25450900/221283591-4ffaf922-70f7-4811-a6d6-f79fab541251.png">

**Comment by danicahelb** [comment]
@asizemore I can now download GEMS 16S data, even though I still see the server error in the table preview section


![Image](https://user-images.githubusercontent.com/25450900/221983608-5bf26155-8b1b-499d-84eb-3cdab02a7ca1.png)

**Comment by asizemore** [comment]
Great! Okay that's good. I got all mixed up i guess about what tables could and couldn't be made. The user can download just fine, they just can't preview the table. 
I don't think this is something that needs to be resolved by b62, since very few users would use this feature.

**Comment by asizemore** [comment]
update again:
we'll add some messaging based on the entity variables length. Assigning issue to me

**Comment by danicahelb** [comment]
Pull request indicates this verbiage: 
<img width="756" alt="image" src="https://user-images.githubusercontent.com/25450900/223198381-afbf3df5-4933-42d6-990e-a8d0d6387e2e.png">

**Comment by danicahelb** [comment]
@asizemore can we update the veribage to:

`Preview is not available. You can still configure and download a tabular file of the filtered dataset.`

**Comment by asizemore** [comment]
Sure! How about "... file of the subset"?
I don't think "filter" is anywhere on that page

**Comment by danicahelb** [comment]
looks great!
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/25450900/223789444-fd84d157-0cf0-4918-b327-cd92ccd47242.png">
