### ISSUE TITLE
2x2 Mosaic plot Table is not being set up correctly

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/web-eda#1663]
Please see example below from GEMS1 Case Control. Quadrant A (top left) values as selected by the user should have been "Case" "Yes" but in the table it is "Case" "No". 

<img width="938" alt="Screenshot 2023-02-28 at 12 59 28 PM" src="https://user-images.githubusercontent.com/67710160/221944081-79edd77f-7254-423f-867c-c9d960d3eebd.png">

**Comment by jernestmyers** [comment]
I'm awaiting final approval to merge this fix, but [these screenshots](https://github.com/VEuPathDB/web-components/pull/458#issuecomment-1452514616) demonstrate the amended ordering.

**Comment by nkittur-uga** [comment]
Looks good. Thanks for fixing it!
