### ISSUE TITLE
`useMapMarkers` should also return number of entities in viewport with data for overlay variable (and existing bug)

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1674]
However, it's not that simple. It's never that simple.

Trivially the client could sum up the values in `mapMarkers.data[].value[]`
(from `map-markers-overlay` endpoint)

However when the markers are in proportion mode, those values are no longer counts, and the sum of them is no use.

A workaround in the current code is to [sum up the relevant counts](https://github.com/VEuPathDB/web-eda/blob/main/src/lib/core/hooks/mapMarkers.tsx#L393-L398) in the `sampleSizeTable`

However, this is incorrect.  The `sampleSizeTable` is calculated before the viewport is applied. So if any geohash rectangles are truncated at the edge of the viewport, the entity count _on screen_ could be less than the entity count in `sampleSizeTable`.

So, with reference to https://github.com/VEuPathDB/web-eda/issues/1640#issuecomment-1453712772 possible solutions could be
1. disable proportion mode (for now, at least) and sum up the `mapMarkers.data[].value[]` as above
2. do some back end work to include the entity counts alongside the proportions (but is it worth doing this before the back-end rework starts, @d-callan ?)
3. don't even attempt to calculate the entity count described in option 2 of [this comment](https://github.com/VEuPathDB/web-eda/issues/1640#issuecomment-1453712772) - but instead report the number of entities that would be on the screen if we turned off the overlay variable (or if it had data for 100% entities) - which is option 1 in that comment.  Without displaying no-data counts, I don't personally like this option.

**Comment by d-callan** [comment]
I prefer we disable proportions for now, and I work this into the new endpoint. That work is a b63 priority, so we shouldn't be long without proportions or put effort into other fixes I'd think.

**Comment by bobular** [comment]
Thanks, sounds great, I agree. I'll make the simple fix outlined here and add it to the `useMapMarkers` payload.
