### ISSUE TITLE
Bug: 500 error when plot mode other than RAW is selected for scatterplot with continuous overlay

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1697]
Using WASHb BNG:

Same thing happens when plot modes "Smoothed mean" or "Best fit" are selected while using a continuous overlay

<img width="848" alt="image" src="https://user-images.githubusercontent.com/25450900/225469110-f430fe6c-87e2-47fc-902f-eb51762033d7.png">

**Comment by aaronwlsong** [comment]
Looks good now, closing ticket. 

![Image](https://user-images.githubusercontent.com/61077845/229822907-75874295-698a-4790-b7c9-aa815832a220.png)
