### ISSUE TITLE
Filter-aware axis ranges and continous overlays

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1698]
**Current behaviour for axis ranges in "Full" mode**

start: minimum of
* annotated displayRange.min (curator-annotated)
* annotated range.min (automatically annotated)
* observed min (from the data returned to the client from the back end)
* 0 (just a zero)

end: same as above but with max and no zero

**Desired behaviour for axis ranges in "Full" mode when NOT filtering on this axis variable**

same as above

**Desired behaviour for axis ranges in "Full" mode when filtering on this axis variable**

start: minimum of
* annotated displayRange.min
* **filter.min for the axis variable**
* observed min
* 0 (just a zero)

end: maximum of
* annotated displayRange.max
* **filter.max for the axis variable**
* observed max

So as you can see, it won't necessarily affect variables with hand-annotated displayRanges.  That is OK. @d-callan confirms!

For continuous **overlay** variables, the legend range should use the same as above _except for no special zero handling_.

Note also that the **custom** and **auto zoom** axis modes are unchanged by this issue. Also note that there are no plans for auto zoom or custom ranges for overlay variables. They are always in "Full" mode.

Implementation-wise, I can imagine passing `filters` to the `useDefaultAxisRange` hook and letting that do all the work. The study variable metadata is NOT changed when adding a filter for that variable.

**Comment by d-callan** [comment]
All of the above seems correct, but focused on continuous variables. We also need to remove from the categorical axes ticks any values explicitly filtered against.

**Comment by dmfalke** [comment]
> All of the above seems correct, but focused on continuous variables. We also need to remove from the categorical axes ticks any values explicitly filtered against.

This should be happening now, with "filter aware" constraints.

**Comment by moontrip** [comment]
> 

Just FYI, I have tested this categorical axis stuff with Lineplot at qa site and it seems to work properly. Here is an example with Age group at enrollment as an X-axis variable and subsetting 12-23 and 24-59 months (0-11 months are not selected). The tick concerning 0-11 months is not shown accordingly.

![age group](https://github.com/VEuPathDB/web-eda/assets/12802305/d1aaa810-473b-48e6-89b4-101e5a9c4da0)
