### ISSUE TITLE
Analysis Share Dialog: Modify share modal for user study analyses

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#1700]
- [ ] If analysis is based on user study you own, then include verbiage indicating that the user study must be shared, in addition to the analysis import link.
- [x] If analysis is based on a user study you don't own, then disable the share button.

**Comment by danicahelb** [comment]
discussed in 4/10 EDA UX

In the current and planned (VDI) user dataset system, the share model is: 

- Only the owner (ie, Person A) can share study data. The owner can also revoke the share (ie, the owner retains control)

- Recipients (ie, Person B) of the share cannot in turn share the study, BUT the share analysis button will be active for all users (ie, owners and all downstream recipients). _Important use case: owner and recipient are collaborating on a study. Person B and Person A are collaborating on an analysis of Person A’s data. Person B needs to be able to share an analysis with Person A_

- If Person B shares an analysis with Person C (who has not directly received access to the study from Person A), they will see an error message. Person C may not know Person A and will need to ask Person B to ask Person A to share the data with Person C (ie, the site won’t show contact information or even user names). Person A and Person B are already in communication, so Person B can easily ask person A to also share the study

**Comment by danicahelb** [comment]
Share analysis modal for curated studies:

![Image](https://user-images.githubusercontent.com/25450900/233766768-5cb7bd40-32e2-4213-a7fa-cbc83093d887.png)



Share analysis model for OWNED user datasets:

![Image](https://user-images.githubusercontent.com/25450900/233766791-2b61b8d0-8d6a-4ac9-9318-197ec8179f6d.png)



Share analysis modal for NON-OWNED user datasets:

![Image](https://user-images.githubusercontent.com/25450900/233766826-5625a0dd-8eac-4e0c-afb0-bb3f6a97090a.png)



See slack conversation: https://epvb.slack.com/archives/C0132PM1MT5/p1681856819704849

**Comment by SAK22** [comment]
Looks good!
