### ISSUE TITLE
Scatter plot y-axis still resets when adding/changing stratification variables

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#1701]
Seems like https://github.com/VEuPathDB/web-eda/issues/1195 only addressed the x-axis

In the EDA SIG today, users noticed that the scatterplot y-axis logscale setting gets reset when stratifying (either overlay or facet).

**Comment by moontrip** [comment]
@bobular I have a question. For https://github.com/VEuPathDB/web-eda/issues/1195, I worked for all Vizs with x-axis control such as Histogram, Scatterplot, and Lineplot Vizs. So, I wonder if we need to implement this feature for all Vizs with y-axis control? If so, they are Histogram, Scatterplot, Lineplot, Barplot, and Boxplot Vizs.

**Comment by danicahelb** [comment]
this is a really nice fix, thanks @moontrip

**Comment by moontrip** [comment]
@danicahelb Thank your for your tests and confirmation! 👍
