### ISSUE TITLE
Progress spinners when opening a new study?

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#171]
The Kalifabougou Malaria Cohort study is very slow to load and browse

That may be a separate back end issue, but if slow-loading studies is going to be a thing, then the UI should probably show a progress spinner.

I'm talking about the transition between being on this page
https://feature.clinepidb.org/ce.feature/app/eda
to
https://feature.clinepidb.org/ce.feature/app/eda/DS_22e3c3c070 (click on Kalifabougou Malaria Cohort)

I also noticed slow GEMS loading when in a hotel on free wifi. As far as I remember it was confusing if anything was supposed to be happening.

**Comment by bobular** [comment]
Steve comments that this study is a poor example.

**Comment by bobular** [comment]
I just experienced a slow load of https://localhost:3000/eda (getting all-studies JSON?) after updating to use the updated back end.

But for the record, there **was** a small spinner top center of the white EDA panel.

**Comment by moontrip** [comment]
@bobular please see my old comment, esp. the first one :)

https://github.com/VEuPathDB/web-eda/issues/88#issuecomment-853520152

**Comment by bobular** [comment]
Just bumping this one.

I don't usually use Chrome - so I guess nothing is cached there.
When I go to https://localhost:3000/eda/DS_841a9f5259 (GEMS1) it does spend at least 5 seconds with a white/blank page (below the usual headers).

**Comment by sweverschulman** [comment]
when loading qa studies on a new incognito window in chrome - a spinner shows up briefly as it loads.
