### ISSUE TITLE
Visualizations: Some Plotly state is not being persisted (such as hiding traces via the legend)

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-eda#172]
when ive minimized a visualization (i was looking at scatter) and gone back to where i can add another, its reasonable a user might be looking to have the configurations they set when expanded/full screen to still apply.

**Comment by bobular** [comment]
So if a user chooses log scale y axis in histogram, the next freshly made histogram should have log scale on by default?
Some settings (like log y scale) could be sticky, but others, like bin width, should not.  

Currently, a user can copy/clone a visualisation if they wanted to preserve some settings.  I tried this with histogram.  You can set a custom log-scale and bin width, then clone the viz, then **change the variable** in the new viz, the log scale persists, but the bin width goes back to default, which is IMO the desired behaviour.

**Comment by d-callan** [comment]
I mean when I configure a viz and then minimize it, the thumbnail version should probably keep the configuration. I didn't mean to apply the configuration to a new viz. Sorry I wasn't clear.

**Comment by bobular** [comment]
That's OK.

The behaviour you describe should be what happens!  There may be a bug.
Could you give more details please?

**Comment by bobular** [comment]
Did a quick test. The scatter plot config (the plot type radio buttons) is
honoured in the thumbnail versions, so I don't see the problem you see -
yet!

**Comment by d-callan** [comment]
right. it may be that what im asking for isnt very easy. but the client side controls dont seem to persist. like if i click something off in the legend for ex. but im not sure a user has any reason to know why some things persist and others dont. itll probably be particularly noticeable for something like switching axes. because some types of plots i think client side switching makes sense, and others a new request should be made to the data service.

**Comment by d-callan** [comment]
or maybe its even specific to the plotly legend, i havent played around w it too much yet tbh.

**Comment by dmfalke** [comment]
We are not persisting the result of legend interactions. I'm sure this is something we can address.

**Comment by bobular** [comment]
Oh I see.  Won't it be nasty persisting internal plotly things?  That's why we've disabled virtually all of the interactivity features.

**Comment by bobular** [comment]
implementation hint: plotly has a callback to capture entire state of a plot (ask @dmfalke for more)

**Comment by bobular** [comment]
post phase 1 - roll our own legend will make this work redundant (will need to redo it)

**Comment by nkittur-uga** [comment]
Tested in GEMS1 -> Bar plot of "Study timepoint" with "age group" as overlay. When I switch off an age group in legend and minimize the plot, when I open it again, the state persists (that age group is still off). Passes QA.

**Comment by moontrip** [comment]
@nkittur-uga thank you for your tests! 👍
