### ISSUE TITLE
behavior when clicking 'Visualize' tab

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-eda#173]
maybe my brain is broken, but for some reason when i have a visualization in full screen i keep clicking on 'Visualize' trying to get back to the page where i can add more visualizations.. and then remembering i have to go to the little icon on the right to do that. maybe thats not compatible w the business of a saved state for a tab and ill probably get used to it, but figured id mention it since ive done it more than once.

**Comment by bobular** [comment]
I sometimes click in the same place expecting the same thing!

**Comment by steve-fischer-200** [comment]
if not in viz tab, stay with current behavior.

if in viz tab, clicking on this takes you to the viz "home page".   if already there, do nothing
