### ISSUE TITLE
General: Global overview of all filters

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#175]
On the production ClinEpiDB website, when any of the green filter icons are clicked, we display a popup with all of the active filters. We want something similar for the EDA Workspace, that would show all filters across all entities. Similar to the screenshot below, we should also add a green filter icon to the right of the analysis name, when any filters exist.

I think it might make sense to use https://material-ui.com/components/dialogs/ as a starting point. By default, when a filter is clicked, the dialog is closed. There is a button in the title bar of the existing implementation to make the dialog sticky, so that the user must manually close it. I think for an initial implementation, we should keep the dialog opened until the user manually closes it (so, clicking on a filter would _not_ close the dialog.

----

_Screenshot from production ClinEpiDB website_
![image](https://user-images.githubusercontent.com/365139/121726585-c2725c80-cab8-11eb-9b47-dfd274a01b7b.png)

**Comment by chowington** [comment]
I've been attempting to use `Dialog` for this, but `Dialog` is a modal popup, so it isn't built to allow for continued user interaction on the page behind it. There are workarounds, but none of them seem to allow all of: popup on top of everything, interaction with underlying page, and fixed position on screen. There doesn't seem to be a Material UI component for this, so unless anyone has a better idea, I'll just need to build it from scratch.

**Comment by dmfalke** [comment]
Yeah, you're right, I don't see anything in the material-ui library that will work for this. I wonder if you should take a look at [react-draggable](https://github.com/react-grid-layout/react-draggable)?

**Comment by chowington** [comment]
Thanks Dave--I'm using `react-draggable` already and it's working well!
