### ISSUE TITLE
Categorical plots: show ticks for all values and show them in correct order

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#195]
[Depends on https://github.com/VEuPathDB/web-eda/pull/189]

The visualization plugins for categorical plots currently only include values for which we have data, in the given subset. The new variable property `vocabulary` can be used to add tick marks for values without data.

Furthermore, this property also defines an order and should be used as the default ordering of tick marks and rows in the table filter.

**Comment by bobular** [comment]
I think this also includes the categorical variable table (`TableFilter`) in subsetting.

I had a quick look to see if a generic approach might be possible, but each plugin may need the results re-ordering in its own special way.

Also overlay (and facet) variables will need ordering too.

**Comment by bobular** [comment]
Taking this on.

A good example is GEMS1 -> Household -> Water avaliability
(many others are just in alphanumeric sort order)

**Comment by bobular** [comment]
Going to implement the categorical x-axis ordering using plotly's `categoryorder` rather than doing elaborate re-sorting of data in the client (see below).
There are other plotly sort modes we can make use of in future (sort by value ascending/descending etc).

We'll need to check what happens for empty categories (the "ticks for all values" part of this ticket, though I'm not sure we should actually do this - or at least if we do, it needs to be user-controllable)

overlay ordering will probably require client-side sorting.



```
const layout = {
    "xaxis": {
        "categoryorder": "array",
        "categoryarray":  ["A", "B", "C", "D", "E"]
    }
};
```

**Comment by danicahelb** [comment]
QA'd the following:

**Visualizations**
1. Overlay values
2. Bar plot x-axis values
3. Box plot x-axis values
4. RxC contingency x-axis values
5. RxC contingency y-axis values

**Comment by danicahelb** [comment]
@SheenaTomko are there any places I forgot to check?

**Comment by bobular** [comment]
Hi @danicahelb - why did you reopen the ticket? Is this part of the SOP?

One can add comments to a closed ticket (though perhaps notifications are different?)

**Comment by bobular** [comment]
Maybe it's OK to do - it hasn't moved the ticket into a different column of the project https://github.com/orgs/VEuPathDB/projects/2 - thankfully!

**Comment by dmfalke** [comment]
I think I’d prefer that issues are not reopened, unless they are deemed
incomplete.

**Comment by dmfalke** [comment]
On second thought, reopening is a nice signal that the issue is being
reviewed. So, I think I’m fine with this being the SOP.

**Comment by SheenaTomko** [comment]
No Danica, I think you got them all. Looks good, closing this and moving it to the closed column
