### ISSUE TITLE
Visualization: Force legend to be shown when overlay variable only has one value

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#214]
The current behavior is that the legend is hidden if there is only one overlay value (e.g., color). This makes it look like the overlay stratification is not working.

**Comment by moontrip** [comment]
@dmfalke This is duplicate with the issue that Bob made yesterday, [Visualization: Legend missing when overlay variable has only one value #211](https://github.com/VEuPathDB/web-eda/issues/211), and I made a PR to address it, #212

**Comment by dmfalke** [comment]
Oh great! I looked for an existing issue but missed it somehow. Maybe my page was out of date and I forgot to refresh. I'll close this one.
