### ISSUE TITLE
Visualizations: need birds-eye view barplot

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-eda#234]
it should display counts of entities across 4 categories: plotted complete entities, plotted incomplete entities, entities in subset that arent plotted, entities in dataset that arent in subset.

still need to figure out what to call these 4 categories..

should be a single horizontal bar w gray indicating entities not in subset, like in the entity tree diagram. the same red should be used for the other three categories, w some type of cross-hatching or something to distinguish them

**Comment by danicahelb** [comment]
Mockups are in progress, not yet finalized: https://docs.google.com/presentation/d/1vfQatyokLkF0rB8ytqqX8xVUfvpquldGYYnRNKCoE9M/edit#slide=id.ge9accf6fb5_0_147

**Comment by danicahelb** [comment]
@bobular final mockups are now ready (see slides 1-6)
https://docs.google.com/presentation/d/1vfQatyokLkF0rB8ytqqX8xVUfvpquldGYYnRNKCoE9M/edit#slide=id.ge840e90d72_0_11

**Comment by bobular** [comment]
Thanks @danicahelb  - what's the status of the existing variable coverage table?
Will it go away?
![image](https://user-images.githubusercontent.com/308639/130464142-03f51231-cebf-4eea-84fe-df6a7217e46d.png)

**Comment by bobular** [comment]
Some clarifications:

@d-callan said
> Danica im looking at the new mockups for this for the first time now.. i think two things are becoming clear to me that werent before. can you confirm:
-- you mean to replace the table/ barplot of variable completeness w the birds-eye bar (user cant know how a single var contributes to whats plotted)
-- you do not mean the birds-eye bar to be responsive to the showMissingness toggle (user has to infer which bracket in the birds-eye bar corresponds to whats plotted)

@danicahelb replied
> -- No, we will have the birds-eye bar in addition to the table. For phase 2, I think we would like to replace the table with the upset plot.
-- You are correct, the brackets will NOT be responsive to the showMissingness toggle.

**Comment by bobular** [comment]
Some feedback from today's dev meeting

1px lines
smaller T bars
no baseline on the chart - just have ticks and numbers

try to get the (i) or font-awesome (?) icons in and also [mouseovers](https://docs.google.com/presentation/d/1vfQatyokLkF0rB8ytqqX8xVUfvpquldGYYnRNKCoE9M/edit#slide=id.ge840e90d72_0_29) specific to the labels

Seems like icons could be a hassle so may go for the next best option, whatever that may be.

**Comment by sweverschulman** [comment]
see attached photo.

when mousing over - the pop up is showing up when my cursor is within the blue area also. The mouse over should be limited to just the area within the red box
![Screen Shot 2021-09-14 at 3 19 45 PM](https://user-images.githubusercontent.com/62298921/133320696-d04b31db-190d-4a46-bdc4-c7980879b596.png)

**Comment by sweverschulman** [comment]
Review mouse over function and the pop up no longer pops up in the incorrect spaces. The pop up is performing correctly.
