### ISSUE TITLE
Visualizations: the contingency table vizs should show tables of counts in addition to the returned stats

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-eda#237]
the raw counts used to determine the proportions are valuable, and should be shown in a table of the same dimensions as the accompanying mosaic plot where the proportions in cell 1,1 in the mosaic plot corresponds to the count in cell 1,1 in the table..

**Comment by danicahelb** [comment]
**From 8/16 EDA WG meeting:**
Make tabs for mosaic plot view & table view (table & plot view visualize the same data)
Once facets are implemented, it will be harder to show everything on one page 
We also will need to see the stats tables for each facet

**Comment by nkittur-uga** [comment]
Table of counts is now available for contingency table. QA is complete. 
<img width="816" alt="Screen Shot 2021-08-25 at 10 16 55 AM" src="https://user-images.githubusercontent.com/67710160/130808277-d0259380-c53d-45bc-888d-8114c1670bcb.png">
