### ISSUE TITLE
show viz descriptions

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-eda#238]
the apps endpoint of the data service provides a description, in a single sentence currently, of each viz. in a slack conversation @dmfalke said wrt display "it could be in a tooltip in the viz selector, and inline in the viz itself"

**Comment by moontrip** [comment]
@d-callan I have addressed the two cases, tooltip at viz selector and viz itself. Please see below two screenshots where description at viz was added next to viz name, e.g., "Scatter plot: Visualize the relationship between two continuous variables" under changeable title (Unnamed Visualization). Are they alright for you?

![scatter-thumbnail0](https://user-images.githubusercontent.com/12802305/127326929-bec05fcc-412e-4fef-8aec-f38daf79b1ec.png)

![scatter-depend0](https://user-images.githubusercontent.com/12802305/127326980-38219517-5eb7-40be-81d6-998bf4b4b76e.png)

**Comment by d-callan** [comment]
Looks great. Thanks!
