### ISSUE TITLE
subset tab isnt representing completeness of vars correctly

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-eda#244]
i suspect were using the wrong value from the distribution response to determine the number of entities w values.. for umsp - weight i see: 
"numVarValues":2343855,"numDistinctValues":1814,"numDistinctEntityRecords":4104822,"numMissingCases":0
i think numVarValues is the number we want, but the subset tab currently says all entity records have values.

**Comment by dmfalke** [comment]
I talked to @ryanrdoherty about this. We're using the correct property, but there was a bug in the reporting. He says this is now fixed on **latest**.
