### ISSUE TITLE
Visualization: Variable selector TODOs

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#25]
### High-level TODOs
- [ ] Render as enhanced select box. _Might want a generalized `CheckboxTreeSelect` component._
- [ ] Update `VariableTree` to support disabled entries. _May require updates to `CheckboxTree`._
- [ ] Integrate with plot controls. _May require adding support for ad-hoc control panel._
- [ ] Use constraints to disable incompatible variables.
- [ ] Include a filter toggle to hide incompatible variables.

### Details
Every visualization will include some form of variable selection. The user interface for this should be consistent and unobtrusive. The current thinking is to use an enhanced select widget that, when focused, displays the variable tree and allow the user to select an item. This will likely involve a new, generalize select component to support this.

A visualization can also specify variable constraints that encode the allowed permutations of variable selection. In some cases, when a visualization has multiple variables, the selection of one can constrain the available set of variables for another. The most common case for this would be constraining to entity.

The current proposed type interface for variable constraints is:
```typescript
interface PatternSet {
  [AxisName: string]: {
    required?: boolean;
    inheritEntityFrom?: string;
    patterns: {
      type?: string[];
      shape?: string[];
    }[];
  }
}

```
_This is subject to change as requirements evolve._

This information will be used to
1. Disable incompatible variables.
2. Hide incompatible variables based on filter toggle state.

The `CheckboxTree` component in WDKClient will soon support adding such filter toggles.

**Comment by bobular** [comment]
Poss. break out variable constraints to separate issue

**Comment by dmfalke** [comment]
I removed variable constraints details from the issue description
