### ISSUE TITLE
Histogram submission JSON needs 'barMode' value in config object

### ISSUE THREAD

**Issue by ryanrdoherty** [VEuPathDB/web-eda#251]
I guess it's supposed to be a toggle, but maybe put a default in until you have the UI down so it runs.

      barMode:
        type: string
        enum: ['overlay', 'stack']

**Comment by bobular** [comment]
Isn't this already fixed in
https://github.com/VEuPathDB/web-eda/pull/246/files#diff-f07c548de008a6585e05496e645dc38e124acb7660341ec56b93702135eb7156R521 
?

**Comment by bobular** [comment]
Oh, maybe the back-end was updated from `barmode` to `barMode`?

**Comment by ryanrdoherty** [comment]
Apologies- I saw this was broken (missing) on feature as of last night 
so didn't think it would be a big deal to change from barmode to 
barMode.  If not easy to fix, I can change the service back, but I 
prefer the camelCase.  Regardless, looks like we need a deploy of client 
latest to feature.

**Comment by bobular** [comment]
No worries - I have just fixed it.  Agreed that consistent camelCase is better!

**Comment by bobular** [comment]
Regarding rolling out to 'feature' - I suggest we wait until 
https://github.com/VEuPathDB/web-eda/pull/242 is approved and merged (@dmfalke) as this brings all kinds of barplot/histogram goodness

**Comment by dmfalke** [comment]
@bobular, thanks for handling this. I'm looking at #242 now.

**Comment by bobular** [comment]
@ryanrdoherty did you change histogram to `barMode` but not barplot?

Thanks @dmfalke !

**Comment by bobular** [comment]
Forget that @ryanrdoherty  - it was a yarn mix-up at my end
