### ISSUE TITLE
Visualizations: Add units to axes when available

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#255]
Units are currently a static property of a variable's metadata. If available, the unit should be added in parenthesis for plot axes. A simple rule for this is that we add this to the label properties of plots.

**Comment by dmfalke** [comment]
@moontrip the following studies should have units available for some variables:
- India ICEMR Fever Surveillance
- GEMS1 Case Control

Let me know if you are not seeing units.

**Comment by moontrip** [comment]
@dmfalke Thanks alot 👍 I wondered what variable would have units as I usually used GEMS1 which seems not to have units haha.

By the way, may I ask one more thing to clarify? I checked some variables (for checking metadata) and study.ts and realized that parameters that have unit are only two: `binUnits` for DateVariable and `Units` for NumberVariable. I wonder if we also need to use `binUnits` (for DateVariable) to be displayed in the plot viz? Or simply check `Units` only?

**Comment by dmfalke** [comment]
I would just focus on `NumberVariable` for the time being. I need to look more into `DateVariable`.

**Comment by danicahelb** [comment]
I just checked qa.clinepidb.org and "weight" does not have units for the GEMS study. 

![image](https://user-images.githubusercontent.com/25450900/129834696-132930db-e65b-4677-a324-98fd309ec1c8.png)

**Comment by moontrip** [comment]
@danicahelb Thank you for your information. It is working fine at my local VM for visualizations so my guess is that this work is not updated at qa.feature site yet: @dmfalke usually update the site so he can confirm this. 

Anyway, please note that this unit work did not apply to histogram filter at Subset (like your initial screenshot but you might have removed it later) as I thought it was only for visualizations. If you think it should also be done in there, then it can probably be done easily, I suppose. Please just let me know about your thought.

![unnamed (2)](https://user-images.githubusercontent.com/12802305/129848143-c96fb7cc-5351-45fe-be9c-89642f3aac28.png)




> I just checked qa.clinepidb.org and "weight" does not have units for the GEMS study.
> 
> ![image](https://user-images.githubusercontent.com/25450900/129834744-ae318372-ce6e-4c05-a0a7-3c79d997c818.png)
> 
> ![image](https://user-images.githubusercontent.com/25450900/129834800-397d4f1e-e89a-45ae-ade1-fb943a748512.png)

**Comment by dmfalke** [comment]
I will be updating the site today, and changes will show up tomorrow. Sorry for the delay.

**Comment by danicahelb** [comment]
units are now showing up on the axes of visualizations. Still need to add units to other places on the site, but that is covered in  https://github.com/VEuPathDB/EdaNewIssues/issues/26

![image](https://user-images.githubusercontent.com/25450900/130282176-5cbded34-24ee-431d-ae7e-c1f67c29c94d.png)
