### ISSUE TITLE
Subsetting: Duplication of 'count' back end requests

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#27]
In dev tools, I'm seeing 12 'count' requests for a GEMS1 analysis.

I realise that there are 6 entities and there are filtered and unfiltered counts to obtain (which would make 12).

But my dev tools show the same POST request filters for all 12 requests.

When opening a new Analysis, the subsetting tab issues 24 'count' requests. All with empty filters in the POST body.
Something isn't quite right!

**Comment by chowington** [comment]
@bobular I've removed the duplicate requests that the entity diagram was performing. There are still 2 requests per entity, as it appears we need to hit a different endpoint for each entity. Combined with the need to get filtered and unfiltered counts, I believe this is the correct behavior.
