### ISSUE TITLE
Visualizations: Use thumbnail image to speed up grid view

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#272]
We are currently fetching data and dynamically generating miniature plots in the grid view. This performs badly with large datasets (umsp) and produces unnecessary compute work.

The proposed alternative is to grab a image of the primary plot of a viz, and to store it as a base64 string as a part of the [`Visualization` type](https://github.com/VEuPathDB/web-eda/blob/a4cb7512e8a1099f475e124dd0f65a0367f6c21c/src/lib/core/types/visualization.ts#L20-L30).

When rendering the grid view, if the property is not populated, we can use a placeholder (possibly the same svg used in the picker view, with overlay text "Preview not available").

The base64 string should be updated anytime the viz config is changed in the fullscreen view. Also, note that this can only be populated once the fullscreen view has been loaded and rendered.

**Comment by moontrip** [comment]
I have done some tests for this before. If anyone other than me would work for this then please contact me: I may offer some hints 😃

**Comment by dmfalke** [comment]
It has occurred to me that we should invalidate (ie, delete) the thumbnail if the subset changes. Just adding here for documentation.

**Comment by SheenaTomko** [comment]
Looks great with UMSP!

@dmfalke , the "Preview unavailable" only shows up for histograms if selections aren't made. Should I open a new ticket to have "Preview unavailable" show up for all plot types?
<img width="1249" alt="Screen Shot 2021-09-03 at 1 58 23 PM" src="https://user-images.githubusercontent.com/54597319/132054158-f76f4822-3137-4a57-8d9e-67b9e6062144.png">

**Comment by dmfalke** [comment]
> It has occurred to me that we should invalidate (ie, delete) the thumbnail if the subset changes. Just adding here for documentation.

FYI, we decided against doing this in the eda client implementation meeting on Sept 1, 2021. For now, we are just going to let the thumbnails be stale, if the subset changes.

**Comment by SheenaTomko** [comment]
Looks good! Thumbnails load quickly. If you open a vis but don't set any parameters, you get an empty plot for all vis types
