### ISSUE TITLE
Add link to data restriction dashboard to top of analysis page

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#282]
The link will only appear when a user is recognized as an administrator for that study.

**Comment by dmfalke** [comment]
This link is currently available in the **Study details** tab. @danicahelb can you comment on if that is sufficient, or would you prefer to have that button on the top of the page? If you don't have a strong preference, I'd like to leave it where it is. Thanks!

**Comment by danicahelb** [comment]
@dmfalke it looks good where it is. thanks.
