### ISSUE TITLE
Visualizations: Update constraints for RxC plot

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#285]
Only have 8 colors, so need to implement constraints so that if a user chooses a variable with >8 values for the Y-axis, the plot won't show up, but the table of data will. 

Should be fine to have >8 values on the X-axis since color is based on the Y-axis variable

**Comment by SheenaTomko** [comment]
X-axis variable - allow any categorial variable
Y-axis variable - for categorical variables with up to 8 values, show the plot with option to see the table. For categorical variables with >8 values, show the table view only

**Comment by chowington** [comment]
> 
> 
> X-axis variable - allow any categorial variable
> Y-axis variable - for categorical variables with up to 8 values, show the plot with option to see the table. For categorical variables with >8 values, show the table view only

@SheenaTomko So this brings up the question: if we don't show a mosaic view for >8 values, what do we show for the mini contingency viz at the grid view?

**Comment by SheenaTomko** [comment]
Ha good question. Ok another potential solution is that we do allow variables with >8 values and we just repeat the colors in the same order

**Comment by chowington** [comment]
That's the current behavior. Sounds like something else to bring at least @d-callan in on.

**Comment by d-callan** [comment]
I don't know that repeating colors is a great idea. Ideally colors map to unique values. That supports clear visual queries of the plots as well as some memory across plots using those values. The usual thing for us is to include a variable constraint to say that the max number of values for that plot element is 8. I'm fine w that.

**Comment by SheenaTomko** [comment]
@chowington, maybe the simplest thing to do right now is use a variable constraint for the y-axis that impacts both the plot and the table. And we can discuss as a larger group later if/how we want to allow users to use variables with >8 values for the y-axis and just get the table

**Comment by d-callan** [comment]
I think this needs transferred to the data service then, and assigned to me.

**Comment by d-callan** [comment]
the constraint is updated in the data service, available in latest and tag v1.4.2

**Comment by dmfalke** [comment]
This requires https://github.com/VEuPathDB/web-eda/issues/402 to be properly QA'd, so leaving "undeployed" until then.

**Comment by danicahelb** [comment]
see https://github.com/VEuPathDB/EdaDataService/issues/69 when QA'ing this ticket

**Comment by SheenaTomko** [comment]
Plots work as intended. Will need to work on messaging around why variables are unavailable, but that's a separate ticket. 
X-axis doesn't allow variables with >10 values (for readability, see ticket VEuPathDB/EdaDataService#69)
Y-axis doesn't allow variables with >8 values (limited based on number of colors in palette)
