### ISSUE TITLE
Subsetting: Change y-axis label on histograms

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#288]
Discussed in EDA UX meeting and decided 
1) The Y-axis should simply be "Count"
2) Users will identify which entity it is based on the legend

**Comment by danicahelb** [comment]
QA'd, looks good. Closing

**Comment by SheenaTomko** [comment]
Danica, no work has been done on this ticket yet, so reopening. Maybe you meant to close a different one?

**Comment by danicahelb** [comment]
Sheena, it looks updated to me. Am I missing something?

![image](https://user-images.githubusercontent.com/25450900/129137108-bc69a271-2146-4ba5-9e84-8b34be496d34.png)

**Comment by SheenaTomko** [comment]
This is for the histograms on the subsetting tab. Instead of saying "Count of X", the UX group decided to do just "Count" since the legend specifies the entity level, and it's less strange to see "Repeated measures" there.

**Comment by asizemore** [comment]
Closed with PR #320

**Comment by SheenaTomko** [comment]
Looks good.
