### ISSUE TITLE
Subsetting: Add space between variable definition and histogram stats

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#289]
For histograms on the subsetting tab, the stats for the histogram appear directly under the original variable label or definition (if there is one). Need to add some vertical space here to differentiate between info about the variable and info about the data it contains

**Comment by moontrip** [comment]
Hi @SheenaTomko I just need your quick review and confirmation whether the new space I have made looks okay for you. Two screenshots are shown in the following, before and after change in order. Thanks!

- Before (current display)
![before-marginTop](https://user-images.githubusercontent.com/12802305/135496382-e90ed99e-1d92-4fe3-971f-b7ef729a915b.png)

- After change
![after-marginTop](https://user-images.githubusercontent.com/12802305/135496483-a52c50ec-b702-4bf5-baae-95098dcaaeb8.png)

**Comment by moontrip** [comment]
Just for a record, Sheena replied me via Slack, saying that it looks great after the change. So I will use that spacing

**Comment by aaronwlsong** [comment]
It looks that this issue exists on qa.website, but not on live site.

For example, in _GEMS1 Case Control study,_ the vars of "weight" and "age".

![image](https://user-images.githubusercontent.com/61077845/136262078-b591d301-1979-4ed0-9186-f3e289ed5830.png)

![image](https://user-images.githubusercontent.com/61077845/136262137-c2a86600-a56a-485b-afd3-b2a779c81b13.png)

**Comment by SheenaTomko** [comment]
Spacing looks great now
<img width="667" alt="Screen Shot 2021-10-07 at 8 37 40 AM" src="https://user-images.githubusercontent.com/54597319/136395425-5e911ad7-04fd-4981-a030-45f4391a6a60.png">
