### ISSUE TITLE
Visualizations: Change location of stratification variables

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#295]
Reviewed [mockups](https://docs.google.com/presentation/d/14WwD95etPuj6MS0wHQZ9_2X8CbEQrdhw/edit#slide=id.ge5d990b9bf_0_158) in EDA UX meeting on Aug 9th. Want to move or otherwise emphasize how stratification variables differ from X- and Y-axis variables. Mockups suggest moving stratification vars under the X- and Y-axis vars. Dan and others suggested an alternative of using subtle shading or other mechanisms to distinguish them to save vertical space. Dev team to come up with an idea and implement it

**Comment by danicahelb** [comment]
Suggest using labels of "Axis variables" for x & y pickers and "Stratification variables (optional)" for overlay & facet pickers

Also suggest moving stratification variable pickers in line vertically with axis pickers (to the right) to save space

**Comment by SheenaTomko** [comment]
looks good
