### ISSUE TITLE
Visualizations: Histograms & bar plots: update text next to button to choose to display proportions

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#300]
![image](https://user-images.githubusercontent.com/25450900/128943403-69ffc5ad-c3b5-4b0a-9e75-93f4dabb9d85.png)

text next to button should say "Proportion" not "Proportional"

**Comment by asizemore** [comment]
Closed with #352

**Comment by SAK22** [comment]
Looks good!
