### ISSUE TITLE
Apps: ranked abundance app vizs

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-eda#303]
this needs one box plot, with a new statsTable component and one scatter plot. think weve said no listVars here..

**Comment by d-callan** [comment]
just kidding. we do want listVars here.

**Comment by asizemore** [comment]
Updated plan:

Include the following two vizs for the ranked abundance app

- [ ] box plot. The computation will specify the x AND y axes. The more important of these two vizs. 
- [ ] scatterplot. The computation will specify the y axes AND the overlay var. Nice to have but not essential.

We also have details [here](https://docs.google.com/document/d/1K2aqAIt09GcD3eoPzKQIyQmxDvhxSwqEs8CdXv85nAI/edit#heading=h.d59lwfzd2ff2)

**Comment by asizemore** [comment]
Closing this issue, since we have #966 and #972 which are more specific.
