### ISSUE TITLE
Apps: alpha div app vizs

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-eda#304]
this needs a box and scatter plot.

**Comment by asizemore** [comment]
Yup! Box and scatter. 
Box
- alpha div on y axis always (will get this from the computation)

Scatter
- alpha div on y axis always (will get this from the computation)
- gradient colormap

**Comment by asizemore** [comment]
Updated plan:

Get working (not necessarily pretty)

- [ ] Boxplot (done by Dave!)
- [ ] Scatterplot (no gradient colormap)

**Comment by asizemore** [comment]
Closed with PR #946 .

Nothing for outreach to QA
