### ISSUE TITLE
Updates to histogram range selection (including minor bug fixes) for testing please

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#316]
Outreach don't need to be concerned with the technical details (various things were streamlined) but it would be great if you could test thoroughly.

The main bug that was fixed relates to date variables in subsetting:

> If you selected a single bar, at any resolution (month, year, day etc), in a date-variable histogram (subsetting), you would see that the size of the subset (in entity diagram) is not the same as the number of entities represented by the bar. This is fixed now.

Also fixed: day-resolution date range selection

But please test all aspects of histogram in subsetting if you can. (Visualisations shouldn't have been affected, because they don't have range selection.)

Here's the PR for reference
https://github.com/VEuPathDB/web-eda/pull/315

**Comment by bobular** [comment]
Already done so closing

**Comment by aaronwlsong** [comment]
This still seems to be an issue in GEMS1_case_control studies. 
It works for the first time, but when reset date period, it does not change according to the reset date, the bar still stays at where the last time date period was set.
![image](https://user-images.githubusercontent.com/61077845/130287954-2f963d4f-fb92-4d78-bf57-f1b24cd70bb6.png)
