### ISSUE TITLE
Visualizations: Some stratification vars produce a 400 response

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#318]
The service response indicates an issue with entities. See an example below.

![image](https://user-images.githubusercontent.com/365139/130122208-5dd41529-24ac-4611-8a6c-8f2bdd244c1c.png)

**Comment by dmfalke** [comment]
I'm not able to debug this right now. I am getting an unrelated 500 response. I think this is related to variables being identified as multiValued (I can't find a related issue, but I'm pretty sure there is one). I will wait to see if the resolution of that makes it possible for me to diagnose this issue.

**Comment by dmfalke** [comment]
The problem appears to be that the client is not restricting the entity lineage properly. In the case presented in the description of this issue, the client is allowing overlay variables from an entity that is outside the lineage of the X- and Y-axis variables.

**Comment by SheenaTomko** [comment]
looks good
