### ISSUE TITLE
General: Add "My analyses" link next to "New analysis" link 

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#322]
It is hard to know where your previous work is ("My analysis" under Workspace up top, but that's not intuitive). 
Please add a "Previous analyses" link next to "new analysis". this link should bring you to the "my analyses" table, but with the table results filtered to only show previous analyses of the current study

![image](https://user-images.githubusercontent.com/25450900/130330437-7254971a-b226-4e40-9308-b34716851500.png)

![image](https://user-images.githubusercontent.com/25450900/130330460-6c0defe1-007b-4dc9-bc9a-9c4ef5db7498.png)

**Comment by danicahelb** [comment]
Discussed in 8/23 EDA WG meeting

Name the link “My analyses”. Clicking this link will bring up a popup window with the "my analyses" table pre-filtered to only show results from the appropriate study. The study name should be in the search box, to make it obvious that this is not the full "My analyses" table.

Mockup of the link:
![image](https://user-images.githubusercontent.com/25450900/130561313-28e0c693-b1cb-4c69-b46b-85eafa488285.png)

Mockup of the filtered table:
![image](https://user-images.githubusercontent.com/25450900/130561367-e4dbfde3-20f2-4acb-94f5-7a72237cbed2.png)

**Comment by danicahelb** [comment]
is it confusing that the icon for "My analyses" is the same as the icon for the filtered results table?

**Comment by dmfalke** [comment]
Some implementation thoughts on this: the AllAnalyses page should take a query parameter in the url with the search term so that we can link to a pre-filtered table. When the user updates the text in the filter box, the query parameter should also update (using history.replace).

**Comment by chowington** [comment]
@dmfalke Is that relevant for this ticket? This button won't take you to the All Analyses page itself; it'll just bring up a modal with the AllAnalyses component inside. If you want it for this ticket I can work on it, but it does expand the cost and scope.

**Comment by dmfalke** [comment]
> Some implementation thoughts on this: the AllAnalyses page should take a query parameter in the url with the search term so that we can link to a pre-filtered table. When the user updates the text in the filter box, the query parameter should also update (using history.replace).

You can use the `useHistory` and `useLocation` hooks provided by the [`react-router-dom`](https://reactrouter.com/web/api/Hooks) package. `useLocation` can be used to access the current value of the query param, and `useHistory` can be used to update it. Given both of these hooks, you ought to be able to do this without needing to use the `useState` hook. Let me know if you have questions.

**Comment by SheenaTomko** [comment]
Looks good
