### ISSUE TITLE
Visualizations: when missing data button is active, color should change from grey to black

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#323]
When a user has selected a stratification variable that has some missing data, the missing data button should visually activate (change from grey (unactive) to black (active)

![image](https://user-images.githubusercontent.com/25450900/130329869-61f355fc-5b35-45fe-9746-5b252cec5612.png)

**Comment by steve-fischer-200** [comment]
this ticket is replaced by a more complete version: https://github.com/VEuPathDB/web-eda/issues/330

**Comment by nkittur-uga** [comment]
This ticket is redundant as this issue is still being worked on in https://github.com/VEuPathDB/web-eda/issues/330
