### ISSUE TITLE
Visualizations: Update text under visualization picker icons

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#325]
1. Update label for "RxC Contingency Table" to "RxC Contingency"
2. Update label for "2x2 Contingency Table" to "2x2 Contingency"
3. Make text below all icons larger

**Comment by danicahelb** [comment]
https://epvb.slack.com/archives/C0132PM1MT5/p1629987169001100

**Comment by danicahelb** [comment]
Can you also update the name of the line plot to "Time series"
Thank you!

**Comment by asizemore** [comment]
Viz names updated and font size increased (from 13px to 16px). @danicahelb is that about the right size for the text below the icons?
<img width="1768" alt="Screen Shot 2021-09-03 at 3 09 27 PM" src="https://user-images.githubusercontent.com/11710234/132056041-a676f0e5-1499-4160-8caa-e739c2f61b7e.png">

Note these viz names are used elsewhere, for example as subtitles when viewing the full screen version or as thumbnails. For these other places we may want to use a one-line version, for example "Mosaic plot, RxC table". See screenshots below
<img width="647" alt="Screen Shot 2021-09-03 at 2 39 13 PM" src="https://user-images.githubusercontent.com/11710234/132056325-2b00df8c-adea-46cb-9a1d-b34f2d849904.png">
<img width="381" alt="Screen Shot 2021-09-03 at 2 39 22 PM" src="https://user-images.githubusercontent.com/11710234/132056332-35457a88-cc4d-432f-b13e-94247c7f00c9.png">

**Comment by danicahelb** [comment]
I think 16px looks good, lets push it and see what it looks like on the site!

I agree that the full screen and thumbnail versions should be on one line. @asizemore do we need a new ticket for this?

**Comment by asizemore** [comment]
Great will do!

We don't need a new ticket for having these versions in one line, the code I have for this issue will solve both this as well.

**Comment by asizemore** [comment]
Closed with web-eda PR #379 and EdaDataService [PR #81](https://github.com/VEuPathDB/EdaDataService/pull/81)

**Comment by SAK22** [comment]
Text still has "Table" under the icons

**Comment by asizemore** [comment]
Just checked locally with all of the latest code and the names are correct. The name changes had to be made in EdaDataService, which had a build fail last time before the qa site was rebuilt, which I suspect is the reason on qa they are not showing up correctly. Should be fixed next time the qa site is built - I will keep checking in on this!

**Comment by SAK22** [comment]
Thank you @asizemore !

**Comment by asizemore** [comment]
@SAK22 please check again when you have a moment -- looks like all was updated!

**Comment by SheenaTomko** [comment]
Looks good!
