### ISSUE TITLE
Subsetting: long labels in the variable tree should be wrapped

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#326]
When a study has long labels and you click "expand all" to see the full list of variables, it expands the real estate dedicated to the variable tree and shrinks the space for the histogram/table view of the data. 

histogram / table view should not shrink. to fix this, wrap long labels onto >1 line

see this example from GEMS1:

![image](https://user-images.githubusercontent.com/25450900/130328918-afdd8ab5-683c-40fe-b70e-e3c8e6a1022d.png)

**Comment by sweverschulman** [comment]
spot checked at random the following studies for the above correct functionality: India ICEMR Cohort, SCORE Mozambique S. haematobium Cluster Randomized Trial, GEMS1 Case Control. All three studies showed correct functionality when the "expand all" was click with long names going across two lines and histogram/table view not changing in size.
