### ISSUE TITLE
Visualizations: Thumbnail Styling (icon changes)

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#327]
Can we add a plus sign to the icon for duplicating a plot? Or change it slightly in some other way? Even now I still continue to hit the wrong icon ~50% of the time when I'm trying to reopen a plot and instead accidentally duplicate it. 
I'd also like to change the maximize icon to match the minimize icon we use. I think on Windows it's just a simple rectangle outline with a dark header.  

Icons when looking at all plots (thumbnails)
<img width="86" alt="Screen Shot 2021-08-19 at 1 01 27 PM" src="https://user-images.githubusercontent.com/54597319/130120666-dd82a453-8297-47d4-b13a-ae4aacf58b35.png">

**Comment by SheenaTomko** [comment]
Phase 1 proposal:
1. Move the delete and duplicate icons to the left side of the icon, leave the maximize icon on the right side
2. Change the maximize icon to https://fontawesome.com/v5.15/icons/window-maximize?style=regular 

<img width="247" alt="Screen Shot 2021-09-15 at 2 28 34 PM" src="https://user-images.githubusercontent.com/54597319/133498821-58e29e07-a681-4a0f-9bd7-b2809311fdbb.png">

3. Change the minimize icon to https://fontawesome.com/v5.15/icons/window-maximize?style=regular

<img width="763" alt="Screen Shot 2021-09-15 at 2 29 02 PM" src="https://user-images.githubusercontent.com/54597319/133498887-80a9bbb3-409d-445e-af4a-c4bae5baede5.png">

**Comment by danicahelb** [comment]
Discussed in 9/27 EDA WG meeting

We have decided to move forward with making the entire picture (other than the icons) clickable to open the visualization in Phase 1. 

For a clean look, the icons to duplicate or delete the visualization will not be visible/accessible until the user mouses over the thumbnail. On mouseover, duplicate & delete icons appear on the upper right hand side of the thumbnail.

See updated mockups designated for Phase 1: https://docs.google.com/presentation/d/14FYZr4G2AiyE67yYRjBTSyuRkhDb8xFE5AUsi_eUDBs/edit#slide=id.gf1324e9192_0_5

**Comment by moontrip** [comment]
@danicahelb Thanks again for updating this ticket that was discussed at Slack 👍

**Comment by moontrip** [comment]
@danicahelb I have made a PR (https://github.com/VEuPathDB/web-eda/pull/485) to address thumbnail related stuffs, including your latest request above. FYI, here is my comment link with a screenshot: https://github.com/VEuPathDB/web-eda/pull/485#issuecomment-929411236

**Comment by danicahelb** [comment]
thumbnails are clickable & icons look great. thanks!
