### ISSUE TITLE
Visualizations: Long variable values for categorical axes may also need ellipsis mouseover

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#328]
PRISM2 bar plot
![image](https://user-images.githubusercontent.com/308639/130087734-30d9f9dd-7fd5-44af-bbf9-bf6f09f1a3d4.png)

**Comment by danicahelb** [comment]
I just checked today and now x-axis labels are straight up & down instead of on an angle. Angle is better. Elipses are still needed

![image](https://user-images.githubusercontent.com/25450900/132081542-38cd9f26-d85d-4f0a-b618-c13f4ef7669c.png)

**Comment by aaronwlsong** [comment]
It looks good now. Closing ticket. 
![image](https://user-images.githubusercontent.com/61077845/134351340-c5b2c615-367a-4925-84a1-c004a798be50.png)

**Comment by moontrip** [comment]
@aaronwlsong Thank you for your tests 👍
