### ISSUE TITLE
Change icon for searching the data

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#337]
The current filled line graph icon used to enter the EDA is not ideal. Recommend switching to something like a histogram or a magnifying glass. Another potential idea would be to reuse part of our logo, with the magnifying glass looking at people, but use a black and white version of it.

**Comment by danicahelb** [comment]
![image](https://user-images.githubusercontent.com/25450900/131729641-a5018f75-2481-4981-bdb4-bafef4bc0bc0.png)

**Comment by danicahelb** [comment]
![image](https://user-images.githubusercontent.com/25450900/131730165-ee9521c9-b576-4ec2-a9df-e7e9aba3188f.png)

**Comment by asizemore** [comment]
@danicahelb and @SheenaTomko I tried both of the above options (see screenshots below of the dropdown). My concern is that while the icon on the card is quite large, the same icon in the dropdown menu is pretty small. While the globe is really awesome, i'm concerned that it's too complex for such a small icon. The magnifying glass with the bar plot inside is a little simpler which helps, in my opinion. What do you both think? 

Additionally, if we go the route of using something like the magnifying glass with plot that can be generalizable, it would be great to get @dpbisme 's opinion, too!

Finally, I do like the bar plot but just noting that we could use any plot/analysis icon ([examples](https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=chart)) here inside the magnifying glass. Not trying to open a can of worms just noting in case we hadn't talked about it yet!
<img width="1655" alt="Screen Shot 2021-09-08 at 3 21 25 PM" src="https://user-images.githubusercontent.com/11710234/132573949-015e1dd1-44b9-4716-9f4c-67bdf9b07016.png">
<img width="1614" alt="Screen Shot 2021-09-08 at 3 48 09 PM" src="https://user-images.githubusercontent.com/11710234/132575561-44a614cb-ddef-492e-a205-56bea26c251b.png">

**Comment by SheenaTomko** [comment]
I think you're right that the globe is too complex. I think if we go with data in the magnifying glass, it should be a bar chart. Another option would be doing the magnifying glass with the people in it, but no globe. Although if we do that, we should consider whether it makes it seem like we're letting users search for individuals
![magnifying_icon](https://user-images.githubusercontent.com/54597319/132578443-b4de14f7-9c34-4fc6-95b3-c017085a5fd5.png)

**Comment by asizemore** [comment]
> I think you're right that the globe is too complex. I think if we go with data in the magnifying glass, it should be a bar chart. Another option would be doing the magnifying glass with the people in it, but no globe. Although if we do that, we should consider whether it makes it seem like we're letting users search for individuals

I like the suggestion -- it is easier to recognize the people inside the magnifying glass than a plot sometimes. I also share your concern about it looking like a search for people. Remind me again the end goal about what we want this icon to display? In a clinepi meeting you all had a really helpful description that I'm forgetting. I recall it's important for the user to "look through" or "search" the data, hence the magnifying glass, but also they can analyze the data and make plots if they follow the link as well. Am I missing anything?

**Comment by SheenaTomko** [comment]
Hmm don't remember what we said exactly. EDA stands for exploratory data analysis, and "explore data" is a term we use a lot.

**Comment by asizemore** [comment]
Below we have the magnifying glass with the people, compared to the globe, the magnifying glass with bar chart, and a few others. Anything jumping out as both good at indicating "exploratory data analysis" and easy to see at this size? Note, each example is duplicated to give a feel for how it will look next to itself. All icons shown are the same height.
<img width="1503" alt="Screen Shot 2021-09-09 at 1 10 07 PM" src="https://user-images.githubusercontent.com/11710234/132731404-1d09fa11-ec9b-4304-a9e2-8721444aa4c7.png">

**Comment by asizemore** [comment]
Based on today's meeting, I'm moving forward with the icon below (also see slack discussion). Note that the PR to address this issue will replace the icon only, not make any of the other styling changes discussed.

**Comment by danicahelb** [comment]
looks great, thanks Ann!

**Comment by asizemore** [comment]
Closed with [EbrcWebsiteCommon PR#65](https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/65)

**Comment by SheenaTomko** [comment]
Looks great. Marking as complete
