### ISSUE TITLE
Visualizations: in legend, grey out text for values of overlay variables that are not in the subset

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#339]
Ex: I subsetted GEMS1 to just include participants from Bangladesh & India. Then did a scatter of weight vs height, and overlayed country. I see that colors have been assigned to all 7 countries, even though only 2 countries are in my subset.

Preferred behavior would be to have the text for the countries that are not in the subset in light grey text instead of black. 

![image](https://user-images.githubusercontent.com/25450900/129837405-a5b870aa-22b2-46e9-bc2e-9c70fd7b9b03.png)

**Comment by bobular** [comment]
Or add "(no data)" or something (if worried about looking the same as clicked-on Plotly legend items)

**Comment by danicahelb** [comment]
clarification: for phase 1 there will be some ambiguity in grey legend text (values with no data in the subset & de-selected values would not be distinguishable). we will fix this in phase 2 (see issue #2 linked above)

**Comment by dmfalke** [comment]
@danicahelb I'm changing the cost of this from "low" to "medium". Much of the work for this will likely be wasted once we have a custom legend component. In light of that, do you want to keep this in phase 1?

**Comment by bobular** [comment]
Greying out might be overkill for a temporary feature.

Is appending "(no data)" a lower-cost solution?

Or putting the legend label in parentheses

**Comment by dmfalke** [comment]
The thing that makes this medium cost is making the legend aware of which traces are "empty". Plotly doesn't appear to have a generic way to do this, so we would have to add a new prop for this and update all visualizations to indicate which traces are empty.

**Comment by danicahelb** [comment]
@dmfalke indicated that this ticket is a higher cost than expected. Given that, and that the work will likely be moot when we have a custom legend, we have decided to move this issue to Phase 2

**Comment by nkittur-uga** [comment]
Right now it looks like we have two legends. The second legend appears whenever a stratification var is applied, regardless of whether data have been subsetted for the stratification var or not. 
<img width="1006" alt="Screen Shot 2021-11-12 at 4 38 06 PM" src="https://user-images.githubusercontent.com/67710160/141538311-6224f535-9206-45e7-a39d-4aa19129e48a.png">

**Comment by moontrip** [comment]
Hi @nkittur-uga Thank you for your tests and comments! I am sorry that I should have left a comment in this regard. For clarification, yes the custom legend is not fully ready yet for all Vizs as it ties with faceted plot works. We will hide the Plotly's legend once we will finalize all custom legend, which is close to be done sooner or later - my PRs are currently under review, e.g., #698

The example you tested is for scatter plot, which is the last item I did (under review) so it does not have markers in the custom legend yet. You can wait for upcoming deployment or you can test histogram and barplot Vizs as they have markers, though we did not hide Plotly's legend in there either. In a sense you as a reviewer has a chance to see whether the custom legend reflects legend items, markers, colors, etc correctly as compared to the Plotly's legends. Hiding Plotly's legend is quite easy task to do.

Hope this would be helpful for you.

**Comment by moontrip** [comment]
@nkittur-uga Since all the new custom legends are now at the qa site (didn't test but I think so), can you please revisit this ticket and see if it can be moved to Complete rather than Failed QA ? Thanks!

**Comment by nkittur-uga** [comment]
Tested and it works as expected! Moving to complete.

**Comment by moontrip** [comment]
@nkittur-uga thank you for your quick tests and reviews! 👍
