### ISSUE TITLE
2x2 axis labels sometimes collide

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/web-eda#348]
this is in the PRISM2 ICEMR Cohort study

![image](https://user-images.githubusercontent.com/43149795/130785020-b5ce00bf-8eaa-49ea-b950-b0ea7dd696a8.png)

**Comment by danicahelb** [comment]
This seems to have been fixed, I'm closing the ticket

![image](https://user-images.githubusercontent.com/25450900/132081179-525d6236-54b2-4be2-87e0-f1a63adfb331.png)
