### ISSUE TITLE
When featured variables are absent, a "0" appears in their place

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/web-eda#350]
When featured variables are not present (example in screenshot shows that none of the featured variables met the variable selection criteria in that particular viz app), a "0" appears in place of the featured variables. This should be removed from the UI.

<img width="484" alt="Screen Shot 2021-08-23 at 12 00 02 PM" src="https://user-images.githubusercontent.com/67710160/130835540-366549c5-606f-4947-b621-bffb7ee837bc.png">

**Comment by SheenaTomko** [comment]
This is fixed on the qa site, closing this ticket
