### ISSUE TITLE
Subsetting: multifilter chip mouseover legibility improvements

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#359]
As discussed in 8/30/21 EDA WG:

Mouseover for multifilter chip: only one filter (variable) per line for legibility improvement. If multiple values for a filter are selected, these can all be on a single line separated by a comma

**Comment by asizemore** [comment]
@danicahelb @SheenaTomko mind if I close this issue?

**Comment by danicahelb** [comment]
looks good, closing this ticket.
