### ISSUE TITLE
Visualizations: Remove "Facet (placeholder) from RxC & 2x2

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#360]
Please remove the "Facet (placeholder)" button from RxC and 2x2 

![image](https://user-images.githubusercontent.com/25450900/131528982-7138f4f7-516e-416b-9056-3caeedeb6d77.png)

**Comment by bobular** [comment]
Aha - thanks Connor

**Comment by SheenaTomko** [comment]
Looks good
