### ISSUE TITLE
Visualizations: cannot select "Country" as x-axis

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#361]
For studies that have been loaded with the latest .owl (where Country is being placed under the Community entity), I get an error message when i try to select the Country variable. This happened with bar plots, RxC, and boxplots when country was selected on the X axis for both GEMS1A Case Control and India ICEMR Behavior CX 

![image](https://user-images.githubusercontent.com/25450900/131527934-2852f1ea-71d6-4e6f-8502-d1eae9c4b731.png)

![image](https://user-images.githubusercontent.com/25450900/131528279-27d8fd93-1801-4f11-aa6b-9cfd1f8b423e.png)

![image](https://user-images.githubusercontent.com/25450900/131528394-b1a6da3c-58e4-460b-9209-16a355b34ab2.png)

**Comment by moontrip** [comment]
well I think this is non-issue as this works just fine without error. So, please close this.

**Comment by danicahelb** [comment]
@moontrip I tried again with GEMS1A data and got this:

![image](https://user-images.githubusercontent.com/25450900/132081275-4bae707d-ac40-4843-a787-c5bbc0be5289.png)

![image](https://user-images.githubusercontent.com/25450900/132081296-0e66792c-460e-44be-875d-d3f555daa6bd.png)

**Comment by moontrip** [comment]
> @moontrip I tried again with GEMS1A data and got this:
> 
> ![image](https://user-images.githubusercontent.com/25450900/132081275-4bae707d-ac40-4843-a787-c5bbc0be5289.png)
> 
> ![image](https://user-images.githubusercontent.com/25450900/132081296-0e66792c-460e-44be-875d-d3f555daa6bd.png)

@danicahelb Thank you for your re-checks! 👍 I have just checked the qa site, and they worked just fine. Thus I guess backend was updated (500 internal server error is related to backend): e.g., updating data, fixing issues, etc.

**Comment by bobular** [comment]
Seems OK for me 

![image](https://user-images.githubusercontent.com/308639/133089470-43984c63-5d6a-4d74-8251-ded5899783a8.png)

(using dfalke-b backend at the moment)

**Comment by SheenaTomko** [comment]
Confirmed that this looks fine now in GEMS1A and in India Behavior. Closing this and moving to Complete
<img width="1139" alt="Screen Shot 2021-09-24 at 3 13 26 PM" src="https://user-images.githubusercontent.com/54597319/134734502-f8da5ae1-5033-465c-940a-b92a6ef921b0.png">
