### ISSUE TITLE
General: stronger feedback when creating a new analysis

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-eda#364]
maybe im crazy. but i feel like idk how many new analyses i just created.. i had a few vizs i made, but never named the analysis. then from the subset tab i clicked new analysis and didnt think anything happened. so i clicked a few more times, and then decided to give up and go back to the viz tab. and my vizs werent there.

**Comment by danicahelb** [comment]
I think having a count of unnamed analyses like **My Analyses (3)** could definitely help

But also, if you are working in an unnamed analysis and you click "new analysis", the name of the current analysis should now be "Unnamed Analysis (2)". 

We would only want the analyses being saved if work had been done (either the user subsetted the data or created at least 1 visualization). so if danielle made a few vizs in "Unnamed analysis" and then clicked "+ new analysis" ten times without doing any work on an analysis, she should now be in "Unnamed analysis (2)"

**Comment by bobular** [comment]
If the main tabs said

`View study details | Browse and subset (N) | Visualise (M)`

where N was the number of filters (mouseover confirms what these are counts of) and M was the number of visualisations, and when either was zero, the `(0)` is not shown at all

Then there would be more visual feedback when clicking "+New analysis"

The problem with **My Analyses (3)** is that analyses are never saved when the user hasn't made any changes.  So clicking repeatedly on "+New analysis" isn't going to make more analyses.

Maybe explore solutions after https://github.com/VEuPathDB/web-eda/issues/366 has been merged/tested?

**Comment by danicahelb** [comment]
Discussed in the 9/13/2021 EDA WG meeting.

There are reasons that it is complicated to keep track & add numbers to the end of “Unnamed analysis” (for example, analyses are never saved when the user hasn't made any changes) → we should steer clear of adding these numbers.

Instead, when a user is working on an unnamed analysis and clicks on “+ New analysis”, they should see a popup asking if they would like to rename (edit) their analysis before creating a new one

**Comment by SheenaTomko** [comment]
This worked as Danica described
