### ISSUE TITLE
General: work on an analysis is not being saved 

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#366]
My work on an analysis is being saved when i close out of qa.clinepidb.org, but it is not being saved as i move through the website using either the  "Search a study" drop-down or navigating to the homepage and clicking on the explore icon on the card. Something also seems weird with previous analyses, so for this ticket I first deleted all of my previous analyses.

I now have no analyses in the "my analyses" table, and i open a GEMS1 analysis from the study card. I apply 2 filters (Country & Case or Control Participant) to select 1394 Bangladesh cases. the analysis is labeled "unnamed analysis"

I click on clinepidb (top left) to get back to the homepage. I next click immediately back on the explore icon for GEMS1. Now I have 3859 participants and the filter for Cases has been removed. 

The same thing happens when i am in my unnamed GEMS1 analysis and have my selected population of 1394 Bangladesh cases and click on GEMS1 analysis icon in the search a study dropdown.

**Comment by dmfalke** [comment]
I’m able to reproduce this, so I can likely figure out what’s going on.
Thanks for the detailed report!

**Comment by aaronwlsong** [comment]
Looks good, closing ticket.
------------------------------
Replicated this issue in the same study and tested in other studies, they all look good now.
