### ISSUE TITLE
Visualizations: GEMS1 cannot select "child waste disposal" as overlay variable

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#367]
I thought there was a ticket for this already, but i've searched for 45min and can't find it. sorry if it is a duplicate.

I cannot select "Child waste disposal" as an overlay variable in the GEMS study when I have main variable(s) selected.

If i don't have any main variables selected, I can select "Child waste disposal" as my overlay variable. But then there are ZERO compatible variables for x &/or y selections

**Comment by d-callan** [comment]
i dont think this is a bug. i think that var is from household repeated measures? if so, then to stratify by it would duplicate values across your x and y axes, which we said we didnt want to automatically do. my memory is that there was discussion to allow the user to very explicitly do this type of thing in a future phase, either as a derived var or some dedicated feature.

**Comment by danicahelb** [comment]
seems to be working now, closing this ticket

![image](https://user-images.githubusercontent.com/25450900/134993820-5fff21c8-c16f-44a0-afe0-5d47d7ed68bf.png)
