### ISSUE TITLE
Subsetting: SCORE study Household->longitude variable should not show a histogram filter

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#37]
I know this is because it's a special kind of number variable.  Just flagging this up so we don't forget to handle it somehow.

**Comment by steve-fischer-200** [comment]
What _should_ we show?

**Comment by danicahelb** [comment]
@nkittur-uga @SheenaTomko I think we should not display latitudes & longitudes as terms in the variable tree, but these should be available in the download files. Do we need to obfuscate the lat / long terms for the SCORE studies?

**Comment by SheenaTomko** [comment]
I think the goal is to have them eventually display in a map that users can subset on. For now, Nupur and I agree with Danica that these should not display in the tree but should be available in the download file. We do not need to obfuscate this as they are village coordinates and belong to a controlled study. We also do not yet have a plan in place for how to obfuscate lat/long terms. That requires a lot more thought and planning.

**Comment by bobular** [comment]
It's OK if this does show up as a histogram, IMO.  There needs to be some minor client work to make this happen however.

**Comment by SheenaTomko** [comment]
@bobular, we are now hiding all lat/long (and all geohash) variables from the variableTree. Can I close this issue?

**Comment by bobular** [comment]
Yes, I'll close it.
