### ISSUE TITLE
Subsetting: SCORE study variables geohash_5 to geohash_7 and village name give empty category barchart tables

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#38]
The back end seems to be returning data fine.  It returns 252 categories for geohash_5.  The problem may be with the front end (haven't investigated further).

![image](https://user-images.githubusercontent.com/308639/113741768-e2248780-96f9-11eb-8202-ebf63bd1d409.png)

Edit to add: so do text-categorical variables with 443 values, e.g. Household->Geographic location->Village
Back end response looks OK to me.

**Comment by bobular** [comment]
I have been investigating further.

It's difficult to trace the dataflow through JSX class components but so far I have found that

MembershipField.activeFieldState.summary.valueCounts HAS what looks like suitable data for the rows of the table.

Could it be something to do with pagination?

**Comment by dmfalke** [comment]
The issue with this is related to the pagination feature of the table filter. Pagination is "turned on" based on the number of values. The EDA code is not passing in the `rowsPerPage` or `onMemberChangeRowsPerPage` props to the `wdk-client` component, which causes the `rowsPerPage` to be interpreted at `0`, thus no rows are shown.
