### ISSUE TITLE
For multifilters, have the provider label space show the variable labels

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#380]
At the moment, multifilters say "No Provider Label available" above the data table. Instead, we'd like this to show the names of all the variables that are displayed as part of the multifilter. This would be an improvement beyond the live site (which just removes that line altogether), so we can move this to a later phase if warranted. 

<img width="614" alt="Screen Shot 2021-09-03 at 3 07 04 PM" src="https://user-images.githubusercontent.com/54597319/132060971-37ac3e93-4c0f-4af4-a819-0c31d17997e6.png">

**Comment by dmfalke** [comment]
@SheenaTomko do you have a preference for how these are formatted? There doesn't seem to be an obvious choice for this.

These are the options I can think of, each with drawbacks:
1. In the same area, one line per variable. This can get tall pretty quickly. We could make this collapsible.
2. In the same area, one line for all variables (with wrapping). This can be difficult to read.
3. In the table near the variable name. This is a departure from how we do it elsewhere.

If you have a preference, or any other ideas, let me know. Thanks!

**Comment by SheenaTomko** [comment]
I think I like 2 best for now, in the same are with wrapping. If you can order the Provider labels using the same order as the variables in the multifilter, that would be ideal. 

We can always reassess this later, but for now I want this to have minimal impact on the page

**Comment by SheenaTomko** [comment]
This works and looks good for small multifilters like this one from the India ICEMR cohort study:
<img width="1097" alt="Screen Shot 2021-09-30 at 4 55 06 PM" src="https://user-images.githubusercontent.com/54597319/135535336-cdd94b2d-f969-4ddb-99af-e74bcbd8f007.png">

However, for really long multifilters, like Bacteria in stool in GEMS, the list gets ridiculously long
<img width="856" alt="Screen Shot 2021-09-30 at 9 54 42 AM" src="https://user-images.githubusercontent.com/54597319/135535222-8c245e01-d5f5-46c4-9046-ed346fa7989a.png">

Potential solutions: 
1) Undo this for now 
2) Remove the labels and just write out the original variable names in the order they're represented in the multifilter
3) Leave as is
4) Something else?

@danicahelb thoughts?

**Comment by dmfalke** [comment]
We can put a Read more button. It would only show up if it’s long.

**Comment by SheenaTomko** [comment]
I like that idea

**Comment by danicahelb** [comment]
i like the idea too @dmfalke. so, would we show the first 3? (2? or 5?) and then follow with a read more or expand button? Or just replace all with the button?

**Comment by moontrip** [comment]
Actually, I noticed the lengthy label for multifilter case when I work for this ticket, [Subsetting: Update how original variable names appear](https://github.com/VEuPathDB/web-eda/issues/290) made by @SheenaTomko 

I also like @dmfalke's idea as it is common to show a link for long texts/sentences like `Read more` or `Show more` link (usually text link, not button style). Certainly @danicahelb's preference would also work to have show all/hide all link/button with line-by-line variable.

If you want this, then I can also work for this as a part of the ticket [Subsetting: Update how original variable names appear](https://github.com/VEuPathDB/web-eda/issues/290)

**Comment by SheenaTomko** [comment]
@moontrip , could we do a "Show more" text link if the text goes >2 lines? Or if you prefer to do it based on number of characters or some other metric let me know and we can figure that out. I'm ok with you working on it as part of that other ticket. If @danicahelb and @dmfalke agree we can then close this one

**Comment by dmfalke** [comment]
We have a [component](https://github.com/VEuPathDB/WDKClient/blob/master/Client/src/Views/Strategy/OverflowingTextCell.tsx) that handles this logic. It's being used in the public analyses table:

![image](https://user-images.githubusercontent.com/365139/135672577-234d7347-dda1-490e-9198-054f8c9d6b8a.png)

**Comment by moontrip** [comment]
@SheenaTomko well I think it is quite difficult to find > 2 lines as the width of the display area is flexible, i.e., the number of lines changes per user's display resolution, browser's zoom level etc. The number of characters is also quite tricky as variables are shown per variable. So, viable options are: a) hide/show all variables with button/link - from [@danicahelb's comment earlier](https://github.com/VEuPathDB/web-eda/issues/380#issuecomment-931830097), this is her preference by putting line-by-line variable ?; b) show limited number of variables (like 3 variables) at first and add Read/Show more link to show/hide the leftovers. It would be great if you let me know what option @SheenaTomko and @danicahelb prefer :)

@dmfalke Thank you for your information. I didn't look at the component but it looks like it is based on the number of characters ? In my opinion, the number of characters is not a good option for this case: a) we use map function to display variables so it is hard to find the number of characters (but doable by making a variable of a full set of texts); b) perhaps this is just my opinion but limiting variables and their names in a certain number of characters may not be better than limiting the number of variables.

**Comment by dmfalke** [comment]
It's not based on the number of characters, but you do need to provide it
with a string. I think you could easily convert the currently list of div
elements to a string joined by a space character.

**Comment by SheenaTomko** [comment]
This looks great!
