### ISSUE TITLE
Pop-up box when truncating axes on histograms in the subsetting tab

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#382]
Recommend removing "Information" and replacing instead with a warning icon.

<img width="528" alt="Screen Shot 2021-09-03 at 1 17 42 PM" src="https://user-images.githubusercontent.com/54597319/132049953-cac03f9a-ae3a-44b6-a2fd-d4f8543242cc.png">

**Comment by SheenaTomko** [comment]
Text for X axis truncation vs Y axis truncation is different. Change Y to be "Data has been truncated by range selection, as indicated by the light gray shading" 
<img width="845" alt="Screen Shot 2021-09-14 at 8 23 32 AM" src="https://user-images.githubusercontent.com/54597319/133265557-3304388c-5c6c-47b2-90a2-451dd8274665.png">

Everything else looks good

**Comment by moontrip** [comment]
@SheenaTomko Thank you for your review. I can change it to be your suggestion 👍

**Comment by bobular** [comment]
That was intentional, Sheena.

The client doesn't know if the data has been truncated in the y-axis
direction without making a pass through the data and adding up counts (and
summing them for overlays).

Changing both to "may" would be fine though.

**Comment by SheenaTomko** [comment]
Makes sense. So @moontrip, instead of what I requested above, please change the X-axis warning to "Data may have been truncated by range selection, as indicated by the light gray shading"

**Comment by moontrip** [comment]
@SheenaTomko @bobular Thank you for your feedbacks. I have done for the change at the following PR (merged) https://github.com/VEuPathDB/web-eda/pull/438

**Comment by SheenaTomko** [comment]
Looks good
