### ISSUE TITLE
Styling issue in entity diagram

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/web-eda#388]
When "Household repeated measures" is clicked in entity digram, the text looks crowded and ugly. 

This will also be an issue for "Participant repeated measures". (Repeated measures will be renamed Participant repeated measures in the near future.)

<img width="1218" alt="Screen Shot 2021-09-07 at 9 34 14 AM" src="https://user-images.githubusercontent.com/67710160/132364241-73e976c8-c5ce-449e-8835-3f77f0cb535f.png">

**Comment by chowington** [comment]
Forgot to update web-eda...

**Comment by SheenaTomko** [comment]
This is fixed
