### ISSUE TITLE
General: implement plural versions of entities

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#393]
Notes from the Aug 16 EDA WG meeting:

Plurals are fully implemented in data loading in dataset specific tables (in same place as the ordinary labels)
Now on UI team’s plate, message Jay with questions

**Comment by SheenaTomko** [comment]
Closing this because it duplicates https://github.com/VEuPathDB/web-eda/issues/311 which is ready to be deployed. Please reopen if I misunderstood
