### ISSUE TITLE
p values need to be fixed

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/web-eda#410]
For p values on plots/tables, we want to use <0.0001, <0.001, and <.01 and only if it’s above .01 then write it out. 

The way it currently appears is shown below. 
<img width="388" alt="Screen Shot 2021-08-26 at 4 30 17 PM" src="https://user-images.githubusercontent.com/67710160/131035509-7d795e8e-8240-4257-babb-0bf9c6b05054.png">

**Comment by bobular** [comment]
Implemented for 2x2 and RxC contingency tables.  Are there any other places?

**Comment by nkittur-uga** [comment]
No those are the only places currently.

**Comment by nkittur-uga** [comment]
Tested in 2 x 2 and r x c and it is fixed. Passes QA.
