### ISSUE TITLE
General: change text and icon for "Table view" to "Study summaries table"

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#413]
In https://github.com/VEuPathDB/EdaNewIssues/issues/116 we requested that the `All studies` table link in the Search a study dropdown be renamed to `Study summaries table` 

In https://github.com/VEuPathDB/EdaNewIssues/issues/117 we requested that a new icon be created for links to the `Study summaries table`

In this ticket, we would like the text and icon for the `Table view` link near the homepage cards to be updated to match the text and icon in the Study dropdown. Please update text to "Study summaries table" and use the new link that Ann is creating

![image](https://user-images.githubusercontent.com/25450900/132931959-4c9f78ba-ff72-4515-9f4f-8aaa4160b757.png)

**Comment by dmfalke** [comment]
closed by
* https://github.com/VEuPathDB/EbrcWebsiteCommon/commit/3f8cbf134d4d1c21199f3c7460136018ebbe19ba
* https://github.com/VEuPathDB/ClinEpiWebsite/commit/b69a5ad3fc4aae298a6d1c58f8c77a717a818c60
* https://github.com/VEuPathDB/MicrobiomeWebsite/commit/70b85514b620d6f08062ecd9e0e112567691e546
