### ISSUE TITLE
Update links in all studies table

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#414]
At the moment, the links in the Study column go to separate study pages rather than the ones in the EDA and the links in the Searches column go to the WDK system rather than the EDA. Both need to be updated. 

<img width="1135" alt="Screen Shot 2021-09-10 at 4 24 52 PM" src="https://user-images.githubusercontent.com/54597319/132919288-19f288c1-4a4b-4c53-b295-b877cc04120c.png">

**Comment by danicahelb** [comment]
Additionally:
1. Rename "searches" column to "Explore & analyze" 
2. reorder the columns:
- 1st column: "Study"
- 2nd column: "Explore & analyze"

**Comment by dmfalke** [comment]
These issues were fixed by https://github.com/VEuPathDB/EbrcModelCommon/pull/8 and https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/69

**Comment by sweverschulman** [comment]
The following studies when spot checked confirmed correct functionality: GAMIN RCT, PRISM 2 ICMR Border Cohort and SCORE Rwanda. The columns names have been updated and ordered correctly. 

<img width="279" alt="Screen Shot 2021-09-24 at 12 55 24 PM" src="https://user-images.githubusercontent.com/62298921/134712692-5f5b10ab-c61d-45d3-82af-2b93dffd1fbf.png">
