### ISSUE TITLE
General: “Search a study” drop down changes

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#416]
Discussed in 9/10/2021 UX meeting. we decided that primary users of the dropdown will be power users who want to navigate directly to studies they are already familiar with, while naive users will primarily use study cards that have more information. 

We want to make the following changes: [mockups](https://docs.google.com/presentation/d/1eHQc8cj1ehWfbaR0s4ZGiph1QI6Mpds5Bmm3vcKAvro/edit#slide=id.p)

1. Change the dropdown label from “Search a study” to “Studies”
2. There will only be one clickable link per row (study). This link will take the user to their latest work in the browse/subset tab. For styling, add Ann's new “explore” icon to the left of the study name
3. “All studies” above the search bar looks like a title, make it look more like a link. Change “All studies” to “Study summaries table” and add its own icon to the left (Ann is making a new icon for this)

**Comment by SheenaTomko** [comment]
Note that https://github.com/VEuPathDB/EdaNewIssues/issues/137 is requesting that an icon is always shown for a study that's been loaded in the EDA and isn't "pre-release". May be relevant to this ticket too

**Comment by SAK22** [comment]
Looks good
