### ISSUE TITLE
Links for Download and New analysis at top of page are different font sizes

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#422]
If you enter the EDA for a given study, say GEMS1, the links to the right of the study name have different font sizes. 

<img width="262" alt="Screen Shot 2021-09-10 at 9 52 57 AM" src="https://user-images.githubusercontent.com/54597319/132874026-edbf8238-4a39-4a4e-a480-5046d016137f.png">

**Comment by asizemore** [comment]
Should be addressed with web-eda PR #537

**Comment by danicahelb** [comment]
closing ticket
