### ISSUE TITLE
Issues in mouseover info for starred variables filter

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/web-eda#424]
1. The mouseover text for the starred variable filter (grey below) often persists long after the cursor is moved away from the starred variable toggle switch.

2. Please remove the period at the end of this text. It should simply read, "To use this filter, star at least one variable below"

<img width="1164" alt="Screen Shot 2021-09-09 at 2 27 14 PM" src="https://user-images.githubusercontent.com/67710160/132746633-0e8f9f58-3cb0-4db9-af44-05b01ea902f0.png">

**Comment by asizemore** [comment]
Closed with #520
