### ISSUE TITLE
Visualizations: viz-level tool tips for greyed out variables 

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#429]
Currently we have a very generic tool tip that applies to all greyed out variables in all viz tools 
`This variable cannot be used with this plot and other variable selections`

More specificity in messaging for why certain variables cannot be used would be better; instead of a generic message for ALL greyed out variables regardless of viz tool, have messages specific to each viz tool

In phase 2 or later, we will attempt a cascade whereby we translate the backend logic into human readable sentences

@d-callan please propose API & write up messaging for 1-2 viz tools as a test

**Comment by nkittur-uga** [comment]
QAed, checked tool tips messages in scatter plot, box plot, 2x 2, and specific messages are popping up. QA is complete.
