### ISSUE TITLE
Updates to My analyses table

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#452]
Change the table so the first column is the study and the second column is the analysis. A similar request is being made for the public analyses table in a separate ticket. 

<img width="1164" alt="Screen Shot 2021-09-17 at 2 17 40 PM" src="https://user-images.githubusercontent.com/54597319/133842642-79389a5f-9c48-4864-899b-2538287d207e.png">

**Comment by danicahelb** [comment]
Additional changes were discussed in 10/1 UX meeting:

1. Allow the author to be able to edit the analysis name directly within the table (implement pencil icon)
2. Remove links to studies in the “Study” column
3. 1st column = Study, 2nd column = Analysis
4. Make all columns searchable (currently, just “Study” and “Analysis” columns are searchable)
5. Move the pins into their own column (don’t have the pin in the same column as the analysis name)

**Comment by danicahelb** [comment]
@jtlong3rd would it make sense to work on this ticket simultaneously to https://github.com/VEuPathDB/web-eda/issues/448?

**Comment by jtlong3rd** [comment]
> @jtlong3rd would it make sense to work on this ticket simultaneously to #448?

@danicahelb Yes, I'll take care of this as part of updating #448!
