### ISSUE TITLE
Visualizations: update boxplot behavior when using number / date variables for x-axis

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#456]
Boxplots variable constraints for the x-axis have been updated to allow us to use numeric or date variables with less than 10 unique values.

When using a number or date variable as a "categorical" we don't want the x-axis to appear as a continuous number line and binning should not be done automatically (or even allowed). Each unique value should appear with its own label & box/whisker.

The downside of that approach is that if there are clusters of values, like say 1, 1.3, 2, and 8, 8.2 then all 5 values will appear evenly spaced apart. But this is preferable to the number line.

See https://github.com/VEuPathDB/EdaNewIssues/issues/132, where I reported strange boxplot behavior, it may be related to using a numeric variable in the boxplot

**Comment by chowington** [comment]
Maybe this one from the other ticket is one:

![image](https://user-images.githubusercontent.com/12377649/137013727-40a11d42-6405-46e1-bde3-ad55c49dd1cb.png)

**Comment by bobular** [comment]
That's right @chowington - all will hopefully be resolved when we merge #508

**Comment by chowington** [comment]
@danicahelb Do you agree, and are you good with closing this ticket?

**Comment by danicahelb** [comment]
@chowington looks great, closing!

![image](https://user-images.githubusercontent.com/25450900/137368994-2041dd09-bafa-4094-a392-f62f4ab442f1.png)
