### ISSUE TITLE
Visualizations: "No data" legend styling

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#464]
Discussed in 9/13/2021 EDA WG meeting

Problem: If the window is small or a user is reading quickly “No data” could be confused with values of “No”

Decision: make “No data” visually different (change font to italics) and show this on the bottom, below all other values in the legend 

This should not change where in the graph the “No data” overlay is appearing 

- In histograms, no data should be on the top of the other bars
- In boxplots, no data should be after boxes for other values

BM noted that we are making our own VEuPathDB version of legends in Phase 2, so we need to be careful to not spend a lot of time reworking the plotly legend now

@bobular  will research if there is an easy way to implement legend order in plotly (rank) and text format (italics)

**Comment by bobular** [comment]
Reassigned as medium cost.

The `legendrank` plotly parameter seems to be new, and not available in the version of plotly.js we are using - nor in the latest version available with `yarn add plotly.js`.

Nor does it seem to work in the latest CDN version of plotly 
https://codepen.io/bobular/pen/BaZdgmY
(you can try to switch the order by adding `legendrank: number` to `trace1` and `trace2` and it makes no difference.

Given that I can't test it - I'm not even sure if this parameter switches the legend order independently of the bar order (which is what we need).

I suggest we mark this ticket as "won't do" and instead we engineer this into the standalone legend for Phase 2.

**Comment by bobular** [comment]
A "roll our own" legend task should probably precede this one.

**Comment by nkittur-uga** [comment]
“No data” appears in italics and and below all other values in the legend. Passes QA.
