### ISSUE TITLE
Visualizations: thumbnail out-of-date styling & refresh when subset has been updated

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#465]
Discussed in 9/13/2021 EDA WG meeting

Problem: When subsets have been updated, Visualization thumbnails become out of date. we are using a cached version of visualization thumbnails and it is not scalable to re-draw all thumbnail plots every time the subset gets updated

Solution: Visualizations that are out of date should still be legible, but a transparent grey shadow will be placed over the thumbnail to indicate that it is out of date. We will add a synchronize button to individual visualizations that are out of date (implement styling to make the synchronize icon stand out). Visualization thumbnails can also be updated by opening up the visualization.

Note that In the future (post-Phase 1), we may want to add a global refresh button to allow the user to update all visualization thumbnails at once. But this will need a warning message as updating all the thumbnails will be very time & resource intensive, especially for large studies. We likely want to avoid a global refresh since users will likely still click on it even after being warned about the time involved

[Mockups](https://docs.google.com/presentation/d/14FYZr4G2AiyE67yYRjBTSyuRkhDb8xFE5AUsi_eUDBs/edit)

**Comment by danicahelb** [comment]
here is the ticket for how viz thumbnails will be improved in phase 2: https://github.com/VEuPathDB/EdaClinepiPhase2NewIssues/issues/14

**Comment by danicahelb** [comment]
Hi @moontrip can you try to make the grey for the out-of-date thumbnails a bit LESS transparent? The text is hard to read over the graphics, and I'm hoping that if we make the plot less visible the text will be easier to read. Thanks!

![image](https://user-images.githubusercontent.com/25450900/135502265-b4c79c84-d73c-4961-961f-f6c6d35925be.png)

**Comment by moontrip** [comment]
Hi @danicahelb Thank you for your review and suggestions! 👍 As suggested I have slightly increased opacity of gray, in addition to, increased text color to be darker (1st screenshot). The second screenshot is applied with a bit more increase of opacity compared to the 1st one (not that visible to distinguish between two though). Please see the screenshot below and let me know if it works: you are always welcome to give me a feedback for further change 😄 

![thumbnail-gray-out3](https://user-images.githubusercontent.com/12802305/135506551-a4aa32d8-a890-4b7d-887a-3fb72caa1f6e.png)

![thumbnail-gray-out4](https://user-images.githubusercontent.com/12802305/135506810-bdfb05d2-8df0-4362-8b3d-a4f5d82c9a77.png)

**Comment by danicahelb** [comment]
Thanks @moontrip! Opacity in the 3rd screenshot looks good to me, I also like the darker text. Sheena suggested adding a slight white halo around the text, I don't know if that would be easy to implement or not.

**Comment by moontrip** [comment]
@danicahelb Sounds great! Also tried to add an outer glow effect to the text, but it is mostly visible under purple (and the scatter plot in some degrees). It is understandable as white is not that visible with light gray 😃 - please see the screenshot. If it is okay, then I will make PR including the effect.

![thumbnail-gray-out6](https://user-images.githubusercontent.com/12802305/135515931-4a6e6109-574c-4e93-ba76-bcd38ecd0d68.png)

**Comment by danicahelb** [comment]
@moontrip this looks perfect, please make the PR. thanks!

**Comment by danicahelb** [comment]
Looks good, thanks DK!

**Comment by moontrip** [comment]
@danicahelb Thank you for your quick review and tests 👍
