### ISSUE TITLE
Visualization: handling long axis tick label with ellipsis and tooltip for Mosaic plot

### ISSUE THREAD

**Issue by moontrip** [VEuPathDB/web-eda#469]
This work is a kind of an extension of previous task, [long axis tick labels for barplot and boxplot](https://github.com/VEuPathDB/web-eda/issues/328), which would apply to Mosaic plot. 

note: this ticket was initially [made at web-components repo](https://github.com/VEuPathDB/web-components/issues/214) expecting that it is shown at our project board, but somehow it does not work. So I made the same one here at web-eda.

**Comment by moontrip** [comment]
well now I realized how it makes happen so I will close this

**Comment by bobular** [comment]
https://github.com/VEuPathDB/web-components/issues/214 is showing on the Kanban board under "this cycle".

ahahaha you got there first

**Comment by moontrip** [comment]
@bobular yes I firstly didn't know how to make this show in the project board so I made this ticket assuming that the board only handles web-eda repo. But I got the point to make it happen by setting Projects at right hand menu 😄 thus I closed this duplicate issue
