### ISSUE TITLE
Visualization: Box / Beeswarm plot

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#47]
**API:** https://veupathdb.github.io/EdaDataService/api.html#resources:/apps/pass/visualizations/boxplot:post
**Plot component:** https://veupathdb.github.io/web-components/?path=/story/plots-box--basic

**Comment by moontrip** [comment]
just for note to me: there are several updates that also affected viz component. Accordingly, this boxplot viz also needs to be updated. This is a record what should be done later (will keep updated): reference to `scatterplotvisualization.tsx` 

- https://github.com/VEuPathDB/web-eda/commit/1fe17d661fbb8f8319d4339f555a797744c20af5#diff-0c42189362f7c0d661b89bf7a2a60fbe4cebaf4258184514f1c8a4117d302cf6

- https://github.com/VEuPathDB/web-eda/commit/c2581bdf4d524e085b05bd76fe440978be012fec#diff-e51b150e769090d14ad16bf64584cca0bf8acda397695949448cb557cc620263

- https://github.com/VEuPathDB/web-eda/pull/131/files#diff-e51b150e769090d14ad16bf64584cca0bf8acda397695949448cb557cc620263

**Comment by moontrip** [comment]
another updates concerning cleanup etc.

https://github.com/VEuPathDB/web-eda/commit/0f8fa33339640ff3bcb0afcdc4ab6d7ee378f35d#diff-e51b150e769090d14ad16bf64584cca0bf8acda397695949448cb557cc620263

https://github.com/VEuPathDB/web-eda/commit/4d4fe1b7dd9e4742041de1f5b255c60e5a73df97#diff-e51b150e769090d14ad16bf64584cca0bf8acda397695949448cb557cc620263

**Comment by moontrip** [comment]
@bobular suggested a refactoring to use quartiles etc. instead of raw data in order to deal with many data: discussed at PR; https://github.com/VEuPathDB/web-eda/pull/120#issuecomment-859941053
