### ISSUE TITLE
Error message appearing for data with data_shape = continuous, data_type = integer

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#472]
Steve updated the services so that integer data won't appear with a decimal place, and Jay updated the loading pipeline so type = integer when the type is numeric and precision = 0. 

However, now that Jay has reloaded PRISM2, the histograms for a number of variables has disappeared and been replaced by the error message "This variable type is not currently handled." Jay checked the variables and reported that the data appear to be loaded correctly with data_shape = continuous, data_type = integer. 

Here's a list of some of the variables where this is occurring: Health facility distance, Market distance, Time since last fumigation, Female Anopheles gambiae count, Gravid Anopheles gambiae count, Bloodfed Anopheles gambiae count, Unfed Anopheles gambiae count, Unable to assess Anopheles gambiae count, Female Anopheles count, Anopheles dissected for parity count, Height, Weight, Temperature, Time since enrollmentr
<img width="338" alt="Screen Shot 2021-09-20 at 1 11 17 PM" src="https://user-images.githubusercontent.com/54597319/134052786-9954fdea-30dd-4d7e-91c2-2e8c929c9502.png">

**Comment by ryanrdoherty** [comment]
Apparently both front-end and back-end issues for this; we never fully implemented on backend.

**Comment by dmfalke** [comment]
@ryanrdoherty please add a comment with the new tags for any affected services. I will wait for that to merge the associated PR.

**Comment by SheenaTomko** [comment]
Looks good. Checked in PRISM2 and India ICEMR cx, 2 studies I know were reloaded recently
