### ISSUE TITLE
Visualizations: Data in response is not being plotted

### ISSUE THREAD

**Issue by aaronwlsong** [VEuPathDB/web-eda#479]
In vizualization section, some compatible variables generate empty plot with negative x-y coordination. For example, in india cohort study, This happens in bar plot when main=" Treated with antimalarials" or " Clinic or hospital" and overlay=" Untreated bednet count"," ITN bednet count, treated >6 months ago"," ITN bednet count, treated <6 months ago" or " Long-lasting ITN bednet count".

![image](https://user-images.githubusercontent.com/61077845/133142884-8deb4800-7f72-44cd-b294-fae874dd1152.png)

**Comment by moontrip** [comment]
@aaronwlsong @d-callan I had a chance to test this via `qa.restricted`, but it seems to work fine in there ? So, I will assign this to @aaronwlsong for further test - this issue might be resolved by other fixes (like handling integer)

![qa-restricted](https://user-images.githubusercontent.com/12802305/136058349-5a5abecb-05f1-4dc7-b3c8-2ecb88d0b1c2.png)
