### ISSUE TITLE
Styling: Use new icons for My Analyses and download current subset

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#487]
Follow up to Creating New Icons issue #415

**Comment by asizemore** [comment]
Closed with above PRs. Note, only changes icons. General styling will be fixed when addressing #450

**Comment by SheenaTomko** [comment]
Icons look great. Showing the new table icon for "My analyses" on the study card and within the EDA; for the Study summaries table in the drop down menu. Showing the new table icon + download icon for downloading the subset table
