### ISSUE TITLE
Visualization: No response for chosen variables in histogram

### ISSUE THREAD

**Issue by aaronwlsong** [VEuPathDB/web-eda#491]
In some india studies, histogram does not respond chosen variables. No any warning messages, just looks like always loading data. 

eg.1. In _india_ICMER_SevereMalaria_ study, for histogram, when main="Calcium", overlay="" or any var
![image](https://user-images.githubusercontent.com/61077845/135300777-d25b055b-12d1-415e-b9e5-8d0c2dc1723a.png)

eg. 2 In _India ICEMR Fever Surveillance_ study,  When x=" Dengue OD cutoff value, Panbio Dengue IgM capture ELISA"," Dengue OD cutoff value, Panbio Dengue Early ELISA".
![image](https://user-images.githubusercontent.com/61077845/135308196-50785211-6dc1-403b-b1ad-3018d54a97fa.png)

**Comment by bobular** [comment]
I had a quick look, this guard in guard.ts should no longer check for dataShape == continuous

```
export function isHistogramVariable(
  variable: VariableTreeNode
): variable is HistogramVariable {
  switch (variable.dataShape) {
    case 'continuous':
      switch (variable.type) {
        case 'date':
        case 'number':
        case 'integer':
          return true;
      }
  }
  return false;
}
```
However, when I remove that check, the histogram request is finally made, but throws a 500 on the back end (dfalke-b)

```
{
	"status": "server-error",
	"message": "Unable to complete processing",
	"requestId": "3p3zD9DgCRMZGLVVFbOBrI"
}
```

There are some other checks for dataShape==continuous and it looks like the NumberVariable and DateVariable in types/study.ts need to allow `rangeMin` and `rangeMax` regardless of data shape.

If I can do a quick fix and PR now, I will - but if it turns out more complex I'll leave it to you or me next week.

**Comment by dmfalke** [comment]
That sounds fine to me. Honestly, I think we should remove all checks from
the visualizations. Let the variable constraints do their thing, and if it
results in a 500, we’ll address on the backend.

**Comment by dmfalke** [comment]
Those guards were really meant for the subsetting tab where we start with a variable and then determine the appropriate filter ui.

**Comment by bobular** [comment]
Cool - I'm nearly done.

I'll push a draft PR for you to have a look at.  Seems some vars are producing 500s for histogram endpoint...

**Comment by dmfalke** [comment]
Thanks! I knew if I waited long enough I’d be rewarded 😁

**Comment by aaronwlsong** [comment]
I retested the issue in both studies, seems they still exist. 

![image](https://user-images.githubusercontent.com/61077845/136264486-552dd010-202a-40b6-901d-36b87941a02f.png)
