### ISSUE TITLE
General: Can't reload a visualization

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-eda#523]
if i try to reload/refresh a visualization i get an error about not being able to load the analysis.
encountered on qa.restricted as guest.
console shows a 404 for some url commonly looking like: https://qa.restricted.clinepidb.org/eda-data/users/303780000/analyses/a963b4e340d16f760cf098d95043bfc9

**Comment by dmfalke** [comment]
This approach breaks in certain situations. For instance, if services are protected by a gateway that uses cookies to validate requests, omitting credentials will cause these requests to break. An alternative approach will be needed.

**Comment by dmfalke** [comment]
The change to the cookies has been deployed to dev/feat/qa sites, so I'm closing this issue.

**Comment by dmfalke** [comment]
As a guest user (not logged in), start a new analysis and set any filter.
This will cause a new analysis to be created. Then reload the page. You
should see the analysis you just created.

Before the fix, you would get the error that Danielle described.
