### ISSUE TITLE
We're sorry something went wrong error message (WASHb Kenya)

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#531]
I am getting the error message below. I am on qa.restricted looking at WASHb Kenya & tried to select Household study timepoint = 2

I tried clearing the metadata cache & reloading the page. This didn't work
I tried clicking the link to clear my browser storage and resetting the session. This didn't work either

![image](https://user-images.githubusercontent.com/25450900/136282790-207b2d0e-cdc2-478b-b7e4-7acb76a10afb.png)

`Unexpected backend type(s) encountered: Invalid value `"2"` supplied to 0 (type: number) of numberSet (type: Array<number>) of 1 (type: { type: "numberSet", numberSet: Array<number> }) of 1 (type: ({ entityId: string, variableId: string } & { type: "numberSet", numberSet: Array<number> })) of 0 (type: (({ entityId: string, variableId: string } & { type: "stringSet", stringSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberSet", numberSet: Array<number> }) | ({ entityId: string, variableId: string } & { type: "dateSet", dateSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberRange", min: number, max: number }) | ({ entityId: string, variableId: string } & { type: "dateRange", min: string, max: string }) | ({ entityId: string, variableId: string } & { type: "multiFilter", operation: "union" | "intersect", subFilters: Array<{ variableId: string, stringSet: Array<string> }> }))) of descriptor (type: Array<(({ entityId: string, variableId: string } & { type: "stringSet", stringSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberSet", numberSet: Array<number> }) | ({ entityId: string, variableId: string } & { type: "dateSet", dateSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberRange", min: number, max: number }) | ({ entityId: string, variableId: string } & { type: "dateRange", min: string, max: string }) | ({ entityId: string, variableId: string } & { type: "multiFilter", operation: "union" | "intersect", subFilters: Array<{ variableId: string, stringSet: Array<string> }> }))>) of subset (type: { descriptor: Array<(({ entityId: string, variableId: string } & { type: "stringSet", stringSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberSet", numberSet: Array<number> }) | ({ entityId: string, variableId: string } & { type: "dateSet", dateSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberRange", min: number, max: number }) | ({ entityId: string, variableId: string } & { type: "dateRange", min: string, max: string }) | ({ entityId: string, variableId: string } & { type: "multiFilter", operation: "union" | "intersect", subFilters: Array<{ variableId: string, stringSet: Array<string> }> }))>, uiSettings: { [K in string]: UnknownRecord } }) of descriptor (type: { subset: { descriptor: Array<(({ entityId: string, variableId: string } & { type: "stringSet", stringSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberSet", numberSet: Array<number> }) | ({ entityId: string, variableId: string } & { type: "dateSet", dateSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberRange", min: number, max: number }) | ({ entityId: string, variableId: string } & { type: "dateRange", min: string, max: string }) | ({ entityId: string, variableId: string } & { type: "multiFilter", operation: "union" | "intersect", subFilters: Array<{ variableId: string, stringSet: Array<string> }> }))>, uiSettings: { [K in string]: UnknownRecord } }, computations: Array<({ computationId: string, descriptor: { type: string, configuration: unknown }, visualizations: Array<({ visualizationId: string, descriptor: ({ type: string, configuration: unknown } & Partial<{ thumbnail: string, currentPlotFilters: Array<(({ entityId: string, variableId: string } & { type: "stringSet", stringSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberSet", numberSet: Array<number> }) | ({ entityId: string, variableId: string } & { type: "dateSet", dateSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberRange", min: number, max: number }) | ({ entityId: string, variableId: string } & { type: "dateRange", min: string, max: string }) | ({ entityId: string, variableId: string } & { type: "multiFilter", operation: "union" | "intersect", subFilters: Array<{ variableId: string, stringSet: Array<string> }> }))> }>) } & Partial<{ displayName: string }>)> } & Partial<{ displayName: string }>)>, starredVariables: Array<{ entityId: string, variableId: string }>, dataTableConfig: { variables: Array<{ entityId: string, variableId: string }>, sorting: Array<{ key: string, direction: "asc" | "desc" }> }, derivedVariables: Array<unknown> }) of 1 (type: { descriptor: { subset: { descriptor: Array<(({ entityId: string, variableId: string } & { type: "stringSet", stringSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberSet", numberSet: Array<number> }) | ({ entityId: string, variableId: string } & { type: "dateSet", dateSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberRange", min: number, max: number }) | ({ entityId: string, variableId: string } & { type: "dateRange", min: string, max: string }) | ({ entityId: string, variableId: string } & { type: "multiFilter", operation: "union" | "intersect", subFilters: Array<{ variableId: string, stringSet: Array<string> }> }))>, uiSettings: { [K in string]: UnknownRecord } }, computations: Array<({ computationId: string, descriptor: { type: string, configuration: unknown }, visualizations: Array<({ visualizationId: string, descriptor: ({ type: string, configuration: unknown } & Partial<{ thumbnail: string, currentPlotFilters: Array<(({ entityId: string, variableId: string } & { type: "stringSet", stringSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberSet", numberSet: Array<number> }) | ({ entityId: string, variableId: string } & { type: "dateSet", dateSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberRange", min: number, max: number }) | ({ entityId: string, variableId: string } & { type: "dateRange", min: string, max: string }) | ({ entityId: string, variableId: string } & { type: "multiFilter", operation: "union" | "intersect", subFilters: Array<{ variableId: string, stringSet: Array<string> }> }))> }>) } & Partial<{ displayName: string }>)> } & Partial<{ displayName: string }>)>, starredVariables: Array<{ entityId: string, variableId: string }>, dataTableConfig: { variables: Array<{ entityId: string, variableId: string }>, sorting: Array<{ key: string, direction: "asc" | "desc" }> }, derivedVariables: Array<unknown> } }) of 0 (type: (({ studyId: string, studyVersion: string, apiVersion: string, isPublic: boolean, displayName: string } & Partial<{ description: string }>) & { descriptor: { subset: { descriptor: Array<(({ entityId: string, variableId: string } & { type: "stringSet", stringSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberSet", numberSet: Array<number> }) | ({ entityId: string, variableId: string } & { type: "dateSet", dateSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberRange", min: number, max: number }) | ({ entityId: string, variableId: string } & { type: "dateRange", min: string, max: string }) | ({ entityId: string, variableId: string } & { type: "multiFilter", operation: "union" | "intersect", subFilters: Array<{ variableId: string, stringSet: Array<string> }> }))>, uiSettings: { [K in string]: UnknownRecord } }, computations: Array<({ computationId: string, descriptor: { type: string, configuration: unknown }, visualizations: Array<({ visualizationId: string, descriptor: ({ type: string, configuration: unknown } & Partial<{ thumbnail: string, currentPlotFilters: Array<(({ entityId: string, variableId: string } & { type: "stringSet", stringSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberSet", numberSet: Array<number> }) | ({ entityId: string, variableId: string } & { type: "dateSet", dateSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberRange", min: number, max: number }) | ({ entityId: string, variableId: string } & { type: "dateRange", min: string, max: string }) | ({ entityId: string, variableId: string } & { type: "multiFilter", operation: "union" | "intersect", subFilters: Array<{ variableId: string, stringSet: Array<string> }> }))> }>) } & Partial<{ displayName: string }>)> } & Partial<{ displayName: string }>)>, starredVariables: Array<{ entityId: string, variableId: string }>, dataTableConfig: { variables: Array<{ entityId: string, variableId: string }>, sorting: Array<{ key: string, direction: "asc" | "desc" }> }, derivedVariables: Array<unknown> } })) of [root] (type: ((({ studyId: string, studyVersion: string, apiVersion: string, isPublic: boolean, displayName: string } & Partial<{ description: string }>) & { descriptor: { subset: { descriptor: Array<(({ entityId: string, variableId: string } & { type: "stringSet", stringSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberSet", numberSet: Array<number> }) | ({ entityId: string, variableId: string } & { type: "dateSet", dateSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberRange", min: number, max: number }) | ({ entityId: string, variableId: string } & { type: "dateRange", min: string, max: string }) | ({ entityId: string, variableId: string } & { type: "multiFilter", operation: "union" | "intersect", subFilters: Array<{ variableId: string, stringSet: Array<string> }> }))>, uiSettings: { [K in string]: UnknownRecord } }, computations: Array<({ computationId: string, descriptor: { type: string, configuration: unknown }, visualizations: Array<({ visualizationId: string, descriptor: ({ type: string, configuration: unknown } & Partial<{ thumbnail: string, currentPlotFilters: Array<(({ entityId: string, variableId: string } & { type: "stringSet", stringSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberSet", numberSet: Array<number> }) | ({ entityId: string, variableId: string } & { type: "dateSet", dateSet: Array<string> }) | ({ entityId: string, variableId: string } & { type: "numberRange", min: number, max: number }) | ({ entityId: string, variableId: string } & { type: "dateRange", min: string, max: string }) | ({ entityId: string, variableId: string } & { type: "multiFilter", operation: "union" | "intersect", subFilters: Array<{ variableId: string, stringSet: Array<string> }> }))> }>) } & Partial<{ displayName: string }>)> } & Partial<{ displayName: string }>)>, starredVariables: Array<{ entityId: string, variableId: string }>, dataTableConfig: { variables: Array<{ entityId: string, variableId: string }>, sorting: Array<{ key: string, direction: "asc" | "desc" }> }, derivedVariables: Array<unknown> } }) & { analysisId: string, creationTime: string, modificationTime: string, numFilters: number, numComputations: number, numVisualizations: number }))`

**Comment by ryanrdoherty** [comment]
@dmfalke, this is a client issue.  The 2 Danica selected is being put in a NumberSet filter as a string "2" and saved as a new analysis, which works fine.  But when the analysis is read back out of the user service, the "2" string cannot be parsed because a number is expected.  Full JSON sent to and received from user service looks like this:
`{
   "displayName":"Unnamed Analysis",
   "descriptor":{
      "subset":{
         "descriptor":[
            {
               "entityId":"EUPATH_0000776",
               "variableId":"EUPATH_0044122",
               "numberSet":[
                  "2"
               ],
               "type":"numberSet"
            }
         ],
         "uiSettings":{
            
         }
      },
      "starredVariables":[
         
      ],
      "dataTableConfig":{
         "variables":[
            
         ],
         "sorting":[
            
         ]
      },
      "derivedVariables":[
         
      ],
      "computations":[
         {
            "computationId":"pass-through",
            "displayName":"Passthrough",
            "descriptor":{
               "type":"pass"
            },
            "visualizations":[
               
            ]
         }
      ]
   },
   "isPublic":false,
   "studyId":"DS_010e5612b8",
   "apiVersion":"",
   "studyVersion":""
}`

**Comment by dmfalke** [comment]
This should be as simple as parsing the value when creating the filter object.

**Comment by danicahelb** [comment]
seems ok now, thanks
