### ISSUE TITLE
Variable tree: order featured variables based on tree and display order

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#544]
Featured variables are currently being ordered using the ordering that the subsetting service produces. Instead, they should be ordered the same as in the tree, using display order.

**Comment by chowington** [comment]
@dmfalke Is this still an issue? It appears to me that the variable tree and the featured variables are using the same ordering. This is both from eye tests on multiple studies and from looking at the code. In the code, I believe the variable tree and the featured variables both derive their order from the ordering that `getStudyMetadata` is doing here: https://github.com/VEuPathDB/web-eda/blob/c0335f832c4bf17ed19f758765fcbebfc9471041/src/lib/core/api/SubsettingClient/index.ts#L50

**Comment by chowington** [comment]
@jtlong3rd See my comment above, thanks!

**Comment by bobular** [comment]
@danicahelb to do QA on this issue

**Comment by danicahelb** [comment]
This still seems to be an issue:

![image](https://user-images.githubusercontent.com/25450900/149237815-c2dbe939-c371-40b2-b346-3ad73c7d742a.png)

**Comment by danicahelb** [comment]
Also an issue in PRISM ICEMR Cohort:

![image](https://user-images.githubusercontent.com/25450900/149238774-2c97012c-a791-4cfb-b69e-2c353399c190.png)

**Comment by danicahelb** [comment]
And PRISM2 ICEMR Cohort

![image](https://user-images.githubusercontent.com/25450900/149238862-49478977-bbbe-454c-a9ab-147115ee01b7.png)

**Comment by danicahelb** [comment]
And SCORE Burundi Mapping Cross sectional

![image](https://user-images.githubusercontent.com/25450900/149239141-7ff238ba-b897-479d-a730-ca1f2919572d.png)

**Comment by danicahelb** [comment]
And SCOORE Rwanda Mapping CX

![image](https://user-images.githubusercontent.com/25450900/149239292-1fb66445-d29b-4ab2-9119-7cdd9433a7be.png)

**Comment by danicahelb** [comment]
And SCORE Zanzibar S. haematobium Cluster Randomized Trial

![image](https://user-images.githubusercontent.com/25450900/149239442-8f866a67-a710-4b11-83d1-a1f4ab4d6d93.png)

**Comment by dmfalke** [comment]
@danicahelb are all of these issues that the order of the featured variables is not the same as the tree? If so, would you say that the order in the tree is correct?

**Comment by danicahelb** [comment]
@dmfalke yes, these studies all have the issue where the order of the featured variables does not match the order in the tree. I guess it is possible that the order of the tree is incorrect for some reason. I didn't work on these studies, so I will check in with Sheena & Nupur about this

**Comment by dmfalke** [comment]
Thanks Danica! After rereading the description of the issue, it's obvious! 🙂

**Comment by SheenaTomko** [comment]
The featured variables for PRISM technically match the order in the tree, but what's happening is that if 2 variables, like "Observation type" and "Malaria diagnosis and parasite status" both have a displayOrder of 1 in different categories, they're being ordered first by their displayOrder, then by the displayOrder of their parent category, rather than being ordered first by the order of their parent category, then by their specific displayOrder. 

If we switch this around, then we should have for PRISM "Observation type", "Age", and "Observation date" followed by "Malaria diagnosis and parasite status".

**Comment by chowington** [comment]
QA hint: Star all featured variables, then show only starred variables ;)

![image](https://user-images.githubusercontent.com/12377649/152859361-cbd61ce0-d93c-41aa-945d-e87019d95545.png)

**Comment by SheenaTomko** [comment]
This looks great. Marking as complete
