### ISSUE TITLE
Solve issue of site-wide CSS messing up our component styling

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#55]
One example is the `textarea` styling of input fields e.g. in HistogramControls coming from `datetimebox.css`

This will need to be done outside of web-eda in 'common website code' but making a note of it here.  Therefore a 'not-for-CRC' issue at present.

**Comment by bobular** [comment]
From closed duplicate ticket
> Styling from web-common is taking precedent over material-ui styling. This needs to be addressed in web-common.

**Comment by dmfalke** [comment]
This will be addressed by https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/53
