### ISSUE TITLE
Handle subsequent updates when transitioning from a saved, to a new analysis

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#560]
Currently, when a _new_ analysis becomes _saved_, the user can continue to add filters while the _saved_ analysis is being created on the back end. These additional filters are lost when the client receives the _saved_ analysis and replaces the analysis state.

We want to keep track of additional filters and apply them to the saved analysis once received.

See the description of #553 for more context.

**Comment by chowington** [comment]
Looks like this ticket is getting stale. I'd be happy to tackle it if @jtlong3rd thinks it's within my ballpark. I'm sure I'd need some guidance at the very least!

**Comment by jtlong3rd** [comment]
> Looks like this ticket is getting stale. I'd be happy to tackle it if @jtlong3rd thinks it's within my ballpark. I'm sure I'd need some guidance at the very least!

Let's discuss at the next dev meeting! @dmfalke and I have been considering, on and off, a large refactor of the `useAnalysis` hook which would affect (ideally simplify) the work needed for this ticket.

**Comment by chowington** [comment]
Ok, sounds good Jamie!
