### ISSUE TITLE
Handle 'N/A' value from histogram stats for both numbers and dates

### ISSUE THREAD

**Issue by ryanrdoherty** [VEuPathDB/web-eda#561]
Backend code lives in EdaSubsettingService branch missing-stats.  Ensures that continuous (bin) number and date histograms contain these values:

subsetMin
subsetMax
subsetMean

If subset size is zero, for dates or numbers, the string "N/A" is returned, which, while technically allowed by the API is inconsistent with the number variable's normal value for these properties.  We could set to -1 instead if that's more convenient?

When complete, feel free to merge this PR:
https://github.com/VEuPathDB/EdaSubsettingService/pull/42

**Comment by ryanrdoherty** [comment]
@dmfalke Is this done?  Looks like the backend PR was merged in October, so client must be handling "N/A", right?

**Comment by dmfalke** [comment]
@ryanrdoherty it looks like that PR was closed.

It looks like the subsetting service is still omitting those values, and the client is rendering "N/A" for them.

**Comment by dmfalke** [comment]
See some relevant discussions:
- https://github.com/VEuPathDB/EdaSubsettingService/issues/40#issuecomment-954209111
- https://github.com/VEuPathDB/web-eda/issues/638

I'm going to close this issue as irrelevant.
