### ISSUE TITLE
Subsetting: disable bulk download button

### ISSUE THREAD

**Issue by moontrip** [VEuPathDB/web-eda#564]
For phase 1 we have decided to disable the button: not to show it. It can be easily done by commenting out the part at `Subsetting` component.

**Comment by moontrip** [comment]
Initially I thought @asizemore's work concerning its icon was already merged in the main but realized that the PR (#537) is still open. So perhaps this issue can be handled at the PR as well - taking to her at Slack.

**Comment by nkittur-uga** [comment]
Checked several studies and bulk download button does not appear in any of them. Passes QA.
