### ISSUE TITLE
General: add "Notes" tab (for Phase 2)

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#572]
Dave had a great idea to add a “Notes” tab next to “Visualize” where the user can write notes about that particular saved analysis (ie, purpose, steps taken, etc)

Users could fill out the study description (needed for making an analysis public) within the notes tab; UI for making public analyses could guide them to filling out a designated section within the notes tab

**Comment by steve-fischer-200** [comment]
we need to confirm that the Eda User Service supports both Brief Description and Details.

(We need the brief description for display in the Analyses Tables)

**Comment by eikonomega** [comment]
This ticket has a dependency on https://github.com/VEuPathDB/EdaUserService/issues/10

**Comment by nkittur-uga** [comment]
Tested Notes tab on qa.restricted and it is working well! 
There is a small issue with the text box overlapping the footer so I am not moving to "Complete" yet.

<img width="1084" alt="Screen Shot 2021-11-10 at 2 06 04 PM" src="https://user-images.githubusercontent.com/67710160/141177371-338057c5-ef47-46cb-b3b1-f9b4046c0ac9.png">

**Comment by nkittur-uga** [comment]
Text box is no longer overlapping footer. Looks good!
