### ISSUE TITLE
Visualizations: allow zooming & truncation

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#573]
In Phase 1 we added the ability to zoom in / truncate axes to the browse/subset histograms: https://github.com/VEuPathDB/web-eda/issues/231

For Phase 2, we want to enable the ability to change the axes ranges for plots in the viz tab. This is needed for:

**Currently available plots**
- Scatter plots 
- histograms
- bar plots (y-axis only)
- boxplots (y-axis only)

**Future plots**
- Line plots
- Density plots 
- hexbin plots

**Comment by steve-fischer-200** [comment]
danielle says that
 - viz histogram already supports this zooming in back end
 - the others are client side zoom

**Comment by danicahelb** [comment]
Once this ticket is ready for QA, whoever is QAing should also please take a look at [VEuPathDB/plot.data#103](https://github.com/VEuPathDB/plot.data/issues/103) and see if zooming is good enough to also close that ticket

**Comment by danicahelb** [comment]
Histograms will have semantic zooming. The x-axis for these plots are binned; zooming in on the x-axis changes the bins and y-axis counts and axis ranges should update accordingly.

Line plots also have binned x-axis but we do NOT want semantic zooming on these plots. The positions of the line markers should NOT change as the user zooms in. 

Thanks!

**Comment by sweverschulman** [comment]
The following plots allow for zooming/truncation

- Scatter Plot - both axis 
![ScatterZoomIndiaICEMRCohort](https://user-images.githubusercontent.com/62298921/160163473-59071538-9bdb-49eb-ab0e-00c66babe7d3.png)

- Histograms - both axis 
![Screen Shot 2022-03-25 at 12 36 27 PM](https://user-images.githubusercontent.com/62298921/160163593-99b4f285-1183-48f6-9bdd-17bfd03f106b.png)

- Bar plot - y axis only 
![Screen Shot 2022-03-25 at 12 43 38 PM](https://user-images.githubusercontent.com/62298921/160164205-278f372f-eaaa-4631-a734-65bead5a6c78.png)

-Box Plot - y axis only 
![Screen Shot 2022-03-25 at 12 38 46 PM](https://user-images.githubusercontent.com/62298921/160164287-ef4c0909-120d-402d-acac-36e6954c05e3.png)
