### ISSUE TITLE
Visalisations (all): Don't gray out the text of show missing data switch

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#574]
The text "Include Participant repeated measures with no data for selected stratification variable(s)" should be black when the switch is active.

Maybe think about other control text too (e.g. in histogram viz) - see "Log scale" and "Bin width" in screenshot - though I think they look fine as is.

![image](https://user-images.githubusercontent.com/308639/137306896-eaf8bbfa-6731-4d19-90f3-2155d2c8ffc9.png)

**Comment by asizemore** [comment]
Thanks @bobular! In that second screenshot above, the active no data toggle is the same DARK_GRAY as the other Log scale toggle. But we actually want the text of this no data toggle to be even darker than the text of the other toggles, correct?

**Comment by bobular** [comment]
Hi @asizemore  - I think maybe the "log scale" text et al should also be black. Check with @danicahelb, @SheenaTomko and co.

I think they look OK all in grey, but when you factor in the greyed out missing data button, it doesn't look much different from the non-greyed out version, so probably all should be black...

**Comment by asizemore** [comment]
ahhhhh okay that makes sense. Thanks for the clarification @bobular!

**Comment by asizemore** [comment]
Closed with [web-components #235](https://github.com/VEuPathDB/web-components/pull/235)

**Comment by aaronwlsong** [comment]
Now the toggle text's color is always black no matter the toggle is switched on and off, which is consistent with toggle of "Log scale" in histogram.   

![image](https://user-images.githubusercontent.com/61077845/141199823-af315e7b-c959-41f6-a88e-891b1d22fcc8.png)

![image](https://user-images.githubusercontent.com/61077845/141199905-f29ee408-f027-4bee-9503-181eb86cc180.png)
