### ISSUE TITLE
Visualizations: Standalone custom plot legend

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#579]
Placeholder ticket for now, but some of what we need includes

- custom spacing, ordering and formatting
- clicks will toggle show/hide traces in the plot(s)

Decision will be needed on where it should go.  Mock-ups for single and faceted plots would be appreciated.

**Comment by danicahelb** [comment]
@bobular are there any other "roll our own" legend tasks that are not included in this ticket?

**Comment by nkittur-uga** [comment]
DK @moontrip I tested custom legends on all 4 plots- bar, scatter, box, histogram- and they look good. Does that mean this ticket can be moved to complete? Please advise.

**Comment by moontrip** [comment]
@nkittur-uga Yes. As mentioned in the other ticket, those four plot vizs are the ones for the custom legend, so if you are alright with those four, then this can be moved to complete 👍

**Comment by nkittur-uga** [comment]
QA is complete.
