### ISSUE TITLE
Histogram viz - height==1 bars don't mouse-over or show up in log scale mode

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#584]
Reproduce:

GEMS1A
Subset: Country==India
Histo viz: main: weight-for-age z-score; overlay: none

Problem: you can see a small third bar, but mouse-over does not make a pop-up (presumably because it's so small).  Related to VEuPathDB/EdaNewIssues#33 (but that's subsetting)

Log-scale mode should accentuate it, but the minimum is 1, so the bar is not shown.  Maybe min y-axis for log-scale count axes should be less than 1? @moontrip 

![image](https://user-images.githubusercontent.com/308639/137305107-adbd6c2f-a05d-4c92-ac80-9bef7aad4dfa.png)
![image](https://user-images.githubusercontent.com/308639/137305655-4bcb17bc-10bb-453c-8cb6-0ef61e8d9038.png)

**Comment by steve-fischer-200** [comment]
i assigned this 'low cost' but not totally sure about that.
