### ISSUE TITLE
Histogram viz bin width control momentarily displays zero in between changes.

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#586]
The behaviour is different compared to the subsetting histogram.

There, the binWidth slider props are calculated client-side. default bin width comes from study metadata and the min/max and step are [calculated](https://github.com/VEuPathDB/web-eda/blob/main/src/lib/core/components/filter/HistogramFilter.tsx#L789) from it.

Here, we get everything apart from the default binWidth from the back end response.  The empty plot shown in a new histogram viz also shows the slider with zero (range is 0 to 100).

New bug: If you adjust the slider while the request is pending, you can set the bin width to 100, which may be outside the expected range.

**Comment by SAK22** [comment]
all good!
