### ISSUE TITLE
General: revisit back arrow functionality

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#590]
I often hit the back button because I want to go to the last screen i looked at (ie, go from viz tab to subset tab). i know i don't _need_ to do this, but using the back button in this way seems more intuitive than bouncing me entirely out of the analysis

Edit (Connor):
Per conversation with Danica, the following should be "backable"
- [x] Analysis tabs (study details, subsetting, visualize, notes)
- [x] Changing entities via the entity diagram
- [x] Changing variables via the variable tree
- [x] Going into/out of an existing visualization
- [x] Going into/out of the new viz selector screen

**Comment by chowington** [comment]
@danicahelb I tested this, and it seems undoing analysis tab navigation is an easy fix; undoing navigation into and out of visualizations is not so easy. What are the specific reqs for this ticket?

**Comment by danicahelb** [comment]
Hey @chowington i'm not sure what you mean by "analysis tab navigation". did you mean undoing (pressing back on) **_browse & subset tab_** (not analysis tab?) navigation? 

If I am in the browse & subset tab, I'd want the back arrow to either remove filters I just applied to the current variable or, if i hadn't applied filters but navigated between variables I would want it to take me to the last variable I looked at. It is very annoying that the back arrow currently completely bounces me out of my current analysis.

If I am clicking through tabs, I'd like the back arrow to bring me to the place i last visited in the tab. For example, if I am looking at "Study timepoint" on the browse & subset tab and then I clicked onto the notes tab, I'd want the back arrow to bring me back to the "study timepoint" variable on the browse & subset tab (I'm not sure if this is one of the things you indicated was difficult).

I guess in general, I don't want the back arrow to bounce me out of my analysis unless the last thing I was doing was looking at something else on the site (outside of my current analysis)

Maybe we should find a time to chat?

**Comment by bobular** [comment]
I've been testing Connor's branch.

And now reading this thread.

@danicahelb wrote
> If I am in the browse & subset tab, I'd want the back arrow to either remove filters I just applied to the current variable

This is a major feature request that we can't just add to this ticket lightly (short version: filters have never been in the URL so it will not be trivial to implement this requested behaviour, because back/forward button browser history uses the URL)

What Connor has done already seems to avoid "backing out of the analysis entirely" which I think is a good step forward :-)

**Comment by chowington** [comment]
@bobular Thanks for looking over this issue! Danica and I had an earlier conversation about the ticket and we agreed with what you say here. The back button shouldn't have anything to do with adding or removing filters, only with navigation. 👍

**Comment by dmfalke** [comment]
Can someone add a succinct summary of how navigation should work? It's not clear to me, from reading the comments. For example, is the back/forward button only going to impact which tab is active?

**Comment by chowington** [comment]
To QA, check
1. All 5 back button cases in this ticket's first comment
2. In each of the 5 cases, the page does NOT jump all the way back up to the top when you use the back button to undo your last navigation
3. Using the browser back button should not make you lose any changes to the analysis you've made, like added filters, starred variables, or added visualizations

**Comment by sweverschulman** [comment]
I was able to confirm that using the back button in the below cases allows for the page to change and yet not loose any data.
