### ISSUE TITLE
Subsetting: histogram bins with little data are hard to see

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#595]
On the EDA site, the axes lines are much darker / thicker than they are on the live site, and "hide" bins that have very little data in them. This data would be easier to see if we made the axis line thinner and less dark.

**EDA:**
![image](https://user-images.githubusercontent.com/25450900/136465943-6d7bbece-b29b-4297-a66c-517c151bead7.png)

**WDK site:**
![image](https://user-images.githubusercontent.com/25450900/136466084-f49b245e-e661-4864-afee-e4ef4f459aee.png)

**Comment by chowington** [comment]
@danicahelb @SheenaTomko Do you just want lighter axes for the histogram, or for the bar plot or other plots as well?

**Comment by aaronwlsong** [comment]
Tested several studies on qa. website, it looks good now, closing ticket.

![image](https://user-images.githubusercontent.com/61077845/141538967-5843b624-d907-4f59-936f-ed725e2361e8.png)

![image](https://user-images.githubusercontent.com/61077845/141538781-fbd71cb3-4784-4ec9-a67b-1c5fe2f1f897.png)
