### ISSUE TITLE
Change Imported from verbiage in strategy description

### ISSUE THREAD

**Issue by sweverschulman** [VEuPathDB/web-eda#615]
Please update the verbiage for imported strategies to add last modified. 

(Imported from Username on time and date, last modified on.)

Please also bold the whole statement.

**Comment by jtlong3rd** [comment]
@ryanrdoherty The form of the provenance JSON looks good! It's okay to have the property be read-only for now.

**Comment by jtlong3rd** [comment]
> @jtlong3rd do you know if I can currently test this ticket?

Yes, this ticket can be tested on QA! You'll need to use the ClinEpi staff account to create a public analysis or two; you can then log in as another user, import the public analysis, and inspect the verbiage in My Analyses. (The "imported from" / "last modified" will appear in the Analysis column.)

**Comment by sweverschulman** [comment]
Verbiage has been added. 
<img width="1030" alt="Screen Shot 2021-11-10 at 1 41 03 PM" src="https://user-images.githubusercontent.com/62298921/141173795-39977533-df4e-427c-b247-aa5addb7335a.png">
r
