### ISSUE TITLE
General: UI for pre-release studies

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#618]
Need to make sure we have the right UI for pre-release studies (like PERCH, LAKANA, Namibia, etc.)

On qa.clinepidb should have no icon to access data (in either the dropdown or the study card), and instead say "COMING SOON!" If the study has real data loaded and the user is logged in with an account with access, the icon should appear. Should have the same behavior on qa.restricted.clinepidb.

For qa, PERCH has real data loaded, while LAKANA doesn't.

**Comment by danicahelb** [comment]
as of 2/28/2022, if I am not logged in (guest), everything looks fine.

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/25450900/156056422-b704cf75-8a56-41f5-be7c-67eb47c19b60.png">


However, after I log in, PERCH (which has data loaded) still says coming soon on the cards

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/25450900/156056290-32c6702c-4c8b-4846-9956-b1b5b52dc841.png">

And "coming soon" language has been removed from all pre-release studies in the drop down

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/25450900/156056594-12685bb4-6499-414c-bde1-d746be6436db.png">

If I click on the PERCH study in the dropdown, I get this error message:
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/25450900/156056724-4fd27f51-7a56-417c-8fe2-8d45afb89194.png">

**Comment by danicahelb** [comment]
Spoke to sheena about this, we need to have this fixed by b58 at the latest

**Comment by dmfalke** [comment]
I believe this is fixed. I checked both the qa site and the production site.

**Comment by SheenaTomko** [comment]
This looks great, thanks Dave!
