### ISSUE TITLE
General: Switching between Browse and Viz tabs causes page to scroll to top in browser

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#63]

**Comment by dmfalke** [comment]
I don't think there is an easy solution for this. This happens because of how the tabs are rendered. We'd likely have to implement some page-level caching so that the content of the tab can be rendered immediately. This might be something to address before the initial public release.

**Comment by dmfalke** [comment]
Another solution is to set a min width on the tab content container to be something like `100vh`, forcing all tabs to have a scrollbar
