### ISSUE TITLE
Boxplot "No data" overlay series has colored outline - should be gray

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#632]
Example

beta site

GEMS1
no subset

boxplot
x: floor material
y: median height
overlay: usual handwashing

It should not be that cyan colour outline...

![image](https://user-images.githubusercontent.com/308639/138966190-895a92e0-8b15-4da3-912c-6f4fcf55b19f.png)

**Comment by sweverschulman** [comment]
no date overlay is now grey and passes qa
<img width="649" alt="Screen Shot 2021-11-01 at 12 43 41 PM" src="https://user-images.githubusercontent.com/62298921/139708275-c31cfaa8-4c12-4a92-a53d-f0d40d4d5e56.png">
y
