### ISSUE TITLE
Subsetting: Handle empty histogram stats

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#638]
See https://github.com/VEuPathDB/EdaSubsettingService/issues/40 for details. Basically, the client should display "N/A" if stats are not available.

**Comment by aaronwlsong** [comment]
As I commented in ticket #40 (https://github.com/VEuPathDB/EdaSubsettingService/issues/40), it is not an issue in PRISM2 anymore. Closing ticket.
