### ISSUE TITLE
Faceting: calculate dependentAxisRange from plugin response for Boxplot and maybe others

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#650]
See BarplotVisualization in `facet-approach1` branch or this [PR](https://github.com/VEuPathDB/web-eda/pull/640) for what was done there (`defaultDependentMaxValue` and `dependentAxisRange`)

**Comment by moontrip** [comment]
made a PR for the Boxplot Viz, #688

**Comment by SheenaTomko** [comment]
looks good
