### ISSUE TITLE
Subsetting: Better selection for default variable when selecting an entity

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#66]
When selecting an entity for the first time, the current behavior is: the first variable in the entity's variable array with `dataShape` defined is selected.

Instead, we should select the first variable in the tree.

**Comment by steve-fischer-200** [comment]
can you clarify:  is your proposal
 1. if the user has previously visited this entity, use their most recent
 2. else, use the first in the tree (with a shape)

**Comment by dmfalke** [comment]
This issue is partially duplicated by https://github.com/VEuPathDB/web-eda/issues/35. I will update this one to reflect the case when an entity has not been visited before, in which case this can be closed.
