### ISSUE TITLE
Trying to open an analysis for a private study that's never been released throws errors

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#662]
On qa.restricted.clinepidb.org, if you are not logged in to a ClinEpiDB account and try to click the name of a new study (GAMIN or ELICIT) or the "Explore the data" icon on a study card or in the drop down menu, you get an error message like the one below. In this case, I clicked on the study name of EILICT on the study card.

If you log into a ClinEpiDB account that has access to the study, then you can open a new analysis. It used to be that I would have to log in, then go to the study summaries table, then click the name of the study to open it view the View study details tab. Now I can open an analysis from anywhere once I'm logged in.

Note, the 2 studies affected, GAMIN and ELICIT, both have a study access level of "private", have never been released on the WDK site, and have "isPublic" set to false in the presenters.
<img width="723" alt="Screen Shot 2021-11-03 at 3 25 53 PM" src="https://user-images.githubusercontent.com/54597319/140189047-5681a971-2405-4e0d-89c3-317a57e77673.png">

**Comment by dmfalke** [comment]
This issue is caused by EbrcWebsiteCommon using an outdated version of `DataRestrictionDaemon`.

**Comment by dmfalke** [comment]
issue close by https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/79 and https://github.com/VEuPathDB/ClinEpiWebsite/pull/11

**Comment by SheenaTomko** [comment]
Tested with ELICIT and GAMIN. For both now, if you try to open the study from the drop down, study card, or study table, you get the correct pop-up box prompting you to log-in and submit a data access request if you are a Guest user. Logging in gives you access as expected
