### ISSUE TITLE
Error in making visualizations in studies loaded since the EDA release

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/web-eda#663]
Browse and subset is working well for the GAMIN study on qa.restricted but throws up an error (see screenshot) when I try to make any visualizations.
<img width="1403" alt="Screen Shot 2021-11-03 at 10 32 23 AM" src="https://user-images.githubusercontent.com/67710160/140189715-58ab0f74-868f-4880-a00f-b1c9658f2090.png">

Comment from Jay: I keep wondering if these errors that say a study "does not exist" are related to the table StudyIdDatasetId. This table should only belong in the ApiDBTuning schema.
However since the beginning of development it was baked into some web code that this table belongs in ApiDB, and then after the schema was parameterized, EDA.
So for the time-being I have been keeping EDA.StudyIdDatasetId as a copy of ApiDBTuning.StudyIdDatasetId. But ApiDB.StudyIdDatasetId is permanently dead and I will never resurrect it. But I wonder if some web code is still referencing that long-dead table.

Comment from Steve: seems we should remove eda.studyiddatasetid.  it is not supposed to be supported.

**Comment by steve-fischer-200** [comment]
dave and danielle are working together to solve this permanently

**Comment by dmfalke** [comment]
I noticed the version of reserve on qa is out of date. I just updated it. I will test again in 30 minutes, when the deployed instance has been updated.

**Comment by d-callan** [comment]
my understanding is this turned out to be a docker compose configuration issue, and that BobB has since resolved this. I'm going to close it, so it can be QA'd.

**Comment by nkittur-uga** [comment]
Issue is resolved.
