### ISSUE TITLE
Visualizations: no data detection needs to be more sophisticated now we have overlay and facet vars

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#676]
This is what it should NOT look like:

(GEMS1 beta site, 8/Dec/2021)

A. Empty "No data" facet for a variable (Country) with no missing data.  (The overlay variable which does have missing data, is triggering this.) 
![image](https://user-images.githubusercontent.com/308639/145263576-043640bd-bcff-48da-be62-5760e26271e3.png)

B. Empty "No data" item in overlay variable legend (facet variable is triggering this)
![image](https://user-images.githubusercontent.com/308639/145264019-1ec0cc79-9972-46f5-a995-4c24e97f70c6.png)
 
Please also test a "Main variable" that has missing data. E.g., "Given stored water for drinking"

**Comment by bobular** [comment]
Hi @danicahelb - this has both b55 and b56 labels!  DSR said it was not a showstopper that unintended "No data" overlays and facets might appear in certain edge-cases.  I will work on it next, but am concerned that a substantial change in the logical behaviour of visualisations might introduce further bugs this close to release.  Your thoughts?

**Comment by bobular** [comment]
Just an update to say I am still working on this!  It's complicated but I am hopefully arriving at a parsimonious solution soon.

**Comment by aaronwlsong** [comment]
Looks good now, closing ticket.
_____________________________________________________________________________________________
The case 1 :  "No data" facet
![image](https://user-images.githubusercontent.com/61077845/146431992-3a501891-2979-4fd4-85ef-efe500518db4.png)
The case 2. "No data" item in overlay variable
![image](https://user-images.githubusercontent.com/61077845/146432336-d1bfe12e-0643-424c-b5e7-4e3129290d3e.png)
The case 3. "No data" in Main variable
![image](https://user-images.githubusercontent.com/61077845/146440682-e88e063c-26d0-47a7-a8e4-5c908140f8e1.png)
