### ISSUE TITLE
Visualization: Custom legend markers and colors

### ISSUE THREAD

**Issue by moontrip** [VEuPathDB/web-eda#678]
while a prototype of custom legend works are done, it is still required to add markers at legend labels like plotly's legend. A basic square markers are already made at #637 which would work for histogram, barplot, mosaic (2x2 and RxC) Vizs but still need to consider two more cases, scatter plot and boxplot Vizs. This ticket will handle the task.

**Comment by moontrip** [comment]
Boxplot Viz is done via [#251](https://github.com/VEuPathDB/web-components/pull/251)

**Comment by sweverschulman** [comment]
@moontrip 
Before I approve this ticket could you confirm the following things.
1. That the open dots are the correct icon in the scatter plot legend
2. That the clickable legend thing is supposed to be there 

I am attaching photos 
<img width="700" alt="Screen Shot 2021-11-15 at 11 24 45 AM" src="https://user-images.githubusercontent.com/62298921/141818202-114c985f-a40e-4eb5-a849-99abf524a4f3.png">

**Comment by moontrip** [comment]
@sweverschulman Thank you for your review and tests. Sorry that it is not clear of your question 1: The attached one is boxplot and you are saying scatter plot legend. FYI, it seems that my custom legend works for the scatter plot (and possibly the latest works from developers) are not updated correctly at qa/qa.restricted: asking Dave about this. So, if you are asking about the style of scatter plot then yes they are almost identical to what the Plotly's default legend shows. You can see [my screenshot in this link](https://github.com/VEuPathDB/web-eda/pull/698#issue-1052360283), which shows what the new markers/colors of custom legend for the scatter plot look like.

As for the number 2, unlike Plotly's default legend that offers clicking texts, we are not supporting it. This is the reason why we have introduced checkbox instead, which controls on-off plot trace(s).

Hope this would be helpful for you.

**Comment by sweverschulman** [comment]
thanks @moontrip. So to clarify the custom legend this. 
<img width="210" alt="Screen Shot 2021-11-15 at 11 40 33 AM" src="https://user-images.githubusercontent.com/62298921/141819984-ebf27e61-79ab-4c5f-95c8-015b80bf9fad.png">

**Comment by moontrip** [comment]
@sweverschulman yes correct. FYI, Jamie just committed his work for overall layout of plot, custom legend, bird eye plot, and table: certainly not reflected at as site yet. Also, we will disable the Plotly's default legend sooner or later and stick to the new custom legend instead for both regular plots and faceted plot.

**Comment by sweverschulman** [comment]
the new custom legend markers and colors are present in both scatterplots and boxplots
<img width="778" alt="Screen Shot 2021-11-17 at 4 02 22 PM" src="https://user-images.githubusercontent.com/62298921/142282590-1f5c3092-4c97-4bc5-a77d-8dbb0bbb9b35.png">
<img width="879" alt="Screen Shot 2021-11-17 at 4 02 30 PM" src="https://user-images.githubusercontent.com/62298921/142282598-efc1a6ef-9cde-4d23-bee2-46acb6e044d2.png">
