### ISSUE TITLE
Visualization: Wiring custom legend to faceted plots

### ISSUE THREAD

**Issue by moontrip** [VEuPathDB/web-eda#679]
Bob is converting Vizs to support faceted plots, thus I will add the custom legend to those plots. Currently, histogram and barplot Vizs are done for custom legend at #637 but will need to work for other Vizs such as boxplot, mosaic, and scatter plot Vizs. This work also involves a task to set legendItems object appropriately, which is different from each plot.

**Comment by bobular** [comment]
Remember to switch off legend in main plot

**Comment by moontrip** [comment]
Boxplot Viz is done via #683. Mosaic (2x2 & RxC) would not have custom legend for now, so only Scatterplot Viz is left

**Comment by nkittur-uga** [comment]
Custom legend looks good for histogram, bar plot, boxplot, scatter. But both mosaic plots don't have it yet so I am not moving to complete yet.

**Comment by moontrip** [comment]
Hi @nkittur-uga thank you for your reviews and tests! 👍 Please note that we will not implement the custom legend to the two Mosaic plots (at least for the time being) because they utilizes Plotly's legend in the left side as Y-axis labels. For this reason, the custom legend is not necessary for them for now.
