### ISSUE TITLE
Visualizations: Remove "info" icon from "compatible viz" toggle tooltip

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#685]
This is the icon to be removed:

![image](https://user-images.githubusercontent.com/365139/141197314-c6dcfc0d-9f0b-4777-ad0c-cd7ee7904ab8.png)

**Comment by danicahelb** [comment]
Icon has been removed, closing ticket
<img width="384" alt="image" src="https://user-images.githubusercontent.com/25450900/172962110-df8a4145-cac8-4acd-bb94-66b6f0c0f0cf.png">
