### ISSUE TITLE
Hidden variable with dataType "longitude" and displayType "hidden" not being hidden from tree (SCORE seasonal)

### ISSUE THREAD

**Issue by jaycolin** [VEuPathDB/web-eda#689]
Study: SCORE Seasonal Transmission S. haematobium Cluster Randomized Trial
variables: Latitude, Longitude
According to the [EDA roadmap: Mapveu needs](https://docs.google.com/document/d/1wKhcm_PnHuJ1i6mXjs-pOp4-_PqNtssz0T_7-Agnupg/edit#heading=h.5ml0x170vllp) longitude is one of the data types (others being string, number, date). The variable is hidden: displayType = "hidden". The variable appears in the navigation tree, and displays the message "his variable type is not currently handled."

**Comment by jaycolin** [comment]
also PRISM2: birth date

**Comment by danicahelb** [comment]
to clarify, terms that were hidden in b54 are no longer being hidden on the qa sites, ex: PRISM2 birth date
terms in studies new to b55 are also not being hidden.

Can we hook back up whatever was hiding variables in the past? Jay said that displayType currently says “hidden” or “multifilter” (or is blank), same as it was in b54

**Comment by nkittur-uga** [comment]
Study: SCORE Seasonal Transmission S. haematobium Cluster Randomized Trial
variables: Latitude, Longitude are appropriately hidden now. QA is complete.
