### ISSUE TITLE
Faceting Custom Legend - Scatterplot best fit R-squared in overlay variable legend needs to be removed

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#690]
Don't want to forget this!

We need to replace the "R2 = 0.1234" with "best fit".   I'm not sure what the long-term fate of the R2 numbers will be.

![image](https://user-images.githubusercontent.com/308639/141379444-e6659666-c091-41d6-812e-3d3dcffe1749.png)

**Comment by moontrip** [comment]
Thank you for your reminder, @bobular 👍 It is easy one, so perhaps I can handle it when working with custom legend stuff with scatter plot.
