### ISSUE TITLE
Visualizations / Faceting: ensure all vizs provide empty plots for empty facets

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#706]
I noticed that faceting Mosaic plots on Country (where country is filtered in subsetting to just one country) looks like a no-op (there's only one facet, so the facet layout handling is not triggered).  There should be mostly empty plots.

Should coordinate with @chowington who is working on https://github.com/VEuPathDB/web-eda/issues/681 - we discussed how to deal with it [here](https://docs.google.com/document/d/1W1iVvO0n29E2ZDN3M8VRoctg29voNOm-td8xLAxcGSA/edit?pli=1#bookmark=id.8jbeg43mqgqg) but I think we concluded the opposite to what we wrote down :grimacing: 

The plot components already test for "empty data" (usually `data.series.length === 0`) and render a skeleton.  However, the individual components all use 'empty data' as a fallback value for the `data` prop.  [Example here](https://github.com/VEuPathDB/web-components/blob/main/src/plots/Histogram.tsx#L92).

We were going to make the plot component (probably at PlotlyPlot.tsx) render its own HTML title and render a no-data message instead of the skeleton plot. We may need to change the fallback handling of `data` as described above.  I think these changes would be too much for a last minute b55 push.

I'll keep thinking about how best to do this in discussion with @chowington

**Comment by dmfalke** [comment]
I think a low cost approach would be to make a "delegate component" in web-eda. This component would be responsible for either rendering the "no data" UI if `data` is `undefined`, or delegating to the actual plot component. The props interface would look very similar to `FacetedPlot`. I'll leave the implementation details as homework, but happy to provide more if needed!

**Comment by bobular** [comment]
> I think a low cost approach would be to make a "delegate component" in web-eda. This component would be responsible for either rendering the "no data" UI if `data` is `undefined`, or delegating to the actual plot component. The props interface would look very similar to `FacetedPlot`. I'll leave the implementation details as homework, but happy to provide more if needed!

Oh, sorry, just saw this.  I think we're going with Connor's solution that is triggered in FacetedPlot by undefined data.

**Comment by nkittur-uga** [comment]
Tested in a number of different plots and they do provide empty plots for empty facets. Passes QA.
