### ISSUE TITLE
Visualizations: Make sure contingency tables in Mosaic 2x2 and RxC are ordered correctly by x and y variable vocabularies

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#715]

**Comment by bobular** [comment]
I have done some work on this and would appreciate some feedback from outreach @d-callan @asizemore @SheenaTomko @danicahelb and also looping in @chowington and @dmfalke 

The simple way to get all the categories in the Mosaic contingency tables is to manipulate the data that comes back from the server to include them - inserting zeroes where necessary.  It's simple because the Mosaic plot and the contingency table both consume the same type of data structure.

![image](https://user-images.githubusercontent.com/308639/142038065-17ea1e4c-c6c1-41c9-96d7-e9f6566189bb.png)

That gives us some data viz issues in the Mosaic however:

![image](https://user-images.githubusercontent.com/308639/142038347-c7fdc788-7296-4ee4-840e-200c41f1d7f1.png)

The main problem is that Kenya/Mali/Mozambique are all on top of each other. And also it's not immediately obvious that The Gambia is a zero-width column.

If/when we have fancy x-axis labels that have L-shaped lines connecting them to the correct x-coordinate, that would be good, but for now, if we continue this implementation direction, it might be good to have an option to prune the zero columns and rows out somewhere for the plot (in Mosaic plot component, or EDA-side?)

Seems crazy to put the zeroes in and then take them out again, but I think it's the most pragmatic approach.

**Comment by bobular** [comment]
Hmm, but there's also the facet dimension to consider.  I think for now just not showing x axis labels that have all zero data would be good to try first.  Will investigate.

**Comment by bobular** [comment]
Well that was unexpected! :rofl: 
![image](https://user-images.githubusercontent.com/308639/142051780-ccf64cae-ca94-41f5-874e-07e1fda90047.png)

**Comment by bobular** [comment]
Easily fixed

Do we want to keep ALL y-axis labels even the ones with no data (including no data across all facets)?
![image](https://user-images.githubusercontent.com/308639/142052406-80ed6917-d47e-4dbe-8a7c-8f0aad4404ea.png)

**Comment by dmfalke** [comment]
I say yes, if only to keep the margins consistent.

**Comment by bobular** [comment]
Thanks, @dmfalke - that reminds me we must re-enable the special legend for mosaic facets. I think we have a ticket for that - yes we do #703  :-)

**Comment by dmfalke** [comment]
I'm having more thoughts about this. I'm not sure it really makes sense to include ticks for values that have no data in this type of plot. It would either be pointing to an empty space (the edge of two adjacent bars); or we would have to add something, which, to me, indicates there is data. It just seems like it's adding noise.

**Comment by bobular** [comment]
> id be ok to leave the 0 value x axis ticks out of the mosaic for now so long as the 0 values are explicit in the table, but think it needs rectifying later. do we have a ticket already for a fancy x axis for mosaics? i imagine something similar to the custom y, where we list the possible values at equidistant ranges and draw lines or something to their x positions if they exist. thats not likely to be pretty though... anyhow id be happy enough w this for now so long as the issue for the custom xaxis tick labels were mentioned here.

There are definitely plans for better x-labels (L-shaped lines to connect labels with axis) 
Possibly two tickets #458 #617 (they should probably be in web-components but hey)

**Comment by SheenaTomko** [comment]
Tested on GEMS. See that if I subset on Age group then include it as the x-axis, the value with no data doesn't appear, and this holds true if I turn on facets. Looks good. 

<img width="1049" alt="Screen Shot 2021-11-19 at 8 50 35 AM" src="https://user-images.githubusercontent.com/54597319/142642338-30e5a8c4-52be-48ae-ac8d-c9dececdcffa.png">
