### ISSUE TITLE
Visualizations mosaic faceting - if keeping vertical layout, add margin-top to facet headings in multi-contingency table

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#723]
The facet "headings" should be closer to the table they apply to (below them) than the one above.

Might be better with a margin-bottom on the table, or some fancy if-not-first CSS rule.

**Comment by bobular** [comment]
Also, empty facets don't need to have quite so much min-height or whatever is causing the gaps.  A "No data for this facet" might be more appropriate.

![image](https://user-images.githubusercontent.com/308639/142197522-5811aa59-8d8b-47ac-a263-2099b9c43c6b.png)

**Comment by chowington** [comment]
@bobular On main the cont tables are arranged horizontally. Is that the final arrangement as opposed to the vertical arrangement shown here?

**Comment by bobular** [comment]
Hi Connor, it's obviated now due to the horizontal layout, which to my eye doesn't need any urgent work either.

![image](https://user-images.githubusercontent.com/308639/144071932-f88c9c2a-05b4-4b6b-8908-83ff775a58d3.png)
