### ISSUE TITLE
QA site: Variable search box not working properly in Visualize tab

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/web-eda#727]
Study: GEMS1 Case Control
Visualize tab
Mosaic plot 2x2 tool
In the X axis variable selection box, I try to search for "rotavirus" but it does not work properly (see screenshot). 
This is only an issue on https://qa.restricted.clinepidb.org/. Compare with the second screenshot where it is working properly on the beta site. 
<img width="433" alt="Screen Shot 2021-11-17 at 10 03 54 AM" src="https://user-images.githubusercontent.com/67710160/142227843-43487bbf-be54-487c-a2e2-13fddb3bf3f9.png">
<img width="400" alt="Screen Shot 2021-11-17 at 10 07 42 AM" src="https://user-images.githubusercontent.com/67710160/142227846-7bec8938-ed5a-436c-8484-fd5f7ef1ca00.png">

**Comment by dmfalke** [comment]
This is specific to mulifilter. In subsetting, we only show the parent node. In visualizations, we also how children. The search logic is currently operating at the multifilter parent level, which collects data from all of its children, and if any match the search term, then all children are displayed. Changing this logic for the viz tab is straightforward.

**Comment by sweverschulman** [comment]
qa passed. search is now working on qa.restricted

![Screen Shot 2021-11-18 at 11 18 45 AM](https://user-images.githubusercontent.com/62298921/142454170-f4b8f032-26f5-41f8-98c9-a81befc27d3a.png)
