### ISSUE TITLE
Categorical variables with actual 'No data' values in database are problematic for the new legend

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#728]
Here's an example from 'SCORE Mozambique S. haematobium Cluster Randomized Trial' which is fooling our new custom legends.

![image](https://user-images.githubusercontent.com/308639/141658475-920a8851-3738-436b-a056-11515f175612.png)

The 'No data' values are correctly plotted in green*, because they are not actually "No data" in the sense that there are no values in the database.

(* though having some 'No data' in green, and others in gray is not an ideal situation - but this is currently what's on the beta site)

However, the custom legend is required to gray out and italicise the "No data" element, and currently can only do this on the basis of the label starting with `No data`.

I have looked for possible workarounds on the client side and there are none possible at present, for the simple reason that is impossible to distinguish overlay strata returned from the back end that contain the database-derived `No data` label and the artificially inserted `No data` label.

Two possible solutions exist:

1. curatorial - replace "No data" values with "No data collected/recorded" or similar (@SheenaTomko)
2. add a new optional boolean property to the back end response: `barplot.data[].facetVariableDetails[].isNoData`which we can detect in the client and handle appropriately (@d-callan)

**Comment by danicahelb** [comment]
ClinEpi team will have all valueMap files fixed and relevant studies reloaded by b56 to fix this issue

**Comment by SheenaTomko** [comment]
Checked all studies on beta site and found just 2 studies (SCORE S. mansoni CRT and SCORE Mozambique) that had 1 variable each ("Sex" in both) with a value of "No data". @nkittur-uga, can you update the valueMap for these studies to say something like "Not collected" or "Unknown" instead and have Jay patch them?

**Comment by SheenaTomko** [comment]
Note, I also updated our valueMap SOP to state that we should not map values to "No data"

**Comment by nkittur-uga** [comment]
SCORE S. mansoni CRT and SCORE Mozambique have both been updated so that valueMap for "Sex" variable says "Unknown" instead of "No data".
