### ISSUE TITLE
Visualization: a custom legend bug for Scatter faceted plot

### ISSUE THREAD

**Issue by moontrip** [VEuPathDB/web-eda#741]
While thinking and checking of a potential scatter plot R-square table with a couple of example cases, I found that there was a bug for for some cases of faceted plots. 

For an example like below with the plot options of Best fit with raw (or Smoothed mean with raw), the custom legend shows 5 Raw and 3 Best fit, however, it should show 5 Best fit legend items. 

![scatter-facet-bug](https://user-images.githubusercontent.com/12802305/142668926-079faa21-bab6-4876-8641-365d3186b186.png)

**Comment by bobular** [comment]
Hi @moontrip - I was going to say are you sure this is a bug?  Maybe the other best fit lines aren't shown because there isn't enough data to calculate them, but there is, and you mentioned that also in the PR (the back end response contains all five best fit line reponses).

Good catch!

**Comment by moontrip** [comment]
@bobular yes initially I was suspected the case you mentioned, but for the example case, I could see that the backend response contained all five best fit data, distributed in countries though :)

**Comment by sweverschulman** [comment]
The bug has been corrected and only showing either best fit or smooth mea
<img width="1096" alt="Screen Shot 2021-11-22 at 1 25 36 PM" src="https://user-images.githubusercontent.com/62298921/142916559-9e8cafdd-e9ee-4b15-a7c8-ed6764c57a9b.png">
n
<img width="1043" alt="Screen Shot 2021-11-22 at 1 25 56 PM" src="https://user-images.githubusercontent.com/62298921/142916566-95e9b33c-c798-47d5-b33c-b8ee70240cea.png">
