### ISSUE TITLE
Mockups: variable collections

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#757]
Variable collections were discussed in the 12/3/2021 EDA UX meeting. See notes here: https://docs.google.com/document/d/1d9m6en4MagA9h0KIOI0_6Ekq7MVaq_-s5puNFm-oJBI/edit#heading=h.3xrvmfechrcu

Mockups are needed, especially around the following considerations:

- it seems difficult to clearly support both the case where the user wants to choose the whole collection and the case where the user cherry-picks children that way. For ex: for the 'z-score' collection, we’d have to make the individual z scores available under the 'z-score' entry in the Variable Collections heading, and have the children behave as a multipick in that context. which would mean they’d be seen in two different places with two different behaviors in the same variable picker?

- Maybe the UI for selecting a subset of the collection can be done in a secondary prompt, once the collection is selected. it could even be done such that it appears right below the collection name. For ex, if a collection visualization can only support 10 variables but there are >10 variables that are a part of that collection (as is the case with TAC Ct values in MAL-ED), how does the user choose which 10 to include in the visualization?

- What if the user just wants to visualize a single Z-score in a box plot? Would picking a single variable out of a collection be the right approach? Or can this be addressed with variable constraints?

- How will the user know that they can select a collection? We can just use an icon (with a tooltip) for collections (only in the vizs) to indicate they can be selected, but that doesn't improve upon selecting a subset of that collection

- How would collections work for faceting or overlays?

**Comment by asizemore** [comment]
Most recent figma mockups in channel. Currently hoping to use only the carrot to select expanding tree, so that we can use clicking on a variable name to close the box.

**Comment by danicahelb** [comment]
Figma mockups: https://www.figma.com/file/hWGoRD0elEQGUU3OgpXqcX/collections-web-eda-%23757?node-id=220%3A1357

**Comment by asizemore** [comment]
No revisions from most recent mockup version. Closing issue.

**Comment by asizemore** [comment]
Nothing for outreach to review. Nothing to deploy
