### ISSUE TITLE
Add new Downloads Tab

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#758]
See mockups in Figma: https://www.figma.com/file/pTcKhGnfWpgckYkAk8lLWH/UX-Meeting-Presentation?node-id=227%3A1252

very old (& out of date) google slides mockups:
https://docs.google.com/presentation/d/1F4bb2P2vHQ-AOhAwQ4vm52_KQQHY1F5Zg_E9rrElEwk/edit#slide=id.gf9c8ddc3a5_0_60

**Comment by eikonomega** [comment]
Plan of Attack (after conversation with Dave)
- For the start, we will assume that the user has the necessary data access permissions and login requirements. We'll come back to that at the end.
- We don't current know what should belong to the "README" or "Ontology Metadata" download buttons.
- We can't do anything with "Entire dataset" at the moment - waiting for backend development.
- Derived variables has not yet been developed... 
- Not sure who we would get the data for Study Documents. Need to follow-up on this.

SO for the moment, just working on allowing the user to bring up the "download modal" for each entity listed in the downloads tab area. Will address other items as we receive more info and/or backend pieces are completed. 

FYI @danicahelb @dmfalke 

Thanks!

**Comment by dmfalke** [comment]
@danicahelb could you provide some details on where to find the **README** and **Ontology Metadata** files? If these are offered on the production website and you point me to which pages they are offered on, I can probably figure out the rest. Thanks!

**Comment by eikonomega** [comment]
Currently awaiting feedback from working group. Meeting to be held later this week.

**Comment by danicahelb** [comment]
@dmfalke if you click on the "download" link on any of the study cards, you will be able to access the README and Ontology metadata files. I can check in with Jay if you need more info

**Comment by danicahelb** [comment]
In the 1/24/2022 EDA UX meeting we decided that the downloads tab would be rolled out in stages. For b56, we will release a stripped down version of the downloads tab:

- We will not include the “ClinEpiDB Documents” or “Study Documents” sections. Study documents will still be available via the View Study Details tab. ClinEpi documents (README and Ontology metadata files) and any study documents requiring access restrictions will be placed under “Full dataset” for the latest release version. ClinEpi Outreach is already placing these files (README, Ontology Metadata, and any study documents that require data access restrictions) in the downloadSite directory. Ryan’s service will pull all files that are in the downloadSite directory for a specific study and release, and Mike will display these files in the Full Dataset table.

- We will only include a table for the latest version of the Full Dataset. Previous versions of the dataset will remain accessible in the Data Versions table on the study details page

- The Full Dataset tables will display the filenames rather than the count + entity name, and will be ordered alphabetically rather than based on the entity diagram. Jay will rename the files to include a shortened version of the study name, the release date, and entity type (https://redmine.apidb.org/issues/47001)

- All files on the downloads tab will be protected via regular study access (full result level access), even those available separately on the view study details tab

**Comment by danicahelb** [comment]
@dmfalke indicated that this ticket should also change the column headers on the table that's created from title case to use the original case that comes from the owl file (for instance, "Observation type" and "Sub-county in Uganda" for the PRISM study)

**Comment by danicahelb** [comment]
Text in the full dataset tables has the wrong font and the text is too small

 
<img width="753" alt="image" src="https://user-images.githubusercontent.com/25450900/155625063-31af2501-af9e-4cca-92db-92c2cb6dd81a.png">

**Comment by danicahelb** [comment]
For previous versions of the dataset, please change "Changelog" to "Change Log"
<img width="254" alt="image" src="https://user-images.githubusercontent.com/25450900/155625875-2700e1bd-3fd3-473b-89cb-979729fa0277.png">

**Comment by danicahelb** [comment]
Please change subtitle under "My Subset" to

`Configure and download one or more tabular files of the filtered dataset.`

<img width="298" alt="image" src="https://user-images.githubusercontent.com/25450900/155626820-7cc99bce-1457-443b-9934-3a37b51ba511.png">

**Comment by danicahelb** [comment]
How are files under "Full dataset" being ordered? Alphabetically would be best...
<img width="573" alt="image" src="https://user-images.githubusercontent.com/25450900/155627308-bcaa8eac-d27c-45d4-b00d-997cbe2e7ae4.png">

**Comment by danicahelb** [comment]
If it is easy, can you italicize the analysis name in the subsetting modals so it matches the way it looks on the main analysis page? I feel like the analysis name is not standing out on the subsetting modal and italics would help. (perhaps the italics is being used to indicate that the text is editable on the main analysis page? but the pencil icon indicates this & lack of pencil indicates i can't edit the analysis name on the subsetting modal.)

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/25450900/155628186-9dd293df-305e-4e34-9e6d-a116a1a0d418.png">

<img width="988" alt="image" src="https://user-images.githubusercontent.com/25450900/155628213-eb5086a0-34cb-4a58-a026-11c122066232.png">

**Comment by bobular** [comment]
I'll do the italicisation thing...

**Comment by dmfalke** [comment]
@bobular sounds like this can be closed again?

**Comment by bobular** [comment]
If #904 is approved and merged and QA'ed, yes. @dmfalke

**Comment by danicahelb** [comment]
thanks!
