### ISSUE TITLE
Basic stats numbers are missing from HistogramFilter and wrong for Categorical Table/barplot

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#76]
In the screenshot from the live site, we're looking at Observation -> Sample -> Stool characteristics -> Stool nature

![image](https://user-images.githubusercontent.com/308639/116990697-605d5500-accb-11eb-8afd-f56f420049c2.png)

Note the 60,958 number.

In the current EDA, this number is wrongly showing 22,567 - which is the number of participants.

![image](https://user-images.githubusercontent.com/308639/116990844-97cc0180-accb-11eb-8e72-18d600d67d03.png)

It seems that 60,858 = EUPATH_0000738 "information of process" 45107 +  EUPATH_0000310 "information on observation details" 15851 (numbers come from `count` requests)

In the new EDA I guess the number we should be using comes from the `count` backend requests (used to shade the Entity Diagram).

Then we need to display the same information for the Histogram Filter

**Comment by dmfalke** [comment]
I can confirm that the number shown in the screenshot is the same that we get from the backend.

**Comment by bobular** [comment]
Seems to be a back end issue (incompleteCases is not correct) or we need to sum the values on the client side.
