### ISSUE TITLE
Facets need to expand past only 7

### ISSUE THREAD

**Issue by sweverschulman** [VEuPathDB/web-eda#763]
One of the main use cases for faceting is exploring variables over treatment allocations of a study. Therefore if there are more than 7 values for the treatment allocation, we will not be able to facet for this major use case.

**Comment by danicahelb** [comment]
would allowing stratification vars to have >8 values & aggregating be enough to fix this?
https://github.com/VEuPathDB/EdaDataService/issues/152

Revisit after implementing this feature

**Comment by asizemore** [comment]
@danicahelb i dont think that will fix the issue for Steph. If there are say 15 treatment allocations, then a user could see 7 of them but the other 8 will all be combined into one panel. I would guess that aggregation of 8 treatment allocations into 1 panel isn't ideal? 
Would be addressed by improved faceting features such as pagination or sticky axes

**Comment by danicahelb** [comment]
Discussed in 7/25 EDA UX meeting

- Change the parameter constraints so the user can select ANY categorical variable, regardless of the total number of unique values it has
- Show a warning message whenever a user has selected a variable with enough values that performance is slowed (we still need to determine the number of values that are needed to cause performance issues)
- Along with allowing more values for faceted variables, also implement wrapping of the faceted plots (It is currently very difficult to compare facets when the faceted plots cannot be shown on the same screen)

**Comment by danicahelb** [comment]
A placeholder ticket has been made with some ideas for improved faceting features: https://github.com/VEuPathDB/EdaNewIssues/issues/395

**Comment by asizemore** [comment]
@danicahelb to clarify, wrapping and increasing the number of facets should come out together, correct? I ask because they're two different fixes so it's possible we do one without the other.

**Comment by danicahelb** [comment]
I moved "Along with allowing more values for faceted variables, also implement wrapping of the faceted plots (It is currently very difficult to compare facets when the faceted plots cannot be shown on the same screen)" to a new ticket https://github.com/VEuPathDB/EdaNewIssues/issues/434

these fixes don't have to come out at the same time

**Comment by danicahelb** [comment]
this should be handled by faceting 2.0
