### ISSUE TITLE
Legend styling: Remove checkbox blue color

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#765]
With the goal of keeping as few colors on the page as possible, consider using only gray for the custom legend checkboxes. Two possibilities below:

<img width="481" alt="Screen Shot 2021-11-17 at 12 04 09 PM" src="https://user-images.githubusercontent.com/11710234/142247330-b36e5665-3c7b-477b-80d6-4e0ee6787d78.png">

My personal favorite is Proposal 1 because it's clear without competing with other elements on the page.

**Comment by sweverschulman** [comment]
Legend checkbox has been changed to green and confirmed.
<img width="1108" alt="Screen Shot 2022-01-20 at 1 15 16 PM" src="https://user-images.githubusercontent.com/62298921/150397819-f1fd781a-7b6a-43c1-9f04-1e58cf61097a.png">
<img width="805" alt="Screen Shot 2022-01-20 at 1 07 28 PM" src="https://user-images.githubusercontent.com/62298921/150397824-33661f3c-887b-463e-a65d-276aa2e84230.png">

<img width="850" alt="Screen Shot 2022-01-20 at 1 05 55 PM" src="https://user-images.githubusercontent.com/62298921/150397833-b4bb45f9-e290-4b8f-b573-ef15956b92d3.png">
