### ISSUE TITLE
Reload of GEMS1 subsetting page with no active filters causes 54 calls to `count` service endpoint

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#766]
Six times ought to be enough (there are six entities in the ED)

Possibly a duplicate of https://github.com/VEuPathDB/web-eda/issues/72 but I think things may have escalated since then!

**Comment by bobular** [comment]
Retested and it's 25 now.  Strange number.  You'd think it would be a multiple of 6.  I will investigate a bit more.

**Comment by bobular** [comment]
Well I looked into it and I found one solution and at least two puzzles

1. inside `useEntityCounts`, when there are no filters, `filters` is either `undefined` or `[]` - this creates different results from the `JSON.stringify` and affects the dependencies on the `counter` increment useEffect.  Solution: make sure it always defaults to an empty array.
2. the `counter` increment useEffect is problematic. Minimally (with no filters in play) there are `counter` values `0` and `1`.  Somehow we need to avoid the zero scenario.  Either with something like `if (counter===0) return undefined;` inside the useCallback (which requires some downstream work) or some other hook magic to make `counter` only ever assume one value in the case of no filters.
3. Somehow all the back end calls are STILL being sent twice on top of all the above.
4. All the above was diagnosed with the debouncing disabled (you could imagine leading/trailing edge causing duplicates, but that is not the issue for 3.)

I will sleep on it but would appreciate some input.

**Comment by bobular** [comment]
Something along the lines of `useFirstRender` in  https://stackoverflow.com/questions/53253940/make-react-useeffect-hook-not-run-on-initial-render ?

Or should I be taking away/simplifying rather than adding more complexity?

**Comment by bobular** [comment]
If not familiar with browser dev tools, then QAing this should just involve testing the subsetting and entity diagram counts carefully.  Check that after changing filters (categorical and continuous) the ED counts update accurately (there will be a 2 second delay at least so you can click multiple checkboxes without causing back end requests for each click)

**Comment by SheenaTomko** [comment]
This looks good
