### ISSUE TITLE
Homepage header updates for b56

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/web-eda#769]
The following updates are to be made to the header section of the homepage of beta.clinepidb.org. These are to be done in time for b56.

1. Shorten the dark blue portion in the header
2. Remove the “Welcome to ClinEpiDB” text in the header
3. Remove the release # and date text under ClinEpiDB logo
4. Replace the tagline with a new one: “Share, explore, and visualize clinical and epidemiological data”
5. Change placement of tagline and drop down menus according to mock-ups on slide 7 of this doc:
https://docs.google.com/presentation/d/10DBhyRYbd3q6LEYZtiungGSVJ1nncir6llsTzLPyeH0/edit#slide=id.p

**Comment by aurreco-uga** [comment]
This is done, this is all we can do without an overhaul of the header.
the overhaul (dom and cs) with deploy flat elements in a grid, like  we have in genomic sites, which allows for more flexible and maintainable layouts.

**Comment by danicahelb** [comment]
Feedback from Steve: please change "ClinepiDB 21" to "ClinepiDB - Release 21" or similar

**Comment by nkittur-uga** [comment]
Updates look good.
