### ISSUE TITLE
Map visualization: Implement basic semantic zooming entity count markers

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#775]
Following from #774 

- [x] based on the current* viewport bounds create an additional filter to add to the `map-markers` request - this will be something like latitude within lat_south, lat_north, and similar for longitude which has special handling of longitudes straddling the 180 degree line, so we should not need to do anything special on the client side.
- [x] from the current Leaflet zoom level, figure out the geohash variable to send to the backend
      - this is likely to require an application-wide lookup table, as we did in the old map.  We can assume that the geohash variable Ids are the same in all studies (but their entity Ids may change):
      - geohash 1 = EUPATH_0043203
      - geohash 2 = EUPATH_0043204
      - geohash 3 = EUPATH_0043205
      - geohash 4 = EUPATH_0043206
      - geohash 5 = EUPATH_0043207
      - geohash 6 = EUPATH_0043208     
- [x] remember the current viewport center and Leaflet zoom level in `vizConfig` user analysis saved state.

\* we may need to add a new study attribute to provide default lat/long center and zoom level for the initial viewport.  Alternatively we can implement auto-fly-to after the initial whole-world map has loaded. For now just hardcode something if there is no current viewport.

**Comment by bobular** [comment]
Oops, all this got done in #782 - I forgot to link it to this issue. Sorry for any confusion.

**Comment by nkittur-uga** [comment]
Basic semantic zooming entity count markers are working as expected.
