### ISSUE TITLE
More back end requests (`distribution` and `users/.../analyses`) need debouncing to pre-empt performance problems/back end stability with heavy use

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#787]
While testing that the `count` requests are being properly debounced when a user clicks on lots of categorical filter checkboxes, I noticed a bottleneck with other requests, namely `distribution` and `/eda-user-service/users/nnnn/analyses/xxxxx` 

The problem is so bad that if you click about 10-20 times in filter checkboxes, you can wait a minute or more before all requests are processed.

**Comment by bobular** [comment]
This didn't make it to the new board.

If I do 5 rapid clicks on this subsetting table (as if I was selecting 5 countries, for example)
![image](https://user-images.githubusercontent.com/308639/174493715-9bc6df7a-5b58-473f-9804-77f1227f25dc.png)

The client makes 5 `distribution` requests:
![image](https://user-images.githubusercontent.com/308639/174493796-944b85ce-85df-4161-9584-389d237cf9d4.png)
and 7 user database updates:  (e.g. to /eda-user-service/users/578013513/analyses/ClinEpiDB/aKEdcNb)
![image](https://user-images.githubusercontent.com/308639/174493830-45ed4296-9aa0-4b2d-a818-e0b77240f44a.png)

Note the long times for the user analyses requests. These are performed in the background, and don't really affect the user (unless they close a tab and lose their latest work), but the load on the server cannot be good news.

I have also seen a massive backlog of the user analyses requests while navigating around the map viz.

The cost to "debounce" these requests is probably low, unless it opens a can of worms

**Comment by dmfalke** [comment]
This issue doesn't have a UX component to it, so I'm going to move it to **Complete**
