### ISSUE TITLE
Map: gray out the map viz tool in visualizations when the study has no geolocation variables

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#796]
Not sure how to do this yet!

We may have a better idea after #776

**Comment by bobular** [comment]
One way to do this would be to run the existing constraints logic on all the visualizations returned from the `apps` endpoint.  If any of the `isRequired` variables end up with no available variables.

Possible problem is that the code (see InputVariables.tsx) seems to focus on determining disabled variables (rather than returning a list of enabled variables, which might be easier to test for length>1)

This is reasonably expensive, right?  So we would want to do it once per session?

**Comment by nkittur-uga** [comment]
Yes, Geolocation map is greyed out with a note saying (Not applicable to this study) in studies which lack GPS data, such as GEMS1 and GAMIN.
