### ISSUE TITLE
Visualizations: allow zooming & truncation for line plot

### ISSUE THREAD

**Issue by moontrip** [VEuPathDB/web-eda#813]
This ticket is an extension of the pre-existing ticket, Visualizations: [allow zooming & truncation](https://github.com/VEuPathDB/web-eda/issues/573), but this focuses on the line plot only.

Danica explained the expected behavior of axis range control for line plot [here](https://github.com/VEuPathDB/web-eda/issues/573#issuecomment-1017639378) and copied in the following:

Histograms will have semantic zooming. The x-axis for these plots are binned; zooming in on the x-axis changes the bins and y-axis counts and axis ranges should update accordingly.

Line plots also have binned x-axis but we do NOT want semantic zooming on these plots. The positions of the line markers should NOT change as the user zooms in.

**Comment by moontrip** [comment]
This was addressed at https://github.com/VEuPathDB/web-eda/pull/1007 Feedbacks from the UX mtg will be addressed in the other tickets

**Comment by nkittur-uga** [comment]
Tested that line plots have binned x-axis but positions of the line markers does not change as binning is changed. QA is complete.
