### ISSUE TITLE
Bug: inconsistency in what variable is open by default in subsetting tab

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#814]
When you first open a study, sometimes the 1st variable in the variable tree is open by default, and other times the 1st variable in the list of featured variables is open by default.

For Example: 

- Amazonia ICEMR Brazil Cohort (Country is open by default and is not a featured variable but is the 1st variable in the tree)
- ELICIT Randomized Controlled Trial (Ward in Tanzania is open by default and is the 1st variable in the featured vars list but the 3rd variable in the tree)

We should pick one option or the other and be consistent.

**Comment by chowington** [comment]
IMO the first featured variable being the default makes more sense, because presumably it's generally more widely used than the first variable in the tree

**Comment by danicahelb** [comment]
@chowington I agree, lets make 1st featured variable open by default. In rare cases where a study doesn't have any featured variables, please make the 1st variable in the tree open by default. thanks!
