### ISSUE TITLE
Use new showUnreleasedData flag (instead of projectId) to determine which studies are shown

### ISSUE THREAD

**Issue by ryanrdoherty** [VEuPathDB/web-eda#822]
We need to get rid of the AllClinEpiDB project ID for advanced subsetting, merging it into ClinEpiDB.  To that end, a new boolean property has been added to the project service response called "showUnreleasedData", which is set to true on previously AllClinEpiDB sites, and false on regular ClinEpiDB sites (i.e. hide is the default).  The current belief is that this is the only use for the AllClinEpiDB project ID (model XML include/excludes appear to be unused).  This ticket is to address the client-side use of AllClinEpiDB, replacing logic with checks of "showUnreleasedData".  Note the difference in responses of:

https://qa.clinepidb.org/ce.b19/service
vs
https://qa.restricted.clinepidb.org/ce.restricted.qa/service

**Comment by dmfalke** [comment]
The client currently uses the `projectAvailability` record attribute to determine if a study should be "disabled": if the current website project is not included in the attribute, then the study is marked as disabled. This attribute is set based on the value of the `isPublic` presenter prop. When the prop's value is `true`, then "ClinEpiDB" is included in the attribute. "AllClinEpiDB" is always included.

To allow the client to continue to mark studies as "disabled", we can add a new dataset record attribute called `isPublic`, which will be based on the value of the similarly named presenter prop. If the `showUnreleasedData` flag is set to false, then the client can mark studies with `isPublic = false` as "disabled".
