### ISSUE TITLE
Visualizations frontend: Line plot viz tool (continuous y-vars only)

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#825]
We need a working line plot viz tool for b56.

Mockups can be found here: https://docs.google.com/presentation/d/16xCzGUs744KD3IQ91ITMt30pbAF9SJ7yvOkWZoE-AeE/edit#slide=id.p

- _Note that the deliverable for b56 only includes "General Line Plots" in the mockups (ignore "Frequency line plots", "Cumulative frequency plots", and "Kaplan Meier plots" for now)_
- _Note also that categorical y axis variables are NOT included in this current ticket_ - see #956 for that

NOTES FOR TESTING/DEMO-ING

* Do not use medians and error bars at the same time, or things will look a bit funny. Known back end issue.
* Mouse-overs are all on one line. Splitting into a nicer layout may/may not be possible. Future ticket?
* When switching off binning for date x-variables, actually a bin width of "1 day" is sent to the back end. This avoids a 500 error. Was this what we intended anyway, @d-callan?
* Y-axis starting at zero or not?  Not sure yet. Wasn't in the mock-ups. Comments please!

**Comment by danicahelb** [comment]
Hi @bobular, I took a look with LLINEUP and found some issues:

1. the y-axis range is currently being set by the range of raw data values and not by the range of the mean (or median, etc selected by the user). outliers in the raw data are making the plots virtually useless for most selections.
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/25450900/159811058-0dd5c07a-5225-436b-ade4-7db33240018c.png">

2. Date binning is really weird! I don't understand what is going on. I set the bin width to 30 thinking this would be 30 days (~1 month), but the date ranged from 2017-03-06 to 2017-10-02! Can you implement the nice binning you have for other visualizations where dates can be binned by week, month, year, etc?
<img width="800" alt="image" src="https://user-images.githubusercontent.com/25450900/159811310-e484578d-8a15-497c-8935-e086bcd726c9.png">

3. Ordinal variables like study timepoint cannot be selected for the x-axis. I added a note in: https://github.com/VEuPathDB/web-eda/issues/963

4.In the mouseover, the y:XXX and N:XXX looked to me at first glance of counts of yes and no! I do think putting the information on 3 separate lines would help, but can we also explicitly write "x-axis:XXX, y-axis:XXX, N: XXX" (note this also includes a comma between each item)

5. We need to implement marginal plots sooner rather than later! Counts in the mouseover are helpful but the plots are still really prone to misinterpretation! In a line plot of "Plasmodium asexual stages, by microscopy result" vs "Female non-anophiline count" with bin width of 10 has >6000 data points on the left of the plot and 1-2 data points on the right side of the plot! the counts in the mouseover are too subtle

6. y-axis should start at zero; the way you have it now is perfect

**Comment by d-callan** [comment]
so the yaxis comments.. currently what were doing is setting the range in a similar way to scatter, which is based on annotated ranges, or when those arent available the range of the data. it seems worth knowing, to me, that the mean of some value typically sits very low in the range of the data for ex. also this ensures that any time the user puts the same var on the yaxis in the line plot they start by seeing the same range by default. a user can always zoom if they like.
as for starting at 0, i think thats true for counts and proportions. but if a user puts a zscore on the yaxis then 0 has a very different meaning than it would for something like counts or proportions, since its not really a baseline to compare positive values against in that case.

**Comment by bobular** [comment]
@danicahelb how would you feel if we don't change the y axis scaling behaviour right now, and (y and probably x when continuous) axis zoom controls were added for b57?  Seems like we need at least a discussion with an odd-number of people ;-)

**Comment by danicahelb** [comment]
Discussed in 4/4/2022 EDA UX meeting. 

- [ ] Error bars should be “on” as the default; user can choose to toggle them “off”

- [ ] For mean & medians, the y-axis range should always include the origin

- [ ] For mean & medians, the absolute value of the maximum for the y-axis range should be scaled to the calculated mean or median values (plus error bars) instead of to the inferred or annotated range of the raw values

**Comment by danicahelb** [comment]
I'm loving the date binning on line plots! I can see trends in seasonality, but also I can see that parasite prevalence is going down over time! This is so beautiful!!! 

<img width="673" alt="image" src="https://user-images.githubusercontent.com/25450900/163237767-94fe8443-acb3-4d8c-a382-ec246504d4da.png">

<img width="645" alt="image" src="https://user-images.githubusercontent.com/25450900/163237838-8fce0b09-9ed9-4fbe-9bbc-e52f96fffc60.png">
