### ISSUE TITLE
Downloads: Use a "form" method for downloading subsets

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#832]
The current method imposes limitations on file size, which varies by browser and environment (current memory usage, etc). In order to remove this limitation, we should use a "form" method to download files. We have some examples of this in WDK. This requires some backend work that @ryanrdoherty is working on.

**Comment by dmfalke** [comment]
From @ryanrdoherty 
> The subsetting service tabular endpoint now supports "Content-Type: application/x-www-form-urlencoded".  A submitted form should contain a parameter named "data", whose value is the stringified JSON normally sent as the entire request body in an "application/json" request.  The response to this sort of request will be identical to that of a "application/json" response with the same config, but a "Content-Disposition" header will be added with value (as requested):
> ```
> attachment;` filename="{studyId}_{entityDisplay}_subsettedData.txt"
> ```

**Comment by danicahelb** [comment]
@dmfalke how do I qa this ticket?

**Comment by dmfalke** [comment]
I can confirm that this is in place. I will move it to the Completed board.
