### ISSUE TITLE
Visualizations: Positioning of faceted plot panels

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-eda#833]
When I facet by any variable the resulting panels seem to be positioned in a way that they are all equidistant from each other while consuming whatever horizontal space is available to them. I think the panels should be as near to each other as reasonably possible starting from the left of the page, to facilitate easier comparison across them. My hope is that would also make their positions more consistent when toggling the no data panels on/ off.

**Comment by d-callan** [comment]
wonder if @bobular has thoughts on this or can indicate how much effort it might be

**Comment by jernestmyers** [comment]
@moontrip [This is the PR](https://github.com/VEuPathDB/web-components/pull/372) we discussed in today's EDA that I believe addresses this issue.

**Comment by moontrip** [comment]
Thanks @jernestmyers for your information. I will check/test and close this ticket if it works 👍

**Comment by moontrip** [comment]
I have tested and confirmed that this seemed to be addressed before, so closed

**Comment by danicahelb** [comment]
looks good!
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/25450900/189185569-18ff7c76-b4c4-4a3a-a38d-b1e08e2bb005.png">
