### ISSUE TITLE
"SwissArmyButton" component title mouseover popups block page even when not visible

### ISSUE THREAD

**Issue by chowington** [VEuPathDB/web-eda#850]
For instance, the grey box that says "View all your analyses of this study" covers the blue icon buttons underneath, not only when the box is visible, but when it's not, leading to the buttons being unusable. In this case it will only happen if the analysis name is long, but other places where these sorts of popup titles are used may suffer the same effect.

![image](https://user-images.githubusercontent.com/12377649/146051025-884c459a-9f2f-4556-9187-d7d2c07b8db1.png)

**Comment by chowington** [comment]
This seems to have been fixed. Closing ticket

**Comment by danicahelb** [comment]
Hey Connor! Could you please update the text to `View all of your analyses for this study`

<img width="162" alt="image" src="https://user-images.githubusercontent.com/25450900/155628745-2b2f0f95-c852-4ad4-ba03-d5f2dd261082.png">

**Comment by dmfalke** [comment]
I can take care of this

**Comment by danicahelb** [comment]
thanks!

**Comment by chowington** [comment]
Thanks Dave!
