### ISSUE TITLE
Non-integer (less than 1) binWidths cause `distributions` back end to time out/fail

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#871]
Tested with LLINEUP

"Persons" variables (e.g. Persons <5 years living in house) - only integer binwidths work - non-integers cause a proxy error (and cause performance problems for subsequent queries if you send too many of these).

Solution: disallow client from requesting non-integer binWidths for integer variables.

May require some slider component work to enforce integer values from both slider and text box.

**Comment by sweverschulman** [comment]
reduced the bin of a few studies and now seemed to stall.
