### ISSUE TITLE
Browse and subset tab: Remove extra x-axis values on histogram when very few values available; and erroneous red outlining of binwidth input

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#872]
Danielle made changes to the use of datashape, so now numeric and date variables that have <10 values are shown using a histogram in the browse and subset tab. This works well until you get down to very few values that are clustered together. In cases like the one below (study = PROMOTE, variable = Placenta count), where there are just 2-4 potential values, you see extra values on the x-axis indicating 0.5, 1.5, etc. that make it look like there are might be more bars there, for instance 2 bars of equal height at 1 and at 1.5. In cases like this, we'd like to reduce the number of values shown on the x-axis to avoid this issue.

<img width="946" alt="Screen Shot 2022-02-09 at 12 46 51 PM" src="https://user-images.githubusercontent.com/54597319/153268997-e1e84ec4-8f6a-48ce-a770-6a7b626c36be.png">

Note for QA testers. I @bobular have combined another minor bugfix along with the original bug. It is described here: https://github.com/VEuPathDB/web-eda/issues/1274#issuecomment-1265309212

> I'm also noticing that the bin width slider box turns red (but with no other warning) when the bin width is set to either of the extremes of the allowed range.

(note that this happens with text input - slider input is subtly different, but also buggy)

![image](https://user-images.githubusercontent.com/308639/201443030-4b6c429c-d308-45c6-9106-3db54b76f7ed.png)

**Comment by danicahelb** [comment]
Also, things get weird when trying to select data. In this MALED example, I am trying to select everyone who has data for "Total deworming treatments". The blue selector stops at 3 on the x-axis (3 is the largest value in the dataset) but participants with 3 deworming treatments are actually represented in the bar spanning [3-4). Given the current behavior, I'm not sure if i correctly selected my population or not!

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/25450900/155021929-a605661b-1199-41e0-a965-6c59cd715ec7.png">

**Comment by danicahelb** [comment]
may be related to https://github.com/VEuPathDB/EdaNewIssues/issues/241

**Comment by bobular** [comment]
> Also, things get weird when trying to select data. In this MALED example, I am trying to select everyone who has data for "Total deworming treatments". The blue selector stops at 3 on the x-axis (3 is the largest value in the dataset) but participants with 3 deworming treatments are actually represented in the bar spanning [3-4). Given the current behavior, I'm not sure if i correctly selected my population or not!

This has been fixed for a while (just tested main branch on my dev site), thanks to @jernestmyers

**Comment by bobular** [comment]
Presumably we would like these non-integer axis ticks eliminated from the visualization too? @danicahelb 

![image](https://user-images.githubusercontent.com/308639/197227173-b56aed52-2979-4da2-8b0b-377789a86b7f.png)

**Comment by bobular** [comment]
Note to self: a possible simple solution to this is to set plotly prop `xaxis.nticks` to the number of bins. Will need extensive testing of course, but this would avoid having to pass extra props into the plot component about the type of value (e.g. integer or not)

**Comment by bobular** [comment]
The new solution involves a threshold, currently set at 4 bins. If there are N <=4 bins, then we make sure there are not more than (N+1) tick labels on the x axis.

The idea is that when there are more than this number of bins, we can visually determine the bin width from the plot, and the axis ticks are less likely to be misleading.

We may need to adjust the threshold after testing.

**Comment by SheenaTomko** [comment]
Looks great!
