### ISSUE TITLE
Downloads: Make subset modal scrollbars always visible

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#877]
Taken from #656:

When the subsetting results table is large enough that the user needs to scroll down to see the bottom of the table, the left/right scroll bar is cut off from view. Please make this scroll bar always visible (like up/down scroll, which is always visible regardless of what part of the table you are looking at)

**Comment by eikonomega** [comment]
This issue has been addressed in the Download Tab PR. 😄

**Comment by sweverschulman** [comment]
ClinEpi outreach team has review the functionality of the scroll bars and have determined that it meets our initial request.
