### ISSUE TITLE
All plots: Better loading indicator

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#88]
The current loading indicator that is used is small and inconspicuous. We probably want to use something that overlays the plot area.

**Comment by bobular** [comment]
Best done after #104

**Comment by bobular** [comment]
Here's what MUI has

https://material-ui.com/components/progress/

But we should be aware of what React's `<Suspense>` does (for lazy-loaded components only, at the moment, AFAIK)

**Comment by moontrip** [comment]
Examined and tested this a bit. Perhaps not a complete solution but it works in some degree. Hope this would be helpful for one who would work for this issue. Please note that below was only tested for viz and there may be a side effect by changing `Promise.tsx` (see below), e.g., `Subsetting`, though I didn't notice much difference at the `Subsetting`.


At `src/lib/core/components/Promise.tsx` (loading icon around top middle area):
change from
`{state.pending && <Loading />}`
to
`{state.pending}`


At a viz component, e.g., `src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx`
(another small loading icon around top left area):

First, import circular progress icon (assumed to use it among others)
`import CircularProgress from '@material-ui/core/CircularProgress';`

then, change from
```
     {data.pending && (
        <Loading style={{ position: 'absolute', top: '-1.5em' }} radius={2} />
      )}
```
to
```
      {data.pending && fullscreen && (
        <CircularProgress color={'secondary'} size={50} thickness={5} style={{ position: 'absolute', marginLeft: '420px', marginTop: '350px', zIndex: 10 }} />
      )}
```

- This will show a red circling progress icon. Certainly size/thickness and pixel (or percent [%]) values can be adjusted per viz.


There still exists unnoticeable small text of `Loading...` at the top left of plot area, but it seems that it comes from `node_modules` library (e.g., wdk-client, etc.). Also, I didn't think of thumbnail/grid view much as it shows `Loading...` message in the center.

As an example, a screenshot for the case of scatterplot viz is attached in the following:

![progressbar2](https://user-images.githubusercontent.com/12802305/120577798-ce905700-c3f2-11eb-8274-9dd1dc41f724.png)

**Comment by dmfalke** [comment]
Thanks for doing this research, @moontrip. I was thinking we might want to do something in https://github.com/VEuPathDB/web-components so that we can have a consistent loading indicator anywhere we use plots.

The `PromiseResult` component is only used in one place, currently, so I'm okay with making changes. I think the entire line can be removed:

```diff
-       {state.pending && <Loading />}
```

**Comment by moontrip** [comment]
@dmfalke thank you for sharing your thoughts. I think that you want to use React `<Suspense>`. One of my curiosity showing small text of "Loading..." at top left of plot area might be coming from `PlotlyPlot` component's `<Suspense>` .

**Comment by dmfalke** [comment]
`<Suspense>` only works for loading components, presently. I think we should use a similar loading indicator there, that we show above. We can use the provided [`height` and `width` props](https://github.com/VEuPathDB/web-components/blob/main/src/plots/PlotlyPlot.tsx#L21-L22) to determine the placement of the loading indicator.

**Comment by chowington** [comment]
Linked the appropriate PR in web-components 👍
