### ISSUE TITLE
upgrade map to use react-leaflet v3

### ISSUE THREAD

**Issue by moontrip** [VEuPathDB/web-eda#881]
Currently, map heavily relies on react-leaflet v2, but the library has a major upgrade to v3 since last year, restructured with functional components, hooks, etc. Thus, it is better to adopt it at this stage. 
However, it is expected that there would be lots of errors and conflicts in codes and libraries so it would take time.

**Comment by danicahelb** [comment]
Hi @moontrip I moved this ticket out of next cycle as we had concerns that upgrading so close to the release could cause breakages.

**Comment by moontrip** [comment]
for records, here is a main PR to address, https://github.com/VEuPathDB/web-components/pull/314

a fix PR for ref can be found at https://github.com/VEuPathDB/web-components/pull/347, which can be either merged into the above PR or main branch as it was branched out from the above PR

**Comment by danicahelb** [comment]
@moontrip @bobular is anyone actively working on this ticket? do we need to upgrade to react-leaflet v3 in the near future? If not, please un-assign DK and move the ticket to Backlog

**Comment by moontrip** [comment]
@danicahelb Yes I have been actively updating this PR whenever changes are made at web-components (especially map-related), so basically it is up to date now. That being said, I am not quite sure when we will merge it into main: we missed several releases.

**Comment by danicahelb** [comment]
OK, thanks @moontrip. let's talk about this at the developer meeting next week

**Comment by SheenaTomko** [comment]
@SAK22, you may need to ask DK or Bob if/how to qa this

**Comment by moontrip** [comment]
@SheenaTomko @SAK22 Thank you for your interests!
For a qa purpose, you can test MapViz (including full screen map) and see if they work fine 😃

**Comment by SAK22** [comment]
<img width="1265" alt="Screenshot 2023-02-28 at 15 17 13" src="https://user-images.githubusercontent.com/22981342/221896752-f4801cb5-cf09-4ac2-ba9c-b2aedc45ffa9.png">

**Comment by SheenaTomko** [comment]
@moontrip, see Sarah's comment above. Does this need a new ticket?

**Comment by moontrip** [comment]
@SAK22 @SheenaTomko Thank you for your reviews and comment. It is irrelevant to this ticket, so it is better to make a new ticket. Perhaps Geo map icon should not be shown at the Select Viz in the full screen map?

**Comment by SheenaTomko** [comment]
Sarah made a new ticket for the issue she brought up. Marking this ticket as complete!
