### ISSUE TITLE
Viz Icons: cement general line plot viz icon, knowing three more line plots are coming someday

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#884]
Previously we had a viz icon we were planning to use for the line plot. However, since we're breaking up the line plot into multiple types, we'll need to be prepared to have a different icon for each type.

Planned types:
1. General line (b56)
2. Frequency line
3. Cumulative frequency
4. Kaplan Meier survival plots

See line plot mockups for examples of each.

**Comment by danicahelb** [comment]
@asizemore we want the icon for general line plots for b57 (the one you made previously is fine for this purpose).

Frequency, cumulative frequency, and kaplan meier plots are not on the schedule for the next 3 build cycles. I'm going to remove the b57 label & move out of next cycle. 

Thanks!

**Comment by asizemore** [comment]
@danicahelb in order to be sure we aren't going to change the general line plot viz icon based on the new line plot vizs coming, we need to have some idea of how the other line plots are going to look. Basically ensuring we have a distinguishing feature for all four. 

I'll change the title to make it clear that the actual goal of this issue is to get the general line plot icon nailed down, but i just want to highlight we'll need some idea of how to depict the other 3 line plots before we can be sure of the first one.

**Comment by danicahelb** [comment]
reviewed icons with ann and we are in good shape!
