### ISSUE TITLE
Visualisations: Faceted Scatterplot causes `users/.../analyses` saved analysis update to return a 500 

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#886]
I'm guessing this is something to do with the size of the thumbnail data.

To reproduce (only reproducible on my dev instance, not through beta.clinepidb.org - possibly due to the involvement of the proxy, see below):

GEMS1
No subsetting
Scatterplot: weight vs mean height **best line fit with raw**
Facet on country (or even a binary variable) and you should get errors that include

```
Unhandled Rejection (Error): 500 Internal Server Error
Error occured while trying to proxy: localhost:3000/users/578013513/analyses/PuxDtIq
```

You can kill the error modal and continue (slowly) - so add a subsetting filter for just Mozambique and you should see the errors stop happening.

Actually on beta I notice that a lot of the back end requests to https://beta.clinepidb.org/eda/users/xxxxx/analyses/c1e3ac4 are taking a long time (minutes!)

**Comment by SheenaTomko** [comment]
Could not reproduce Bob's error. Looks good
