### ISSUE TITLE
Bug: error message when opening subsetting modal

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#890]
I often get this error message when I open the subsetting modal. I cannot clear the error from within the modal. if i close the modal and reopen, the message goes away

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/25450900/155400220-315da414-b70d-47b6-ad3a-d9038b8135f1.png">

**Comment by dmfalke** [comment]
It's possible this issue has resolved since #885 was merged. Please check on the QA sites tomorrow (Thursday).

**Comment by bobular** [comment]
I can't reproduce that error (which happened when switching from one entity with a few custom columns added, to another entity) in the new Downloads tab version :tada:

**Comment by sweverschulman** [comment]
I can't reproduce the error in WASH Kenya and assuming that the bug has been corrected by the above work.
