### ISSUE TITLE
Bug in visualization constraints pop up

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#897]
On macbook pro, using Google Chrome, using qa.clinepidb.org (which redirects to https://qa.clinepidb.org/ce.b19/app/, which I don't know if it's an issue that the URL says b19 rather than b21).

I clicked on the "Amazonia ICEMR Brazil Cohort", went to the Visualize tab, opened a Mosaic plot: 2x2 table, clicked on the X-axis dropdown, moused-over "Only show compatible variables", moused-over "Learn more" and took the following screenshot, then tried to click "Learn more", but the expected white box containing the visualization constraints information never appeared.

Tested with a few different studies, tried adding a subset before mousing over, tried adding a variable to the x-axis before clicking learn more, tried clicking Learn more from the drop downs of other parameters (overlay and y-axis) in other visualization types. I was able to see the pop up once, but not able to reproduce how I saw it.

![Screen Shot 2022-02-24 at 9 47 39 AM](https://user-images.githubusercontent.com/54597319/155559333-bff46203-e5c9-47a1-a389-825e5ff93d46.png)

**Comment by moontrip** [comment]
@dmfalke FYI I could confirm this as well: actually all variable tree selector at Viz had the same issue. Looked at some relevant codes but didn't notice specific issue at a glance. Thus suspected that it might be related to material-ui's issue and noticed a possibly related one via googling. 

I tried it and it seemed to resolve the issue. Add a new prop at <HtmlTooltip> in the VariableList component, `disableFocusListener={true}`

More details can be found in https://github.com/mui/material-ui/issues/30973

**Comment by dmfalke** [comment]
@moontrip thank you for looking into this. I was able to reproduce and it does seem your solution works. There are some other strange interactions going on with the variable selector pop up and the documentation modal. Fixing might be somewhat involved, so I'm wondering if we should open the documentation in a new tab for now? It's possible we can fix the modal before release. 

@SheenaTomko Thoughts on this?

**Comment by SheenaTomko** [comment]
@dmfalke I'm fine with opening the documentation in a new tab for now

**Comment by dmfalke** [comment]
Thanks, @SheenaTomko. I will make a new issue to temporarily remove the modal behavior.
