### ISSUE TITLE
bug: pre-release studies are clickable in dropdown when user is logged in

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#918]
if I am not logged in (viewing website as guest), everything with prerelease studies looks fine.
<img width="820" alt="image" src="https://user-images.githubusercontent.com/25450900/156057479-7627542f-1629-42f6-8722-bf185a9e6105.png">

However, after I log in, "coming soon" language has been removed from all pre-release studies in the drop down
<img width="816" alt="image" src="https://user-images.githubusercontent.com/25450900/156057536-ff1a0a4c-a9d9-4898-bfe7-2f16bcc9af55.png">

If I click on one of the prerelease studies in the dropdown, I get this error message:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/25450900/156057600-9d6a723e-eed8-441b-b191-2c4d5d5593f8.png">

**Comment by SheenaTomko** [comment]
It might actually be better to wait a couple weeks to work on this or qa it so we can test it with pre-release studies where some data is loaded, like PERCH or Namibia once that data is loaded

**Comment by danicahelb** [comment]
paused until PERCH or Namibia is loaded

**Comment by danicahelb** [comment]
from @dmfalke, via slack: _We had discussed adding a new attribute to the dataset record to indicate that there is no data, but I don't think this ever happened._ 

outreach or data dev should add that attribute to the presenter, then pass off to UI to implement

**Comment by danicahelb** [comment]
@dmfalke can we use `<history buildNumber="999"/>` from the presenter? We are currently setting the build number for pre-release studies to "999". 

"999" could be used to represent pre-release studies with data loaded and we could choose another number, such as "888" to represent pre-release studies that do not yet have data loaded.

Note: PERCH has data loaded now

**Comment by dmfalke** [comment]
@danicahelb I took a different approach (see https://github.com/VEuPathDB/web-eda/issues/1093 for details). That should resolve this issue, so I'm closing this one. It should be deployed soon.

**Comment by SheenaTomko** [comment]
This looks great
