### ISSUE TITLE
styling fixes for layout of birds eye view plot with overlayed vs faceted plots

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#924]
Noticed this in the LLINEUP study:

when plot is not stratified, birds eye shows on right side of plot:
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/25450900/155808014-4ff6baae-75aa-47c5-ac2b-ba8f5b8a970f.png">

when an overlay is added, birds eye moves to below the plot (presumably because the birds eye view is less important than the featured plot):
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/25450900/155807840-3ca5d99d-6e67-4ca6-834b-c9aa1fc9e8b2.png">

when a facet is added, birds eye now moves to the top of the plot!
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/25450900/155807969-c1b9e81e-0e87-4f36-8786-fb82a42d4385.png">

we need to be consistent with the placement of the birds eye view so it doesn't jump around as the user builds their visualizations

**Comment by bobular** [comment]
This is mainly an issue for small screens.  The moving of the supplementary plots between faceted and non-faceted is intentional and I think has already been through the committee.

There is a related issue with the new map viz which causes wrapping of the birds eye plot below the map, which @chowington and I have discussed (but I don't remember where). The map's main viz panel is wider than the other plot types, so it makes things wrap more readily.

When the birds eye goes below the plot or map, it doesn't look great. It needs some padding/margin above it.

**Comment by jernestmyers** [comment]
@bobular Obviously, I don't know the history of these UX conversations. I played with this Friday afternoon and thought it made sense to fix the table, birds eye, and legend to be above the visualizations. I've attached pictures to demonstrate how it behaves when building a visualization. My screenshots are in Firefox on a 27" monitor.

1. New scatterplot
![image](https://user-images.githubusercontent.com/69446567/162744345-cea89f6d-96ea-440c-8782-ca11b9ecfd76.png)
2. Set axis variables
![image](https://user-images.githubusercontent.com/69446567/162744478-4f9a0d2e-476c-4776-9ff2-3fba0fd1d546.png)
3. Add an overlay
![image](https://user-images.githubusercontent.com/69446567/162744805-d2c1e767-44ee-412c-8419-f81ec548407b.png)
4. Add a facet
![image](https://user-images.githubusercontent.com/69446567/162744961-1c0e9351-7c71-452f-b3a4-d7ba2eb33967.png)

**Comment by bobular** [comment]
We should also consider @danicahelb , @asizemore  etc hiding the empty completeness table because IMO it looks weird. 

We should be careful that things don't jump around the screen while things are loading. For example, the birds eye component is hidden with, IIRC,  the `visibility` CSS property, in order to preserve its real-estate.

Just for the record, this is mentioned (in passing only) here: https://github.com/VEuPathDB/web-eda/issues/994

**Comment by danicahelb** [comment]
discussed in 4/11/2022 EDA UX meeting.

**In non-faceted view**, the layout should be 2 columns:
1. Left column, ordered from top to bottom: (i) plot and (ii) viz controls
2. Right column, ordered from top to bottom: (i) legend, (ii) birds eye bar plot, (iii) variable completeness table

**In the faceted view**, the right column should be transposed into a row above the left column. The order from left to right should be (i) legend, (ii) birds eye bar plot, (iii) variable completeness table

**Additional notes from the EDA meeting:** 
With this proposed change, in the faceted view, the legend, birds eye bar plot and variable completeness table appear above the main plot being created (ie, scatterplot, box plot, etc)
- It is important that the plot legend does not end up far below the main viz (ie, if we move the legend, birds eye bar, and var completeness table to below the plot controls, the legend will be quite separated from the main plot)
- We considered just placing the plot legend above the main plot, and placing the birds eye bar & variable completeness table below the plot controls, however this leaves lots of empty space to the right of the plot legend
- Note that faceted plots that do not have an overlay will still have their birds eye bar and variable completeness table appearing above the main plot
- We may need to revisit this layout in the future based on user feedback. Generally, we want the most important aspects of the visualization to appear highest on the page. Placing the birds eye bar and variable completeness table above the main plot in the faceted view may be confusing. 
- However, as the user builds their visualization, they will first select axis variables and the birds eye bar will take a secondary position to the right of the main plot. Hopefully, this will help the user to understand the importance of the main plot
-

**Comment by danicahelb** [comment]
@bobular @jernestmyers I also agree that we should hide the variable completeness table until it is populated

**Comment by danicahelb** [comment]
this looks great, thanks @jernestmyers!

I did create a related ticket (NOT for b57), I'm hoping I could get some feedback to see whether this new ticket is worth fixing or not?
