### ISSUE TITLE
styling of faceted plots with no data

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#925]
When faceted plots have no data, I'd still like to read their title. currently, the whole plot area is greyed out and i can't make out which plots correspond to which missing values. Can we make the grey a bit more transparent or not have the grey extend over the plot title or make the plot title darker? any of these would be fine with me

Also, the "no data" could be a bit darker too

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/25450900/155803450-148c9ac4-a608-4cba-ac9a-72855c49ed14.png">

**Comment by jernestmyers** [comment]
@danicahelb I believe this can be closed- I linked the PR after the merge, so it didn't close automatically.

**Comment by danicahelb** [comment]
looks good, thanks @jernestmyers
