### ISSUE TITLE
Styling: Use theming in text

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#933]
Currently we have a clinepi teal from the coreUI theme (ex. Show all filters button) and one in the text (ex. Browse and Subset, variable names in the tree). 

<img width="1752" alt="Screen Shot 2022-02-21 at 11 34 33 AM" src="https://user-images.githubusercontent.com/11710234/154995641-41f0afc9-e531-4b37-bb68-8883d36653e0.png">

I believe these should all be the same color? If yes, we should change the text color to be the primary color set in the theme.

**Comment by asizemore** [comment]
Noting that this ticket is more meaningful now that the mbio eda is coming online soon. The mbio blue is different enough that the color discrepancy is really obvious.
Attaching a b58 label.

**Comment by SheenaTomko** [comment]
Variable tree text now matches the teal text seen elsewhere, like the "New analysis" link
