### ISSUE TITLE
Increase amt of real estate for variable tree

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#937]
I noticed that the amount of real estate dedicated for the variable tree is smaller than the length of my page (see white space in lower left of the screenshot). It would be nice to extend this area all of the way down to the bottom of my screen

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/25450900/153287037-e1559e2e-3092-4fa7-a666-77fe1305d8c0.png">

**Comment by nkittur-uga** [comment]
I noticed the same issue in LLINEUP. The variable tree could be extended. Right now it is showing barely 1-2 vars at a time.
<img width="1317" alt="Screen Shot 2022-05-11 at 12 33 56 PM" src="https://user-images.githubusercontent.com/67710160/167904095-b9ae2983-b372-4c53-a7ab-ffafe4aa26c5.png">

**Comment by danicahelb** [comment]
david left the same comment in a user support request: https://redmine.apidb.org/issues/47945

`why restrict scroll window at left to such a limited amount of space (vertically)? Also, should draw a box around this, and provide a graphical clue to indicate that this is a scrollable window`

I concur that we need a visual indicator that the variable tree is scrollable. the scroll bar is not always visible

**Comment by danicahelb** [comment]
yes, this is what we want, thanks @moontrip

**Comment by moontrip** [comment]
@danicahelb Thank you for your confirmation 👍

**Comment by aaronwlsong** [comment]
Randomly checked one study, and replicate LLINEUP study case, looks good now. Closing ticket. 


![Image](https://user-images.githubusercontent.com/61077845/174130653-a1fb824c-2645-4761-92a9-838458112ea7.png)


![Image](https://user-images.githubusercontent.com/61077845/174130654-c2aa061d-8247-476c-812c-bad22665b08f.png)

**Comment by moontrip** [comment]
@aaronwlsong Thank you for your tests and confirmations! 👍
