### ISSUE TITLE
Apps: add thumbnail page that has all apps together

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#950]
Currently we have apps and their vizs being saved, and links back to them. We'd like a page that holds all of the apps and has all of their vizs in thumbnail view. 

Mockup
<img width="1202" alt="Screen Shot 2022-03-08 at 4 29 27 PM" src="https://user-images.githubusercontent.com/11710234/157329222-64b1f4b0-f944-4b26-ae7a-d3c4648f4424.png">
s

The above mockups assume we will have a compute service which would supply info like "Status", "Started at", etc, so we don't have to worry about those yet.

Major pieces to get functional:

- [ ] Table of contents/List of apps on the left.
- [ ] New app/module button. Goes to add-new-app page
- [ ] App instance section that includes app name, icons for copy/configure/delete, a New Visualization button, and app instance's thumbnails.

Not worried about styling in this ticket, just function :)

**Comment by asizemore** [comment]
Right now i'm thinking these would be the routes:

- `/visualizations/`: shows thumbnail page that has all apps and vizs. Also has + new app button.
- `/visualizations/new/`: shows list of possible apps to add. The view we get when clicking on the Visualize tab in the feature site currently.
- `/visualizations/new/{app.name}/ `: app configuration. Nothing to change here
- `/visualizations/computationId/new`: add a new visualization to that app. Should land on the page that shows viz options, so for example "Scatterplot" and "Boxplot" options (`NewVisualizationPicker`). _Not_ the page that has the + new app button. Nothing to change here.
- `/visualizations/computationId/visualizationId`: the full page visualization view (`FullScreenVisualization`). Nothing to change here.

Not set in stone! Let me know if there is an issue with the above!

**Comment by dmfalke** [comment]
This all sounds good to me!

**Comment by asizemore** [comment]
Deployed to mbio feature site so moving to Ready For Testing!
