### ISSUE TITLE
Apps: Enable app instance to set a "base" entity

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#952]
Would be helpful for the app instances to be able to tell the vizs the main entity we care about for the viz. For example, in alpha div the user picks a collection var. The entity of that collection var will determine all vars a user could pick in the viz. 

For alpha div and ranked abundance, the collection var's entity is the entity we want to use.

**Comment by asizemore** [comment]
Moving to tech debt because i think it falls into the viz/app reorganization category.

**Comment by dmfalke** [comment]
I think this could be done by adding a new optional prop to `InputVariables` that indicates the "base" entity. Each viz would be responsible for determining this based `Options`, etc.

**Comment by asizemore** [comment]
I haven't thought about this ticket for a while so i may be missing something, but i think the way the new code handles the entities of computed vars would solve the issue? 
I remember two driving points for this issue:
1. Ensuring the entity of the computed var that lives on the y axis is the entity that drives the plot
2. Allowing the ranked abundance box plot to appear on load (a lack of an outputEntity was preventing this feature for a while).

Is there another reason we'd need to add this information to `InputVariables`?

**Comment by dmfalke** [comment]
I was thinking it would impact what variables are available for stratification. I didn't focus on that aspect in https://github.com/VEuPathDB/web-eda/pull/1244, so it's possible it's not an issue.

For some more background, we had discussed stubbing in provided variables to `InputVariables`, but that proved to be less straightforward that I was thinking. Perhaps another approach is to include an entityId for "readyonly" variables.

**Comment by asizemore** [comment]
Everything seems to be working as we'd expect, in terms of variables available for stratification. Maybe this is not an issue anymore?

**Comment by dmfalke** [comment]
If everything is working as expected, then I think we an close this.

**Comment by asizemore** [comment]
excellent. Closing!
