### ISSUE TITLE
Apps: apps wrap vizs and send parameters

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#953]
The app instance should tell the visualization which variables to expect the computation to provide. All other variables would be user-defined just like normal.

Examples:
alpha div box - compute defines y axis (alpha diversity). All other variables user-selected.
alpha div scatter - compute defines y axis (alpha diversity). All other variables user-selected.
ranked abundance box - compute defines x AND y axes. All other variables user-selected.

Consider having the data service return this information.

**Comment by moontrip** [comment]
@asizemore Will change the codes to accommodate your suggestions at the `initial-apps-run-update` branch 👍

**Comment by asizemore** [comment]
@dmfalke should i close this issue since it's part of the whole refactoring?

**Comment by dmfalke** [comment]
I think that's fine. Thanks!
