### ISSUE TITLE
Apps: add singleAppMode to switch between clinepi and mbio views

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#954]
In `workspaceRouter`, add `singleAppMode` prop with value the name of the app to be used. For clinepi, name is 'pass'. If we have this set, the user only lives in one instance of the app always. Otherwise, user gets to choose from a list of apps (mbio view)

Important to get this out quickly so that we can start working on mbio apps on the main branch.

**Comment by asizemore** [comment]
Closed with #962

**Comment by SheenaTomko** [comment]
@asizemore, does this need qa or can we move to "Complete"?

**Comment by asizemore** [comment]
@SheenaTomko this is one the clinepi team is best to QA, but QA is straightforward: if the QA site is showing the correct pass app and it looks just like it always did, then this ticket can be moved to Complete

**Comment by SheenaTomko** [comment]
QA.clinepi looks like normal on the visualize tab. Moving to complete.
