### ISSUE TITLE
Apps: filter apps list by projectId

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#955]
Each app has a list of projects with which it is compatible. Have dataClient use the projectId to filter the list of all apps to only those that are compatible with that project.

**Comment by asizemore** [comment]
Closed with #959

**Comment by SheenaTomko** [comment]
@asizemore, does this need qa or can we move to "Complete"?

**Comment by asizemore** [comment]
Moving to complete. Definitely working, as exemplified by the restricted site bug (no computation apps shown) that @danicahelb found
