### ISSUE TITLE
Visualizations: Line plot, add categorical variable handling

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#956]
See mock-ups [here](https://docs.google.com/presentation/d/16xCzGUs744KD3IQ91ITMt30pbAF9SJ7yvOkWZoE-AeE/edit#slide=id.g1080fb1c068_0_421)

Also, don't forget handling 0/0

![image](https://user-images.githubusercontent.com/308639/158681978-e9cf6664-98a6-4ec3-8440-e9b5e282c498.png)
(see discussion in #825)

**Comment by danicahelb** [comment]
Discussed in 4/4/2022 EDA UX meeting

For proportions, the y-axis range should always extend from 0 to 1

**Comment by danicahelb** [comment]
The line plot is not properly calculating proportions. For example, in LLINEUP I tried to plot proportion of malaria positive by thick smear across study timepoints. malaria positive by thick smear has values of yes, no, and did not consent. If I select values of yes in the numerator and yes, no in the denominator, I get a proportion of 1/2 for all timepoints. if i select values of yes in the numerator and yes, no, did not consent in the denominator, I get a proportion of 1/3 for all timepoints.

the proportion needs to calculate the # of counts for the selected numerator / denominator values, not the # of values selected for the numerator / denominator

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/25450900/162852941-c662aee9-3ada-494c-a825-22e5ad5ffb98.png">

**Comment by danicahelb** [comment]
also, i believe we decided that we will NOT offer error bars for the proportion mode. @d-callan @asizemore can you confirm?

**Comment by d-callan** [comment]
That problem w the proportion calculation was a known bug a bit ago that I thought I resolved already. I can check on it. As for error bars I don't see any reason not to offer them, and it's possibly confusing to the user if we don't without explanation.

**Comment by dmfalke** [comment]
> @dmfalke this was marked ready for testing but it seems some backend work wasnt actually deployed. wondered if this was an oversight? should i, or you, update the qa tagger branch now for the data service and rserve? or was there some reason you didnt?

It was an oversight. I will update tagger now!

**Comment by dmfalke** [comment]
https://github.com/VEuPathDB/tagger/commit/448e3cd84c447e759536251c19f8f606cb8ff520

**Comment by SheenaTomko** [comment]
@nkittur-uga, this is ready for testing now

**Comment by nkittur-uga** [comment]
Categorical variables are being handled as expected.
