### ISSUE TITLE
Trivial: change order of visualization icons in new viz picker

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#958]
Not for next week's demo, but needs to be done for b57

The icons are currently in this order (below).  Geo map needs to go higher, before the faded out other icons.

![image](https://user-images.githubusercontent.com/308639/157548177-3bb77ee1-52d7-4dd5-ad92-7b4bb06d7481.png)

**Comment by dmfalke** [comment]
The lodash function [orderBy](https://lodash.com/docs/4.17.15#orderBy) is well suited for this task.

**Comment by SheenaTomko** [comment]
@aaronwlsong, when qc'ing, use UMSP or some of the SCORE studies like SCORE seasonal, which have geolocation data, as well as some studies like PRISM, which doesn't.

**Comment by aaronwlsong** [comment]
Checked different type studies, it looks good now. Closing ticket.

Eg1. Study includes geolocation data

<img width="1996" alt="Screen Shot 2022-03-31 at 3 13 03 PM" src="https://user-images.githubusercontent.com/61077845/161132446-5616f21d-49d9-458a-8311-ee3f2f91eab1.png">

Eg2. Study does not include geolocation data

<img width="1931" alt="Screen Shot 2022-03-31 at 3 18 19 PM" src="https://user-images.githubusercontent.com/61077845/161132678-a08f7504-2864-4513-9bbc-a1c894e5e351.png">
