### ISSUE TITLE
Ranked abundance app: update scatter plot and box plot visualizations

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#966]
Generally speaking, the changes needed for this issue are
1. Use variables provided by the computation configuration for the visualization configuration.
2. Use variables provided by the computation configuration for plot and facet labels.

For the time being, we can simply omit variables in `InuptVariables` that are provided by the computation. 

**The following visualizations will be used for the ranked abundance app**
- **BoxPlotVisualization**
    - **x-axis** is ranked collection var (*new from alphaDiv*)
    - **y-axis** is computed var
    - *Backend bug requires that an overlay var be included*
- **ScatterPlotVisualization**
    - **y-axis** is computed
    - **overlay** is ranked collection var (*new from alphaDiv*)

**In other words, the following changes need to be made for each visualization when used with the ranked abundance app**
- BoxPlot will use the collection variable as for it's x-axis. This means that `xAxisVariable` does not need to be specified as a part of the visualization configuration, and the collection variable should be used for the x-axis label.
- ScatterPlot will use the collection variable for overlay. This means that `overlayVariable` does not need to be specified as a part of the visualization configuration, and the collection variable should be used for the overlay label. It also means that the user will have to choose an x-axis variable before anything can be displayed (this shouldn't require any additional work, but it is worth mentioning).

_Note that collection variables are just categories in an EDA study's variable tree. This is useful for constructing the associated label(s) in the visualization._

**Comment by moontrip** [comment]
@dave and @asizemore First of all, thank you for your detailed description made in this ticket @dmfalke. This is very helpful and resolves several questions I tried to ask 👍 I have tried to understand initial apps run and what we want to implement - studied some background knowledge about alpha div and ranked abundance too 😄  

Based on the current status and Ann's works and issue, a couple of questions arise regarding this issues and its scope of works. Please correct me if I misunderstand something. 

a) As far as I know, currently we do not have rankedAbu (ranked abundance) component, though we have alphaDiv component.

b) We should accommodate both alphaDiv and rankedAbu at each Viz. Given that the two types of plots have different choice of variables (X, Y, and Overlay) each other, we would need to distinguish them. With the absence of rankedAbu component, I can't check it contents of computation props. Based on alphaDiv component and its Vizs, I guess `computation.descriptor.type` is a unique name that can be used for this purpose. Certainly I may use known computation.descriptor.type for alphaDiv so it may be fine for the time being.

c) From my understanding, rankedAbu is generally a plot of rank (x-axis) and abundance (y-axis). I don't know the backend response so can't tell correctly but we may need to use different axis label ?

d) This is for alphaDiv: I feel that we are better to use y-axis label with alphaDiv method, not simply type name (alphaDiv). It is typically said Shannon index, Simpson index, etc. so perhaps we can adopt it - we can ask others about the naming later 😄

**Comment by asizemore** [comment]
@moontrip for a) that's on my plate :) Let me see if i can't get you something to work with by the end of today!

**Comment by moontrip** [comment]
@asizemore Thank you for your information. I think that I can live without it for the time being 👍

**Comment by SheenaTomko** [comment]
@asizemore, does this need qa or can we move to "Complete"?
