### ISSUE TITLE
Map visualization: persist "mouse pointer mode" 

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#971]
The state of this little guy should persist in vizConfig

![image](https://user-images.githubusercontent.com/308639/158412541-af9270a5-85c2-4397-92f0-7f8440e28107.png)

It may need some web-components work on `MapVEuMap` because it doesn't have a `mouseMode` prop. Instead it has local state. While we are at it, we could remove the comments that start with "this is the React Map component" because I think they have long-lost the code they were referring to!

**Comment by danicahelb** [comment]
This ticket is for situations where the user changes the mouse mode from the default, leaves the visualization, and then re-opens the viz. When this happens, we want to the users mouse mode selections to persist selections when they leave and come back

**Comment by danicahelb** [comment]
@moontrip i moved this out of "this cycle" as it is only a nice to have and we are in crunch time for b58. thanks!

**Comment by SAK22** [comment]
Looks good!
