### ISSUE TITLE
Apps: Add Ranked abundance plugin

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#972]
Add a ranked abundance plugin. Eventually this app will have a scatterplot and boxplot as defined in the [spreadsheet](https://docs.google.com/spreadsheets/d/1oO265vVOVR13MovZDQ9ubG9-nIJGruz54wSyrmCAfQI/edit#gid=0).

This PR is ONLY to add the plugin and configuration page. Nothing more at this time. Adding visualizations will be handled in #966

**Comment by asizemore** [comment]
Closed with #973

**Comment by SheenaTomko** [comment]
@asizemore, does this need qa or can we move to "Complete"?

**Comment by asizemore** [comment]
No QA needed. Moving to Complete!
