### ISSUE TITLE
Fix client to handle new study variable `displayType` values from studies service.

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#977]
At the time of writing UMSP has the new values (see [here](https://github.com/VEuPathDB/EdaLoadingIssues/issues/22#issuecomment-1071031940))

"SCORE Seasonal" did have it but they were reverted for a demo this week.

There may be one other study, @jaycolin ?

NOTE: I will add another issue that actually makes use of the new values.

TESTING: make sure UMSP and SCORE Seasonal (when reloaded) load in EDA OK, and that you can see the usual variables (but shouldn't see lat/long/geohash variables) and that the geo map viz works.

**Comment by SheenaTomko** [comment]
This doesn't seem to be working. If I open UMSP on qa.restricted.clinepidb I get a very large error message. Maybe some fix wasn't pushed completely?

![Screen Shot 2022-03-18 at 10 52 03 AM](https://user-images.githubusercontent.com/54597319/159037067-281a5f3d-a389-463c-b77f-46d1cefe0fc4.png)

**Comment by bobular** [comment]
Needs testing when the studies come back on line.
I haven't tried UMSP for a few weeks, but SCORE Seasonal was working fine (which also has the 'geoaggregator' variable annotation) so I think this is probably already fixed.

**Comment by SheenaTomko** [comment]
Yes this works fine now. Closing and marking as complete
