### ISSUE TITLE
Map visualization: make use of new `displayType` values in study variable metadata (frontend)

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#979]
See #977 for prior work.

When all mappable studies are loaded with the new `displayType` values for geo-related variables can be used by the map visualization code in `entityToGeoConfig` in `geoVariables.ts`.

**Comment by danicahelb** [comment]
dependent on backend work in https://github.com/VEuPathDB/EdaLoadingIssues/issues/22

**Comment by danicahelb** [comment]
changes all made in database and frontend allows displayType but doesn't actively use it yet. @bobular how essential is this to make maps usable in b57?

**Comment by bobular** [comment]
Not at all essential, and potentially risky to do this right before release. Definitely one for b58 though.

**Comment by danicahelb** [comment]
hey @bobular what does outreach need to do to QA this?

**Comment by bobular** [comment]
There's not much to check, other than that nothing's broken.

From the PR:

> TESTING: no new functionality here. All we can do is check that a) the map works and b) the map viz option is available in the appropriate projects (SCORE Seasonal, SCORE Mozambique, UMSP) and not in the others.

**Comment by danicahelb** [comment]
paused until maps are working again

**Comment by SheenaTomko** [comment]
Looks good. Checked UMSP and all SCORE studies plus a WASH-B study. Maps were available only for the studies with geohash variables, as expected, and those geohash variables were never displayed or downloadable (though latitude and longitude could be downloaded).
