### ISSUE TITLE
Unify tooltips on home page

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#984]
[Original redmine](https://redmine.apidb.org/issues/39539) written by Cristina and assigned to Dave:

currently we have 2 styles:
- the basic title attribute that shows browser dependent and cannot be styled.
- the one with yellow background, mesa based.

(dave:
we have two tooltip components, one that is using the jquery qtip library, and one that Austin wrote along with Mesa.)

**Comment by dmfalke** [comment]
Even though the code is in EbrcWebsiteCommon, I moved this issue to web-eda since it has the labels we use for project management.

**Comment by SheenaTomko** [comment]
All tool tips on the home page have a yellow background and the same font. Marking this as complete
