### ISSUE TITLE
Apps: Ranked abundance box plot can appear on load

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#993]
The ranked abundance boxplot gets both its x and y variables from the computation/collection variable. Consequently the boxplot could appear as soon as the visualization loads.

Pro: User gets to see un-stratified visualization. This is arguably the most important view, as it would show exactly the distribution of abundance values for the top N taxa in the data.
Con: No other visualizations work like this :/

**Comment by asizemore** [comment]
I think this is related to #952 . I'm pretty sure if we can have `outputEntity` immediately get set, then the box would appear.

Note: for alpha div and ranked abundance, the outputEntity should be the collection var entity.

**Comment by asizemore** [comment]
@moontrip to be honest i'm not 100% sure why it's xAxisVariable in the pass app, because the output entity constraints in the backend are based on the yAxisVariable. But i'm sure there's a reason i just don't know of or understand 😄 !

> So, computation apps like alphadiv and abundance should use (computed) yAxisVariable (or even xAxisVariable or overlayVariable for abundance)

Yes exactly. Right now we're always inputting a collection variable to the app, and the output computed variable will have the same entity as the collection variable. So I'd guess it's probably safest to just define the outputEntity as whatever the entity of the collection var is, if that makes sense? What do you think about that approach?

Thank you for your feedback on the Google sheets!! I made a few updates that i hope clarify your questions. Let me know what else I can do to improve that list!

**Comment by moontrip** [comment]
@asizemore great to know! IDK why we used xAxisVariable as outputEntity in most (think all though) Vizs but perhaps it comes from an initial Viz component: basically other Vizs were based on the initial/prototype one, but no complaints from others for that outputEntity so maybe works fine somehow? haha

Your explanation makes sense to me 👍 Just want to make sure that you are talking about [this one](https://github.com/VEuPathDB/web-eda/blob/77b822c9fd923d598fd90716687c8e971d6bd339/src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx#L259) or [another one](https://github.com/VEuPathDB/web-eda/blob/77b822c9fd923d598fd90716687c8e971d6bd339/src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx#L297) 

And thank you for your changes on the Google sheets! 👍

**Comment by asizemore** [comment]
Ooh yes good question. From my small investigation into getting the box to just appear on load for the abundance app, I _believe_ that assigning the first one ` const outputEntity = useFindOutputEntity(` would be enough, because I _think_ this [line](https://github.com/VEuPathDB/web-eda/blob/77b822c9fd923d598fd90716687c8e971d6bd339/src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx#L275) is what prevents that immediate load (usually outputEntity is null until we have made some variable selection). 

That's just what i had discovered so far, but there might be a better way to go about the whole thing 😄

**Comment by asizemore** [comment]
Moving out of next cycle until the viz refactor is complete - i think (hope?) this should be much simpler once that is done!

**Comment by asizemore** [comment]
I think this should be straightforward after #580

**Comment by bobular** [comment]
I played with mbio and was just about to submit a ticket for this...

This can be fixed quite easily already:

Inside the `data = usePromise(...`, we only ever need the outputEntity ID (`hasIncompleteCases()` only uses the ID internally) so we could do something like this

```
  const data = usePromise(
    useCallback(async (): Promise<BoxplotDataWithCoverage | undefined> => {
      const outputEntityId = computation.descriptor.configuration
            ? (computation.descriptor.configuration as any).collectionVariable.entityId
            : outputEntity ? outputEntity.id : undefined;
      if (
        // abundance case for xAxisVariable
        (computation.descriptor.configuration == null &&
          (vizConfig.xAxisVariable == null || xAxisVariable == null)) ||
        (computation.descriptor.configuration == null &&
          (vizConfig.yAxisVariable == null || yAxisVariable == null)) ||
        outputEntityId == null ||
        filteredCounts.pending ||
        filteredCounts.value == null
      )
        return undefined;
```
Then change `hasIncompleteCases()` to use the ID instead of the `StudyEntity` type.

The only problem is that the `hasIncompleteCases` serves more visualisations than this one, so it becomes a costly/annoying fix to make everywhere.

**Comment by bobular** [comment]
Haha the PR looks great too!

**Comment by asizemore** [comment]
assigning to @dpbisme for QA
