### ISSUE TITLE
Standardise birds eye plot mouse-over with (?) icon and it should not be active when plot is hidden

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#994]
Make a new barplot, but don't pick a variable. Hover over the area above the almost empty table and you see a small rectangle appear.

The Lineplot viz has an example of the (?) font awesome icon we want to use.

**Comment by moontrip** [comment]
I have know that issue too. Perhaps the simplest solution is to only show the BirdsEyeView component's return with a condition (e.g., birdsEyeData != null)

**Comment by bobular** [comment]
I have just added a new help tooltip in Lineplot

![image](https://user-images.githubusercontent.com/308639/160250934-6f5cb6e4-a21f-4c81-b4a5-b7578f41fd37.png)

as per the mockups [here](https://docs.google.com/presentation/d/16xCzGUs744KD3IQ91ITMt30pbAF9SJ7yvOkWZoE-AeE/edit#slide=id.g1097c687406_0_96)

I wonder if we should standardise and put a font-awesome `fa-question-circle` next to the birds-eye too (instead of the whole-mouse-over we have now) ?

**Comment by bobular** [comment]
> I have know that issue too. Perhaps the simplest solution is to only show the BirdsEyeView component's return with a condition (e.g., birdsEyeData != null)

We don't want the variable data/no data table below to jump around.  But maybe that could disappear too.  What we want is nice behaviour for the first plot the user makes, and then on every tweak they make to it.  Perhaps the BirdsEye should stay on the screen during an update (like the main plot does).

The empty variable table looks a bit bad IMO.  Tidying up all this behaviour would be nice to have!

**Comment by jernestmyers** [comment]
@bobular I'm curious where you'd place the icon in the `BirdsEyeView`. I played around a bit and reworked it as shown, but not sure how I feel about it.

![Image](https://user-images.githubusercontent.com/69446567/177401473-b6259e5b-184c-46d9-b9a6-f56401c03ccc.png)

**Comment by danicahelb** [comment]
thanks, I've added to the agenda for 7/11/2022 EDA UX meeting

**Comment by nkittur-uga** [comment]
Looks good.
<img width="1335" alt="Screen Shot 2022-08-01 at 12 07 07 PM" src="https://user-images.githubusercontent.com/67710160/182192032-e67f0246-3476-49b6-9b28-beae9d2ce1fc.png">
