### ISSUE TITLE
Visualisations: x-zoomed histogram is not including config.viewport.xMin/xMax in back end request

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#996]
e.g. GEMS1 
histogram visualization
main var: Age
binWidth: 3 (default)
set the x-axis range [20,40]

You can see a tiny sliver of the (15,18] bar on the left hand side and its mouse-over is active.

Solution
`config.viewport.xMin` and `config.viewport.xMax` should be sent to the back end.

**Comment by moontrip** [comment]
thank you for your information, @bobular I will take a look at it.

**Comment by sweverschulman** [comment]
I can confirm that there is no longer a sliver of a bar at (15, 18] in the GEMS plot. See attached image. 
<img width="652" alt="Screen Shot 2022-04-13 at 11 57 14 AM" src="https://user-images.githubusercontent.com/62298921/163221654-f7c15cd5-7020-4358-954f-a7085c876bf3.png">

**Comment by moontrip** [comment]
Thank you for your review, @sweverschulman 👍
