### ISSUE TITLE
Mosaic plot (2x2 and RxC) tabs need styling fix

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#998]
When making a mosaic visualization, tables are positioned so that they overlap the nice tab list.

Here if we look at the mosaic view we can see a nice line under the tabs...

<img width="878" alt="Screen Shot 2022-03-24 at 4 48 39 PM" src="https://user-images.githubusercontent.com/11710234/160008034-a4bcb1ac-46fc-4ce6-bb0a-d979262e7716.png">

but if i switch to the table or statistics view, the table is placed at the tippy top so that it covers that nice line

<img width="874" alt="Screen Shot 2022-03-24 at 4 48 48 PM" src="https://user-images.githubusercontent.com/11710234/160008150-e6bd7ae5-d222-47b9-947a-c2f533ae798f.png">

I would suggest adding a small amount of space above the table so that we can still clearly see the entire tab list. Open to other ideas though!

**Comment by danicahelb** [comment]
another styling issue with the mosaic tools is that the non-active tabs are shown in grey text. We tend to use grey text when something is not accessible, so to me it looks like i shouldn't be able to click on the table or stats views.

We provide nice highlighting to indicate which tab is active, so i think we can make the grey text black on the inactive tabs

**Comment by SheenaTomko** [comment]
Looks great. Now the tabs are no longer grey but the theme color and the table appears in it's own box below the line
